### ISSUE TITLE
clipboardWrite and history permissions are valid but cause errors

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-linter#1006]
The linter errors with valid permissions "clipboardWrite" and "history".

It should allow add-ons with these permissions without any errors.

**Comment by tofumatt** [comment]
Closed by #1005.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF49(Win 7)
Postfix screenshot:
![newperm](https://cloud.githubusercontent.com/assets/15685960/19719909/9f577dca-9b74-11e6-8a42-105d4a863e70.png)

@tofumatt : Is this fix in -prod already, or I did not manage to test it right?
