### ISSUE TITLE
web-ext lint error: Too many non-option arguments: got 1, maximum of 0

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-linter#1023]
### Describe the problem and steps to reproduce it:

To reproduce:
- upgrade the `addons-linter` dependency of `web-ext` to `0.15.7` (or higher)
- run `npm install` and `npm run build` to get a new `web-ext`
- cd into any add-on
- type `web-ext lint`
### What happened?

It shows a usage message with this error:

```
Too many non-option arguments: got 1, maximum of 0
```
### What did you expect to happen?

The command should show a lint report
### Anything else we should know?

`web-ext` simulates passing a directory of source as the first command line argument to `addons-linter` [like this](https://github.com/mozilla/web-ext/blob/master/src/cmd/lint.js#L75). Maybe something changed? I don't see anything obvious at a glance.

The mystery saga of https://github.com/mozilla/addons-linter/issues/969 continues! It was definitely fixed but now it's broken again. See https://github.com/mozilla/web-ext/pull/606 and https://github.com/mozilla/web-ext/pull/616

**Comment by muffinresearch** [comment]
Looks like Yargs was updated 6 days ago: https://github.com/mozilla/addons-linter/pull/1003 and that was included in the 0.15.7 release.

**Comment by josteink** [comment]
I'm having this error too. It's a bit of a bummer too, because with this, I finally planned to land the warnings-as-errors support in web-ext linting.

**Comment by muffinresearch** [comment]
@kumar303 Running web-ext lint with a version of web-ext where the tests are failing, `web-ext lint --source-dir [SOURCE]` runs correctly so I think this might be an issue with how the cli tests in web-ext are being run and less a bug in addons-linter.

**Comment by kumar303** [comment]
@muffinresearch Did you rebuild `web-ext` after upgrading its linter dep? I can still reproduce it. This is how I do it:
````
cd web-ext
npm install
npm run build
web-ext lint -s ~/dev/webextensions-examples/beastify/
# No errors
npm install addons-linter@0.15.9
npm run build
web-ext lint -s ~/dev/webextensions-examples/beastify/
# Too many non-option arguments: got 1, maximum of 0
````

**Comment by muffinresearch** [comment]
@kumar303 It's working for me but the test still fails. What node / npm versions are you using?

**Comment by josteink** [comment]
I can reproduce this error too and I'm using v4.6.1 (default on Fedora 24) and v4.2.6 (Ubuntu 16.04).

This tool really *should* work with the Node LTS releases since it's bound to be involved in many CI-processes on build-servers with 100% standard configurations where adding custom repos is big no-no.

**Comment by kumar303** [comment]
I can reproduce it in any version combo. The lats one I tried was:
````
$ node --version
v6.3.0
zenith:~ kumar$ npm --version
3.10.8
````

**Comment by josteink** [comment]
I've run up the following script to bisect the error, and I cannot get any good results when going over addons-linter:

````bash
#!/bin/bash

cd $HOME/build/addons-linter/
npm install
npm run build
cp $HOME/build/addons-linter/dist/addons-linter.js $HOME/build/web-ext/node_modules/addons-linter/dist/../

cd $HOME/build/web-ext/
npm run build
$HOME/build/web-ext/bin/web-ext lint -s $HOME/build/webextensions-examples/beastify/
````

Going back 40 commits on `addons-linter` doesn't fix the problem in `web-ext`: It keeps on failing with the same failure mode.

From this I've gathered that the error probably has to be in `web-ext` somewhere... I'll dig deeper and see what I've found.

**Comment by josteink** [comment]
We'll that's the strangest thing ever.

I just did `git pull origin master` on both `addons-linter` and `web-ext` and ran the following script. It runs fine:

````bash
#!/bin/bash

cd $HOME/build/web-ext/
npm install
cp $HOME/build/addons-linter/dist/addons-linter.js $HOME/build/web-ext/node_modules/addons-linter/dist/addons-linter.js
npm run build
$HOME/build/web-ext/bin/web-ext lint -s $HOME/build/webextensions-examples/beastify/
````  

And now it works fine...

@kumar303: Can you reproduce the same behaviour?

**Comment by muffinresearch** [comment]
@josteink Kumar and I have just been debugging this and the problem is related to the way the ManifestJson parser tries to look up the self-hosted option. The causes the the yargs parser to run again and it breaks down from there.

I couldn't initially repro it since I was pointing it at a directory with an old style extension and if the directory doesn't have a `manifest.json` the bug isn't triggered. addons-linter will still run in those cases since it has some functionality for dealing with install.rdf for legacy reasons. 

@kumar303's working on a patch.

**Comment by kumar303** [comment]
@josteink thanks for the help!

This was an odd bug. We tracked it down to some code in the linter that was being a bit too lazy in how it parsed the command line for configuration. However, it's a mystery to me how this ever worked!

The bug was fixed in https://github.com/mozilla/addons-linter/pull/1037
