### ISSUE TITLE
Validate icons

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-linter#1026]
We should check that images referenced in the manifest are present, we should also check that they are an allowed type (Not sure exactly what this list is, chrome web exts allow any image format supported by webkit [1] MDN docs don't specify allowed formats [2])

We could also go further and check files are the filetype the extension suggests they are.

[1] https://developer.chrome.com/apps/manifest/icons
[2] https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/icons

**Comment by mstriemer** [comment]
Firefox isn't handling missing icons very well as noted in ﻿﻿﻿﻿﻿[bug 1368447](https://bugzilla.mozilla.org/show_bug.cgi?id=1368447). We should look into performing this check and probably error if the file is missing.

**Comment by mstriemer** [comment]
STR

1. Start with a valid webextension.
2. Add an icon to manifest.json that doesn't exist in the package.
3. An error is reported and references the path that is missing.

**Comment by mstriemer** [comment]
Before these changes extensions with missing icons would be considered valid, but we would like to prevent that.

If there are multiple icons they must all be present to pass validation.

**Comment by vcarciu** [comment]
Verified as fixed : 
![iconaction](https://user-images.githubusercontent.com/1583842/27389786-1a9cc44c-56a8-11e7-84fc-22c8ef2dcd01.gif)
