### ISSUE TITLE
author should be a string

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-linter#1029]
In bug https://bugzilla.mozilla.org/show_bug.cgi?id=1313567 we use author if its a string, for anything else Firefox will throw a warning. Let's do the same:

1477940090315	addons.webextension.tabs-tabs-tabs@mozilla.org	WARN	Loading extension 'tabs-tabs-tabs@mozilla.org': Reading manifest: Error processing author: Expected string instead of {"email":"foo"}

**Comment by vasilicamihasca** [comment]
There is no warning displayed at validation while submitting a webextension which contains an object as the "author" in manifest.json. 
- Attaching the webextension: 
[https_everywhere-2016.9.21-an+fx.zip](https://github.com/mozilla/addons-linter/files/654170/https_everywhere-2016.9.21-an.fx.zip)
- Validation Results:
![2016-12-15_1051](https://cloud.githubusercontent.com/assets/18114210/21217378/8bafdeea-c2b4-11e6-8dbf-8149d5158cb5.png)

**Comment by muffinresearch** [comment]
@vasilicamihasca It's almost certainly not released yet.

**Comment by vasilicamihasca** [comment]
@muffinresearch I forgot to mention that I tested in AMO-dev.

**Comment by muffinresearch** [comment]
@vasilicamihasca np, to be on -dev this needs to be released as a package and then that new version needs to be added to the dependencies so that it's used by addons-server. This can mean there's a bit of a delay between patches landing and being deployed.

**Comment by vasilicamihasca** [comment]
@muffinresearch  Do you have an estimated time for this package release in -dev? I’m asking this in order to be checked by the QA team.

**Comment by EnTeQuAk** [comment]
I can do this a bit later today and land it in dev. I'll update the
issue afterwards.




On Fri, Dec 16, 2016, at 09:19 AM, vasilicamihasca wrote:

> @muffinresearch[1] Do you have an estimated time for this
> package release in -dev? I’m asking this in order to be checked
> by the QA team.
> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[2], or mute the
> thread[3].
> 


Links:

  1. https://github.com/muffinresearch
  2. https://github.com/mozilla/addons-linter/issues/1029#issuecomment-267541246

**Comment by EnTeQuAk** [comment]
This is now on -dev

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF50(Win 7).
Postfix screenshot:
![2016-12-19_1106](https://cloud.githubusercontent.com/assets/15685960/21306769/52017134-c5db-11e6-9ee0-516478864569.png)
