### ISSUE TITLE
Move yargs closer to the linter object instantiation and remove getConfig()

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-linter#1036]
This is a follow-up to https://github.com/mozilla/addons-linter/issues/1023

The yargs config code must only be called once so it should be run as close to the instantiation of the linter as possible and from there all access to config should be either from the linter object or the linter object can pass it's config down into things that need access it.

The yargs config also should not be exportable in any way to ensure its usage is limited to only the one place where it's relevant.

The need to refactor this will help avoid strange side-effects of arg parsing running multiple times when the linter is consumed via other projects such as web-ext.

**Comment by kumar303** [comment]
The main goal is to prevent any linter component from trying to parse the command line for configuration. When used as a library, it should never need to do that anyway since it can ask the Linter instance for config values.

**Comment by hiikezoe** [comment]
I believe #1926 fixes this to some extent.

**Comment by EnTeQuAk** [comment]
I think it did, and we can re-use that approach for other components if needed. `getConfig` is currently only used twice where it's supposed to be used.
