### ISSUE TITLE
eval() not caught

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-linter#1047]
### Describe the problem and steps to reproduce it:
`eval()` is missed here:
https://addons.mozilla.org/en-US/firefox/files/browse/544938/file/js/background.js#top

### Anything else we should know?
ref: transferred from here
https://github.com/mozilla/amo-validator/issues/370

**Comment by erosman** [comment]
Missing `document.createElement('script')`
https://addons.mozilla.org/en-US/firefox/files/browse/545185/file/scripts/analytics.js#top

**Comment by erosman** [comment]
Misses everything
https://addons.mozilla.org/en-US/editors/review/pulsee

**Comment by andymckay** [comment]
Is `document.createElement('script')` a problem with WebExtensions? What does miss everything mean? And could you please file new bugs instead of adding new things to old bugs?

**Comment by erosman** [comment]
I initially crated the bug with the title "**Validator is missing issues**".
Therefore, I was listing issues that were missed in this topic.

The topic title was changed to "**eval() not caught**" although that was only ONE of the missed issues.

There are 100s of items that are missed and filling 100s of bug seems counterproductive.

> What does miss everything mean? 

It means the validator shows a CLEAN result with zero warning while there are multiple issues that should have been listed eg:

**createElement('script')**, **innerHTML**, **JQuery** libraries with multitude of warnings, etc

I suggest passing the same addon as a normal SDK addon and checking the validator result for reference.
