### ISSUE TITLE
Add WebExtension Experiment type to ADDON_TYPE_MAP

### ISSUE THREAD

**Issue by groovecoder** [mozilla/addons-linter#1059]
### Describe the problem and steps to reproduce it:
1. Add `<em:type>256</em:type>` to `install.rdf`
2. Run `addons-linter` on the resulting `.xpi` file

### What happened?
```
Validation Summary:

errors          1
notices         0
warnings        0

ERRORS:

Code               Message                   Description                                                                            File          Line   Column
RDF_TYPE_INVALID   Invalid <em:type> value   The only valid values for <em:type> are 2, 4, 8, and 32. Any other values are either   install.rdf
                                             invalid or deprecated.
```

### What did you expect to happen?
No errors

### Anything else we should know?
MDN Doc: https://developer.mozilla.org/en-US/Add-ons/Install_Manifests#type

**Comment by EnTeQuAk** [comment]
Short notice: the addons-linter is only run against webextensions currently so all old-style add-ons should use `amo-validator` for linting purposes. That doesn't mean we shouldn't fix this though :)

https://github.com/mozilla/amo-validator

**Comment by andymckay** [comment]
Closing in favour of #1063
