### ISSUE TITLE
Drop all support for non-WebExtensions add-ons

### ISSUE THREAD

**Issue by groovecoder** [mozilla/addons-linter#1063]
### Describe the problem and steps to reproduce it:
I ran the `addons-linter` against my old-school add-on `.xpi` file.
I saw old-school rule violations & error messages.

### What happened?
I worked on the violations & error messages

### What did you expect to happen?
I should see an error message to use amo-validator on old-school add-ons.

### Anything else we should know?
https://github.com/mozilla/addons-linter/pull/1060

**Comment by muffinresearch** [comment]
@andymckay do we have a plan on the Firefox side of things re: dictionaries and langpacks migrating to a web-ext wrapper?

**Comment by andymckay** [comment]
None in the works yet.

**Comment by muffinresearch** [comment]
> None in the works yet.

@andymckay Ok - so if we go ahead and remove all non-web-ext related features from the linter it would mean we'll continue to use the amo-validator for dictionaries and lang-packs until such point that we do something different with them in the future. 

I think that makes sense - do you think that sounds ok? It would be nice to not block on making the linter web-ext only.

**Comment by andymckay** [comment]
Ditching the old validator (eventually) would be nice. I can imagine though prioritizing support for moving them to the linter won't come until we are getting ready to drop the validator as we drop support for legacy add-ons.

**Comment by wagnerand** [comment]
@EnTeQuAk is your branch https://github.com/mozilla/addons-linter/tree/feature/remove-legacy-addons doing this? What keeps us from merging it?

**Comment by EnTeQuAk** [comment]
actually my branch is old and should be deleted. @andymckay did most of the work and I think we're in a pretty good shape now, there's a few more things like `legacyCode` that should go away but maybe we should file separate issues for them?

**Comment by wagnerand** [comment]
Yeah I think it makes sense to file issues and remove code as we come across it. Can't be that much left, can it? 😆

**Comment by ValentinaPC** [comment]
Please add some STR for us to check this or the label "qa:not needed". Thanks!
