### ISSUE TITLE
I'm bored of scrolling up past coverage

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-linter#1067]
Write some code, write some tests. Run tests. Get to the end and then scroll back up past all the coverage to find which test failed. Fix code. Write some tests. Run tests. Scroll again.

Coverage is going to complain on a pull request anyway. Could I get a summary instead of details every time? Or something? Could we make this easier?

**Comment by andymckay** [comment]
`grunt test-no-coverage` does this, I think this should be the default.

**Comment by tofumatt** [comment]
I want the default test run locally to be the ones that contributors new to the project run as well; I find it counter-intuitive when `npm test` passes locally but would fail our CI tests.

That said, `npm run testwatch` would be ideal, running only the tests and not coverage on code change.

**Comment by andymckay** [comment]
This is actually mentioned in the README as well. Since the functionality exists and is documented, let's close it. Sorry for the noise.
