### ISSUE TITLE
Bring style rules, tasks, etc. in line with add-ons frontend

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-linter#1069]
We should be consistent across add-ons node/ES6 projects and use the styles, build commands, etc. that we do in the frontend. I like them more and the consistency helps; I already find it weird to look at our slightly different code.

**Comment by muffinresearch** [comment]
I wonder if it's worth packaging up stylelint/eslint rules so we can use a shared package in all the addons projects?

**Comment by tofumatt** [comment]
Definitely; we did that for node-firefox and a few other things in the past and it was awesome.

**Comment by muffinresearch** [comment]
I think this is mostly fixed with the move to eslint-config-amo and the test commands have mostly been synced up.
