### ISSUE TITLE
Syntax Highlighting for es6 file-extensions

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-linter#1073]
### Describe the problem and steps to reproduce it:
es6 files are missed by the syntax highlighter

### Examples:
```
https://addons.mozilla.org/en-US/editors/review/snaplinksplus
https://addons.mozilla.org/en-US/firefox/files/browse/543834/file/src/background-scripts/background.es6#top
```

There are 14 es6 files in above addon.

Note: Does the non-WebEx parser handle them??!

**Comment by andymckay** [comment]
The linter doesn't syntax highlight them, addons-server does. It looks like there are multiple bugs on this: mozilla/addons-server#4147, mozilla/addons-server#4149

**Comment by wagnerand** [comment]
We decided to not do this in https://github.com/mozilla/addons/issues/147.
