### ISSUE TITLE
Create a checkIfPathExists method for IO

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-linter#1079]
If we could check if a path exists (`_locales/`) inside an add-on regardless of directory, XPI, etc. we could avoid [looping through all files](https://github.com/mozilla/addons-linter/pull/1078/files#diff-baa432d9354e3de899d28a2638d1499eR146) when checking for `_locales`.

**Comment by andymckay** [comment]
Hmm, I think in #1078 we need a regex anyway. I don't think this is worth it, and iterating over files is just iterating over the object I think, its not hitting the actually file system is it?

**Comment by tofumatt** [comment]
Yeah in the case of the new code this isn't needed.
