### ISSUE TITLE
Revisit whether there's a better way to consume eslint rules

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-linter#1113]
This is to summarize a conversation on vidyo with @EnTeQuAk 

When the linter was originally built out we took the decision to use eslint internal APIs because that made it easier to run rules and define our own error messages. 

It would be a good idea to revisit this and check if there's any better options for being able to run eslint rules via the linter in standard form so that we can more easily consume existing eslint rules and so that any custom rules here are more readily usable via other eslint clients in editors directly.

Once all the legacy non-webext rules are ripped out there will be minimal eslint rules so that might provide a good time to do this if it's already been investigated and found to be viable.

As an example this json reporter might be one avenue worth exploring: https://github.com/sindresorhus/eslint-json

**Comment by EnTeQuAk** [comment]
There is and this just got implemented with https://github.com/mozilla/addons-linter/issues/1140 and other PRs.
