### ISSUE TITLE
On Windows, NO_MESSAGES_FILE error is logged even if messages.json exists.

### ISSUE THREAD

**Issue by asamuzaK** [mozilla/addons-linter#1148]
### Describe the problem and steps to reproduce it:
When running `web-ext lint` (`addons-linter .`) on Windows, `NO_MESSAGES_FILE` error is logged even if messages.json exists.

1. Save attached test add-on.
2. Run `addons-linter .`

### What happened?
`NO_MESSAGES_FILE` error is logged

### What did you expect to happen?
No error.

### Anything else we should know?

https://github.com/mozilla/addons-linter/blob/master/src/parsers/manifestjson.js#L137
```
let msg = `_locales/${this.parsedJSON.default_locale}/messages.json`;
```
I think `msg` should be created with path.join() instead.

Note:
https://github.com/mozilla/addons-linter/blob/master/src/parsers/manifestjson.js#L145
should be fixed too, I suppose.

[webExtTest.zip](https://github.com/mozilla/addons-linter/files/810074/webExtTest.zip)
[log.zip (json)](https://github.com/mozilla/addons-linter/files/810078/log.zip)

**Comment by EnTeQuAk** [comment]
We join paths not using `path.join` all over the place afair, I'll take a look at this.
