### ISSUE TITLE
Incorrect error message for duplicated permission

### ISSUE THREAD

**Issue by vasilicamihasca** [mozilla/addons-linter#1152]
**Steps to reproduce:**
Submit the attached webextension on AMO-dev: 
[duplicatedpermission.zip](https://github.com/mozilla/addons-linter/files/813534/duplicatedpermission.zip)

**Expected results:**
The proper error message about the duplicated permission is successfully displayed.

**Actual results:**
The following error appears in Validation Report: "Permissions must be strings. If a permission is an object, it's likely from a Chrome App Extension and will not work in Firefox." 

**Additional notes:**
- This issue reproduces on AMO-dev using Firefox 54.0a1 (2017-03-01) under Windows 10 64-bit.
- Please see the attached screenshots for this issue:
![2017-03-02_1248](https://cloud.githubusercontent.com/assets/18114210/23504120/dd952818-ff46-11e6-9036-82f0f4065135.png)
![2017-03-02_1249](https://cloud.githubusercontent.com/assets/18114210/23504127/e1e3e922-ff46-11e6-996f-ca349d0c0d98.png)

**Comment by wagnerand** [comment]
@vasilicamihasca Could you please see if this is still an issue?

**Comment by vasilicamihasca** [comment]
Retested this issue on all 3 AMO branches (dev,stage and production) on Firefox 57.0a1 (2017-08-10) under Windows 10 64-bit and seems that the initial error is no longer reproducible and the following message is displayed in its place:     Permissions should NOT have duplicate items (items ## 0 and 1 are identical). 

@wagnerand, I have some doubts related to 2 things:
- Is it ok how the “##” are displayed? Is this a standard format?
- Having more than 2 identical permissions, they will not be all specified in the same error. They are grouped by 2. Is this intended? Or all duplicated items should be mentioned in one error? (Tested with the attached webextension, which has 5 identical permissions [duplicatedpermission1.zip](https://github.com/mozilla/addons-linter/files/1217384/duplicatedpermission1.zip))

![2017-08-11_1217](https://user-images.githubusercontent.com/18114210/29207490-0076888c-7e8f-11e7-9442-6c29768b5b00.png)

**Comment by wagnerand** [comment]
It seems like we're using a third party library (*ajv*) to detect and output duplicates. The notation seems ok to me, I am not sure how much we can do about finding multiple duplicate pairs. This might be an upstream bug, but I am not that familiar with *ajv*.

Summoning @mstriemer ...

**Comment by andymckay** [comment]
Notation looks good to me too. And I'm not too worried about detecting 3 or 5 permissions. It could be optimized, but we've got the basic case sorted out. People can keep removing permissions until they get it right :)

**Comment by vasilicamihasca** [comment]
@andymckay  I am not sure about “##” notation. Isn’t it a typo? Shouldn't be one # in front of each digit?

**Comment by andymckay** [comment]
It does seem odd, as @wagnerand says the error string is straight from ajv:

https://github.com/epoberezkin/ajv/blob/52e944b9faabdf5895041e1687e436ff72639d52/lib/dot/errors.def#L117

We could file an issue against ajv: https://github.com/epoberezkin/ajv

**Comment by wagnerand** [comment]
I can imagine this being an abbreviation for *numbers* (**plural**), whereas *#* is usually used for *number* (**singular**)
