### ISSUE TITLE
Duplicated error at webextension validation

### ISSUE THREAD

**Issue by vasilicamihasca** [mozilla/addons-linter#1153]
**Steps to reproduce:**
Submit on AMO-dev the attached webextension which contains duplicated keys in manifest.json: 
[duplicatederror.zip](https://github.com/mozilla/addons-linter/files/813725/duplicatederror.zip)

**Expected results:**
The error is specified only one time for each key.

**Actual results:**
The error is duplicated.

**Additional notes:**
- This issue reproduces on AMO-dev using Firefox 54.0a1 (2017-03-01) under Windows 10 64-bit.
- Please see the attached screenshots for this issue:
![2017-03-02_1421](https://cloud.githubusercontent.com/assets/18114210/23507010/b9c853bc-ff53-11e6-83dc-6d647d5a500d.png)
![2017-03-02_1412](https://cloud.githubusercontent.com/assets/18114210/23507052/ea23acaa-ff53-11e6-8165-0d47c6bbd8f7.png)

**Comment by EnTeQuAk** [comment]
This is very much expected so I'm closing this. The linter raises messages for every line that it finds. We could potentially collapse them in AMO but I don't think this is reasonable to do for now.
