### ISSUE TITLE
Add documentation about how to use this package programmatically

### ISSUE THREAD

**Issue by erikvold** [mozilla/addons-linter#1156]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

I can't seem to find any documentation about how to use this package programmatically instead via cli.  It would be nice if there was a node api which one could use instead of having to use subprocesses to call the cli, then parse the stdout.

### What happened?

I can't seem to find any documentation about how to use this package programmatically.

### What did you expect to happen?

There should be some docs that explain how to use this package via node/commonjs api instead of merely via cli.

**Comment by EnTeQuAk** [comment]
This is correct, at the moment it's mostly used via the command line. https://github.com/mozilla/web-ext/ uses it programmatically and we're profiting from any changes to make this easier, this isn't our current focus right now though.

We should and will work on this eventually though. Thanks for the report!
