### ISSUE TITLE
unexplained error: `"/incognito" should match pattern "^spanning$"`

### ISSUE THREAD

**Issue by erikvold** [mozilla/addons-linter#1170]
### What happened?

when I run `addons-linter src` on my add-on I get this error: `"/incognito" should match pattern "^spanning$"` I can't seem to find any docs about it.

### What did you expect to happen?

No error.

**Comment by andymckay** [comment]
@wbamberg could we create a page for the incognito manifest key and the support on the various browsers on MDN please? Then we can link to that page.

I tried but got a scripting error from MDN.

**Comment by andymckay** [comment]
The message is now different. It says ""/incognito" should  be equal to one of the allowed values" because it now is using the schema. 

The docs now exist at https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/incognito.

We could probably file a generic "point to the MDN docs page" when an error occurs on a manifest file as a new bug.

**Comment by wbamberg** [comment]
@andymckay , I've added https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/incognito and submitted a PR to add compat data: https://github.com/mdn/browser-compat-data/pull/216, which will indicate that "spanning" is the only supported value in Firefox.

But I'm a bit unclear how "split" and "not_allowed" work in Chrome.

With "split", do you get essentially 2 versions of the add-on, one in all non-private windows, one in private windows? Do they have the same ID? Do they share storage, for instance?

With "not_allowed", is the idea that private windows and tabs are just invisible to the add-on?

Perhaps it's not worth dealing with this until/unless it's supported in Firefox though.

**Comment by andymckay** [comment]
I have found that @Rob--W knows everything about Chrome so I'll summon him...

**Comment by Rob--W** [comment]
> With "split", do you get essentially 2 versions of the add-on, one in all non-private windows, one in private windows?

Yes. In Chrome with "spli", there will be two separate extension processes if the user has opted in to enabling the add-on in incognito mode.
With "spanning" there will be only one process, with all pages being in non-incognito mode. Chrome does not allow mixing incognito and non-incognito tabs, so a consequence of "spanning" is that extension pages cannot be opened in incognito windows.

> Do they have the same ID?

Assuming that you mean the value of `chrome.runtime.id`, yes. Firefox is the only browser that randomizes this value.

> Do they share storage, for instance?

`chrome.storage.local`? Yes. Whether the caller is in an incognito window has no influence on the execution of an API (with a few exceptions, e.g. the default value of "incognito" in the tabs/windows API and `chrome.extension.getViews()`).
`localStorage`? No. Regular web platform APIs are isolated.

> With "not_allowed", is the idea that private windows and tabs are just invisible to the add-on?

Yes. In Chrome, users have to opt in to enable an individual extension in incognito mode. The "not_allowed" value removes the ability to do so.

**Comment by wbamberg** [comment]
Thanks, that's very enlightening :). @andymckay, do you know how far back Firefox supports "incognito":"spanning"? As far back as 48?

**Comment by wbamberg** [comment]
Never mind, found it: https://bugzilla.mozilla.org/show_bug.cgi?id=1277686.
