### ISSUE TITLE
Let SemVer for WebExtensions add-on versioning

### ISSUE THREAD

**Issue by asamuzaK** [mozilla/addons-linter#1172]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

1. Create some WebExtensions add-on
2. Fill in `"version": "1.0.0-a.1"` for example in manifest.json
3. Upload to AMO

### What happened?

Upload is rejected due to version string.

### What did you expect to happen?

Accept version control in SemVer.

### Anything else we should know?
(Please include screenshots and any relevant files.)

Initially filed at [1345685 - WebExtensions: Let SemVer for versioning](https://bugzilla.mozilla.org/show_bug.cgi?id=1345685)

**Comment by gneatgeek** [comment]
+1

Albeit that the version number is a tad weird, but our generator came up with "10.1704.14.024" as a version number and the linter threw an error for it. Worked fine once the 0 was removed "10.1704.14.24".

**Comment by EnTeQuAk** [comment]
Before this can be tackled, addons-server needs to understand these versions properly too: https://github.com/mozilla/addons-server/blob/master/src/olympia/versions/compare.py - this is needed so that we can understand and compare versions across the system.

**Comment by julienw** [comment]
Here is my conversion function in JS:
```javascript
function semverToWebExtVersion(version) {
  return version.replace(/-(\w+)\.(\d+)$/, '$1$2');
}
```

**Comment by EnTeQuAk** [comment]
So this got closed because semver isn't supported by Firefox thus the linter can't support it either. @asamuzaK added lots of tests that verify a more correct behavior of our version format matching.
