### ISSUE TITLE
Linter misses innerHTML

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-linter#1187]
### Describe the problem and steps to reproduce it:

The add-on file at https://addons.mozilla.org/firefox/downloads/file/588154/joshua_tree_extension-3.0.9-an+fx.xpi includes _innerHTML_ calls which are not flagged by the linter.

### Anything else we should know?

scripts/contextMenu.js
104:        itemLink.innerHTML = menuItem.text;

scripts/editorEnhancements.js
38:        comment.innerHTML = constructPreviewHtml(commentInput.value);

**Comment by EnTeQuAk** [comment]
![screenshot from 2017-03-20 13-55-49](https://cloud.githubusercontent.com/assets/139033/24107101/c8f630de-0d81-11e7-9e2b-3ad4d26d03b5.png)

Works for me, the add-on probably got validated on AMO before we added that functionality. Closing this issue after our discussion IRC about revalidation of all add-ons in the queue but we agreed that that's too complicated for the enhancement we get.
