### ISSUE TITLE
Replace `singleLineString` with common-tags equivalent

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-linter#1199]
There is a wonderful package that provides an equivalent to our `singleLineString`, let's use it

https://www.npmjs.com/package/common-tags

**Comment by jvillalobos** [comment]
If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started. 

Mentor: @EnTeQuAk

**Comment by ValentinaPC** [comment]
Please add some STR for us to check this or the label "qa: not needed". Thanks!
