### ISSUE TITLE
Warn about `strict_max_version`

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-linter#1214]
I've seen at least a few developers include `strict_max_version` in their manifest files, and I don't think they're aware they don't need to include it. It'd be good to warn about it so developers avoid doing this. The warning message could be something like `strict_max_version shouldn't be used unless the add-on is expected not to work with future versions of Firefox.`

**Comment by andymckay** [comment]
@cgrebs, you took this bug in April, would you mind if I did it? Not sure if you have a patch planned.

**Comment by andymckay** [comment]
Got this in #1442 which didn't link up, sorry about that.
