### ISSUE TITLE
Fresh install produces ENOENT error

### ISSUE THREAD

**Issue by ineffyble** [mozilla/addons-linter#1217]
I just installed addons-linter for the first time with an npm global install.

Attempting to run any files gives the following error:
`Error: ENOENT: no such file or directory, scandir '../../usr/local/lib/node_modules/addons-linter/src/schema/imported'`

I've checked, and the node_modules/addons-linter folder contains no `src` directory.

I removed the package, and ran `npm install --global addons-linter@0.17.0`, which worked, so it's potentially an issue with latest version.

**Comment by EnTeQuAk** [comment]
This is being fixed in https://github.com/mozilla/addons-linter/pull/1215 and should be in a release-build soon.

**Comment by EnTeQuAk** [comment]
#1215 was merged, 0.18.1 got released and seems to be working now. Please feel free to re-open if that's not the case, otherwise I'm going to close this.

Thanks for the quick report!
