### ISSUE TITLE
Handle duplicate permissions error messages

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-linter#1240]
### Describe the problem and steps to reproduce it:
1. Set a permission to a non-string (like `24`).
2. Validate the extension.

### What happened?
You probably got a multiple errors stating that the permission must be a string. This is a bit annoying.

### What did you expect to happen?
One message stating it should be a string.

### Anything else we should know?
There was some work done in #1195 to hide duplicate messages. That should have some leads on where to look to fix this.

**Comment by ccarruitero** [comment]
Hi, I want to work on this issue.

I was checking the code and I think that if we only allow add a message to the collector if it had a different `dataPath` could solve the problem and show only one error in this case.
But not sure, What do you think?

**Comment by muffinresearch** [comment]
@ccarruitero yep - there's some functionality around that idea already see: https://github.com/mozilla/addons-linter/blob/e3c310e8efdb40dc50d96617f5c6708cbef1d786/src/collector.js#L69
