### ISSUE TITLE
Extract synchronized Firefox schemas into a new Node module

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-linter#1254]
It would be fantastic if the Firefox schemas [here](https://github.com/mozilla/addons-linter/tree/master/src/schema) were available as a separate Node module.

Here are a couple things I'd like to see the schemas used for:
* Static Flow analysis, possibly integrated into https://github.com/rpl/flow-typed-webextensions/
* WebExtension API mocks, possibly with something like https://github.com/acvetkov/sinon-chrome

For all of these things it wouldn't make sense to depend on `addons-linter` just to work with the synchronized schemas. In fact, the libraries mentioned above already use Firefox schemas but each are synchronized with mozilla-central independently.

If the schemas were available as a standalone Node module, every time it synchronized with Firefox and got a version bump all upstream deps could get a notification about it.

**Comment by muffinresearch** [comment]
@mstriemer do you have thoughts on this? Iirc it was already considered to some degree - are any things that might make doing this problematic?

**Comment by kumar303** [comment]
I think [webextension-polyfill](https://github.com/mozilla/webextension-polyfill) would really benefit from this too.
