### ISSUE TITLE
Make a non-beta release

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-linter#1257]
We've been using addons-linter in production for quite some time and it will soon be the only validator/linter we run on AMO. It is used by web-ext which is on version 1.9.0 and addons-linter is on version 0.19.1. Maybe it's time we make a non-beta release.

**Comment by EnTeQuAk** [comment]
I'd maybe target this for after the outreachy when we might land a few bigger releases which also should be around or shortly after Firefox 57 which marks a huge push of people developing WebExtensions and we get more and more feedback.

**Comment by AlexandraMoga** [comment]
Could you please add STR or the label "qa:not needed"?
Thank you
