### ISSUE TITLE
Do not require git for installation

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-linter#1259]
### Describe the problem and steps to reproduce it:

Try to install the linter (or `web-ext`) without having git on your machine

### What happened?

You get a cryptic `npm` error saying that git is not installed, probably triggered by this dependency: https://github.com/mozilla/addons-linter/blob/ca8b718821523fd9ad80dc8cbdd0018f49c0bba4/package.json#L82

### What did you expect to happen?

You should be able to install the linter without git

### Anything else we should know?
(Please include screenshots and any relevant files.)

@EnTeQuAk could you publish that module to npm instead?

Here is the web-ext bug report https://github.com/mozilla/web-ext/issues/933

**Comment by muffinresearch** [comment]
Assigning @EnTeQuAk since the linked package is his fork.

**Comment by muffinresearch** [comment]
Looks like consuming the package https://github.com/mozilla/eslint-plugin-no-unsanitized would now contain the relevant patches.

**Comment by muffinresearch** [comment]
> Looks like consuming the package https://github.com/mozilla/eslint-plugin-no-unsanitized would now contain the relevant patches.

Actually it's not published on npm yet

**Comment by wagnerand** [comment]
Hm, I think it is.

**Comment by muffinresearch** [comment]
> Hm, I think it is, which is why I included it in #1271

Ah ok - that fixes this issue 👍 -  I was talking about `eslint-plugin-no-unsanitized`  which is the new name for this package, but that can be handled separately.

**Comment by kumar303** [comment]
Thanks @wagnerand
