### ISSUE TITLE
Migrate from eslint-plugin-no-unsafe-innerhtml to eslint-plugin-no-unsanitized

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-linter#1273]
The package `eslint-plugin-no-unsafe-innerhtml` has been renamed and been released as `eslint-plugin-no-unsanitized` on npm. The new package is version 2 and the changelog suggests there are breaking changes so filing this to handle it independently.

**Comment by jonathanKingston** [comment]
Please let me know if there are issues.

The breaking changes that will impact you are:

- Different config to use
- Some error messages changed slightly (I know you regex them, ESLint hasn't resolved the issue we filed for shareable params)
- Some new error messages thrown

**Comment by jonathanKingston** [comment]
This somewhat hinges on: https://github.com/eslint/eslint/issues/8344 it could be implemented without however would be cleaner for us to provide a blob of stuff instead of a string.

**Comment by jonathanKingston** [comment]
ESLint ended up closing my issue; then solving it in another bug despite them suggesting they only wanted to do messageIDs: https://github.com/eslint/eslint/issues/6740 

Either way this should allow us to colab on some shape between each other. I think @mozfreddyb and I can take a first stab at what data you will need here so we can get this moving :).

**Comment by muffinresearch** [comment]
> ESLint ended up closing my issue; then solving it in another bug despite them suggesting they only wanted to do messageIDs: eslint/eslint#6740

That's great news!

**Comment by ncaq** [comment]
eslint < 4.18.2 has bug.
[Fix: remove catastrophic backtracking vulnerability (fixes #10002) (#… · eslint/eslint@f6901d0](https://github.com/eslint/eslint/commit/f6901d0bcf6c918ac4e5c6c7c4bddeb2cb715c09)
However eslint-plugin-no-unsafe-innerhtml has `eslint@3.19.0` in dependencies(no devDependencies).
So GitHub notice security issue project that depend addon-linter.
I think to this pull request priority that is high.

**Comment by mozfreddyb** [comment]
Yeah. eslint-plugin-no-unsafe-innerhtml is deprecated. It would be good to move on.
