### ISSUE TITLE
start script failed

### ISSUE THREAD

**Issue by ccarruitero** [mozilla/addons-linter#1280]
### Describe the problem and steps to reproduce it:

- Clone the repo
- install dependencies (`npm install`)
- Run `npm start`

### What happened?
the script is aborted with this message
```
Running "webpack:buildwatch" (webpack) task
Warning: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.cache should be one of these:
   boolean | object
   Cache generated modules and chunks to improve performance for multiple incremental builds.
   Details:
    * configuration.cache should be a boolean.
    * configuration.cache should be an object. Use --force to continue.
```

### What did you expect to happen?
Complete the build and watch the files

### Anything else we should know?
I found that adding `cache` option for the [buildwatch](https://github.com/mozilla/addons-linter/blob/master/tasks/webpack.js#L26) task seems to solve the problem.

I think that could be a bug in `grunt-webpack`, but not sure.

**Comment by wagnerand** [comment]
Thank you for the report
