### ISSUE TITLE
Flag violations of "Mozilla conditions of use"

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-linter#1285]
This will be based on a list of forbidden terms.

**Comment by diox** [comment]
Worth noting that, as with the other post-review related things to flag, this should only be added to the metadata, not block submission. (Not sure if that should be exposed to the developers either)

**Comment by andymckay** [comment]
I believe it should be exposed to developers, we shouldn't be surprising them but be as up front and clear. Should this be something in the linter?

**Comment by diox** [comment]
The problem is false positives: there is no foolproof way of doing this detection, which is why it has been left to the appreciation of reviewers until now. 

With the post-review process, the add-on would be automatically approved, the flag would only make the priority of the add-on go up in the post-review queue so that an human reviewer can look at it.

It should not come as a surprise to developers: it will be clearly indicated in the agreement that should be presented at submission time. Per the [Post-Review Implementation Plan](https://docs.google.com/document/d/1rZvM2QGk8WtkNUDRvLEvrbqZ190hvHfOle4zVRllQmw/edit#): 
> Developer Agreement, Review Policy, and Review Rules. Each document will have a checkbox next to it indicating the developer has read them and agreed to them. Ensure all developers see these documents on their next submission, even for an update.

**Comment by jvillalobos** [comment]
I think showing these flags to developers is good, for the sake of transparency and self-policing.

**Comment by muffinresearch** [comment]
@jvillalobos Can you point to the list of terms to be checked for?

**Comment by jvillalobos** [comment]
Here's a list I found online. It was about twice as long, and I removed a bunch of terms that didn't seem necessary to flag. @atsay, can you give this a look and see if it looks right or needs changes?
[flagged-terms.txt](https://github.com/mozilla/addons-linter/files/1082140/flagged-terms.txt)

**Comment by jvillalobos** [comment]
Here's an updated list after some review.
[flagged-terms.txt](https://github.com/mozilla/addons-linter/files/1088479/flagged-terms.txt)

**Comment by ValentinaPC** [comment]
Please add some STR for us to check this or the label "qa: not needed". Thanks!

**Comment by EnTeQuAk** [comment]
This got backed out recently.

**Comment by ValentinaPC** [comment]
Verified this using AMO-dev FF55(Win 7).
@EnTeQuAk please see my results:

1. After submitting a webextension that has a restricted term in its name, a warning is displayed, but only in the validation report - expected?

2. The webextension gets auto-approved but the weight is incremented only with 10 - https://addons-dev.allizom.org/en-US/editors/review/asshat or with no value - https://addons-dev.allizom.org/en-US/editors/review/butt, and not 20 as listed in the Post Review Prioritization doc - did the value changed? I am missing something out?

3. Also, if the add-on name contains 2, 3 restricted words the weight is not incremented at all - expected?
Example: https://addons-dev.allizom.org/en-US/editors/review/bitch-bitched-bitches

4. Beside add-on name and description, are there some other places where these restricted words can be added to raise a violation flag?

**Comment by EnTeQuAk** [comment]
> After submitting a webextension that has a restricted term in its name, a warning is displayed, but only in the validation report - expected?

Yes, this is only a notice not a warning. The results of this tagging/flagging are used later for post-review risk scoring but using bad words isn't a blocker to get something submitted so this is fine.

> The webextension gets auto-approved but the weight is incremented only with 10 - https://addons-dev.allizom.org/en-US/editors/review/asshat or with no value - https://addons-dev.allizom.org/en-US/editors/review/butt, and not 20 as listed in the Post Review Prioritization doc - did the value changed? I am missing something out?

This is simply not yet added to the risk scoring, that's a separate issue so fine for now.

> Also, if the add-on name contains 2, 3 restricted words the weight is not incremented at all - expected?
Example: https://addons-dev.allizom.org/en-US/editors/review/bitch-bitched-bitches

Fair point, this might be a bug but edge-casy… I'll check with product and others and get back to you on that whether or not this is expected.

**Comment by jvillalobos** [comment]
> Also, if the add-on name contains 2, 3 restricted words the weight is not incremented at all - expected?

It's intentional. Most prioritization weights are binary to avoid one factor overwhelming the others. We will probably have to make adjustments as we use it.

**Comment by ValentinaPC** [comment]
We can mark this verified-fixed based on above comments.
