### ISSUE TITLE
Flag permissions that are required but not used

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-linter#1286]
If a developer asks for various permissions that are not used it would be helpful to flag this during the lint process.

This might be difficult to do, so it needs investigation for viability and to provide some examples.

**Comment by EnTeQuAk** [comment]
As far as I can tell the schema have a `permissions` property that marks APIs requiring a specific permission so we might be able to collect what APIs are used, collect the `permissions` and just diff with the manifest.

**Comment by EnTeQuAk** [comment]
We also have perfectly good APIs to access the schema properties since we already warn about deprecated, temporary or unsupported APIs so fetching the permissions along the way seems reasonable.

**Comment by EnTeQuAk** [comment]
Actually, is this a duplicate of #978?
