### ISSUE TITLE
Do not ignore node-modules/bower_components folder in add-ons

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-linter#1288]
If an add-on includes a `node-modules` folder, each JS file in that folder raises the following warning:
`Warning: File ignored by default. Use "--ignore-pattern '!node_modules/*'" to override`.

We should not ignore contents of that folder.

**Comment by muffinresearch** [comment]
Related to https://github.com/mozilla/addons-linter/issues/1141

**Comment by kewisch** [comment]
Same with bower_components `File ignored by default. Use "--ignore-pattern '!bower_components/*'" to override.`

https://addons.mozilla.org/en-US/developers/addon/cyberalterego/file/636394/validation
