### ISSUE TITLE
Exclude webpack eval from being flagged

### ISSUE THREAD

**Issue by kewisch** [mozilla/addons-linter#1300]
### Describe the problem and steps to reproduce it:
All add-ons using webpack will trigger an eval warning, which is not helpful. The code is try-catched, and just used to detect the global:

https://github.com/werbug/webpack/commit/2ff9a247e242f716b8ad41da460ca57108617d36

This triggers an eval warning in the linter which we should ignore.

https://addons.mozilla.org/en-US/editors/review/exactly-english-dictionary
https://addons.mozilla.org/en-US/firefox/files/browse/630790/file/build/js/babel.bundle.js#top

**Comment by muffinresearch** [comment]
This needs to be excluded by the upstream project https://github.com/mozilla/eslint-plugin-no-unsanitized

**Comment by EnTeQuAk** [comment]
This requires `no-new-func` to be modified too but tbh right now I have no idea how we could even remotely detect that other than looking for the try/except around it and pray to god it's insides are not harmful? Enabling `allowIndirect` for `no-eval` "fixes" this warning for this specific code, then there's only `no-new-func` raising a warning.

I'm open to suggestions :)
