### ISSUE TITLE
Switch to jest for tests

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-linter#1303]
Jest is a really great test-runner, it would be great to use for addons-linter using the node test environment setting.

Moving to Jest will allow us to:

* Remove the separate coverage instrumentation.
* Makes tests feedback very fast and provides much more control.

Since it bypasses webpack it will be necessary to ensure the build still works.

**Comment by EnTeQuAk** [comment]
This is actually fixed now.
