### ISSUE TITLE
Expose total size of "code" files in metadata

### ISSUE THREAD

**Issue by diox** [mozilla/addons-linter#1304]
For [post-review queue prioritization purposes](https://github.com/mozilla/addons-server/issues/5473), we'd need the total size of all "code" files (manifest, css, js, etc) in each add-on exposed in the metadata returned by the linter. Libraries ignored because of dispensary should not count towards the total.

The name of the property doesn't matter, the unit should probably be bytes.

**Comment by EnTeQuAk** [comment]
Side note, we already calculate the file-size in the linter to block files that are too large: https://github.com/mozilla/addons-linter/blob/master/src/linter.js#L361

So there's already code to grab it, guess we simply need to store and expose the total.

**Comment by EnTeQuAk** [comment]
This should also be easier once https://github.com/mozilla/addons-linter/pull/1296 lands

**Comment by ValentinaPC** [comment]
Please add some STR or the label "qa: not needed". Thanks!

**Comment by ValentinaPC** [comment]
@diox : I see that weight will be implemented in https://github.com/mozilla/addons-server/issues/6033.
Is there anything else we can see after these changes, at validation maybe?
Thanks!

**Comment by diox** [comment]
Currently you can't see anything, no.

**Comment by ValentinaPC** [comment]
Based on above comments we can mark this verified fixed.
