### ISSUE TITLE
Update eslint rules for this codebase.

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-linter#1306]
It would be good to consolidate the lint rules and add things like [prefer const over let](http://eslint.org/docs/rules/prefer-const) and update it. 

For example we have a lot of `for of`/`for in` loops that use `let` but could use `const`.

mozilla/addons-frontend probably has a good configuration (though obviously the react pieces can be ignored for this project) - a longer term plan would be to extract those rules out and make them shareable.

**Comment by pdehaan** [comment]
> For example we have a lot of `for..of`/`for..in` loops that use `let` but could use `const`.

Using `const` instead of `let` used to cause issues in earlier versions of Firefox. Ref: https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Statements/for...of#Gecko_note_2

> _Prior Firefox 51, using the `for...of` loop construct with the `const` keyword threw a `SyntaxError` ("missing = in const declaration"). This has been fixed ([bug 1101653](https://bugzilla.mozilla.org/show_bug.cgi?id=1101653))._

**Comment by muffinresearch** [comment]
@pdehaan thanks for the info. This is a node application and this issue is solely about changing how we write code in this code-base rather than anything in regard to rules used to lint web-ext for FF.

**Comment by muffinresearch** [comment]
This was fixed in that we now use the eslint-config-amo.
