### ISSUE TITLE
Add some code that verifies and normalizes `filename` in `recordScannedFile`

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-linter#1310]
This should avoid unneccessary duplicates.

**Comment by EnTeQuAk** [comment]
Note to whoever wants to work on this: The idea here is that `filename` should be normalized a bit - all lower-cased etc. More importantly is a bit of research what `filename`s `recordScannedFile` will see, it's being called in `src/linter.js` around line 402, I am honestly not too sure.

If it turns out that the `filenames` are unique and have their full path this issue probably doesn't need an implementation but at the very least a unittest to verify we handle this correctly.

**Comment by tmoskun** [comment]
Can I take this issue?

**Comment by EnTeQuAk** [comment]
This isn't really a thing to do anymore.
