### ISSUE TITLE
Warn when detecting a <script> tag with a remote URL

### ISSUE THREAD

**Issue by diox** [mozilla/addons-linter#1321]
For post-review, we want to increase priority of add-ons using a `<script>` with a remote URL. The linter should detect this and add a warning with a specific code that addons-server can look for.

**Comment by ValentinaPC** [comment]
Please add some STR for us to check this or the label "qa: not needed". Thanks!

**Comment by diox** [comment]
ValentinaV: include an html page in your add-on with a remote `<script>` element, like this: `<script src="http://foo.bar/my.js"></script>`

The linter should then add a warning. Note that the post-review weight part is not done, that'll be handled in #6033.

**Comment by ValentinaPC** [comment]
Verified this as fixed on AMO-dev FF55(Win 7) in what concerns the linter warning.
The weight will be checked in https://github.com/mozilla/addons-server/issues/6033.
Postfix screenshot form validation report:
![script](https://user-images.githubusercontent.com/15685960/30028184-bc2791b0-918c-11e7-91e3-b372d5626d97.png)
