### ISSUE TITLE
Warn when detecting synchronous (non-local) HTTP requests

### ISSUE THREAD

**Issue by diox** [mozilla/addons-linter#1322]
For post-review, we want to increase priority of add-ons using synchronous (non-local) HTTP requests. The linter should detect this and add a warning with a specific code that addons-server can look for.

**Comment by EnTeQuAk** [comment]
I don't really understand what should be flagged here. Are we talking about https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/webRequest and the use of the `blocking` argument? I mean, there is `XMLHttpRequest` and https://developer.mozilla.org/en-US/docs/Web/API/GlobalFetch/fetch which both seem to work in WebExtensions, both `fetch` and `webRequest` seem to be asyncronous though so this should essentially flag syncronous usage of `XMLHttpRequest`?

**Comment by wagnerand** [comment]
> this should essentially flag syncronous usage of XMLHttpRequest?

That. :)

**Comment by EnTeQuAk** [comment]
> That. :)

Awesome! Thanks, that helps.
