### ISSUE TITLE
Fetch npm library hashes to detect libraries more broad

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-linter#1326]
cc @wagnerand and @muffinresearch on this for input.

When I thought about a few things for our post-review process I noticed that the list of libraries we actually can detect is fairly short. Especially in our modern world where people use npm to install dependencies.

So my proposal for a better detection of libraries:

…based on the list of libraries we care about (anuglar, jquery etc...)

 * Fetch hashes and file-names of packages distributed on npm in addition to our staticly configured names (that usually represent how these libraries are distributed on CDNs)
  * This should probably happen in dispensary
 * Make sure `BANNED_LIBRARIES` is using hashes for detection in addition to file-names too

This should make the detection of https://github.com/mozilla/addons-linter/issues/1323 or https://github.com/mozilla/addons-linter/issues/1304 much more reliable.

**Comment by wagnerand** [comment]
We intentionally removed fetching from NPM, rationale is in https://github.com/mozilla/dispensary/issues/200. Does that make sense to you?

**Comment by EnTeQuAk** [comment]
> sometimes the versions on NPM differ from those elsewhere

thats precisely why I vote for actually implementing it. I am aware that this won't be easy to do. I'd like to give it a try, just a plain simple MVP and see how that goes. I personall would love for us to have both, the manually added hashes and filenames (because CDNs and direct downloads) and npm packages.

**Comment by wagnerand** [comment]
Can you elaborate on how your approach is going to be different from what we used to have in dispensary?

**Comment by muffinresearch** [comment]
> Fetch hashes and file-names of packages distributed on npm in addition to our staticly configured names (that usually represent how these libraries are distributed on CDNs)

I don't think I completely understand the check you're proposing to implement. What would the hash be made from and compared with? Maybe I'm missing something but I don't see obvious reliable way to compare source packages on npm with unpacked modules in a node_modules directory supplied in the xpi.

**Comment by muffinresearch** [comment]
@EnTeQuAk where did we get to on this - I'm not sure there's a clear outcome on this yet. We should also revisit the existing libs for additional detection since they might provide an easier way forward.

**Comment by muffinresearch** [comment]
Closing this out in favour of looking in a different direction.
