### ISSUE TITLE
Do we want to localize the linter?

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-linter#1330]
Initially when the linter was started we didn't want to rule out the idea of localizing the linter. 

However we've not gone any further than wrapping strings with noop gettext functions etc.

Do we want to actually localize the linter? In considering this we'd need to weigh up the engineering cost versus the value it would bring for the linter's community of users. 

If we decide not to proceed then we can rip out the gettext and friends.

/cc @jvillalobos

**Comment by tofumatt** [comment]
The npm stats indicate that the linter is downloaded a reasonable amount:

<img width="327" alt="screenshot 2017-06-07 20 49 02" src="https://user-images.githubusercontent.com/90871/26898152-cf95c8a8-4bc2-11e7-8987-d7e816e1761f.png">

If we have any way to contact those users or even ask them maybe during next time they run the linter with a little prompt–it would be cool to know if they'd enjoy a localised linter. From my experience, lots of add-on developers' first language isn't English.

**Comment by andymckay** [comment]
The validator was never localised, but I think this would be a nice thing to do. We've got a large number of international developers and the documentation on MDN is being translated.

Localising errors from eslint or JSON schema sounds like it could be hard.

Would pushing error to be a URL and place a link to a website (eg MDN or AMO), make sense? The localisation could then occur on that website. Its something we do for a lot of cases already.

**Comment by jvillalobos** [comment]
Most communications we have with developers, including review messages, are exclusively in English, so we're already forcing them to use English to some extent. Being fully localized is always a noble goal, but it seems unrealistic in this case.

Documenting all linter flags on MDN or some other place that can be localized would be awesome, but it's also one of those things that probably won't happen or won't be updated due to lack of resources.

**Comment by tofumatt** [comment]
The thing about localisations happening with the linter is that we already have the gettext wrapper set up… so aside from a bit of process around extracting and using the strings, there isn’t much that has to happen to the app to localise it. I think it’s not worth the effort to remove the fake get text at the very least. It’s very little/no technical debt.

**Comment by andymckay** [comment]
How about messages back from other libraries, or dynamically built text, eg: json schema? Just don't bother with those?

**Comment by tofumatt** [comment]
> How about messages back from other libraries, or dynamically built text, eg: json schema? Just don't bother with those?

Those will definitely be more work. Something is better than nothing I think, but translating those might be quite difficult, yeah 😢

**Comment by EnTeQuAk** [comment]
We do have a system now though to overwrite them to some extend and
there's work going on in eslint to allow definition of message ids so
that we can overwrite more and more detailed messages later.It'd say it's worth trying, eslint is the only source that's
currently using 3rd party rules and half of them use our own
messaging already anyway.

On Thu, Jun 8, 2017, at 05:09 AM, tofumatt ☕️ wrote:
>> How about messages back from other libraries, or dynamically built
>> text, eg: json schema? Just don't bother with those?> Those will definitely be more work. Something is better than nothing I
> think, but translating those might be quite difficult, yeah 😢> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].> 

Links:

  1. https://github.com/mozilla/addons-linter/issues/1330#issuecomment-306939762

**Comment by muffinresearch** [comment]
Ok I've filed a tracker as a prospective outreachy focus see #1535 for details.
