### ISSUE TITLE
chrome_settings_overrides should always be flagged on WebExtensions

### ISSUE THREAD

**Issue by mkaply** [mozilla/addons-linter#1335]
Because chrome_settings_overrides has the potential to be abused, it should be something that automatically flags extensions for admin review.

In that review, we should make sure the description of the add-on clearly states that it either changes the homepage or search engine.

The reason Google doesn't need this is because it only allows homepages or search engines to be set to the verified domain on the Chrome store account.

**Comment by wagnerand** [comment]
Thanks for filing!

I'm not sure what role the admin flag will play in a post-review world, but I guess we can assign a risk factor to this. @jvillalobos what do you think?

**Comment by mkaply** [comment]
Even in a post review world, aren't we still going to be able to flag certain things as review no matter what?

**Comment by wagnerand** [comment]
We won't "flag" add-ons for review, we will prioritize reviews based on signals ("flags") from the validation pipeline.

**Comment by andymckay** [comment]
This currently doesn't allow you to set the default search engine, just add search engines. Changing the default search engine is a sensitive topic that we'll need to bounce up to @deadsquid and others on exactly how we want to handle this.

**Comment by jvillalobos** [comment]
Changing the default is where I would draw the line for a flag. I don't think adding engines poses a big enough risk to warrant this test.

**Comment by wagnerand** [comment]
`chrome_settings_overrides` and `chrome_url_overrides` currently allow to override the default homepage and newtab.

**Comment by jvillalobos** [comment]
I agree those cases should be flagged, then.

**Comment by andymckay** [comment]
Does the term "flag" have any meaning yet? Should there be a blocking bug for that?

**Comment by wagnerand** [comment]
In this case "flagging" means that it should probably be assigned a risk factor and perhaps a warning should be added for reviewers.

**Comment by muffinresearch** [comment]
There are now doorhangers for this to confirm it in-product. Closing.
