### ISSUE TITLE
Icon could not be found in manifest.json

### ISSUE THREAD

**Issue by YehudaK** [mozilla/addons-linter#1374]
One week ago I successfully uploaded my new web extension. It was accepted without error but I was instructed that this migration is one way. I was offered to submit hybrid extension first, so I canceled migration to read more about hybrid addons. Today, when I decided to submit the same extension, I got error message that icon files are missing:

> An icon defined in the manifest could not be found in the package.
> Error: Icon could not be found at "./data/img/icon16.png".
> manifest.json

I tried to change relative path to "/data/img/icon16.png" without any success. I double checked archive which I am uploading and it contains giving files under this path. Here is how I declare icon files in manifest:

```
  "icons": {
    "16": "./data/img/icon16.png",
    "48": "./data/img/icon48.png",
    "128": "./data/img/icon128.png"
  },
```

Seems like server side extension validation script has issue. Thanks

**Comment by vcarciu** [comment]
Verified as fixed : 
![pathtoicons](https://user-images.githubusercontent.com/1583842/27689549-32ac1fc0-5ce7-11e7-8c23-d67cf4961b2c.png)
