### ISSUE TITLE
yarn test should run watch and not coverage by default

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-linter#1391]
Would be nice to have the default test command be more useful in development. 

By default running coverage slows things down too so that could be skipped by default.

Moving what the current test command does to a CI specific command would mean that the right things continue to be run for CI.

**Comment by kumar303** [comment]
Is this still happening? I deleted everything in my `coverage` directory, started `yarn test`, and triggered a run of all tests -- after that my `coverage` directory was still empty.

**Comment by EnTeQuAk** [comment]
It's still reporting the coverage though which probably slows things down.

**Comment by kumar303** [comment]
Hah, ignore me. I thought this was an issue in `addons-frontend`; I wasn't even trying this in the linter at all. Sorry!
