### ISSUE TITLE
Do you need an automated code style review tool?

### ISSUE THREAD

**Issue by tgrundmanis** [mozilla/addons-linter#1395]
Myself and a cofounder created a style linter developer tool that comments on style errors in GitHub pull requests (for 15 languages and counting). It is free for open source projects.

You can check out the product on https://stickler-ci.com. Just authorize your GitHub account, enable a public repo, and then open/update an existing pull request (or create a new pull request).

**Comment by muffinresearch** [comment]
For us linting is already a test fail, so we avoid most stylistic issues as part of the code review process already.
