### ISSUE TITLE
Deleting an addon that hasn't been reviewed doesn't let you resumbit it from another account.

### ISSUE THREAD

**Issue by telliott** [mozilla/addons-linter#1409]
### Describe the problem and steps to reproduce it:
Uploaded an XPI to my account. Realized it should be uploaded to the project account. Deleted the XPI from the submission queue. Submitted XPI from project account. 

### What happened?
Upload rejected due to duplicate addon-id

### What did you expect to happen?
Upload accepted.

**Comment by telliott** [comment]
Confirmed that this is intended behavior for understandable security reasons. I'm noting it because it's a bit strange to do before the addon has ever been reviewed, but I suspect you can just close as wontfix.

**Comment by jvillalobos** [comment]
Yes, it's intended. You can change the owner account after uploading.
