### ISSUE TITLE
Browser API check fails with "Warning: undefined.undefined is not supported"

### ISSUE THREAD

**Issue by kewisch** [mozilla/addons-linter#1410]
The linter seems to be choking on the following code:

    chrome['contextMenus']['onClicked']['removeListener'](function(tab) {

With the following message:

    Warning: undefined.undefined is not supported
    
    This API has not been implemented by Firefox.

https://addons.mozilla.org/en-US/firefox/files/compare/673243...574262/file/ci.bg.pack.js#L885

**Comment by muffinresearch** [comment]
@kewisch is this still happening with the latest version - there was a recent schema update.

**Comment by kewisch** [comment]
This seems to work now, thanks for checking in!
