### ISSUE TITLE
Can't run tests on Windows 10

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-linter#1441]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

cd addons-linter
npm test

### What happened?

No tests run

### What did you expect to happen?

Tests run

### Anything else we should know?
(Please include screenshots and any relevant files.)

Under cygwin:

```
~/sandboxes/addons-linter npm test

> addons-linter@0.22.7 test c:\Users\andy\sandboxes\addons-linter
> jest tests/ --runInBand --coverage

No tests found
In c:\Users\andy\sandboxes\addons-linter
  195 files checked.
  testMatch: c:\Users\andy\sandboxes\addons-linter\**\[Tt]est(*).js?(x),c:\Users\andy\sandboxes\addons-linter\**\__tests__\**\*.js?(x) - 0 matches
  testPathIgnorePatterns: c:\\Users\\andy\\sandboxes\\addons-linter\\node_modules\\,c:\\Users\\andy\\sandboxes\\addons-linter\\tests\\fixtures\\,c:\\Users\\andy\\sandboxes\\addons-linter\\(bin|coverage|dist|docs|src)\\ - 195 matches
Pattern: "tests/" - 0 matches
----------|----------|----------|----------|----------|----------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
----------|----------|----------|----------|----------|----------------|
All files |  Unknown |  Unknown |  Unknown |  Unknown |                |
----------|----------|----------|----------|----------|----------------|
```

Similar on a normal command prompt.

**Comment by EnTeQuAk** [comment]
There's quite a few open windows bugs open on Jest, see https://github.com/facebook/jest/issues/3121 and linked issues there. Not sure what to do about it, it seems `testMatch` contains something that is wrongly escaped or not escaped and thus no tests are found on your machine.

I don't have windows so I can't really test this locally. I might be able to grab have a windows laptop from family so do you have a relatively straight forward way of getting me to run the linter on a windows machine?

**Comment by andymckay** [comment]
I'd be tempted to wait for Jest to fix it and let me retest it when they do.

**Comment by Divya063** [comment]
@andymckay @EnTeQuAk  I use windows and I'm getting this on executing the command `npm test`
![screenshot 256](https://user-images.githubusercontent.com/21216969/30603754-23708e6c-9d86-11e7-8eb1-6f23343a760f.png)
After pressing "a" to run all the tests
![screenshot 255](https://user-images.githubusercontent.com/21216969/30603806-54f6c956-9d86-11e7-9261-7e336fe5af68.png)

**Comment by EnTeQuAk** [comment]
@Divya063 please make sure you're using the latest master and run `npm install` (or `yarn install` depending on how you installed everything) to ensure eslint get's upgraded to the latest version. This got fixed in https://github.com/mozilla/addons-linter/pull/1515

**Comment by Divya063** [comment]
@EnTeQuAk Thanks for the update :)

**Comment by EnTeQuAk** [comment]
Soooo, we do have appveyor running tests now and they're stable and green. I'm going to close this but please let me know if anyone runs into any problems with using Windows.
