### ISSUE TITLE
Run eslint on bin/addons-linter

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-linter#1487]
JS linting/style errors aren't being caught in `bin/addons-linter`; I'm guessing we don't include it in our files to lint.

We should! 😄

This should just be a matter of adding it to the files `eslint` scans.

**Comment by wagnerand** [comment]
Mentor: @tofumatt 

If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started.

**Comment by pdehaan** [comment]
Yeah, I think ESLint only validates *.js files by default. But I think this is as easy as tweaking the package.json `eslint` script to include the `bin/*` directory as well (since those files don't include file extensions).

**Comment by Divya063** [comment]
can I take this issue?

**Comment by tofumatt** [comment]
Yes, that’s totally fine. Thanks! :-)

**Comment by Divya063** [comment]
@tofumatt Tweaking the eslint script to `"eslint": "eslint bin/* ."` is working  fine while using the command `npm run eslint`

**Comment by muffinresearch** [comment]
@Divya063 I've tentatively added this to the upcoming milestone (if it needs to move into the next one, that's not a problem it can be updated as needed) - let us know if you have any questions.

**Comment by Divya063** [comment]
@muffinresearch I was wondering if changing the eslint script to `"eslint": "eslint bin/* ."` would be a right approach as all the *.js files  and files under bin folder are getting included while running `npm run eslint`.

**Comment by tofumatt** [comment]
I think the best way to test this is to create a patch using your proposed solution (which sounds like it would work to me), and then create a linting error in a file in `bin/addons-linter` and also somewhere in the regular code base (a file in `src` and a file in `tests`).

**Comment by muffinresearch** [comment]
This is currently blocked by #1517

**Comment by muffinresearch** [comment]
Ok this is unblocked now, I've landed a fix to re-enable linting via CI.

**Comment by ValentinaPC** [comment]
Please add some STR for us to check this or the label "qa: not needed".
Thanks!
