### ISSUE TITLE
linter should report wrong min version for APIs usage, based on mdn/browser-compat-data

### ISSUE THREAD

**Issue by yfdyh000** [mozilla/addons-linter#1493]
### Describe the problem and steps to reproduce it:
e.g. https://github.com/M-Reimer/undoclosetab/pull/9

### What happened?
No errors or warnings reported.

### What did you expect to happen?
Based on https://github.com/mdn/browser-compat-data/tree/master/webextensions, check for possible errors and report in amo validator and `web-ext lint`.

**Comment by EnTeQuAk** [comment]
I think this is a great idea, we already have our linter use the official schema for validation but that schema is not yet versioned so either we start versioning the schema and report based on that or indeed use mdn/browser-compat-data which seems quite extensive. I don't know if the browser-compat-data contains all APIs though, maybe @andymckay knows how that's maintained?

**Comment by EnTeQuAk** [comment]
Note to myself: https://github.com/mdn/browser-compat-data#installation - browser-compat-data is available as an npm package which should make things easier.

**Comment by andymckay** [comment]
@EnTeQuAk that repo is maintained by @wbamberg and the MDN team.
