### ISSUE TITLE
Inline script warning should only appear when scripts are actually executed

### ISSUE THREAD

**Issue by kewisch** [mozilla/addons-linter#1516]
### Describe the problem and steps to reproduce it:
Visit https://addons.mozilla.org/en-US/firefox/files/compare/704052...577665/file/templates/plids.extensions.popup.main.search.htm#top

![image](https://user-images.githubusercontent.com/607198/30056761-47397758-9234-11e7-8661-6f7374ba5f05.png)

### What happened?
A validator message appeared saying `Warning: Inline scripts blocked by default`, but the "script" is actually just a HTML template: `<script type="text/html" id="my-html-template-used-in-knockout">`

### What did you expect to happen?
The validator should just warn for scripts that actually execute, i.e. `type="something with javascript"` and without a type attribute. Possibly ask security if there are other cases.

**Comment by wagnerand** [comment]
Might be a good first bug.

We want to add a check in `src/rules/html/warn-on-inline.js` to make sure the type is JavaScript.

I could mentor this.

**Comment by wagnerand** [comment]
Mentor: me.

If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started.

**Comment by vcarciu** [comment]
Verified as fixed. Used the script from description and the "Warning : inline scripts blocker by default" is not displayed anymore(it was displayed yesterday with same script) : 
![inline](https://user-images.githubusercontent.com/1583842/30375398-1032d994-9891-11e7-88d5-c39a8ea3ef0f.png)
