### ISSUE TITLE
Support WebExtensions Language Packs in the linter

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-linter#1526]
Part of https://github.com/mozilla/addons-server/issues/6297

[Bug 1365709](https://bugzilla.mozilla.org/show_bug.cgi?id=1365709) introduces language packs that use WebExtensions packaging. We need to be able to validate them like the old validator does.

- [ ] The main thing to check for is that language packs should only be allowed to use metadata manifest properties and language pack manifest properties. They must not include any others. The schema [can be found here](https://hg.mozilla.org/mozilla-central/rev/960c3df4ced4#l2.12).
- [ ] I don't know if the legacy validator checks for anything else. If so, we need to discuss if it's worth porting.

**Comment by diox** [comment]
Extra check from mozilla/addons-server#6350 that makes more sense in the linter:
- [ ] If it's a language pack, *force* `strict_min_version` and `strict_max_version` to be present (addons-server will validate that the versions are correct)

**Comment by EnTeQuAk** [comment]
Assigning this for me for now for tracking, afaik we decided to not mark this as contrib: welcome to have this completed earlier rather than later to make releasing support for it more predictable.

I can take a look at this next week.

**Comment by EnTeQuAk** [comment]
@jvillalobos amo-validator contains a few more checks for language packs:

* A test for l10n completeness - as far as I know checks that a certain amount of strings is actually translated
That's quite a lot of code that would need porting so depending on how important that is I'd rather do that in a separate step

* Verify that all DTD files are either ASCII or UTF-8 encoded.
I think that can and should be kept.

* Verify package layout - makes sure that it only contain a `install.rdf`, `chrome.manifest`, `chrome/*.jar` and files with `.manifest`, `.rdf`, `.jar`, `.dtd`, `.properties`, `.xhtml`, `.css` extensions.
This can and probably should be kept. From what I see the new language packs contain the following files: `*.dtd` (containing translations), `*.properties` (also containing translations)
There's a search-plugin in the `pl` example translation at `browser/chrome/pl/locale/browser/searchplugins/` which contains XML and ICO files. Should that be linted too? Is that new? Seems to overwrite default searches and configures them to their localized versions. With that comes `.json`, `.xml` and `.ico` files that needs to be allowed, same as regular search plugins. Interestingly enough it's not referenced in the `manifest.json` as far as I can see (see attached file)

What needs to be done:

* [ ] Find a good DTD parser, probably will need to do some SAX-based parsing ourselves. See https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/Tutorial/Localization#DTD_Files for a bit more details
* [ ] Start linting `manifest.json` against the schema
* [ ] https://github.com/mozilla/addons-linter/issues/1526#issuecomment-329121902 (min/max version)

**Comment by jvillalobos** [comment]
> A test for l10n completeness

This doesn't sound like something we should keep. The majority of language packs are maintained by Mozilla and should be complete.

> Verify that all DTD files are either ASCII or UTF-8 encoded

Keeping this one makes sense.

> Verify package layout

I don't think we need this, beyond what we already check in the manifest. The Add-ons Manager should know to only load the files relevant to the language pack.

> There's a search-plugin in the pl example translation at browser/chrome/pl/locale/browser/searchplugins/

@zbraniecki is it still possible for language packs to bundle different search engine defaults?

I think either way we don't have anything extra to validate there.

**Comment by EnTeQuAk** [comment]
> I think either way we don't have anything extra to validate there.

I can work with that :)

**Comment by zbraniecki** [comment]
> This doesn't sound like something we should keep. The majority of language packs are maintained by Mozilla and should be complete.

We will want to allow for partial-localizations in langpacks. We also will handle multi-locale langpacks (for example with partial es-MX, and full es-ES as a backup)

> Verify that all DTD files are either ASCII or UTF-8 encoded.
> I think that can and should be kept.

Yes, but in the new langpack there are three l10n formats used: .dtd, .properties and .ftl. The former two will be eventually dropped and only .ftl will remain

> Verify package layout - makes sure that it only contain a install.rdf, chrome.manifest, chrome/*.jar and files with .manifest, .rdf, .jar, .dtd, .properties, .xhtml, .css extensions.

The new langpack only has manifest.json and l10n files

> @zbraniecki is it still possible for language packs to bundle different search engine defaults?

We didn't change how we package search engine defaults, so my guess is that nothing changes in this regard here.

**Comment by EnTeQuAk** [comment]
> We will want to allow for partial-localizations in langpacks. We also will handle multi-locale langpacks (for example with partial es-MX, and full es-ES as a backup)

Luckily nothing that we need to lint imho. If we do we should do that in a separate step.

> Yes, but in the new langpack there are three l10n formats used: .dtd, .properties and .ftl. The former two will be eventually dropped and only .ftl will remain

Besides that we still need to implement all three right now, is there a timeline on when things get deprecated / dropped?

**Comment by Pike** [comment]
I don't think it makes sense to validate encodings these days. Most folks have set their OSes to utf-8 by now, and that's that.

We should still check the completeness of DTDs and properties, notably, everything in chrome://. These are things that break the build, and can just happen while we break string freezes on beta and the like.

It's probably also a good idea to validate the chrome.manifest entries that they're not registring chrome we don't expect.

**Comment by EnTeQuAk** [comment]
> I don't think it makes sense to validate encodings these days. Most folks have set their OSes to utf-8 by now, and that's that.

We learned the hard way that this is not true so we are going to validate this :) It's not too hard anyway.

> We should still check the completeness of DTDs and properties, notably, everything in chrome://. These are things that break the build, and can just happen while we break string freezes on beta and the like.
> It's probably also a good idea to validate the chrome.manifest entries that they're not registring chrome we don't expect.

That'll take a while more to implement so I'm going to split them out into separate issues that can be tackled once basic WebExtension LanguagePack support landed.

**Comment by jvillalobos** [comment]
Since language packs are automatically imported and approved, the completeness tests would need to be hard errors in order to prevent the import. And I'm not even sure if validation errors stop the import. @wagnerand should know.

**Comment by wagnerand** [comment]
Unfortunately, I am not that familiar with the internals. I'm not sure whether those even run through the validator.

@Pike is there any way we can fully automate this? Currently, on each release day, I have to go to a page and manually start the process. There must be an event we can listen to when the langpacks are up on ftp.

**Comment by Pike** [comment]
I have no idea about the release mechanics, but it'd be nice to have this. @callek might be able to redirect that question.

Note, I'm perfectly fine to ignore the AMO validator for language packs uploaded from mozilla automation, I actually think we should.
We need the validator for communities that are self-empowered, anything from Klingon to Pirate English ;-)

**Comment by wagnerand** [comment]
> We need the validator for communities that are self-empowered, anything from Klingon to Pirate English ;-)

I fully agree. I was talking about the 'official' ones pulled from FTP only.

**Comment by Callek** [comment]
@wagnerand - Re: can this be automated.

There are a few approaches we can do here, we can give you a pulse message you can watch, or we can eventually (likely Q1) help get an upload to AMO for locales into in-tree taskcluster. Or some other option.

There begs some questions for which approach is good, best, etc. including the timing of things depending on those answers. I suggest either a new Issue here with me CC'd or a bug in bugzilla (Release Engineering::Automation).

We should certainly reduce the manual human interactions between AMO and automation we control.

**Comment by wagnerand** [comment]
@Callek Thanks a lot, I will follow up!

**Comment by EnTeQuAk** [comment]
>  Yes, but in the new langpack there are three l10n formats used: .dtd, .properties and .ftl. The former two will be eventually dropped and only .ftl will remain

@zbraniecki is there a language pack that already makes use of FTL? If so, can you link to it?

**Comment by diox** [comment]
> And I'm not even sure if validation errors stop the import. 

Langpacks imported from the FTP by the task @wagnerand is currently triggering manually are not validated at all at the moment.

**Comment by jvillalobos** [comment]
Then I don't think it's worth keeping the completeness validation.

**Comment by zbraniecki** [comment]
> @zbraniecki is there a language pack that already makes use of FTL? If so, can you link to it?

Will this work: https://send.firefox.com/share/b50c5c20db

in browser/localization you have a bunch of FTL files.

**Comment by EnTeQuAk** [comment]
Hmm, the link unfortunately expired. Mind sharing it again? 


On Thu, Oct 19, 2017, at 06:57 PM, Zibi Braniecki wrote:
>> @zbraniecki[1] is there a language pack that already makes use of
>> FTL? If so, can you link to it?> Will this work: https://send.firefox.com/share/b50c5c20db


> in browser/localization you have a bunch of FTL files.


> — You are receiving this because you were assigned. Reply to this
> email directly, view it on GitHub[2], or mute the thread[3].> 

Links:

  1. https://github.com/zbraniecki
  2. https://github.com/mozilla/addons-linter/issues/1526#issuecomment-337971113

**Comment by zbraniecki** [comment]
Ugh. Is that the right time to complain about "1 download" thing in Send?

https://send.firefox.com/download/596abf9296/#QaF5xD9Yj55yYXBpmir1-g

**Comment by EnTeQuAk** [comment]
Hehe, got it, thanks! I'll add FTL support from the beginning then. 


On Thu, Oct 19, 2017, at 11:25 PM, Zibi Braniecki wrote:
> Ugh. Is that the right time to complain about "1 download" thing
> in Send?> https://send.firefox.com/download/596abf9296/#QaF5xD9Yj55yYXBpmir1-g> — You are receiving this because you were assigned. Reply to this
> email directly, view it on GitHub[1], or mute the thread[2].> 

Links:

  1. https://github.com/mozilla/addons-linter/issues/1526#issuecomment-338042621

**Comment by zbraniecki** [comment]
btw. we have a lot of code for parsing/formatting/validating of .FTL files as part of `python-fluent` package and `compare-locales` package. Not sure if you'll need to go that deep, but we have ready to use code to get you an AST or validate the syntax of FTL.

**Comment by Pike** [comment]
I'd recommend trying compare-locales against the en-US language pack, unpack en-US, anpack the submitted localization, create a l10n.toml file that allows to compare one against the other.

Sadly, I don't know a way to create that toml file from the en-US langpack, but you could just create a list of patterns per release, or figure out a script. The file format is documented at http://moz-l10n-config.readthedocs.io/en/latest/fileformat.html. You can use https://hg.mozilla.org/mozilla-central/file/default/browser/locales/l10n.toml as an inspiration.

**Comment by EnTeQuAk** [comment]
Thanks a lot for all these links! That helps. 

Luckily I already found the project fluent libs and already started
using the nodejs lib. I'll have a look regarding the toml generation but
might implement that in a separate step to get the actual support landed
asap first.
Looks great though! 


On Thu, Oct 19, 2017, at 11:45 PM, Axel Hecht wrote:
> I'd recommend trying compare-locales against the en-US language pack,
> unpack en-US, anpack the submitted localization, create a l10n.toml
> file that allows to compare one against the other.> Sadly, I don't know a way to create that toml file from the en-US
> langpack, but you could just create a list of patterns per release, or
> figure out a script. The file format is documented at
> http://moz-l10n-config.readthedocs.io/en/latest/fileformat.html. You
> can use
> https://hg.mozilla.org/mozilla-central/file/default/browser/locales/l10n.toml
> as an inspiration.> — You are receiving this because you were assigned. Reply to this
> email directly, view it on GitHub[1], or mute the thread[2].> 

Links:

  1. https://github.com/mozilla/addons-linter/issues/1526#issuecomment-338047045

**Comment by EnTeQuAk** [comment]
I merged basic support in the linter for langpacks, linting the schema and validating doctype, properties and fluent files. I opened https://github.com/mozilla/addons-linter/issues/1621 as a follow-up.

@wagnerand we need to add code to addons-server though to make sure we lint these packages on import now right?

**Comment by wagnerand** [comment]
I am not entirely sure whether the admin import page needs updating. We might have to, to support FTL.

**Comment by ValentinaPC** [comment]
@EnTeQuAk : beside validation, is there anything else should be checked here? Thanks!
