### ISSUE TITLE
Minimal code example (for scanning a ZIP)

### ISSUE THREAD

**Issue by matatk** [mozilla/addons-linter#1550]
I'm calling addons-linter from JS code to lint built extension ZIP files.

I found the [example code](https://github.com/mozilla/addons-linter#import-linter-api-into-another-nodejs-application) a bit confusing; it seemed to imply that I needed to set `config._` to the current directory, and `config.scanFiles` to an array containing the name of the extension's ZIP file.  Eventually, I realised that the minimal config I needed to scan a ZIP file is more like:

```js
config: {
	_: ['extension.zip'],
	logLevel: process.env.VERBOSE ? 'debug' : 'fatal'
}
```

Could something like this be added to the README? (I'd be happy to submit a PR if you agree.)

Additionally, would it be possible to rename `config._` to `config.extensionFile`, `config.source` or similar?

Thanks for this helpful tool :-).

**Comment by EnTeQuAk** [comment]
I'm not too familiar with [yargs](http://yargs.js.org/) which is imho where this `config._` is actually coming from. As far as I know this is simply the first positional command line argument that isn't specifically named.

If you find an alternative way to do that with yargs and name this appropriately we're very happy to accept a pull request!

**Comment by matatk** [comment]
I've been reading through yargs' docs and GitHub issues and I agree there doesn't seem to be a straightforward way to do this, but I have asked about it, and if a straightforward way is found, I'll submit a PR.

**Comment by EnTeQuAk** [comment]
Cool, thanks for asking around! Feel free to keep us in the loop if something good comes up that we can use instead of that ambiguous `_`
