### ISSUE TITLE
Drop `legacyCode` from our code-base

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-linter#1559]
Based on https://github.com/mozilla/addons-linter/issues/1063 and the fact that we don't have to maintain legacy compatibility with amo-validator anymore we can get rid of `legacyCode`.

Let's just remove it everywhere where it's being used / referenced. Also make sure to update our `rules.md` file to represent that change.

**Comment by ravneette** [comment]
Hi @EnTeQuAk 
I would like to work on this.

From #1063, I could get that now amo-validator is being used for testing old school extensions, so there is no need for the legacyCode parameter in the code base.

Please correct me if I'm wrong, and I'll start working on this.

**Comment by Anshika-G** [comment]
@EnTeQuAk, I would like to solve this!
Can you please guide?

**Comment by EnTeQuAk** [comment]
> From #1063, I could get that now amo-validator is being used for testing old school extensions, so there is no need for the legacyCode parameter in the code base.

The amo-validator has always being used to test legacy (old school) extensions and the addons-linter was supposed to superseed this but with the push towards WebExtensions we deprecate amo-validator eventually and dropped all code related to legacy add-ons from addons-linter.

That's why the `legacyCode` can be dropped from the code base.

Feel free to start working on this! I am setting this to "contrib: assigned" to label this appropriately.

**Comment by ravneette** [comment]
Hey @EnTeQuAk 

Could you point me to the P.R. that removes the amo-validator dependency? It'll help me understand which parts of the code were being referenced by it, so I can remove them.

An obvious approach I see, and correct me if I'm wrong, is to remove the legacyCode parameter from the objects defined in messages. But I'm not sure if this might break the code.

**Comment by EnTeQuAk** [comment]
@ravneette [amo-validator](https://github.com/mozilla/amo-validator) is a completely different code-base and essentially the predecessor of the addons-linter. The removal process of removing linting code for legacy add-ons was progressive and happened in multiple pull requests.

> An obvious approach I see, and correct me if I'm wrong, is to remove the legacyCode parameter from the objects defined in messages. But I'm not sure if this might break the code.

That is actually what this issue is all about. It will certainly break some code and tests and you're going to have to fix them, either by removing tests that use `legacyCode` (most probable solution) or by removing code that references it. It'll be lots of fun to primarily remove code 😃

**Comment by ravneette** [comment]
Haha
Sure was a lot of fun to remove the code! Thanks for the guidance @EnTeQuAk.

Filed a P.R here https://github.com/mozilla/addons-linter/pull/1565

**Comment by ravneette** [comment]
I could find only one test that used to check if each message has legacyCode defined.
Removed that and the tests ran fine locally.
