### ISSUE TITLE
warn about invalid extensions of icons

### ISSUE THREAD

**Issue by pkpriya** [mozilla/addons-linter#1575]
### Describe the problem and steps to reproduce it:
I used icons having invalid extensions like img.html and linter did not produce any error or warnings

### What did you expect to happen?
I used the command bin/addons-linter  myfile.zip and expected linter to throw a warning 

### Anything else we should know?
(Please include screenshots and any relevant files.)
![screenshot 274](https://user-images.githubusercontent.com/24734840/30965788-3ea16c70-a474-11e7-81fc-6b62fc5a45a5.png)

**Comment by EnTeQuAk** [comment]
This got fixed in https://github.com/mozilla/addons-linter/pull/1558 which did not yet get released but we'll push a new release soon so that you can profit from that patch.

I'm closing this since it's already fixed and just waiting on a release.
