### ISSUE TITLE
CSS uri values should checked in further detail

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-linter#158]
Would be nice to check quotes match when specified. 

Also if no quotes are supplied we should check for correct escapes used for ', " and () chars. [1]

[1] https://drafts.csswg.org/css-values-3/#urls

**Comment by andymckay** [comment]
Is there a security reason to do this, or a check for invalid CSS?

**Comment by apoorvasingh17** [comment]
@muffinresearch Hi, can I take this up?

**Comment by EnTeQuAk** [comment]
I didn't find anything useful yet but maybe there's some XSS bypassing things using data uris?

**Comment by muffinresearch** [comment]
I'm going to close this out since it's unlikely to be a priority ever.
