### ISSUE TITLE
No error or warning displayed when the extension has an empty language directory

### ISSUE THREAD

**Issue by ExE-Boss** [mozilla/addons-linter#1585]
### Describe the problem and steps to reproduce it:
1. Create an internationalized extension
2. Create an empty language directory in the _locales folder

### What happened?
The linter didn’t say anything.

### What did you expect to happen?
The linter should display an error that the empty language directory is missing the required messages.json file.

### Anything else we should know?
Firefox refuses to load extensions that have a language directory that is missing the required messages.json file.

**Comment by pardeepshokeen** [comment]
Hi @wagnerand  I would like to work on this issue. Can I take this?

**Comment by wagnerand** [comment]
@pardeepshokeen Sure, go ahead!

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev FF57 Win10

![image](https://user-images.githubusercontent.com/31961530/34207905-04a9e526-e595-11e7-95c6-a30d166eb26a.png)
