### ISSUE TITLE
Error should be displayed in case script is missing from the content_script folder.

### ISSUE THREAD

**Issue by paavininanda** [mozilla/addons-linter#1590]
### Describe the problem and steps to reproduce it:
Remove the script from content_script folder of any web extension and try to run it in Firefox. 

### What happened?
Web extension did not work properly

### What did you expect to happen?
A error message notifying that the Script is missing.

### Anything else we should know?
Error should be displayed in case script is missing from the content_script folder, or even if the content_script folder is missing.

**Comment by paavininanda** [comment]
@EnTeQuAk Hi,
If you think this issue needs to be looked upon, i would like to work on this issue.

**Comment by EnTeQuAk** [comment]
@paavininanda this sounds like a great idea! If you still have time to work on it, please feel free to do so and let me know if you run into any problems.

**Comment by hameleonka** [comment]
does anyone work on this issue, I can take it @EnTeQuAk, @paavininanda?

**Comment by paavininanda** [comment]
@hameleonka Yea you can take it :)

**Comment by EnTeQuAk** [comment]
@hameleonka feel free to hack on this issue anytime, looks like no one is working on it right now.

**Comment by hameleonka** [comment]
There a 2 [ways](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Content_scripts) to load content scripts 
1) declaration in manifest.json
2) programmatically with `tabs.executeScript()`

first case is simple, just check if files declared and if they actually exist in the folder, question about second case, should I parse all the js files and check if someone trying to execute script from content_scripts or I can make a simple warning about empty folders?
In case when someone removed script from content_scripts it will show warning, but when somebody removed folder completely I will show nothing.
