### ISSUE TITLE
"Violation of Mozilla conditions of use" when uploading addon

### ISSUE THREAD

**Issue by ericjung** [mozilla/addons-linter#1606]
### Describe the problem and steps to reproduce it:
Upload attached addon to AMO

### What happened?
Received informational message: "Violation of Mozilla conditions of use. Warning: Words found that violate the Mozilla conditions of use. See https://www.mozilla.org/en-US/about/legal/acceptable-use/ for more details."

The file mentioned is background.html. That file contains an SVG and canvas; not much else.

### What did you expect to happen?
Not to be told I'm violating Mozilla conditions of use.
 
### Anything else we should know?
I suspect the SVG XML is the cause. There is nothing offensive there to my knowledge.

**Comment by ericjung** [comment]
[archive.zip](https://github.com/mozilla/addons-linter/files/1385909/archive.zip)

**Comment by EnTeQuAk** [comment]
hmm, I'll look into it but this has the ability to become messy. Parsing content we already understand isn't much of a problem though it might degrade our ability to find violations more broadly since we can't be parsing all possibilities of where to hide bad words. In any case, we should reduce our false positives so this is worth looking into.

Thanks for the report.

**Comment by muffinresearch** [comment]
Looks like the false positive is caused by `stroke-linecap:butt;`

We should probably remove `butt` from badwords.json

**Comment by ericjung** [comment]
I dont particularly care if it's fixed since it's only informational and
didn't stop me. I was asked to open the bug by mat, IIRC. Don't fix it on
my account :)

eric

**Comment by jvillalobos** [comment]
I think it's a good idea to fix it since it looks like it will cause more noise than anything.

**Comment by ericjung** [comment]
As an interim compromise, how about displaying the offending line (s) in
the output?

**Comment by icl7126** [comment]
Since the list of forbidden words is [public](https://github.com/mozilla/addons-linter/files/1088479/flagged-terms.txt), I don't see a reason not to tell developer what problematic words it found. It would be really helpful since nobody will read whole `messages.json` file to find it.

**Comment by ashclarke** [comment]
This applies to Highcharts.js:

![image](https://user-images.githubusercontent.com/963023/33556338-73def388-d8fb-11e7-9c31-9abf9ffb60fd.png)

**Comment by AlexandraMoga** [comment]
Is the term allowed now anywhere in the manifest (i.e. "name", "description") or this applies only to `stroke-linecap` attribute?
If the latter, may I have an example to properly test this with?
