### ISSUE TITLE
A syntax error prevents upload (false positive)

### ISSUE THREAD

**Issue by olr** [mozilla/addons-linter#1616]
### Describe the problem and steps to reproduce it:
I tried to upload an extension on AMO. That was an update.

### What happened?
It says: “There is a JavaScript syntax error in your code; validation cannot continue on this file.”
But this code works.
There no syntax error here.

**Comment by olr** [comment]
When I tried the day after, it worked.

But today, I uploaded an update, and the same kind of bug is still there.

As long as this bug exists, there should be a way to bypass the syntax checker.

**Comment by olr** [comment]
Is there any chance to see this problem solved soon?

[grammalecte_fr_-0.6.0.3.zip](https://github.com/mozilla/addons-linter/files/1421574/grammalecte_fr_-0.6.0.3.zip)

**Comment by diox** [comment]
@olr we'll look into it, but in the meantime, maybe you could split the offending regexp to try to work around the issue ? You can install the linter locally to test if that works, or use https://addons.mozilla.org/en-US/developers/addon/validate

**Comment by olr** [comment]
This is very strange.

I had the regex:
`/(lundi|m(?:ardi|ercredi)|jeudi|vendredi|samedi|dimanche),? (?:le |)(\d\d?)-(\d\d?)-(\d\d+)(?![a-zA-Zà-öÀ-Ö0-9_ø-ÿØ-ßĀ-ʯ–-])/gi`
I changed it for:
`/(lundi|mardi|mercredi|jeudi|vendredi|samedi|dimanche),? (?:le |)(\d\d?)-(\d\d?)-(\d\d+)(?![a-zA-Zà-öÀ-Ö0-9_ø-ÿØ-ßĀ-ʯ–-])/gi`
And it works. The syntax checker passed over it.

But the strangest thing is that on the following line, I had the regex:
/(lundi|m(?:ardi|ercredi)|jeudi|vendredi|samedi|dimanche),? (?:le |)(\d\d?) (janvier|février|ma(?:rs|i)|a(?:vril|o[ûu]t)|jui(?:n|llet)|septembre|octobre|novembre|décembre) (\d\d+)(?![a-zA-Zà-öÀ-Ö0-9_ø-ÿØ-ßĀ-ʯ–-])/gi
And it passed over it also, though I let it unchanged.

And then it blocked on another regex:
`/tout ([a-zA-Zà-öÀ-Ö0-9_ø-ÿØ-ßĀ-ʯ][a-zA-Zà-öÀ-Ö0-9_ø-ÿØ-ßĀ-ʯ][a-zA-Zà-öÀ-Ö0-9_ø-ÿØ-ßĀ-ʯ]+)(?![a-zA-Zà-öÀ-Ö0-9_ø-ÿØ-ßĀ-ʯ–-])/gi`

I can’t really simplify this. This regex is just the transcription in JS of "(?i)tout (\w\w\w+)\b" written with the Python regex syntax.

It not a complicated regex compared to many other ones in this file.

Wouldn’t it be better for the syntax checker to be non-blocking until it works properly?

**Comment by diox** [comment]
@bnjbvr kindly investigated the issue and provided a fix, it should be merged soon and go in production next week.

> Wouldn’t it be better for the syntax checker to be non-blocking until it works properly?

This is not possible, we absolutely need to lint all add-ons, it helps determine review priority, prevents broken add-ons from being submitted, etc. This issue is quite specific, your add-on is the first that we have heard about that triggers it, so we're not going to let anyone bypass validation just to work around it. However, you can contact admins (amo-admins@) and *they* can upload a version for you bypassing validation, on a case-by-case basis.

**Comment by olr** [comment]
Thanks to you all for having fixed this.
