### ISSUE TITLE
Rename rules files to match eslint ones.

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-linter#162]
Should be lower-case with underscores.

**Comment by muffinresearch** [comment]
No longer needed.

**Comment by EnTeQuAk** [comment]
Actually that's being done with my pull request :) 





On Mon, Feb 20, 2017, at 07:56 PM, Stuart Colville wrote:

> Closed #162[1].



> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[2], or mute the
> thread[3].
> 


Links:

  1. https://github.com/mozilla/addons-linter/issues/162
  2. https://github.com/mozilla/addons-linter/issues/162#event-969663620

**Comment by muffinresearch** [comment]
> Actually that's being done with my pull request :)

@EnTeQuAk yep I closed it because it was about to get fixed.
