### ISSUE TITLE
"/version" should match format "versionString"

### ISSUE THREAD

**Issue by 523860169** [mozilla/addons-linter#1641]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### What happened?
upload the new version of webextension then it shows me 
```
"/version" should match format "versionString"
Error: Your JSON file could not be parsed.

```
### Anything else we should know?
(Please include screenshots and any relevant files.)
manifest.json: 
`  "version": "17.11.07.1",
`

**Comment by asamuzaK** [comment]
You should remove leading zero.

**Comment by 523860169** [comment]
thank you
