### ISSUE TITLE
JavaScript syntax error: false positive

### ISSUE THREAD

**Issue by CoolCmd** [mozilla/addons-linter#1642]
### Describe the problem and steps to reproduce it:
Trying to submit new version of [extension](https://addons.mozilla.org/en-US/firefox/addon/twitch_5/) (attached)

### What happened?
2 JavaScript syntax errors:

Error: There is a JavaScript syntax error in your code; validation cannot continue on this file.
worker.js line 415 column 16

Error: There is a JavaScript syntax error in your code; validation cannot continue on this file.
player.js line 397 column 19

### What did you expect to happen?
There are no errors in these files. The extension runs perfectly in Firefox, Chrome and Edge.

### Anything else we should know?
A year ago the old validator showed a bunch of stupid warnings. Now it shows 2 errors. Good progress. (sarcasm)

[twitch5_gecko.zip](https://github.com/mozilla/addons-linter/files/1454943/twitch5_gecko.zip)

**Comment by CoolCmd** [comment]
Today I tried to repeat the submission and no errors were found. Maybe something has been fixed in the validator?

**Comment by wagnerand** [comment]
Works for me too, closing.
