### ISSUE TITLE
Extra weight added for extensions that don't use minified code

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-linter#1645]
Steps to reproduce:

1. Log into AMO-stage and submit a new add-on using eval() risk factor
2. In the submission process note the validation warning triggered
3. Once the add-on is auto-approved go to Reviewers tools and check the applied weight (i.e. https://reviewers.addons.allizom.org/en-US/editors/queue/auto_approved)

Expected results:
The submitted add-on received a weight of 20, according to the criteria for eval() risk factor

Actual result:
The add-on receives and extra 10 points to weight

Notes:
- the extra 10 points are resulting from an apparent minified code, as Mat pointend out on IRC, but the add-on does not contain any minified code
- should be also helpful to display a warning for minified code too, in case it exists, to better deduct the weight.

Extension used: 
[eval.zip](https://github.com/mozilla/addons-linter/files/1457398/eval.zip)

**Comment by AlexandraMoga** [comment]
@wagnerand I have two examples you could look at: 
1. [https://addons.allizom.org/en-US/firefox/addon/家に帰りたい家Thursadyたい 家に帰りた/](https://addons.allizom.org/en-US/firefox/addon/%E5%AE%B6%E3%81%AB%E5%B8%B0%E3%82%8A%E3%81%9F%E3%81%84%E5%AE%B6thursady%E3%81%9F%E3%81%84-%E5%AE%B6%E3%81%AB%E5%B8%B0%E3%82%8A%E3%81%9F/)
2. https://addons.allizom.org/en-US/firefox/addon/webext-docwritelexa/

**Comment by wagnerand** [comment]
@EnTeQuAk I think the added weight for minified code is because the file is one line only. I remember us talking about that a while ago. Maybe we should make sure that the line length is < X characters if the file has only one line?

**Comment by ValentinaPC** [comment]
Another example with wrong weight (not entirely sure), from my calculations:
https://reviewers.addons.allizom.org/en-US/editors/review/webext-evalinsandbox-test-w

**Comment by EnTeQuAk** [comment]
> @EnTeQuAk I think the added weight for minified code is because the file is one line only. I remember us talking about that a while ago. Maybe we should make sure that the line length is < X characters if the file has only one line?

This definitely needs some fine-tuning. I've seen a few other cases where unminified code was detected as minified. How important is that? Otherwise, I'd like to tackle this during next week so potentially targetting next tag or the one after that.

**Comment by wagnerand** [comment]
Given the added weight is only 10 currently, it doesn't make a huge difference, so it is not a priority.

**Comment by diox** [comment]
Heads-up: the weight is now 100+10 per instance, so this becomes more relevant. QA just stumbled upon it while testing the new weights.

**Comment by diox** [comment]
> Maybe we should make sure that the line length is < X characters if the file has only one line?

IMHO this should be enough as a workaround, btw.

**Comment by EnTeQuAk** [comment]
I'll give this a look for next weeks tag.
