### ISSUE TITLE
manifest.json > applications > strict_min_version failing

### ISSUE THREAD

**Issue by peter-kehl** [mozilla/addons-linter#1648]
"applications": {
    "gecko": {
      "strict_min_version": "57.a"
    }
  }
generates: Cannot find min/max version. Maybe "strict_min_version" or "strict_max_version" contains an unsupported version?

However, when I click at 'See full validation report', that has all checks green and OK:
https://addons.mozilla.org/en-US/developers/upload/e05493c69eb343a795f2b782107b33ef
![image](https://user-images.githubusercontent.com/4270240/32722042-b5577078-c8bc-11e7-938c-e51698df8942.png)

Unsure whether this is related to https://github.com/mozilla/addons-linter/issues/1527.

**Comment by asamuzaK** [comment]
"strict_min_version": "57.0a"
Add digit before alpha version string

**Comment by peter-kehl** [comment]
Dear Kazz,

Thank you for the tip. Still negative: "strict_min_version": "57.0a" doesn't work either, unfortunately.

To eliminate my potential human error:
1. my manifest is compatible with web-ext. The following demonstrates it (since my local Firefox is 56 and not 57 yet):
  web-ext run
  ...
  run: WebExtError: installTemporaryAddon: Error: unknownError: Could not install add-on at 
  '/home/pkehl/SeLite/hands-on-gui': Error: Add-on hands-on-gui@selite.googlecode.com is not 
  compatible with application version. add-on minVersion: 57.0a.
2. The manifest went into .zip:
zip -r -FS ../hands-on-gui.zip *
updating: manifest.json (deflated 38%)
3. I've re-uploaded the zip (with a newer add-on version):
![image](https://user-images.githubusercontent.com/4270240/32749965-33f2c70e-c915-11e7-868a-d2f5729a42f8.png)

Yet, again, the detailed report has every check in green:
https://addons.mozilla.org/en-US/developers/upload/27047c65f3c6487eab326eef7e0e1d8b
![image](https://user-images.githubusercontent.com/4270240/32749996-4e77fed2-c915-11e7-895b-df7ae4c5f418.png)

Please have someone confirm.

**Comment by peter-kehl** [comment]
This affects developers who have updates for new Firefox only. Release of Firefox 57 tomorrow (or soon) is making this urgent.

**Comment by jvillalobos** [comment]
[Here's the list](https://addons.mozilla.org/firefox/pages/appversions/) of valid minimum and maximum application versions you can use.

Using `57.0a1` should work.

**Comment by peter-kehl** [comment]
Jorge @jvillalobos,
Thank you.
