### ISSUE TITLE
NO_MESSAGES_FILE reported on Windows, but not on macOS

### ISSUE THREAD

**Issue by matatk** [mozilla/addons-linter#1649]
### Describe the problem and steps to reproduce it:

When I lint an add-on on macOS, it reports no errors. When I lint the same add-on on Windows, I get a `NO_MESSAGES_FILE` error. 

### What happened?

A `NO_MESSAGES_FILE` error was reported.

### What did you expect to happen?

No errors to be reported.

### Anything else we should know?

[Repo for the add-on I'm working on.](https://github.com/matatk/landmarks)

**Comment by matatk** [comment]
Sorry, to build the add-on, issue `npm run build:firefox` (or `npm run build:all`). I have also attached an add-on file to this message.

[landmarks-2.1.0-firefox.zip](https://github.com/mozilla/addons-linter/files/1492829/landmarks-2.1.0-firefox.zip)

**Comment by wagnerand** [comment]
Hm, I tried to install the linter from npm on Windows, but getting weird dependency installation errors. @EnTeQuAk have you ever tried to run the linter on Windows?

**Comment by matatk** [comment]
The errors are probably due to needing to compile stuff to install Sharp.

I got it to work by running [`npm install --global windows-build-tools`](https://www.npmjs.com/package/windows-build-tools) from an admin command prompt.

**Comment by wagnerand** [comment]
Thanks, yes I just found that on the internets...running now...

**Comment by matatk** [comment]
There's a [function in my build script that creates the ZIP file](https://github.com/matatk/landmarks/blob/bc1b09f28d41abbeee7282cb38f4e9c832795288/scripts/build.js#L209-L227).  The ZIP file passes all the tests on AMO (and on macOS).  Actually I am pretty sure I transferred the ZIP file generated on macOS to Windows and found that addons-linter reported the error on Windows, but not on macOS with the same ZIP file.

However I am very-much open to the possibility of there being a bug in my code :-).

**Comment by EnTeQuAk** [comment]
This should have been fixed via https://github.com/mozilla/addons-linter/pull/1730 and the `sharp` dependency has been removed in another PR as well.

In case it hasn't please let us know.

**Comment by vcarciu** [comment]
Tried on Windows 10x64 with latest linter, [webext](**https://github.com/mozilla/addons-linter/files/1492829/landmarks-2.1.0-firefox.zip**) from this issue and there are no errors  : 
![noliontererrors](https://user-images.githubusercontent.com/1583842/34835807-a780f08a-f6fe-11e7-9274-1e360b81cc3c.png)

**Comment by matatk** [comment]
Same here; working fine now; thanks :-).
