### ISSUE TITLE
Remove term from list of Conditions of Use violations

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-linter#1656]
We added a list of forbidden terms in #1285. A [forum report](https://discourse.mozilla.org/t/words-found-that-violate-the-mozilla-conditions-of-use/21606) points out that the Ace.js library is being flagged by this. Looking at the source, it appears that the term "alt-right", referring to a key combination, is the one being flagged.

Let's remove that term from the list.

**Comment by AlexandraMoga** [comment]
I've submitted an extension with name "alt-right addon", which passed validation with no warnings. After auto-approval the add-on had 0 weight in reviewer tools.
Based on this outcome we can mark this as verified fixed in AMO-dev, FF57 (Win10)

**Comment by plroebuck** [comment]
Apologies for adding on to closed issue here.

So we get notice from someone for using the term "bang" in reference to an exclamation point.
Is this linter's implication that functioning code should be rewritten if it contains _any_ words that can have more than one meaning?
