### ISSUE TITLE
CSP wrongly considers default-src+script-src unsafe

### ISSUE THREAD

**Issue by kewisch** [mozilla/addons-linter#1660]
https://reviewers.addons.mozilla.org/en-US/firefox/files/browse/782622/#top

has default-src with various hosts, but script-src self. The validator things that this allows remote scripts.

This is actually ok since the script-src is reset to self. The validator should understand this.

**Comment by ValentinaPC** [comment]
Please add some STR for us to check this or the label "qa: not needed". Thanks!

**Comment by wagnerand** [comment]
STR:

Create a webextension that has the following CSP in the manifest:
`defaults-src: https:; script-src 'self'`

When submitted to AMO, this should not throw the CSP warning during validation.

**Comment by ValentinaPC** [comment]
> Create a webextension that has the following CSP in the manifest:
> default-src: https:; script-src 'self'

Is there a mandatory order while writing CSP content?
Because `"content_security_policy": "script-src 'self' default-src:https://example.com;"` triggers a warning and `"content_security_policy": "default-src: https://example.com; script-src 'self' "` does not.

**Comment by wagnerand** [comment]
Yes, this has a special syntax. The former syntax is not valid.

I think we can mark this as verified.

**Comment by wagnerand** [comment]
For background information, https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy documents what the syntax is.

**Comment by ValentinaPC** [comment]
@wagnerand : just for my inner peace - why the syntax you say is not valid, triggers a CSP warning and corresponding weight, and not an error?
![csp](https://user-images.githubusercontent.com/15685960/33215592-1811004c-d139-11e7-96ae-f783fa475771.png)
Example: https://reviewers.addons-dev.allizom.org/en-US/editors/review/csp

**Comment by wagnerand** [comment]
That is a reasonable question and a discussion we need to have at some point. So far, we have refrained from using `error` in most cases because those tests have to be 100% accurate, otherwise, we're failing for legitimate submissions.

The CSP evaluation in the linter needs some further tweaking...
