### ISSUE TITLE
Can't re-sign an unhosted .XPI

### ISSUE THREAD

**Issue by peter-kehl** [mozilla/addons-linter#1678]
### Describe the problem and steps to reproduce it:
Visit https://addons.mozilla.org/en-US/developers/addon/submit/distribution
Choose 'On your own.' Hit Continue. Upload a .ZIP of new version of an extension that you had signed here before (as an older version).

### What happened?
Error: "Duplicate add-on ID found"
Yet, the detailed validation was all OK. However, 'Sign Add-on' button is disabled.

### What did you expect to happen?
Allow to sign the new version of an add-on with the same ID, as far as it's not hosted on AMO web.

**Comment by jvillalobos** [comment]
I'm pretty sure there's a duplicate somewhere in the addons-server repo for doing the right thing when submitting an update via the new add-on flow. I can't find it now, but that's what I think is the right solution for this.
