### ISSUE TITLE
The linter fails to detect a flagged term contained by the add-on name

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-linter#1679]
Steps to reproduce:

1.Submit an add-on with a name in the following format: "name": "word1_word2". One (or both) of the terms needs to violate Mozilla's conditions of use
2. Observe the results triggered in the validation report

Expected result:
The flagged term is detected during add-on validation

Actual result:
The submission passes validation with no warnings

Notes: another scenario would be "name": "w.o.r.d" (where "w.o.r.d" is a flagged term)
reproduced on all AMO servers with FF57 Win10

Examples used: 
[uncompliant.zip](https://github.com/mozilla/addons-linter/files/1514200/uncompliant.zip)
[uncompliant1.zip](https://github.com/mozilla/addons-linter/files/1526281/uncompliant1.zip)

**Comment by harry-7** [comment]
I want to work on this issue. I have looked at the source code and figured out that there is a regex [here](https://github.com/mozilla/addons-linter/blob/master/src/const.js#L101) and corresponding code is [here](https://github.com/mozilla/addons-linter/blob/master/src/scanners/filename.js#L30). But I did not find where I can find the rules regarding add-on naming policies. Can anyone guide me to the next step? Thanks :)

**Comment by sudipt1999** [comment]
@AlexandraMoga  I would like to work on this issue

**Comment by wagnerand** [comment]
Closing in favor of https://github.com/mozilla/addons-linter/issues/2591.
