### ISSUE TITLE
Warn about more APIs with a temporary ID

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-linter#1685]
### Describe the problem and steps to reproduce it:

Use nativeMessaging in your add-on.
Don't specify a applications > gecko > id in your manifest.

### What happened?

No warning.

### What did you expect to happen?

A warning, just like if you have a temporary id but use storage.local.

### Anything else we should know?

nativeMessaging is listed on this page: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/WebExtensions_and_the_Add-on_ID as an API that needs an applications  > gecko > id.

**Comment by andymckay** [comment]
Actually there's a couple more:

* pcks11
* runtime.onMessageExternal
* storage.managed

This is hopefully just a matter of copying and pasting rules for STORAGE_SYNC and the relevant code.

**Comment by wagnerand** [comment]
I would prefer if warnings like these would only show up during `web-ext lint`, for example. They are not useful to developers in validation reports when submitting to AMO or to reviewers.

Legacy developers have suffered from warning fatigue, and I would like to avoid the same for webextension developers. 😄

**Comment by EnTeQuAk** [comment]
We can talk about adding a "local" (e.g via web-ext, ide etc) and "remote" (on AMO) mode that enables/disables different warnings/errors

**Comment by jvillalobos** [comment]
Mentor: @EnTeQuAk 

Let's move the discussion about the warning levels to a different issue.

**Comment by harry-7** [comment]
I would like to work on this issue. Can someone guide me on what has to be done? and where to start looking at?

**Comment by caitmuenster** [comment]
Hey @harry-7! Welcome! 

@EnTeQuAk, could you provide some guidance about what the warning needs to look like?

**Comment by sudipt1999** [comment]
I would like to work on the bug

**Comment by caitmuenster** [comment]
Hey @sudupt1999, welcome! This one's all yours. :)

**Comment by caitmuenster** [comment]
Hey @sudipt1999, how's it going with this bug?

**Comment by iYung** [comment]
Hello, can I work on this? I asked to do issue #2248 but was directed here.

**Comment by caitmuenster** [comment]
Hey @iYung, go for it!

**Comment by melvin2016** [comment]
Should we need to check if the permission mentioned int the manifest file is of nativeMessaging?
Currently no checks are implemented in manifestjson parser.
@EnTeQuAk @caitmuenster

**Comment by melvin2016** [comment]
@iYung @EnTeQuAk @caitmuenster someone please guide on checks to be done ?

**Comment by Shubhamchinda** [comment]
Hey @caitmuenster, can I take this up?

**Comment by wagnerand** [comment]
@Shubhamchinda Yes, this is free for anyone to take!

**Comment by Shubhamchinda** [comment]
Hey @wagnerand , I need help on how to proceed on this issue. 
Thanks :)

**Comment by wagnerand** [comment]
@Shubhamchinda Hi, what help do you need?

**Comment by Shubhamchinda** [comment]
> @Shubhamchinda Hi, how can we help?

I read all the comments, but I couldn't figure out properly that where and what changes are needed to be done.
