### ISSUE TITLE
Linter should not suggest including large JSON file as separate JSON file

### ISSUE THREAD

**Issue by wareya** [mozilla/addons-linter#1700]
![image](https://user-images.githubusercontent.com/585488/33924606-d4c6827e-dfa4-11e7-824f-7fddd4aa4f49.png)

**Comment by muffinresearch** [comment]
@wareya please can you provide an example so we can investigate?

**Comment by wareya** [comment]
JMdict.json was a ~32MB JSON file, comprising a translingual dictionary. It was generated from the JMdict XML file from http://www.edrdg.org/jmdict/edict_doc.html using this python script https://gist.github.com/wareya/c2175520db5f1927e4f6ba839487dd8c/44722c80dfbe814594616ba48c018f9c6cf5e92a

It just kind of triggered the FILE_TOO_LARGE error, but the text in the message for FILE_TOO_LARGE wasn't written with being triggered by JSON files in mind.

Rewording the beginning of the last sentence to something like "If this is a JavaScript file with a large list" would fix that specific issue.

The issue of not being able to use large JSON files is #1361 or #1248. #1248, however, technically deals with the case of having a very long list in a JavaScript file, rather than a separate large JSON file. I don't really understand why it's necessary to scan JSON files when huge flat text files are okay (flat text files are one of the ways that other addons with JMdict's data work around this restriction). But I suppose there's probably a reason.

**Comment by wareya** [comment]
Unless the logic or text for this was changed at some point without the issue being touched, it's still a problem.

**Comment by eladkarako** [comment]
Moving a large data away from JS files into JSON is good practice (although there is an RAM/CPU payload of loading the data while loading it from JS is considerably faster).

Mozilla linter will notify you to move the data into a JSON, 
but will <strong>still</strong> notify you after you've moved the data to JSON, 

The solution/workaround is to use another file-extension, other than <code>.json</code>, 
the loading/handling of the JSON data should all stay the same.

Here is an example (with `fetch` and `json` promises):  https://github.com/mozilla/addons-linter/issues/2943#issuecomment-559845634

**Comment by wareya** [comment]
Unless this was fixed without someone touching this issue, it's still an issue.

**Comment by wareya** [comment]
As far as I can tell, the code and error message responsible for this have not been touched since I opened this issue. All that needs to happen is for someone to go in and change the wording for the error to not imply that the oversized file is a Javascript file in particular. I don't see why the "needs: discussion" tag is attached to this and there's no reason it couldn't be fixed with five or ten minutes of work. The issue of whether large JSON files should be supported is separate and distinct and shouldn't block at least fixing the wording.

**Comment by jvillalobos** [comment]
Suggested copy:

> **Error:** This is file is not binary and is too large to parse. Files larger than 4MB will not be parsed. Consider moving large lists of data out of JavaScript files and into JSON files, or splitting very large files into smaller ones.

**Comment by caitmuenster** [comment]
@rpl is going to take a look at how complex this is, and he'll be mentoring it whether if's a good first bug or a contrib: welcome bug.

**Comment by rpl** [comment]
After re-reading the issue it seems that its scope is limited to just changing the wording and so it looks definitely as a reasonable good first bug.

mentor: @rpl

Follows some details related to the kind of fix that has to be applied:
- the wording of the rule message defined [here](https://github.com/mozilla/addons-linter/blob/5045967ef1383d89ddea8f3c9b0e77838de8c5a6/src/messages/layout.js#L31-L34) should be changed into what suggested by @jvillalobos in this comment https://github.com/mozilla/addons-linter/issues/1700#issuecomment-736861398

The description of the rule doesn't seem to be covered by [the test related to this rule](https://github.com/mozilla/addons-linter/blob/cc92e134df63d66389ac4d4a0c6d5d534bb28abb/tests/unit/test.linter.js#L1283-L1352), and so there may not be any change needed to the tests if we do limit the fix to the rule description.

**Comment by FlashV998** [comment]
@rpl  ,Hi I'm new over this open source contribution thing,it would be great help if you could tell me the steps to get this error,I've already cloned this repo to local and went through the code as well.

**Comment by prianka01** [comment]
@rpl, Hi, I would like to work on this as a new developer. Checked out the README.md, and changed the line as suggested by you. Also have run the test after changes and got the same result as before the changes. Is there something else that I need to take care of or send a pull request for the same?

**Comment by rpl** [comment]
@prianka01 please feel free to create the pull request, we can evaluate if there are any further changes needed as part of the pull request review. 

Besides opening the PR the only other thing I would suggest is to make sure to try to reproduce the issue (it should be as simple as creating a small test extension and add into it a JSON file bigger then the current maximum allowed size) and then verify that your changes did update the rule description message as expected.
