### ISSUE TITLE
Fluent no longer supports Node 6

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-linter#1701]
The `fluent` dependency states in its README that it no longer supports Node 8. I can't tell if that's just for project maintenance or if there is really some code that is broken in Node 6. Also, it seems that *only* [version 0.4.2](https://github.com/projectfluent/fluent.js/releases/tag/fluent%400.4.2) has introduced a hard dependency on Node 8 in its `package.json`.

This causes installation of web-ext to fail with yarn on Node 6:

```
web-ext kumar$ yarn
yarn install v1.3.2
...
[3/5] 🚚  Fetching packages...
error fluent@0.4.2: The engine "node" is incompatible with this module. Expected version ">=8.9.0".
error Found incompatible module
indigo:web-ext kumar$ npm ls fluent
web-ext@2.2.2 /Users/kumar/dev/web-ext
└─┬ addons-linter@0.30.0
  └── fluent@0.4.2
```

Maybe the easiest thing is to set the linter's dependency on fluent to an exact version like `"fluent": "0.4.1"`?

**Comment by EnTeQuAk** [comment]
This will be fixed with https://github.com/mozilla/addons-linter/issues/1789 which is what I'm working on right now.
