### ISSUE TITLE
Static Theme that works in about:debugging fails in linter

### ISSUE THREAD

**Issue by designakt** [mozilla/addons-linter#1703]
### Describe the problem and steps to reproduce it:
Create a theme that uses an RGB Array for "accentcolor". e.g. [222,184,135]
Try this theme via about:debugging. It will work in Firefox. Create a zip file from the manifest and submit it to AMO. It will fail the validator with: 
>"/theme/colors/accentcolor" should be string

### What did you expect to happen?
I expected a theme that works in Firefox to pass the validation.

### Anything else we should know?
(Please include screenshots and any relevant files.)

e.g. manifest:

> {"description": "A Theme that works in Firefox, but does not pass the linter.",
> "manifest_version": 2,
> "name": "Confusing",
> "version": "0.1",
> "homepage_url": "",
> "theme": {"images": {"headerURL": ""},
> "colors": {
>   "accentcolor": [222,184,135],
>   "textcolor": [34,23,9,1]}}}

Talking with @mstriemer and @eviljeff it seams the validator should accept what Firefox can display.

**Comment by wagnerand** [comment]
Arrays got introduced in https://searchfox.org/mozilla-central/commit/3adfb3eca60d5b284e55c1384c335afef656a8f9.

**Comment by muffinresearch** [comment]
@designakt The schema was recently updated - so this might be fixed now.

**Comment by designakt** [comment]
Yay!
On dev I can now upload my WebExtension-Theme. 
However, when trying to install, Nightly states it is corrupt... 
(not sure why that is... installing via about:deugging works)
![install_my_theme](https://user-images.githubusercontent.com/8145891/35916377-82ed6ab6-0c0a-11e8-8d43-a0d8f8867b3c.PNG)

https://addons-dev.allizom.org/de/firefox/addon/burlywood-css-named-color/

**Comment by eviljeff** [comment]
signing from the dev/stage servers is different from production AMO so it will be regarded as corrupt (unless you change some settings in about:config - I forget which)

**Comment by EnTeQuAk** [comment]
Closing since this issue isn't an issue anymore and seems to work on dev and stage now.

We're also working on static theme support in https://github.com/mozilla/addons-linter/issues/1587
