### ISSUE TITLE
Fixed Linter Errors, Manifest is Now "Missing"

### ISSUE THREAD

**Issue by Incrested** [mozilla/addons-linter#1727]
I was porting some Chrome extensions the "proper" way (if that makes sense) by editing the manifest.json's errors from Firefox's Online Linter and changing them on my desktop. When I got to fix the "author", I simply changed the author. However, when I re-zipped the source and went to upload the addon, it said "Could not find manifest.json." Of course, I didn't expect this to happen as the manifest.json was in that folder at the time of zipping and unzipping to edit the source for Firefox. I just expected that it would simply toss the XPI file at my face and I could enjoy Chrome-Exclusive extensions on the better Firefox Quantum.

I was hoping, if there is a script issue, if anyone could point me in the right direction of fixing it. Not really asking for all the work to be on someone else.

Original Extension: https://chrome.google.com/webstore/detail/data-saver/pfmgfdlgomnbgkofeojodiodmgpgmkac
Images (labeled): https://imgur.com/a/9DZC4
manifest.json File: https://gist.github.com/Incrested/2742670454877ec138d306e80b44455e

**Comment by wagnerand** [comment]
Can you please link to the XPI file you tried to upload?

**Comment by Incrested** [comment]
I was trying to compile into an XPI but it wouldn't work. The extension is already given above.

**Comment by wagnerand** [comment]
Can you please provide detailed steps to reproduce the issue?

**Comment by Incrested** [comment]
1. I downloaded the CRX from Google's Chrome Web Store

2. I extracted the CRX using a CRX Viewer and compressed it into a ZIP, removing some Chrome specific features

3. I went to Mozilla's Addon Website and did the steps to submit an add-on for my own site, not Mozilla's

4. I uploaded the ZIP file and it prompted that the "\author" field could not be a boolean, even though it was as follows:

```json
"author": "Google Inc.",
```

5. I open up Notepad++ to swiftly change the text above to:

```json
"author": "Google, LLC.",
```

6. I re-compress and re-upload the ZIP to Mozilla and now it reads that it cannot find the "manifest.json", even though, as you can see from the images linked in the original post, that it is clearly there.

7. I came here to submit this issue, as this seemed like the most appropriate response to such an issue

**Comment by wagnerand** [comment]
Thank you for the detailed steps. I assume in step 6 you zipped the folder that contains the code instead of the files inside that folder.

Can you please attach the zip files created after step 2 and 6 to this issue or upload them somewhere we can access them?

**Comment by Incrested** [comment]
Of course!

Original Extension: [Chrome Webstore - Data Saver by Google](https://chrome.google.com/webstore/detail/data-saver/pfmgfdlgomnbgkofeojodiodmgpgmkac)
Step 2 (modifications): [1st Edits.zip](https://github.com/mozilla/addons-linter/files/1609023/1st.Edits.zip)
Step 6 (fixing "author" error): [2nd Edits.zip](https://github.com/mozilla/addons-linter/files/1609024/2nd.Edits.zip)

**Comment by wagnerand** [comment]
Yes, it's what I assumed in the previous comment. The files in the zip file in step 6 are nested in a subfolder, instead of top-level. Just zip the files directly instead of the folder that contains them and you should be able to upload successfully.

**Comment by Incrested** [comment]
I did what you asked, but it made the original issue and one that makes 0 sense. "Can't parse" and "can't find" the manifest

https://gyazo.com/ccbcd7fe394242a090418c3edc91fe4f

**Comment by wagnerand** [comment]
Please provide the file you tried to upload

**Comment by Incrested** [comment]
[2nd Edits.zip](https://github.com/mozilla/addons-linter/files/1619188/2nd.Edits.zip)
^ The ZIP I uploaded with the Edits you asked

**Comment by wagnerand** [comment]
So, running your manifest file through a JSON parser reveals that your JSON is not valid, hence we can't parse it:

Line 25 has a trailing space:
`    "scripts": [ "background_compiled.js" ],`
should be
`    "scripts": [ "background_compiled.js" ]`

**Comment by Incrested** [comment]
Just needed to define "default_locale" and the scripts issue, and I was good. Thanks for the help @wagnerand
