### ISSUE TITLE
Import detected as "JavaScript syntax error"

### ISSUE THREAD

**Issue by JGames101** [mozilla/addons-linter#1732]
I am using Material Design Components from Google, this is the first of many imports detected as an error:
`import autoInit from '@material/auto-init';`

**Comment by EnTeQuAk** [comment]
Hey @JGames101, thanks for the report!

Are you able to upload the XPI or a minimalistic so that we can directly try to reproduce that problem locally?

**Comment by wagnerand** [comment]
This is most probably because you're using the `import` statement which is not enabled by default in Firefox yet, and thus causing a syntax error.
