### ISSUE TITLE
Hook up Pontoon to allow translators to translate the strings.

### ISSUE THREAD

**Issue by ravneette** [mozilla/addons-linter#1784]
The PR that contains the .po files for the current project state has been made. (https://github.com/mozilla/addons-linter/pull/1739)
As @EnTeQuAk mentioned, the next step should be to hook up Pontoon to allow translators to actually translate the strings.

According to the website, we need to create a bug here
https://developer.mozilla.org/en-US/docs/Mozilla/Implementing_Pontoon_in_a_Mozilla_website

There are a few instructions about the making addons-linter localizable, but I think those are done right in https://github.com/mozilla/addons-linter/pull/1739

**Comment by EnTeQuAk** [comment]
Thanks for filing this, I'm in contact with the l10n team to get this set-up, I'll cc you on any mails.

**Comment by ravneette** [comment]
Great, thanks! :)

**Comment by EnTeQuAk** [comment]
This is now working properly

**Comment by AlexandraMoga** [comment]
Could you please add some STR to help us verify this?

**Comment by ravneette** [comment]
Could you elaborate what that means @AlexandraMoga 
Do you mean some way to test that translation is working?

**Comment by AlexandraMoga** [comment]
@ravneette yes, what we require are some steps that would help us understand where we should focus our testing in order to make sure that these changes are properly verified.

**Comment by EnTeQuAk** [comment]
Sorry to chime in but this isn't really testable by QA and not end-user visible yet. It's merely the process how translations will land in addons-linter.
