### ISSUE TITLE
Fluent Linter should use fluent-syntax, not fluent

### ISSUE THREAD

**Issue by zbraniecki** [mozilla/addons-linter#1789]
Fluent linter seems to be using `fluent` package according to:
 - https://github.com/mozilla/addons-linter/blob/master/src/parsers/fluent.js
 - https://github.com/mozilla/addons-linter/blob/master/package.json#L96

The `fluent` package is a runtime Fluent implementation meant for performance, not conformance. We have another package, called `fluent-syntax` that provides a better parser, with better errors, full AST and a serializer - all of that intended for tools like linters.

**Comment by EnTeQuAk** [comment]
Oh, that's a great hint, thanks a lot! That should be ported to use the
Syntax package then.

On Thu, Jan 25, 2018, at 7:23 PM, Zibi Braniecki wrote:
> Fluent linter seems to be using fluent package according to:


>  * https://github.com/mozilla/addons-linter/blob/master/src/parsers/fluent.js
>  * https://github.com/mozilla/addons-linter/blob/master/package.json#L96> The fluent package is a runtime Fluent implementation meant for
> performance, not conformance. We have another package, called fluent-
> syntax that provides a better parser, with better errors, full AST and
> a serializer - all of that intended for tools like linters.> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].> 

Links:

  1. https://github.com/mozilla/addons-linter/issues/1789

**Comment by wagnerand** [comment]
Since `fluent-syntax` requires at least node 8.9.0, we can't migrate to it before we drop support for node 6.

**Comment by EnTeQuAk** [comment]
> Since fluent-syntax requires at least node 8.9.0, we can't migrate to it before we drop support for node 6.

it does too? That's sad :( Well, then we'll have to wait for a bit I suppose.

**Comment by Callek** [comment]
This issue was discovered as a blocker for the work happening in https://bugzil.la/1438246 and per IRC discussion there may be a path forward here.

**Comment by EnTeQuAk** [comment]
Steps forward:

* [ ] Add an example implementation that uses fluent-syntax for fluent parsing and error extraction
* [ ] Try out their compat build for node 6 compatibility

Since this seems to be a blocking part of  https://bugzil.la/1438246 I pushed the priority and started working on it.

**Comment by EnTeQuAk** [comment]
Added an upstream [patch](https://github.com/projectfluent/fluent.js/pull/164) to relax their engines configuration a bit, the compat build works fine with node6. 

#1789 is WIP and adds support for fluent-syntax.

**Comment by vcarciu** [comment]
@EnTeQuAk : Please add STRs to this issue or mark it as "qa: not needed"
