### ISSUE TITLE
Get the language from user as a command line parameter

### ISSUE THREAD

**Issue by ravneette** [mozilla/addons-linter#1797]
To facilitate translation, we need to take the input language from the user either as a command line parameter, or set it as an environment variable. (As discussed in today's meeting)

I can get some inspiration for extracting environment variables from addons-frontend, but not sure how we will take a parameter from the user from the CLI to get the language. @EnTeQuAk could you point me to some examples?

**Comment by muffinresearch** [comment]
As a suggestion it might be possible to just start with using something like https://github.com/sindresorhus/os-locale and then seeing if overrides are needed and add them later if they are.
