### ISSUE TITLE
Error when attempting to find content scripts 

### ISSUE THREAD

**Issue by notdls** [mozilla/addons-linter#1803]
### Describe the problem and steps to reproduce it:
Recently I was trying to upload a new version of my add-on but I kept getting the error "Content script file could not be found.". However, the scripts still run how and when they're supposed to and don't get any errors while debugging with the browser. So Inside my main folder I have one main JavaScript file and several which are executed by the main script. 
- hackbar.js (main file which calls the other js files and handles all of the events)
- polyglot.js, post.js, redirect.js and custom.js (These are all executed using ``browser.tabs.executeScript``)

Just a quick note so it makes more sense, all of these files are in the same folder. 
Calling one of the scripts like ``var auto = browser.tabs.executeScript({file: 'polyglot.js'});`` works fine, however when ran like this I get prompted when uploading that says ``Content script file could not be found.`` (but when testing on my machine and another it works fine). I can get the error to go away by adding "hackbar/" to the front of it (e.g. ``var auto = browser.tabs.executeScript({file: 'hackbar/polyglot.js'});``) but adding this breaks the script and the script is no longer executed and I'm presented with ``Error: An unexpected error occurred`` in debugging.

### What happened?
Add-on linter cannot detect my script files

### What did you expect to happen?
I expected it to upload and pass normally as it has in the previous versions
### Anything else we should know?
(Please include screenshots and any relevant files.)
Here is a copy of the add-on that _should_ be passing but is receiving the ``Content script file could not be found.`` error.
[hackbar_error.zip](https://github.com/mozilla/addons-linter/files/1692529/hackbar_error.zip)
Here is the copy of the add-on that _is passing_ but the scripts are no longer executed
[hackbar_no_error.zip](https://github.com/mozilla/addons-linter/files/1692531/hackbar_no_error.zip)

**Comment by pardeepshokeen** [comment]
hi @muffinresearch . I want to work on this bug. Can I take this?

**Comment by EnTeQuAk** [comment]
> hi @muffinresearch . I want to work on this bug. Can I take this?

Sure thing, feel free to give this a try.

As a helping note, it seems there's a problem with the path in `src/rules/javasript/content-scripts-file-absent.js` probably somewhere around or in the `normalizePath` call in line 39.

As an alternative have a look at our https://github.com/mozilla/addons-linter/issues?q=is%3Aissue+is%3Aopen+label%3A%22contrib%3A+good+first+bug%22 - good first bugs - to start contributing to addons-linter.

**Comment by AlexandraMoga** [comment]
I've used the two webextension examples provided to check the validation reprot.

[1] - [hackbar_error.zip](https://github.com/mozilla/addons-linter/files/1811143/hackbar_error.zip) - no error generated during validation anymore

![image](https://user-images.githubusercontent.com/31961530/37404043-5aea3a8a-2799-11e8-80fa-a9cef8c53abd.png)


[2] - [hackbar_no_error.zip](https://github.com/mozilla/addons-linter/files/1811151/hackbar_no_error.zip) - is now generating a 'content script' error

![image](https://user-images.githubusercontent.com/31961530/37404121-922d6a4e-2799-11e8-8caa-6bb018f6adf7.png)

@EnTeQuAk @pardeepshokeen Is what's happening in the second case expected?

**Comment by pardeepshokeen** [comment]
hi @AlexandraMoga 
yes second case has error 

here is quote from issue
>  I can get the error to go away by adding "hackbar/" to the front of it (e.g. var auto = browser.tabs.executeScript({file: 'hackbar/polyglot.js'});) but adding this breaks the script and the script is no longer executed and I'm presented with Error: An unexpected error occurred in debugging.

here hackbar/polyglot.js is relataive path but in previous patch everything was considered as absolute path so there was no error before.

**Comment by AlexandraMoga** [comment]
Considering that the initial error will no longer reproduce, this issue can be marked as verified fixed.
Verified on AMO-stage, FF59 Win10x64.

**Comment by kvetko** [comment]
@AlexandraMoga Do you think it is OK that the change has broken what was working before, thus the task can be considered as fixed? 
This change most likely prevents us from publishing our extension to the store and more it will most likely break all existing addons after upgrade to FF59 if check is applied in FF runtime

**Comment by AlexandraMoga** [comment]
sorry @kvetko , but my understanding was that the main issue with your submission was raised by the first example, namely [hackbar_error.zip](https://github.com/mozilla/addons-linter/files/1819170/hackbar_error.zip), which was passing validation after this fix has landed.

**Comment by kvetko** [comment]
Indeed but fixing something by breaking something else is not the best approach ;-) Don't worry about that I believe we have catch it on time. I have created #1915 for our current issue.
