### ISSUE TITLE
Link translation to addons-server to show warnings and error messages in different languages

### ISSUE THREAD

**Issue by ravneette** [mozilla/addons-linter#1806]
As discussed in the biweekly outreachy meeting, after we've added i18n in addons-linter, we would need to make changes in addons-server which allow the user to see the warnings in various languages. I'm still a little unclear with the requirements for this one.
@EnTeQuAk , Could you point me to some code in addons-server where we need to make the changes?

**Comment by muffinresearch** [comment]
I've filed an issue for this on addons-server https://github.com/mozilla/addons-server/issues/7515
