### ISSUE TITLE
Warn when getting undefined message in default_locale

### ISSUE THREAD

**Issue by freaktechnik** [mozilla/addons-linter#1807]
### Describe the problem and steps to reproduce it:
 - Extension calls `browser.i18n.getMessage("someMessage");`
 - Extension manifest defined `default_locale`
 - Extension contains `messages.json` for default locale, but no `someMessage` key in it

### What did you expect to happen?
The linter shows a warning, that `someMessage` does not exist for the default locale.

It may even make sense to check all valid `messages.json` files in the extension, but that would be a lot more complicated in extensions with many localizations.

Maybe instead there should be an independent check for all `messages.json` files to contain the messages present in the `default_locale`.

**Comment by Eccenux** [comment]
Note that `browser.i18n.getMessage` might not be called directly to e.g. support testing outside of the browser environment.

**Comment by freaktechnik** [comment]
As far as I'm aware still something that would catch potential errors.

**Comment by freaktechnik** [comment]
Thanks stalebot, since there's a WIP PR that I really should get back to, this maybe shouldn't be closed?

**Comment by freaktechnik** [comment]
<3 you too stale bot.

**Comment by wagnerand** [comment]
This is a nice-to-have. Marking P4.
