### ISSUE TITLE
Allow firefox schema to be imported from RC and Release tags

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-linter#1811]
We should allow the firefox schema import to fetch other tags than just beta.
It'd be best to import directly from https://hg.mozilla.org/mozilla-unified/tags which contains RC tags and others as well.

Background: We had the scenario that after the 58 schema import from beta there was a uplift in a later Firefox release which changed the schema and actually added a new API. We should catch that and try to import from more recent Firefox releases as well, if there's no reasonable change: fine, if there is, let's import and release that.

Unfortunately this isn't a great candidate for automatisation since quite a lot of times we had to change the import process for more recent schema updates.

**Comment by vcarciu** [comment]
Can you please add some STRs from this bug and mark it as "qa: not needed" ?
