### ISSUE TITLE
Font Awesome: Should it be allowed and hashed?

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-linter#1820]
ref: `https://fontawesome.com/`

Recently, I have seen a lot of add-ons using the large 656.7kb Font Awesome minified library.

Should it be allowed and if so, should it be hashed?
It is not practical to check it manually.

Example:
`https://reviewers.addons.mozilla.org/en-US/firefox/files/browse/849237/file/js/fontawesome-all.min.js#top`

@wagnerand

**Comment by wagnerand** [comment]
I need to run a few queries first to see how many add-ons really use this and check how complex updates of that library are.

Generally, add-ons using minified code should should be admin flagged. You can also compare the hashsums of the file in the add-on and the file in the maintainer's repository and if they match review the unminified original in that repository.
