### ISSUE TITLE
Problems with "strict_min_version" when uploading to AMO

### ISSUE THREAD

**Issue by spikespaz** [mozilla/addons-linter#1848]
While uploading to [AMO](https://addons.mozilla.org/en-US/developers/addon/submit/distribution), I am getting an error `Cannot find min/max version. Maybe "strict_min_version" or "strict_max_version" contains an unsupported version?`.

Then, if I click [See full validation report](https://addons.mozilla.org/en-US/developers/upload/3a87718c18f545f18d52f34b2f2ce565), it shows no errors, and I did make sure that my `strict_min_version` matches the regex given, `^[0-9]{1,3}(\.[a-z0-9]+)+$`.

The first time I trued this, I set `strict_min_version` to `57`, as I had seen in other addons. But I changed it to `57.0b14`, which matches the pattern, and it still gave me the error. I copied that version string directly from the [private-browsing-theme](https://github.com/mdn/webextensions-examples/tree/master/private-browsing-theme) example.

The following is my full manifest:

    {
      "manifest_version": 2,
      "name": "Native Dark",
      "version": "1.0",
      "author": "spikespaz (Jacob Birkett)",
      "description": "Dynamic theme for Firefox Quantum that colorizes the title bar, tabs, and URL bar based on your Windows accent color.",
      "homepage_url": "https://github.com/spikespaz/Firefox-NativeDark",
      "background": {
        "scripts": [
          "background.js"
        ]
      },
      "permissions": [
        "theme"
      ],
      "applications": {
        "gecko": {
          "strict_min_version": "57.0b14"
        }
      }
    }

Thanks for taking a look at this.

**Comment by andymckay** [comment]
The versions that AMO knows about are here: https://addons.mozilla.org/en-us/firefox/pages/appversions/

Likely private-browsing-theme never got uploaded to AMO. Let's file a bug on the example repo to remove that.

**Comment by spikespaz** [comment]
This can be closed now as the issue has been posted to the MDN repo.
