### ISSUE TITLE
Can't find these JS files

### ISSUE THREAD

**Issue by lightalex** [mozilla/addons-linter#1920]
Can't find these JS files
But files exist
`chrome.tabs.executeScript(tabs[i].id, {
	file: 'files/script/preload.js'
});
chrome.tabs.executeScript(tabs[i].id, {
	file: 'files/script/postload.js'
});`

Error from your test system - `Content script file could not be found`

In past uploads, errors didn't arise. The files didn't change. Only one file was exchanged. And after your update, boom, got an error. I have to make a fast fix, but i can't. Thx! 😡

**Comment by EnTeQuAk** [comment]
Can you upload a test extension that reproduces that error? That'll help find and fix your scenario quickly.

**Comment by lightalex** [comment]
You can download it here
https://addons.mozilla.org/ru/firefox/addon/darkvk/
I changed only CSS in my update

**Comment by vcarciu** [comment]
Verified as fixed using the extension from description : 
![contentscriptnotfound](https://user-images.githubusercontent.com/1583842/37716704-cea91e9e-2d27-11e8-9ef2-3e9953177c2d.gif)

**Comment by lightalex** [comment]
Doesn't work with ZIP archives
ZIP archive for test
https://yadi.sk/d/dVcAwtLp3TcUfg
