### ISSUE TITLE
Numerous Errors: Your JSON file could not be parsed.

### ISSUE THREAD

**Issue by andy61i** [mozilla/addons-linter#1921]
I've got 906 errors "Error: Your JSON file could not be parsed." while uploading my extension to addons.mozilla.org today. They all are about localization files. This did not happen with the previous version (with almost the same localization files). The extension also loads and works normally via about:debugging.

Here is the extension's zip: https://www.dropbox.com/s/f4rrzq294z2lftm/safeincloud_firefox.zip?dl=1

**Comment by EnTeQuAk** [comment]
Actually your message.json files are invalid but I agree we should issue a more reasonable error message.

`description` should be a valid string (even empty works) but must not be `null` or anything that is not a string. You can also just omit the `description`. If you change that your add-on should validate.

I keep this issue open to improve the error message on this.

**Comment by andy61i** [comment]
Thanks, it worked!

**Comment by muffinresearch** [comment]
@EnTeQuAk I'm assuming you're planning to work on this since you updated the milestone.
