### ISSUE TITLE
Get rid of calls of getConfig() in ManifestJSONParser

### ISSUE THREAD

**Issue by hiikezoe** [mozilla/addons-linter#1925]
The constuctor of ManifestJSONParser uses getConfig() to get default argument value for selfHosted and isLanguagePack, so if caller doesn't specify these values, getConfig()  incidentally parses command line arguments, thus if the command does not specify any argument,  yargs output 'Not enough non-option arguments: got 0, need at least 1' error unfortunately.

You can easily confirm the error to run below script on the top of addons-linter source directory.

```
#!/usr/bin/env node

require('./dist/addons-linter')
  .createInstance({
    config: {
      logLevel: 'debug',
      _: ['./tests/fixtures/webextension_scan_file/'],
    },
    runAsBinary: true,
  }).run();
```

**Comment by hiikezoe** [comment]
A solution I can think of is to split options object for yargs into an independent variable and then re-use it to get the default argument value for  ManifestJSONParser too.  I will send a PR soon.

**Comment by vcarciu** [comment]
Can you please add some STRs to this bug or mark it as "qa : not needed" ?

**Comment by hiikezoe** [comment]
STR is just running the script in https://github.com/mozilla/addons-linter/issues/1925#issue-307127344.

1. Copy the script text into a new file, e.g. run-lint
2. Save the file, run-lint, in the top of source directory of addons-linter
3. $ chmod +x run-lint
4. $ ./run-lint

**Comment by hiikezoe** [comment]
oops, already marked qa: not neened.
