### ISSUE TITLE
Local modules could over shadow node_modules, preventing imports

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-linter#1931]
### Describe the problem and steps to reproduce it:

Add an import like this to any local module, such as for [`logger.js`](https://github.com/mozilla/addons-linter/blob/cc2cb5b1f6ca0e72924972c030066ecd40d42fc9/src/logger.js):

```js
import log from 'logger';
```

Install an npm package by the [same name](https://www.npmjs.com/package/logger), just as an example.

### What happened?

There is no way to import the `logger` module from `node_modules` because `src` is first in the [webpack resolve config](https://github.com/mozilla/addons-linter/blob/cc2cb5b1f6ca0e72924972c030066ecd40d42fc9/webpack.config.js#L56)

### What did you expect to happen?

Local modules should not overshadow `node_modules`.
### Anything else we should know?

You could move all modules under `src/` to `src/linter/` to enable a namespaced import like:

```js
import log from 'linter/logger';
```

**Comment by jvillalobos** [comment]
Mentor: @EnTeQuAk

**Comment by devcer** [comment]
Hey, can I work on this?

**Comment by caitmuenster** [comment]
Hey @devcer, good to see you! 👋🏼 Go for it! We'll tag this as 'assigned' when you have a PR up. :)

**Comment by devcer** [comment]
Hi, I was able to fix the paths and submitted a PR. created a build and tested my add-on. However, my test cases fail with a common issue which I cannot resolve. can someone help? PFA of the screenshot below.
<img width="1120" alt="Screenshot 2019-05-24 at 10 32 50 AM" src="https://user-images.githubusercontent.com/3799600/58303855-94594b80-7e0f-11e9-9b50-6c4ab3448103.png">

**Comment by kewisch** [comment]
@EnTeQuAk can you help @devcer here?

**Comment by muffinresearch** [comment]
The problem here is that cli has moved, so the reference to the mock needs to be updated.

Seeing the patch, I'm not sure about making this change in a direction of namespacing. The way that module resolution currently by looking in `src` first then `node_modules` is largely for convenience and whilst that does mean the issue in the OP is possible, I'm not sure if namespacing is the best direction.

I wonder if there's a better pattern we could use here? Calling @mozilla/addons-service-developers for thoughts.

**Comment by EnTeQuAk** [comment]
> I wonder if there's a better pattern we could use here? Calling @mozilla/addons-service-developers for thoughts.

My experience here regarding patterns in the JavaScript world is not the best but looking at addons-code-manager it seems that most of the imports are local `import ... from ./foo/bar`-style. addons-frontend kinda uses the same import structure as addons-linter so I'm wondering if this is actually a big problem that needs fixing?

Haven't had the time to play around with it much tbh.

**Comment by muffinresearch** [comment]
After discussing this in the triage we've decided that the the problem isn't best solved by the current approach. Since this problem is currently not impacting us massively we're going to work on the basis that we'll reconsider this should it become a problem in the future.
