### ISSUE TITLE
Extensions with some white spaces in the name don’t display the name from submission process in Add-ons Manager

### ISSUE THREAD

**Issue by cosminbadescuSV** [mozilla/addons-linter#1933]
### Describe the problem and steps to reproduce it:
Submit an add-on that has some white spaces in the name from manifest.json.
At the submission process, the user is forced to choose a name because of the white spaces. 

### What happened?
After you add a name in the submission process, the add-on validation has successfully passed and the extension can be installed.
After install, in Add-ons Manager you can see that the extension has no name displayed.

### What did you expect to happen?
The expected behavior was presented in https://bugzilla.mozilla.org/show_bug.cgi?id=1438149#c5.

### Anything else we should know?
Reproduced on AMO -dev, stage and prod  with FF59, FF60 and FF61 on Win 7 64-bit and Mac OS X 10.13.2 

I have also filed a bug in https://bugzilla.mozilla.org/show_bug.cgi?id=1448805

![nameamo](https://user-images.githubusercontent.com/15885467/37900777-e071f262-30f7-11e8-97bb-e4d6a9a45698.gif)

**Comment by EnTeQuAk** [comment]
quoting from the bugzilla issue

> Upon further discussion, we decided this would be simpler to address purely on the AMO side (via the github issue linked above).

> In short, we can pretty easily validate the immediate contents of the manifest file, but an extension name is localized, which means its possible values are spread across a bunch of different files (one per locale).  The linter can look through and validate all of these, which is a prerequisite for having an extension signed by AMO.  But it would be a lot of unnecessary work for Firefox to do at install time.

> This means that temporarily installed or unsigned extensions (on nightly or dev edition with the preference flipped) can have empty names, but in the normal case of signed extensions, empty names will not be allowed.>
