### ISSUE TITLE
Liner Inconsistent on JQ 3 Hash

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-linter#1936]
I have seen a few times that linter fails to recognise valid jQuery v3.3.1 hash.

Example:
`https://reviewers.addons.mozilla.org/en-US/firefox/files/browse/842459/file/jquery.js#top`

Where are the hashes and why does it fail on some occasions?

**Comment by wagnerand** [comment]
Weird, this seems like a bug. The hash of that file matches the original and I confirmed that that hash is in the production instance.

**Comment by wagnerand** [comment]
Ah, no, no bug. The add-on got submitted (and therefore validated) end of January, but we only added the hash for that jQuery version beginning of February.

**Comment by erosman** [comment]
I hash check myself using my own hash-check system, but this system of cached validation can lead into a lot of compilations for the reviewers and developers.
