### ISSUE TITLE
[Review Tools] Handling of JSON and CSS is hampers the Review

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-linter#1943]
I had already mentioned this issue a few times (maybe starting from over a year ago).
e.g. https://github.com/mozilla/addons/issues/313 https://github.com/mozilla/addons/issues/455

Just now, I spent about 5 minutes trying to load `manifest.json` and every time being faced with multiple "Page is slowing down your browser" and finally failing to load.

`https://addons.cdn.mozilla.net/en-US/firefox/files/browse/881906/file-serve/manifest.json`

It is quite similar with medium to large size CSS files which frankly can do without any highlighting (when it is breaking the page).

The effect on the browser, CPU and memory is also considerable.

It is similar with small JS files that have a medium to large JSON/Array/Object in them. The tool simply breaks down.

**Comment by EnTeQuAk** [comment]
This is not a linter issue and solely addons-server related. We are going to touch reviewer tools in Q2 so some things may change and get improved as part of that.
