### ISSUE TITLE
Handle misspelled properties for static themes

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-linter#1944]
From https://github.com/mozilla/addons-linter/issues/1913 

The linter detects no errors when certain properties are misspelled, for example: `theme`, `headerURL`, `additional_backgrounds`, `colors`, `accentcolor`, `textcolor` etc. - all these can be misspelled

**Comment by EnTeQuAk** [comment]
This should be fixed by updating the schema, either upstream or via a manual overwrite.

**Comment by muffinresearch** [comment]
@EnTeQuAk has an upstream bug been filed to get the schema updated?

**Comment by EnTeQuAk** [comment]
> @EnTeQuAk has an upstream bug been filed to get the schema updated?

No I haven't, the upstream schema is actually quite unstrict about missing or misspelt properties since forever for some reasons. But I think filing an upstream issue to at least open the discussion about it and making clear which part lints what may make sense.

I'll do that!
