### ISSUE TITLE
Handle invalid color values, e.g an empty string

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-linter#1945]
From https://github.com/mozilla/addons-linter/issues/1913

accentcolor and textcolor - no error when value is an empty string ie. "" or when they contain a wrong color value (i.e. any value is accepted, like dje757$%#, 4)

**Comment by muffinresearch** [comment]
@EnTeQuAk has an upstream bug been filed to get the schema updated?

**Comment by EnTeQuAk** [comment]
`accentcolor` and `textcolor` have been deprecated and migrated recently.

A quick look through the schema shows that most other color related properties are reusing `ThemeColor` (theme.json) or `ColorValue` (browser_action.json) and are validated properly.

With that, I'm going to close this issue.
