### ISSUE TITLE
Regex fails validation

### ISSUE THREAD

**Issue by jeffg2k** [mozilla/addons-linter#1954]
This regex fails validation.  I've tried several different ways to write it and it keeps getting rejected when I submit my Firefox Extension.  It works fine, so not sure what the problem is.

`var regex = /PRELOADED_STATE__ \= .*?(?=;.*?<\/script>)/gs;`

Here was my first attempt, which worked as well and validated at regex101.com:
`var regex = /(?<=window\.__PRELOADED_STATE__ \= ).*?(?=;.*?\<\/script>)/gs;`

**Comment by jeffg2k** [comment]
I was able to get this to work / validate when submitting my Firefox Extension.
var regex = new RegExp('(?<=window\.__PRELOADED_STATE__ \= ).*?(?=;.*?\<\/script>)', 'gs');

**Comment by jeffg2k** [comment]
When I tried to upload it to the Mozilla Add-On Developer Hub, I got this error message.

> JavaScript syntax error
> Error: There is a JavaScript syntax error in your code; validation cannot continue on this file.
> 
> collections/ancestryfree.js line 28 column 24

Here is an Add-On that exhibits the problem.
[smartcopy-4.3.15.zip](https://github.com/mozilla/addons-linter/files/1915293/smartcopy-4.3.15.zip)

As a side note, seems it would make sense to exclude jQuery from the "Unsafe assignment to innerHTML" warnings.  Nothing anyone can do about that.

**Comment by jeffg2k** [comment]
@wagnerand Please reopen this.  You are incorrect that it is modified.  I had the same problem jQuery v3.2.1.  I only download from jQuery.

The checksum is different because I copy / pasted the text instead of the file, but if you want me to prove it.. hold on.  Acting like I'm some noob.  

Also, even if it was modified.. it shouldn't matter.  The linter should still see it as a valid syntax.  If it doesn't regex correctly is my own problem.

**Comment by jeffg2k** [comment]
This one is the direct file download: 160a426ff2894252cd7cebbdd6d6b7da8fcd319c65b70468f10b6690c45d02ef.

It still has the problem.
[smartcopy-4.3.15.2.zip](https://github.com/mozilla/addons-linter/files/1915440/smartcopy-4.3.15.2.zip)

**Comment by wagnerand** [comment]
That file does not throw any innerHTML warnings for the jquery file, so it works as expected.

**Comment by jeffg2k** [comment]
I'd also note that the linter doesn't have a problem when I put it in the new RegExp.  The validator should work in either format.

Ok, so you were addressing the jQuery warnings (the side note).  I thought you were talking about the regex issue.

**Comment by jeffg2k** [comment]
Unless - are you saying the regex doesn't work in FireFox?  To be honest, I only tested it in Chrome.  So maybe their javascript supports it, but mozilla doesn't?

**Comment by wagnerand** [comment]
You are using a regular expression that is not valid in JavaScript. Therefore our JavaScript parser throws an error.

**Comment by jeffg2k** [comment]
But this works and no errors is thrown and its the same regular expression. 
`var regex = new RegExp('(?<=window\.__PRELOADED_STATE__ \= ).*?(?=;.*?\<\/script>)', 'gs');`

**Comment by jeffg2k** [comment]
Going to test it in Firefox to see if it works..

**Comment by wagnerand** [comment]
Sorry, I misspoke. Those regex features were recently added and are in fact valid JS. But, since they are rather new, they time timeline is for browser vendors to implement them some time in 2018.
While Chrome has already implemented them, Firefox hasn't yet, see http://kangax.github.io/compat-table/es2016plus/ (under '2018 features').
