### ISSUE TITLE
Add FF60 new namespace proxy.settings

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-linter#1972]
Ref: https://bugzilla.mozilla.org/show_bug.cgi?id=1455755

> **proxy.settings is not supported**
> 
> **Warning:** This API has not been implemented by Firefox.

Example:
https://addons.mozilla.org/en-US/developers/upload/9066b64a76224d14925992d914426f9c

**Comment by EnTeQuAk** [comment]
This is part of Firefox 61 which will be merged to beta on Monday and once that happens we'll import it's schema to the linter.

**Comment by erosman** [comment]
> This is part of Firefox 61 which will be a beta release on May 9th and once that happens we'll import it's schema to the linter.

Actually not.. it is part of FF60 

status-firefox60: fixed → verified
status-firefox61: fixed → verified
status-firefox-esr60: fixed → verified

**Comment by EnTeQuAk** [comment]
Hmm, it certainly wasn't in the `FIREFOX_60_0b15_RELEASE` I recently checked

**Comment by erosman** [comment]
> Hmm, it certainly wasn't in the FIREFOX_60_0b15_RELEASE I recently checked

It has recently been added. It was decided that FF60 is a major milestone as it correlates with esr60 therefore, it was decided to push the change more rapidly as the previous API `browserSettings.proxyConfig` was broken and discarded for FF60-ESR60

**Comment by EnTeQuAk** [comment]
> It has recently been added. It was decided that FF60 is a major milestone as it correlates with esr60 therefore, it was decided to push the change more rapidly (and later than normal) as the previous API browserSettings.proxyConfig was broken and discarded for FF60-ESR60

I see, yeah we can only import directly from tags from mozilla-unified so once this lands there I'll import it.

**Comment by AlexandraMoga** [comment]
Could you please add STR or the label 'qa:not needed'?
Thanks

**Comment by EnTeQuAk** [comment]
STR:

* run the addons-linter against an add-on that uses the new `proxy.settings` API, e.g `
browser.proxy.settings.set({value: { proxyType: 'system' }});` or so.

This isn't on -dev yet, once it is I'll update the issue.

**Comment by AlexandraMoga** [comment]
@EnTeQuAk I have tested this on -dev with some add-ons using `proxy.settings`
- add-ons using `browser.proxy.settings` - have passed validation without warnings (see [ex. 1](https://addons-dev.allizom.org/en-US/developers/addon/proxy-settings-test-dev/file/254943/validation) and [ex. 2](https://addons-dev.allizom.org/en-US/developers/addon/foxypac-dev/file/254944/validation))
- add-on with `browserSettings.proxyConfig` are still giving [this warning](https://addons-dev.allizom.org/en-US/developers/upload/de4bf22be67b4631baf1f093ef7bcf4f). I've tried it in FF59 and FF60. 
Should I understand that `browserSettings.proxyConfig` is still not supported?

**Comment by EnTeQuAk** [comment]
> add-on with browserSettings.proxyConfig are still giving this warning. I've tried it in FF59 and FF60.
Should I understand that browserSettings.proxyConfig is still not supported?

This is the currently correct behavior. There is https://github.com/mozilla/addons-linter/issues/1992 to discuss future backwards compatibility so for now this is expected and correct.

Thanks a lot for testing!

**Comment by AlexandraMoga** [comment]
Marking issue as verified fixed on AMO-dev and stage with FF60, Win10x64
