### ISSUE TITLE
Show error when submitting legacy language pack for Firefox

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-linter#1985]
We're discontinuing legacy language packs on AMO, so we need to show an error to stop any future submissions. The presence of the `install.rdf` file is how they are detected. This is limited to language packs that support Firefox (all add-ons supporting Thunderbird and SeaMonkey are going to be handled separately).

The error message should be:

> Legacy language packs for Firefox are no longer supported. A [WebExtensions install manifest](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json) is required.

**Comment by wagnerand** [comment]
> The presence of the install.rdf file is how they are detected.

Is that distinctive enough? Wouldn't dictionaries meet that requirement too?

**Comment by jvillalobos** [comment]
They have a different type in the manifest. I didn't mean that having an `install.rdf` is the *only* condition, but rather that is how you distinguish between the legacy and non-legacy variants.

**Comment by EnTeQuAk** [comment]
@jvillalobos what's the timing on this? When can this be implemented or go live?

**Comment by jvillalobos** [comment]
Developers have already been notified, so this can go out as soon as it's ready.

**Comment by EnTeQuAk** [comment]
Alrighty, I'll get this ready for the 06.21 milestone.


On Fri, Jun 8, 2018, at 5:39 PM, Jorge Villalobos wrote:
> Developers have already been notified, so this can go out as soon as
> it's ready.> — You are receiving this because you commented. Reply to this email
> directly, view it on GitHub[1], or mute the thread[2].
Links:

  1. https://github.com/mozilla/addons-linter/issues/1985#issuecomment-395800673

**Comment by EnTeQuAk** [comment]
QA: Make sure that no language packs using an install.rdf (e.g, uploading one older Firefox times) should not work anymore. This feature is behind the `disallow-legacy-langpacks` waffle.

**Comment by AlexandraMoga** [comment]
Verified on AMO -dev after enabling the `disallow-legacy-langpacks` switch.
When submitting a legacy language pack, the new incompatibility error message is received.
Dictionaries and webextension language packs submission works as expected.

![image](https://user-images.githubusercontent.com/31961530/41600169-ce179d28-73dd-11e8-93dd-46e9278acf0f.png)

Marking issue as verified fixed
