### ISSUE TITLE
[Ongoing] Update Library Hashes

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-linter#2005]
IMHO, it would be an idea to keep one topic for this report, instead of opening a new topic each time ...

Bootstrap.js 4.1.1
underscore 1.9.0
AngularJS v1.7.0

**Comment by EnTeQuAk** [comment]
These are already in dispensary afaik and I disagree that we should not have one issue to track them all. Separate issues are much easier to follow and reference for specific milestones. That way we know exactly when something lands.
