### ISSUE TITLE
There is a JavaScript syntax error in your code, line 1, column 1

### ISSUE THREAD

**Issue by woky** [mozilla/addons-linter#2024]
Report:

    $ addons-linter output/archives/upload.zip                                                                                              
    Validation Summary:
    
    errors          2              
    notices         0              
    warnings        0              
    
    ERRORS:
    
    Code              Message                   Description                                                                   File                      Line   Column
    JS_SYNTAX_ERROR   JavaScript syntax error   There is a JavaScript syntax error in your code; validation cannot continue   generated/background.js   1      1     
                                                on this file.                                                                                                        
    JS_SYNTAX_ERROR   JavaScript syntax error   There is a JavaScript syntax error in your code; validation cannot continue   generated/Pinboard.js     1      1     
                                                on this file.                                                                                                        

Source files:

    % gist ./generated/background.js
    https://gist.github.com/9489b9b2885dc4c9a4510ced718023ed
    % gist ./generated/Pinboard.js  
    https://gist.github.com/0434b22d30ced28d76d7c5a8effb6d95

**Comment by wagnerand** [comment]
Looks like eslint doesn't know about `import/export`.

**Comment by kewisch** [comment]
See #1775
