### ISSUE TITLE
Fix rules gh-pages favicon

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-linter#2030]
Rules favicon was committed directly to the gh-pages branch [here](https://github.com/mozilla/addons-linter/pull/1546/files), but since this is generated it gets blown away but the rules publication. 

Fixing this requires adding it to the template instead.

**Comment by vcarciu** [comment]
@muffinresearch  : Can you please add some STRs to this issue or mark it as "qa: not needed" ?
