### ISSUE TITLE
[Static Themes] The linter doesn't detect when an image specified in the manifest is missing from the theme package

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-linter#2052]
STR:

1. Log in to AMO -dev
2. Choose a static theme and make sure that an image specified in the manifest is missing from the package - i.e. delete the image or change its type (from `.png` to `.jpg`)
3. Submit your static theme via dev hub distribution page
4. Observe the validation results

Actual result:
There is no error generated at static theme submission

Expected result:
The linter should detect when an image specified in the manifest is missing from the package

Notes:
- here is an example of a submitted theme: https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/st-theme-zip-j
- reproduced on AMO -dev with FF60, Win10x64

**Comment by rpl** [comment]
@EnTeQuAk @AlexandraMoga This should have been fixed in #2271 as part of the changes introduced to fix #2051.

**Comment by AlexandraMoga** [comment]
This was indeed verified in #2051 and the issue can't be reproduced anymore:

![image](https://user-images.githubusercontent.com/31961530/48704698-ec648a80-ebff-11e8-9a99-0609d1b7e43b.png)

Verified fixed on AMO -dev with FF63, Win10x64
