### ISSUE TITLE
ES6 import is not supported

### ISSUE THREAD

**Issue by lunu-bounir** [mozilla/addons-linter#2053]
### Describe the problem and steps to reproduce it:

In my extension's window (basically an HTML page), I have ES6 static import statement and I get "JavaScript syntax error" in the addons-linter which does not let me to submit my add-on.

### What happened?
Got syntax error message and the submit button is disabled

### What did you expect to happen?
The linter should support or ignore ES6 import keyword.

### Anything else we should know?
no

**Comment by lunu-bounir** [comment]
btw, the extension works just fine in the latest released version of FF (debugging mode)

**Comment by EnTeQuAk** [comment]
This work is ongoing and will be handled in #1775, es6-modules are currently unsupported in the linter but that very certainly will change next Thursday (not this weeks Thursday unfortunately).

Please stay tuned :)
