### ISSUE TITLE
Validate Web Extension Dictionaries

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-linter#2055]
In the linter, validate that:

* [ ] Dictionaries only includes the dictionary manifest flags. Dictionaries shouldn't run any code.
* [ ] Show an error if a dictionary uses strict_max_version, since they shouldn't have compatibility restrictions.

**Comment by diox** [comment]
On this topic:

> Dictionaries only includes the dictionary manifest flags. Dictionaries shouldn't run any code.

@EnTeQuAk suggested this:

> Similarly to static themes I'd guess that dictionaries should never contain anything in the manifest from regular WebExtensions, e.g content_script or others should error. (This should be happening for langpacks too but hasn't been implemented yet). We achieve this by injecting `additionalProperties: false`.

**Comment by AlexandraMoga** [comment]
I believe this issue was verified through https://github.com/mozilla/addons-linter/issues/1984#issuecomment-411032806
