### ISSUE TITLE
"Words found that violate the Mozilla conditions of use" for official IANA and ICANN TLDs lists

### ISSUE THREAD

**Issue by therealglazou** [mozilla/addons-linter#2057]
### Describe the problem and steps to reproduce it:

For various reasons, we have to include in our WebExtension the official list of existing TLDs IANA regularly updates at https://data.iana.org/TLD/tlds-alpha-by-domain.txt .

### What happened?

addons-linter complains that file contains "Words found that violate the Mozilla conditions of use"...

We have the same problem when we include another official resource provided by this time ICANN: https://www.icann.org/resources/registries/gtlds/v2/gtlds.json

And we have a last similar problem with a well-known fulltext language detector called Franc: https://github.com/wooorm/franc

### What did you expect to happen?

We understand the presence of some words inside the official IANA and ICANN lists trigger the warning but we're clearly not responsible for that and there is absolutely nothing we can do here. These are official TLDs, after all. Similarly, we just cannot fork Franc library to remove the faulty words; it would be extremely complicated anyway since France is multilingual.. On another hand, the warning in the results of addons-linter scares our team and we have no idea how AMO is going to react to it.

Maybe just change the warning prose to say that such cases will be studied on case-per-case basis and do it in practice?

### Anything else we should know?
(Please include screenshots and any relevant files.)

**Comment by jvillalobos** [comment]
The message is just a warning, and reviewers shouldn't reject on it unless they find something that is really objectionable. Maybe we can do something about the content of the message to better reflect that.

/cc @wagnerand @kewisch

**Comment by caitmuenster** [comment]
I'd like to update the content of the message to make it clear that it's just a warning and will not block submission. 

Maybe the warning could say something like "Words found may violate Mozilla's Conditions of Use and could result in your extension being rejected from addons.mozilla.org. For more information, please see https://www.mozilla.org/about/legal/acceptable-use/."

**Comment by wagnerand** [comment]
I am fine with the suggested change of copy, although to me it sounds more scary than the current one. I am also not sure whether it really makes clear that this is a warning only, and if we should even try and do that. The validation result design uses a distinct layout for warnings vs blocks.

**Comment by jvillalobos** [comment]
Separately from this, we should probably make it clearer that warnings are non-blocking, since most devs will never see hard errors.

**Comment by wagnerand** [comment]
Closing in favor of https://github.com/mozilla/addons-linter/issues/2591.
