### ISSUE TITLE
Import Firefox 62 Beta schema

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-linter#2073]

**Comment by EnTeQuAk** [comment]
This isn't on -stage yet, only on -dev.

QA: Just make sure that add-on validation works as expected and as before. There should not be any obvious changes that require testing.

You can test this change by writing an add-on that uses https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/getSecurityInfo which should now be allowed by the linter.

**Comment by EnTeQuAk** [comment]
This is now on -stage too.

**Comment by vcarciu** [comment]
Verified in Stage: 
![webrequest](https://user-images.githubusercontent.com/1583842/43829522-d4f5a648-9b07-11e8-94e9-59d0c7f3faf3.gif)
