### ISSUE TITLE
Firefox Addons upload doesn't accept WebExtension theme

### ISSUE THREAD

**Issue by Dani3lNL** [mozilla/addons-linter#2074]
Tried to upload my .zip containing the manifest.json and a .png. Error message appeared.

**Comment by wagnerand** [comment]
Can you please attach the file you were trying to submit?

**Comment by wagnerand** [comment]
Actually, webextension theme submission is not enabled yet as we're still working on the implementation.

**Comment by Dani3lNL** [comment]
@wagnerand Will the implementation (webextension theme submission) come to Firefox Nightly first/is it firefox client related, or will it directly work with the Firefox release version aswell? And can I read somewhere about the current progress of implementation/an expected week for release? (I hope we can get it to work next week or until mid july)

**Comment by wagnerand** [comment]
Once submission on AMO is enabled, they should work in current release (61) and newer.

**Comment by wagnerand** [comment]
> Once submission on AMO is enabled, they should work in current release (61) and newer.

I should probably add that this should not be considered an authoritative answer, since I am not involved in the client-side work for themes. I do know that relevant people have it on their radar and scheduling will be coordinated.

**Comment by Dani3lNL** [comment]
Is there a specific github Issue (link?) that states what work remains until webextension themes can be allowed? Or is there even more than one AMO problem that must be solved before WE themes can be accepted?

**Comment by wagnerand** [comment]
Maybe @eviljeff has more information he can point you to.

**Comment by Dani3lNL** [comment]
@wagnerand and is there a way to get an email once the update has been pushed (so that I will know the instant when AMO accepts webextension themes) ?

**Comment by jvillalobos** [comment]
We will announce it in the [Add-ons Blog](https://blog.mozilla.org/addons/) and [Discourse](https://discourse.mozilla-community.org/c/add-ons).

**Comment by eviljeff** [comment]
https://github.com/mozilla/addons-frontend/projects/6 has the remaining frontend issues and
https://github.com/mozilla/addons-server/labels/project%3A%20static%20themes shows the remaining backend (api/developer hub) issues.  Not all of the issues are blockers on launching the feature though.

**Comment by Dani3lNL** [comment]
But I assume you want to/must have fixed all P3 priority issues before launching the feature?

**Comment by eviljeff** [comment]
Not really. P3 is just general priority we'd like fix at some point. Some
relate to cleaning up code later; some to the existing theme migration
rather than the launch; some will just be too complicated to fix in the
next few weeks and we'll aim to do afterwards.

**Comment by Dani3lNL** [comment]
Could somebody please reply here if currently the plan is to fix all of these issues listed [here](https://github.com/mozilla/addons-server/labels/project%3A%20static%20themes) before allowing webExtension theme uploads?

**Comment by wagnerand** [comment]
That question has been answered above.

**Comment by Dani3lNL** [comment]
"P3 is just general priority we'd like fix at some point" he wrote, which makes the impression that there is currently no issue which delays the release of the feature/must be fixed before we can upload webExtension theme?

**Comment by wagnerand** [comment]
There might be other, non-code related tasks like cross-team coordination, documentation, testing etc that plays a role. We will announce a timeline soon.

**Comment by Dani3lNL** [comment]
I hope you (developers) will announce it this week? Or what is your estimate?

**Comment by jvillalobos** [comment]
As I wrote above, it will be announced in the add-ons blog when it happens.  No other status updates will be posted here.

**Comment by Dani3lNL** [comment]
Cool!! Only Issue #8038 remaining! :D

**Comment by wagnerand** [comment]
I am locking comments in this issue since it's already closed and I don't see any relevant information to this issue being added. Communication schedules and timelines are outside of the scope of this issue. For everyone interested in this, please monitor the [Add-ons Blog](https://blog.mozilla.org/addons/) for an announcement.
