### ISSUE TITLE
Show a warning when validating an extension that uses native messaging

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-linter#2075]
STR:

1. Log in to Developer Hub
2. Submit a new extension that uses a native messaging permission (see example)
3. Observe the validation results

Actual result:
There is no warning triggered at validation

Expected result:
A warning should be displayed to inform the developers that they are using a sensitive permission

Notes:
- add-ons with native messaging will receive a weight of 100 now, which places them quite high in the risk factor queue
- example used:  
[native-messaging.zip](https://github.com/mozilla/addons-linter/files/2139964/native-messaging.zip)
- reproduced on all AMO servers, with FF60, Win10x64

**Comment by asamuzaK** [comment]
As an addon developer, it will be very annoying to be warned every time.
How about staying at notification, not warning?

**Comment by wagnerand** [comment]
It could be useful for reviewers, yes. But I see @asamuzaK's point. I think we need to start categorizing and splitting linter annotations (reviewers vs developers) and then only show the respective category by default before we can add more warnings like this one.

**Comment by muffinresearch** [comment]
Since the status quo (no warning or notification) doesn't impact developers at all except that their code might get a manual review sooner, I don't see the a strong need to add a warning for this.
