### ISSUE TITLE
'Font Awesome Free' Library Hashes

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-linter#2104]
I have seen many add-ons using the _Font Awesome Free_ JavaScript. As a result, I have added them to my own hash checker. I thought maybe it is worth considering its inclusion in the linter.

CDN (example): https://use.fontawesome.com/releases/v5.1.0/js/fontawesome.js
```
'3b0de868f7abdc8997b51dae1e1ec9b8e81479301e1a697531ac1a2a93751887': 'fontawesome-5.0.4.js',
'64740333022d3deb7f274a00abb57cc09925ae38dbdec31583f7a155e6364e68': 'fontawesome-5.0.5.js',
'374682a501cf4a232a7c2508c9be6a778e5f03307870f9ce6d228c9c8a8b8bda': 'fontawesome-5.0.6.js',
'ec5270793d58a03bc75e4461a443e9baafea7010ccd933d5966eaab6a313de83': 'fontawesome-5.0.7.js',
'b8e3256cf5e9c1d7653ef8f13112f7f78e449626711353248ed1629ea5984f08': 'fontawesome-5.0.8.js',
'bcd2ff02fd95d4e57e387e6fc11d96b14b7448279bafa4a9c8c6e48c2bb24afb': 'fontawesome-5.0.9.js',
'e6ddadded7c3e5ade7691b3d2aea8b3e6188da118b62db001f4beb47ff0591b1': 'fontawesome-5.0.10.js',
'b4ff28a1f1d6b79523c5c928ab999feba29d27855bd004f4057746aeae89019c': 'fontawesome-5.0.11.js',
'6958d93a5d110d1f5d8f35dbddc24ade4d4ecb1f160c35cc5e86aebf64619e2c': 'fontawesome-5.0.12.js',
'dc95e73cf623a2cdf21ecc979ad38a1c8408b95034b9ed6d5898e9b56eaffc79': 'fontawesome-5.0.13.js',
'e2c15189607eb27c4d2c2708dfd8e08dcc71a671f8904dbd8484d8a767105621': 'fontawesome-5.1.0.js',
'f1520fa4c6e7d78d0bb81039b3f7bf6016c67a7e27cb701d9309a822f7c61de5': 'fontawesome-5.1.1.js',
```
@wagnerand

**Comment by wagnerand** [comment]
Have you reviewed them to make sure they are safe?

**Comment by erosman** [comment]
> Have you reviewed them to make sure they are safe?

https://github.com/FortAwesome/Font-Awesome
I have checked them overall and they mostly deal with safe functions but I haven't checked them deeply and thoroughly.

It has `innerHTML` & `outerHTML` but no `fetch/ajax/xhr` so they are all local string (even though they didn't really need to use `innerHTML` in some places e.g. `style.innerHTML = css;` where `css` is text and `textContent` would have been optimal).

Here is the unminified code:
https://github.com/FortAwesome/Font-Awesome/blob/master/svg-with-js/js/fontawesome.js

The fact is that they have already been in use and accepted in a great number of add-ons on AMO so I thought we might as well have the hashes.

**Comment by wagnerand** [comment]
I am closing this for now. I agree that it's a good idea to expand the list, but the process is very manual currently and we don't have a good way (yet) to assess impact. There is some upcoming work planned around code search where we could hook into for this. I am planning to revise the known libraries list after that has been landed.
