### ISSUE TITLE
Replace NPM token

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-linter#2105]
Tokens have been revoked and need re-issuing.

These tokens were revoked because of a backdoor in eslint-scope@3.7.2 that stole the content of ~/.npmrc: https://status.npmjs.org/incidents/dn7c1fgrr7ng

This affected any installation of eslint-scope@3.7.2 for two hours last thursday (12 July 2018). For the exact timeline, see https://eslint.org/blog/2018/07/postmortem-for-malicious-package-publishes

**Comment by vcarciu** [comment]
@muffinresearch : can you please add some STRs to this issue or mark it as "qa: not needed" ?
