### ISSUE TITLE
Rule: Flag any reference to XPIProvider as a high severity signing warning

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-linter#211]
XPIProvider is a private interface which add-ons should not be allowed to access. We need to flag any reference to either the symbol or the name. See bug https://bugzilla.mozilla.org/show_bug.cgi?id=1200929 for more.

**Comment by EnTeQuAk** [comment]
stupid question, is that interface something only relevant for legacy add-ons? It seems that way, if so let's close this one here since we only support WebExtensions :)

**Comment by wagnerand** [comment]
I am pretty sure this does not apply to the linter, but it sounds like something we want for amo-validator.

**Comment by jvillalobos** [comment]
This issue has been open for over a year, with no action, and dropping legacy add-ons is less than a year away. It doesn't sound like it's going to happen.

**Comment by wagnerand** [comment]
We have to support legacy add-ons for ESR after November, which means we also have to support amo-validator for a longer period. So let's move this over to amo-validator?

**Comment by EnTeQuAk** [comment]
Opened in amo-validator repository: https://github.com/mozilla/amo-validator/issues/500
