### ISSUE TITLE
Validate extensions as language packs if language pack properties are found in the manifest

### ISSUE THREAD

**Issue by diox** [mozilla/addons-linter#2120]
It looks like the only way for the linter to validate language pack properties is through the use of the `--langpack` command line flag. This is a problem, because addons-server does not pass that flag to the linter.

I believe the linter should detect the type on its own, like it does for static themes, by looking for the `langpack_id` property in the manifest. 

To prove that it doesn't work on AMO right now: I uploaded https://addons-dev.allizom.org/en-US/developers/addon/not-a-real-polski-language-pac/ which uses an invalid `langpack_id`, I didn't receive a validation error. Locally, when validating it I don't receive an error either, unless I manually use the `--langpack` flag.

**Comment by diox** [comment]
The code responsible for this:
- https://github.com/mozilla/addons-linter/blob/10e4ba9a50736a94bb78c8139f9a381c952cdcd3/src/parsers/manifestjson.js#L42 sets `isLanguagePack` from the config
- https://github.com/mozilla/addons-linter/blob/10e4ba9a50736a94bb78c8139f9a381c952cdcd3/src/parsers/manifestjson.js#L60 sets it on `this`
- https://github.com/mozilla/addons-linter/blob/10e4ba9a50736a94bb78c8139f9a381c952cdcd3/src/parsers/manifestjson.js#L119-L121 does the langpack-specific validation, but only if `this.isLanguagePack` is `true`.

**Comment by diox** [comment]
If it's just a matter of changing that initial `isLanguagePack` value, detecting it from the manifest and removing the `--langpack` option, I can do it myself. However, I'd like confirmation that I'm not looking at this wrong first :)

**Comment by diox** [comment]
Also, language packs should not run any code. @EnTeQuAk suggested to inject `additionalProperties: false` when validating dictionaries, like it's done for static themes, and we can do the same for language packs.

**Comment by diox** [comment]
While we are at it the notice about `strict_max_version` should not apply to langpacks. They *are* meant to have a max version.

**Comment by AlexandraMoga** [comment]
@diox I've used the language pack example you posted above and I've uploaded it on -dev, however, I don't see any changes during validation, specifically:
- there is no error triggered for the invalid `langpack_id`
- the `strict-max-version` notice is still present in the validation results 
- if I include any properties which are not supposed to be present in language pack manifests (i.e. a CSP) there are also no errors triggered

Am I missing some steps here maybe?

**Comment by diox** [comment]
@AlexandraMoga sorry, we haven't made a new linter release with those changes, so it hasn't been pushed to dev yet.

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF61, Win10x64

- errors are generated for invalid `langpack_id` or unintended additional properties 
- `strict-max-version` notice is no longer displayed in the validation results 

Validation results: https://addons-dev.allizom.org/en-US/developers/upload/877ce4f6c3fc42b38c9b7b9dee020f96

![image](https://user-images.githubusercontent.com/31961530/43720578-380867d6-9999-11e8-8d65-5b8d9c2df5a0.png)
