### ISSUE TITLE
Unify manifest.json schema overwrites

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-linter#2131]
Thanks to me not looking properly we now have two places where we have manifest.json schema overwrites:

In the `schema/validator.js` - https://github.com/mozilla/addons-linter/blob/master/src/schema/validator.js#L79-L96
And (I actually just found this or noticed it) in `schema/updates/manifest.json` we also have schema overwrites.

We should unify this and probably merge the first one with the second one since that contains already quite a lot of overwrites.

**Comment by muffinresearch** [comment]
@EnTeQuAk would it be possible to add more specific actionable instructions so this can be opened up to a contribution?
