### ISSUE TITLE
Bad Word "AltRight" conflicts with KeyboardEvent.code "AltRight"

### ISSUE THREAD

**Issue by roysix** [mozilla/addons-linter#2151]
### Describe the problem and steps to reproduce it:
The [KeyboardEvent.code](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code) returns the String `AltRight` when the Alt Right modifier key is pressed. When developers write extensions that need to check for the return value of this specific key's event, they'll see a warning that their code violates Mozilla's policy. I am guessing this may be due to the conflict with the Bad Word `altright` in [badwords.json](https://github.com/mozilla/addons-linter/blob/master/src/badwords.json).

In [#1656](https://github.com/mozilla/addons-linter/issues/1656), the Bad Word `alt-right` was originally in the list, but was removed/replaced due to a conflict with a 3rd party JS library called `Ace.js` that apparently uses `alt-right` in its code. However, the correct spelling of the term according to [Wikipedia](https://en.wikipedia.org/wiki/Alt-right) is indeed `Alt-right`. Also, IMO, the standardized JS `KeyboardEvent.code` should supersede the 3rd party library `Ace.js` on priority on this.

I suggest replacing the Bad Word `altright` with `alt right` (space), or revert back to the correct spelling `alt-right` (hyphen), or perhaps maybe even renaming it `alternative right`. What do you all think?

**Comment by wagnerand** [comment]
Closing in favor of https://github.com/mozilla/addons-linter/issues/2591.
