### ISSUE TITLE
Restrict length of add-on name and summary (description)

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-linter#2154]
We're setting these limits on the dev hub in https://github.com/mozilla/addons-server/issues/9243, but it would also be good that the linter warns developers about this during development.

**Comment by jvillalobos** [comment]
The requirement is that both `name` and `description` are required in the manifest, with a minimum length of 2 characters each. And, the _combined lengths_ of `name` and `description` should be 70 characters at most. So, in theory, the `name` could be 68 chars and the `description` 2 chars, and vice versa.

**Comment by kewisch** [comment]
@andreeaNeamtiu will be working on this.

**Comment by caitmuenster** [comment]
Hey @andreeaNeamtiu, can you hold on this? This was part of a larger project that is on hold indefinitely and we're not ready to accept patches for this issue.
