### ISSUE TITLE
angular 1.7.2 marked as Error

### ISSUE THREAD

**Issue by szz-dvl** [mozilla/addons-linter#2155]
### Describe the problem and steps to reproduce it:
I'm trying to upload a new version of  [jsloader] (https://github.com/szz-dvl/JSLoader), with my libraries updated to last version, it is angular 1.7.2, however it still complains.

### What happened?
I can't carry on with my review process since I can not upload a new version.

### What did you expect to happen?
Upload a new version updated.

### Anything else we should know?
I was banned from Listing ...

**Comment by wagnerand** [comment]
We are monitoring the [github page](https://github.com/angular/angular.js/releases) for angular and that one has 1.7.3 listed as the newest release. It seems they just haven't updated the website yet.

Can you upgrade to 1.7.3 please and resubmit?
