### ISSUE TITLE
Don't allow use of "Mozilla" or "Firefox" in add-on names 

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-linter#2158]
Up until now, we've allowed add-on names to end with "for Firefox" or "for Mozilla". For SEO reasons, we don't want to allow this anymore. Any use of those terms in add-on names should produce an error.

/cc @wagnerand to coordinate policy change when this lands.

**Comment by wagnerand** [comment]
Thanks Jorge!

What is the timeline for this?

I assume there will be some kind of validation for any submission (both new add-ons and updates to existing ones). We need to keep in mind that updates with a changed name in the XPI does not automatically update the name on AMO.

What will happen to existing add-ons that don't get updates? Will they be automatically updated by us? We need to keep potential conflicts in mind, e.g. when an add-on gets renamed from "Ad Blocking for Firefox", but there is already an "Ad Blocking" add-on listed.

We also might want to add "Fire fox" to the list, since that is an easy workaround with a similar impact on SEO.

**Comment by EnTeQuAk** [comment]
Luckily the current validation happens directly on addons-server and not on the linter, so we should be able to distinguish between new submissions and updates in case we want to handle them differently.

**Comment by jvillalobos** [comment]
> What is the timeline for this?

It's part of a Q4 project, but if anyone wants to tackle this before then, it should be fine.

> What will happen to existing add-ons that don't get updates?

Once the check is in place for submissions, we'll have to reach out to devs and give them some time to adjust. After that, we'll just change the names ourselves.

> We also might want to add "Fire fox" to the list,

There are so many variations that I don't think we should try to cover them automatically.

> Luckily the current validation happens directly on addons-server and not on the linter,

@EnTeQuAk should I move this to addons-server then?

**Comment by jvillalobos** [comment]
> should I move this to addons-server then?

Or, rather, should I _also_ file an issue on addons-server?

**Comment by EnTeQuAk** [comment]
> Or, rather, should I also file an issue on addons-server?

I guess both projects need a change, we currently don't have any checks in addons-linter regarding the trademark but eventually, we should warn developers ahead of time in case they're using disallowed add-on names.

So yes, both would be nice. Thanks!

**Comment by muffinresearch** [comment]
@jvillalobos since the server-side changes are done and it appear based on https://github.com/mozilla/addons-server/issues/9267#issuecomment-432577779 to not affect specific account presumably the change on the linter side should only be a warning?

**Comment by jvillalobos** [comment]
Yeah, as long as we block submission on addons-server (for non-Moz accounts), it should be okay to have the linter just warn about it.

**Comment by vaindil** [comment]
This is already being enforced (my add-on can't have "for Firefox 57+" in the name), but the [add-on policies page](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/AMO/Policy/Reviews#Content) has not been updated. I just ran into this issue for an add-on and had search to find this issue here.

**Comment by caitmuenster** [comment]
Thanks @vaindil! I can look into updating this.

**Comment by muffinresearch** [comment]
The outstanding action here is to add warnings here in the linter.

**Comment by marchiore** [comment]
Is this still in the roadmap? Can i work on it?

To make the proposed solution clear, it is necessary to create a new rule in linter to see if the extension name (property name in manifest.json) has the words `Mozilla` or `Firefox`and warn the user. Am I right?

**Comment by vaindil** [comment]
I'm not sure if this is still accurate, because the [add-on policies page](https://extensionworkshop.com/documentation/publish/add-on-policies/#content) has the below quote. I don't know if that has always been there though.

> Add-ons that make use of Mozilla trademarks must comply with the [Mozilla Trademark Policy](https://www.mozilla.org/foundation/trademarks/policy/). If the add-on uses “Firefox” in its name, the naming standard the add-on is expected to follow is “<Add-on name> for Firefox”.

**Comment by jvillalobos** [comment]
> Is this still in the roadmap? Can i work on it?

Yes

> To make the proposed solution clear, it is necessary to create a new rule in linter to see if the extension name (property name in manifest.json) has the words Mozilla or Firefoxand warn the user. Am I right?

That's right. You might also need to check for localized versions of the name, but I don't know how complex that is to do on the linter.

**Comment by marchiore** [comment]
Just created #3123

**Comment by vaindil** [comment]
Is the add-on policies page ever going to be updated to reflect this?

**Comment by wagnerand** [comment]
> Is the add-on policies page ever going to be updated to reflect this?

Probably, in a future update.

**Comment by vaindil** [comment]
This has been enforced for over a year now but the policies page hasn't been updated, that was why I asked. Thanks!

**Comment by marchiore** [comment]
@vaindil I can send a PR to `extension-workshop` update if you want.

https://github.com/mozilla/extension-workshop/blob/30fbb23760bc073fa133d8834d1231d8803223a3/documentation/publish/add-on-policies.md

from:

> Add-ons that make use of Mozilla trademarks must comply with the Mozilla Trademark Policy. If the add-on uses “Firefox” in its name, the naming standard the add-on is expected to follow is “<Add-on name> for Firefox”.

to:

> Add-ons name must not uses the words `mozilla` or `firefox` like `<Add-on name> for Firefox` and if it make use of Mozilla trademarks must comply with the Mozilla Trademark Policy.

do you think it is necessary to add some more information or is this good?

**Comment by wagnerand** [comment]
Thanks, I appreciate the effort but we do not accept pull requests for changes to the policies page. There is a larger process involved, we will likely change that with our next planned update.

**Comment by willdurand** [comment]
see also https://github.com/mozilla/addons-server/issues/14656#issuecomment-650144734
