### ISSUE TITLE
No longer allow jQuery 2 in add-ons

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-linter#2168]
jQuery 2.x is unsupported and as communicated to add-on developers earlier this year, will no longer be allowed in add-ons after a grace period that is now over.

When the linter detects a jQuery 2.x file, the validation should fail.

**Comment by AlexandraMoga** [comment]
@wagnerand  can this be tested already in -dev or should we wait for a new linter update?
Thanks

**Comment by EnTeQuAk** [comment]
This is now on -dev.

**Comment by AlexandraMoga** [comment]
I've tried to upload an extension that included a jquery 2.x file (jquery-2.1.1) and I received the following validation results:

Full validation can be checked [here](https://addons-dev.allizom.org/en-US/developers/upload/3124c01ee8df40aa8c9fa63e8ea44948)
![image](https://user-images.githubusercontent.com/31961530/45081167-4aa0c780-b0ff-11e8-80ae-2408ffda8aec.png)



@EnTeQuAk could you please have a look an let me know if this is the expected result?

**Comment by EnTeQuAk** [comment]
Yes, jQuery 2.x is now a banned 3rd party library so the error message is expected and correct.

**Comment by AlexandraMoga** [comment]
Ok, in that case I'm going to mark this issue as verified fixed on AMO -dev and stage with FF62, Win10x64
