### ISSUE TITLE
Import Firefox 63 Beta schema

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-linter#2170]
Firefox 63 Beta will be released Sept 04th

**Comment by wagnerand** [comment]
Raising to P2 because 63 release is approaching.

**Comment by EnTeQuAk** [comment]
Fixed as part of https://github.com/mozilla/addons-linter/pull/2181

**Comment by ioanarusiczki** [comment]
Verified on AMO stage with FF62(Win10) - release testing was performed [here](https://testrail.stage.mozaws.net/index.php?/runs/view/13043&group_by=cases:section_id&group_order=asc)
I tested the submission with all add-on types (listed and unlisted, mixed versions) and the submission works, the add-ons were signed.
