### ISSUE TITLE
AngularJS 1.x support

### ISSUE THREAD

**Issue by eiselzby** [mozilla/addons-linter#2176]
### Describe the problem and steps to reproduce it:
In `addons-linter/docs/third-party-libraries.md` is declared, that is allowed only latest version of Angular 1.x. In file `addons-linter/src/libraries.js` is banned every version till 1.7.2. Therefore extension containing AngularJS 1.7.2 library fail validation. But on webpage https://angularjs.org/ under _Download AngularJS_ button is presented version 1.7.2 as the latest.

### What happened?
Rejected updated extension upload because of presents of AngularJS 1.7.2.

### What did you expect to happen?
Approved extension and at most be warned about using 3rd party library.

### Anything else we should know?
1. Using Angular 1.7.2
2. Forbidden in `libraries.js` 
https://github.com/mozilla/addons-linter/blob/0171a6f3b32f0d29de41b741f2c5c547f5b3bdb2/src/libraries.js#L204
3. The ?latest? AngularJS 
![image](https://user-images.githubusercontent.com/9251078/45038018-a49e8000-b060-11e8-91a4-890116421550.png)
4. Failed AMO validation 
![image](https://user-images.githubusercontent.com/9251078/45038957-b719b900-b062-11e8-97a9-8270646122ce.png)

**Comment by wagnerand** [comment]
According to https://github.com/angular/angular.js/releases, the latest version is 1.7.3. Can you please use that version instead?

**Comment by eiselzby** [comment]
Thank you for your answer. I will.

Couldn't be added the information about latest supported version in extension validation process to prevent similar misunderstandings, when webpages like https://angularjs.org/ are a bit out of date?
