### ISSUE TITLE
Upgrade to Babel 7

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-linter#2177]
https://babeljs.io/docs/en/v7-migration

**Comment by pdehaan** [comment]
Possibly relevant/helpful: https://github.com/babel/babel-upgrade

**Comment by EnTeQuAk** [comment]
Thanks! Already found and used as part of #2175

**Comment by AlexandraMoga** [comment]
@EnTeQuAk  any testing required?
Thanks
