### ISSUE TITLE
Look at switching back to Sentry's babel-gettext-extractor lib #6457 

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-linter#2211]
Looks like they've pulled in the changes from the Mozilla fork so we can switch back to it and deprecate the mozilla version ([once the frontend switches too](https://github.com/mozilla/addons-frontend/issues/6457)).

See https://github.com/getsentry/babel-gettext-extractor

**Comment by muffinresearch** [comment]
Note they are still awaiting Babel 7 changes so that might be something worth considering.

**Comment by EnTeQuAk** [comment]
https://github.com/getsentry/babel-gettext-extractor/pull/17 for tracking.

**Comment by willdurand** [comment]
🎉 https://github.com/getsentry/babel-gettext-extractor/pull/17

**Comment by AlexandraMoga** [comment]
Please add STR or the qa:not needed label.
Thanks
