### ISSUE TITLE
Support "menus.overrideContext" on "permissions" and "optional_permission"

### ISSUE THREAD

**Issue by piroor** [mozilla/addons-linter#2242]
### Describe the problem and steps to reproduce it:

A new permission "menus.overrideContext" was introduced by changes at https://bugzilla.mozilla.org/show_bug.cgi?id=1280347 and related bugs. Firefox ESR60 and existing release versions accept such an unknown optional permission, but the linter reports error, thus I cannot release any addon using the new feature. Please add it to the list of allowed permission names. Steps to reproduce:

 1. Prepare an addon.
 2. Put "menus.overrideContext" into the "optional_permissions" in the "manifest.json".
 3. Pack files to XPI.
 4. Upload the XPI.

### What happened?

The linter reports errors for the new permission. For example:

 * "/optional_permissions/2" should be equal to one of the allowed values
   Error: Your JSON file could not be parsed.
 * "/optional_permissions/2" is not a valid key or has invalid extra properties
   Error: Your JSON file could not be parsed.
 * "/optional_permissions/2" should match pattern "^(https?|wss?|file|ftp|\*)://(\*|\*\.[^*/]+|[^*/]+)/.*$"
   Error: Your JSON file could not be parsed.
 * "/optional_permissions/2" should match pattern "^file:///.*$"
   Error:  Your JSON file could not be parsed.
 * "/optional_permissions/2" should match pattern "^resource://(\*|\*\.[^*/]+|[^*/]+)/.*$|^about:"
   Error: Your JSON file could not be parsed.

### What did you expect to happen?

No error is reported for the new permission "menus.overrideContext".

**Comment by EnTeQuAk** [comment]
This will probably be fixed by https://github.com/mozilla/addons-linter/pull/2181 which is WIP and boggling our minds but we're focusing to get this merged and deployed asap.

**Comment by piroor** [comment]
Thanks! But `menus.overrideContext` is added on Firefox 64. Is it convered by #2181?

**Comment by EnTeQuAk** [comment]
Actually, I lied and you're right. It's not covered by #2181 and the linter will start supporting Firefox 64 features once we have the first beta release after the merge. So, sometime around 2018-10-22 depending on when the builds are happening.

**Comment by rpl** [comment]
This issue has been fixed in #2255, which imported Firefox 64 schemas (released as part of version 1.3.7 in #2260).
