### ISSUE TITLE
Discourage use of phrases such as 'WE', 'WebExtension' and 'WebExtensions' in add-on names

### ISSUE THREAD

**Issue by grahamperrin** [mozilla/addons-linter#2247]
Comparable to #2158

[Save Page WE](https://addons.mozilla.org/addon/save-page-we/), for example. Plus some of what's found by <https://addons.mozilla.org/search/?type=extension&q=WebExtension>, and so on. 

In the context of [legacy switch off](https://github.com/mozilla/addons-server/labels/project%3A%20legacy%20switch%20off), distinguished naming is a waste of space.

**Comment by jvillalobos** [comment]
This doesn't have the same SEO implications as #2158, but it's still worth considering for the reasons stated above. It's a product + reviewer decision. /cc @atsay @wagnerand @caitmuenster, maybe next week when we're together is a good time to talk this through.

**Comment by EnTeQuAk** [comment]
@jvillalobos quick product opinion on this given this taking into account our 2019 focus?

**Comment by jvillalobos** [comment]
It might still apply, but let's hold off until we have a clear plan.

**Comment by muffinresearch** [comment]
@jvillalobos any further thoughts on this or can we close it out?
