### ISSUE TITLE
src/badwords.json false positive "dago" is benign "there is" in Basque.

### ISSUE THREAD

**Issue by Leif-W** [mozilla/addons-linter#2248]
### Describe the problem and steps to reproduce it:

False positive from src/badwords.json.  One of my messages.json has this word in a eu-ES (Basque) language file.  The translation of "dago" is a benign "there is".

### What happened?

Submitted an .xpi to AMO site and got the error "Violation of Mozilla conditions of use."

### What did you expect to happen?

I expected a benign word in a foreign language to not trigger errors that confuse add-on reviewers and potentially flag my account for deletion.

### Anything else we should know?

src/badwords.json is an overly simplistic technique that is ignorant of multiple languages.  Every language has potentially offensive words, and there is overlap with totally benign words.  Therefore a more sophisticated technique needs to be employed such that potentially offensive words are given a context of what languages they apply to.  This is the only way to avoid false positives.

**Comment by jvillalobos** [comment]
It's fine to remove.

**Comment by jvillalobos** [comment]
Mentor: @EnTeQuAk

**Comment by RizwanSyed357** [comment]
Hi, I'd like to work on this if possible? This will be the third bug I've worked on for Mozilla. Cheers :)

**Comment by caitmuenster** [comment]
Hey @RizwanSyed357, welcome! This one's all yours. If you have any questions, please mention the issue mentor in the comments!

**Comment by caitmuenster** [comment]
Hey @RizwanSyed357, how's it going with this bug?

**Comment by RizwanSyed357** [comment]
> Hey @RizwanSyed357, how's it going with this bug?

Hey - sorry, may you please un-assign this bug? I've been crazy busy and didn't get time to work on it. 

Thanks again :)

**Comment by caitmuenster** [comment]
No worries, @RizwanSyed357! We'll see you around. :)

**Comment by iYung** [comment]
Hello, can I work on this bug?

**Comment by caitmuenster** [comment]
Hey @iYung, we've put a pause on this issue for the moment for evaluation. 

Would you be interested in working on #1685 instead?

**Comment by wagnerand** [comment]
Closing in favor of https://github.com/mozilla/addons-linter/issues/2591
