### ISSUE TITLE
A bundled JS file with 1 MB in size is not being parsed. It says "File is too large to parse.".

### ISSUE THREAD

**Issue by shridhar-tl** [mozilla/addons-linter#2258]
In my package a JS file with 1MB in size is available. It is a bundle of multiple JS files. It is not being parsed as the size is huge. 1MB isn't a too bit file. Very easily this size can be reached. So kindly fix it ASAP. Because of this issue I was not able to publish a new package.

**Comment by jvillalobos** [comment]
Can you include the XPI you were going to upload?

**Comment by EnTeQuAk** [comment]
@shridhar-tl if you have the time to include the XPI you're having a problem with, that'd help us a lot helping you with the problem you have.
