### ISSUE TITLE
Prepare to prevent use of the deprecated theme property names in new webextension themes submissions

### ISSUE THREAD

**Issue by rpl** [mozilla/addons-linter#2259]
As part of [Bug 1472740 Remove aliased property names from themes](https://bugzilla.mozilla.org/show_bug.cgi?id=1472740), we should coordinate the deprecation of these "aliased theme property names" with the addons-linter, so that we can prevent new theme submissions from using the deprecated aliased properties.

**Comment by rpl** [comment]
> @rpl Are we able to write a migration script which can convert themes hosted on AMO to use the non-aliased names?

@msujaws you mean a script to run locally or a conversion that is meant to happen on the AMO server side?

Looping in @eviljeff, he likely knows more about our plans related to the conversion of the existing LWT themes.

**Comment by msujaws** [comment]
I mean a script that will run on AMO, changing these themes to use the non-aliased names, and which will in-turn trigger updates for Firefox clients to get the non-aliased version of the theme.

**Comment by eviljeff** [comment]
> our plans related to the conversion of the existing LWT themes.

This is about webextension based themes that have been uploaded by users, rather than LWTs, afaik.

@msujaws can you log an issue on mozilla/addons-server?  A script is _possible_ but I wouldn't want to commit to something that may take significant dev & ops time without it going through Product, etc.

**Comment by EnTeQuAk** [comment]
Marking as "in progress" given that there's already a PR up for this, that only needs some updating.

**Comment by AlexandraMoga** [comment]
@rpl can we already verify that the properties mentioned in https://github.com/mozilla/gecko-dev/commit/5b052494ce948cff59bbb1692919df7ea19b1220 are no longer supported by the linter?
