### ISSUE TITLE
mocha.js has term(s) from src/badwords.json that violates Conditions of Use

### ISSUE THREAD

**Issue by lmj0011** [mozilla/addons-linter#2273]
### What happened?

During validation of my addon, I got a notice that a 3rd party library contained words that violates the Mozilla conditions of use.

### What did you expect to happen?

To not have any warnings that were in violation of Mozilla conditions of use.

### Anything else we should know?

here's a gist of the exact file --> https://gist.github.com/lmj0011/992b395794d5504e4a548896abedf439

you can get that file from installing mocha.js v5.2.0

`npm i mocha@5.2.0 --save` 

The file in question will be located at `./node_modules/mocha/mocha.js`

(Please include screenshots and any relevant files.)

![screenshot-addons mozilla org-2018 11 09-18-36-54](https://user-images.githubusercontent.com/9396189/48295150-d9f38f80-e44e-11e8-8520-a0dc503e4fc3.png)

related https://github.com/mozilla/addons-linter/issues/1656

**Comment by plroebuck** [comment]
So, where/what's the problem since you don't specify? Provide line#s instead of a 16K LOC file.
This file is a browserified distribution so it has Mocha's source _and every other dependency package we're using_.

**Comment by lmj0011** [comment]
So, where/what's the problem since you don't specify?

A word from this [list ](https://github.com/mozilla/addons-linter/blob/master/src/badwords.json) is in that dist file.

The addon-linter does not specify what that the word is.

**Comment by plroebuck** [comment]
Does it tell you _where_ in the file? Highlighted somehow?

**Comment by lmj0011** [comment]
@plroebuck 

it only gives a line number if it's a "Warning".

This is a "[Notice](https://mozilla.github.io/addons-linter/#package-layout)", what you see in the screenshot is all the info I got.

**Comment by plroebuck** [comment]
I glanced your badword list. Mocha itself does contain the word 'bang' and its usage is consistent with [reasonable](https://www.google.com/search?q=bang+exclamation+point) usage, not the NSFW variety. So, are we expected to change our code from valid usage b/c a word "can" mean more than one thing?

**Comment by plroebuck** [comment]
```bash
$ grep -r bang lib/*.js
reporters/base.js:  bang: '!'
reporters/dot.js:    process.stdout.write(Base.color('fail', Base.symbols.bang));
```

**Comment by lmj0011** [comment]
> I glanced your badword list. Mocha itself does contain the word 'bang' and its usage is entirely reasonable within context (not the NSFW variety). So, are we expected to change our code from valid usage b/c a word "can" mean more than one thing?

https://github.com/mozilla/addons-linter/issues/2273#issuecomment-437550766 

@jvillalobos

**Comment by jvillalobos** [comment]
It's just a warning message, so it shouldn't be a problem for submission or review. Reviewers verify whether the warning is valid or not before taking any action.

However I don't mind removing that word from the list, given that it can be found in library code.

**Comment by jvillalobos** [comment]
We're removing the bad words list because it's causing more confusion than it helps. So, closing this.
