### ISSUE TITLE
wrong validation error - Duplicate add-on ID found?

### ISSUE THREAD

**Issue by ufb** [mozilla/addons-linter#2274]
### Describe the problem and steps to reproduce it:
I released a new version of my extension and a little later I uploaded a hot fix version with a new version number.
### What happened?
I got a validation error saying: Duplicate add-on ID found.
### What did you expect to happen?
No error message
### Anything else we should know?
(Please include screenshots and any relevant files.)
![error](https://user-images.githubusercontent.com/17272252/48296651-cd485900-e499-11e8-8ba2-fddf931082cf.jpg)

**Comment by ufb** [comment]
Just changed the version number in manifest.json to 3.9.2 and now it worked :]
Still unclear where the Duplicate add-on ID error came from

**Comment by jvillalobos** [comment]
It sounds like you tried to submit using the New Add-on button, rather than the New Version option for that specific add-on.

**Comment by ufb** [comment]
Oh, you are right - it clearly says "Upload Version" at the to of the screenshot. This is weird anyway, cause I always use the "New version" link on https://addons.mozilla.org/en-US/developers/addons, which brings me to https://addons.mozilla.org/en-US/developers/addon/<addonname>/versions/submit/
