### ISSUE TITLE
Transpile before publishing

### ISSUE THREAD

**Issue by LinusU** [mozilla/addons-linter#2278]
### Describe the problem and steps to reproduce it:

I'm getting the following warning when installing addons-linter:

```js
npm WARN @babel/register@7.0.0 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must install peer dependencies yourself.
```

It seems like this project is using `@babel/register` to transform the source code into compatible JS at _runtime_. It's seems like babel is only used in the `bin/firefox-schema-import` file, which means that my library usage of this is probably safe from crashing because of missing `@babel/core`. However, there are still some drawbacks with this approach. Apart from the warning that's a bit annoying/scary, I also get to install a lot of babel-dependencies which won't be used at all.

Would it be possible to simply transpile the code before publishing to npm? I think that a simple `"prepublish": "babel src --output-dir lib"`, `"files": ["lib/"]`, and changing the require to point to `lib/` instead of `src/` in `bin/firefox-schema-import` would suffice.

**Comment by LinusU** [comment]
That sounds great, let me know if you want any help with the actual work ☺️

**Comment by EnTeQuAk** [comment]
Sounds like a perfect plan!

**Comment by LinusU** [comment]
#2309 🎉
