### ISSUE TITLE
Add support for 'browser_specific_settings' as an alias to 'applications' in the manifest

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-linter#2280]
Following https://github.com/mozilla/addons-server/issues/9989, let's add support for `browser_specific_settings` to the linter as well.

I haven't checked in detail what needs to be updated, but there are a few code paths that touch `applications`. We should probably also have at least one test that uses `browser_specific_settings`.

Note: This should already be in the schema, if I understand correctly, added as part of https://bugzilla.mozilla.org/show_bug.cgi?id=1262005.

**Comment by wagnerand** [comment]
@eviljeff yes, we reverted the changes on MDN until this has landed on prod.

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF63, Win10x64

Extensions using `browser_specific_settings` in the manifest are treated equally as those using `applications`
