### ISSUE TITLE
[Static Themes] Unnecessary files included in theme packages are not detected during validation

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-linter#2282]
Follow up for #2051 

STR:

1. Create a static theme package
2. Add an unnecessary file type inside, i.e. a `.js` file
3. Submit the theme through the add-on distribution page in AMO Developer Hub
4. Check the validation results

Actual result:
There are no errors thrown by the linter when files unrelated to static themes are included in the package uploaded

Expected result:
The linter should throw an error when a static theme package includes unrelated files, to make sure that the user is not able o continue with the submission

Notes:
From jvillalobos : 
>Because of the add-on type, Firefox won't run any JS files, so any attack should be fruitless. However, if people are trying to upload malicious themes, it's best that we know or don't allow it. So, I agree that they should be detected.

Example:
[st_size-1.0-fx.zip](https://github.com/mozilla/addons-linter/files/2594434/st_size-1.0-fx.zip)
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/st-size5656

**Comment by jvillalobos** [comment]
I was asked on IRC what kind of tests should be run on the unrelated files. I think that just showing a warning that they exist, maybe listing their names, is sufficient. We don't need to run any tests on their contents.
