### ISSUE TITLE
Evaluate turning linting rule for missing content script files into a warning

### ISSUE THREAD

**Issue by rpl** [mozilla/addons-linter#2289]
In #1640 we have introduced a linting rule to verify that content scripts referenced in the manifest actually exists.

At the time we agreed to make it a linting error (See https://github.com/mozilla/addons-linter/issues/1640#issuecomment-344942150).

As part of the discussions in #2285, it come out that we may actually prefer to turn it into a warning and allow extensions on which the linter reports this kind of issue to be submitted on AMO successfully (See https://github.com/mozilla/addons-linter/pull/2285#discussion_r235975378).

The goal of this issue is to evaluate this proposed change in behavior and then plan the changes needed of the linter if we agree that the current behavior (marking it as a blocking error) is not the one that the linter should have.

**Comment by wagnerand** [comment]
I would be in favor of that.
