### ISSUE TITLE
Update fluent-syntax to pick up bug fixes.

### ISSUE THREAD

**Issue by Pike** [mozilla/addons-linter#2305]
### Describe the problem and steps to reproduce it:

AMO refused to sign language packs for en-US 'cause the files triggered a bug in fluent-syntax 0.7. See https://bugzilla.mozilla.org/show_bug.cgi?id=1511988 for details

### What happened?

Beta 1 busted

### What did you expect to happen?

Not bust :-)

### Anything else we should know?

I tested the different versions, 0.8 had a different bug, 0.9.0 is fine.

CC @callek

**Comment by EnTeQuAk** [comment]
> We worked around it by changing the en-US file and releng respun builds.

Ah perfect, then the fix will be going out on regular deployment on Dec 13th

**Comment by AlexandraMoga** [comment]
I'm not sure how relevant this is in this context, but I have submitted several language packs on AMO -dev and they were correctly signed.

@EnTeQuAk if there is anything else that I could check, please let me know.
