### ISSUE TITLE
JavaScript syntax error when using an encapsulated function in a module

### ISSUE THREAD

**Issue by jasonsavard** [mozilla/addons-linter#2312]
module2.js

```
(function () {
})();
```
I get this linter error:
JavaScript syntax error
Error: There is a JavaScript syntax error in your code; validation cannot continue on this file.
module2.js line 8 (last line of file) column 1

The code actually works and the linter should pass the test.

Here is a sample extension file

[test.zip](https://github.com/mozilla/addons-linter/files/2653113/test.zip)

**Comment by muffinresearch** [comment]
This needs investigation into where the error is, presumably it's related to an upstream dependency.
