### ISSUE TITLE
Please switch fluent lint errors to not block addon signing

### ISSUE THREAD

**Issue by Callek** [mozilla/addons-linter#2313]
We would like fluent files in language packs to still give messages about issues but not actually block language pack signing/publishing.

I'm flagging @Pike and @flodolo to comment and give this a thumbs up from a localization team perspective.

Some background:
For the past few releases and early on we've had issues that were flagged by AMO as errors with fluent, however these issues are not blockers for our users; and when they strike they block a release process (chemspill included, though luckily its never blocked in that urgent of a time) but means these issues put AMO developers and admins in a critical path for releases, liable to be paged or be asked to have sudden deploys. Which is counter to what we all want.

Some of the notable issues we've hit with fluent on AMO:
* https://bugzilla.mozilla.org/show_bug.cgi?id=1511988 - which spawned issue #2305
    * This one was an issue in validator version...
* https://bugzilla.mozilla.org/show_bug.cgi?id=1502234
    * This one was an actual issue in files contained in the language packs `however` the way fluent (ftl) works is that if these strings were invalid they wouldn't get used and it would fallback to english anyway, which would not harm the build
    * Additionally l10n team signs off on translation validity externally before we take a changeset for a release
    * In this particular case it was for a .ftl file that wasn't even used in the Gecko version of the build that we were shipping for (all .ftl files that exist are shipped as part of the language packs, even if they are for "newer" trains)
* Back in march we also had issue #1901 which burned some cycles.

**Comment by flodolo** [comment]
Thanks Callek, I think this describes the situation perfectly. 

In general, we have safeguards in our build process to guard us against issues. In both cases, we ended up with a broken build process, when the builds were actually fine.

**Comment by AlexandraMoga** [comment]
@EnTeQuAk Does this require QA? If so, please add some STR.
Thanks
