### ISSUE TITLE
Add-on ID comparison is case-sensitive when new version, case-insensitive when new add-on

### ISSUE THREAD

**Issue by Alien426** [mozilla/addons-linter#2381]
### Describe the problem and steps to reproduce it:
Critical error when uploading new version: "The add-on ID in your manifest.json or install.rdf (CheckCase@xxx) does not match the ID of your add-on on AMO (checkcase@xxx)"
Critical error when uploading new add-on: "Duplicate add-on ID found."

### What happened?
Signing of the add-on was prevented in both cases.

### What did you expect to happen?
Either allow a new version of existing add-on or allow a new add-on.

**Comment by EnTeQuAk** [comment]
This should be moved to [addons-server](https://github.com/mozilla/addons-server/issues/new) instead? That's where the checking is actually done.

I'll do that in a bit. Closing here for now.
