### ISSUE TITLE
Distribute validator rules in an npm package

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-linter#244]
so we can run them with an eslint binary independently, for example in an IDE or Atom (with plugins).

**Comment by tofumatt** [comment]
Oh, that’s a cool idea. Will require a bit of reworking, but I like it! 👍

**Comment by wagnerand** [comment]
I have already set up the plugins for Atom on my computer to test. The only thing that missing is the rules as eslint requires them to be in an npm package. Let me know once we have something to test.

Would it make sense to move the rules to a separate repo?

**Comment by tofumatt** [comment]
Moving the rules to their own repo would make it harder for us to work on, as we would only be moving the JS rules.

The best option to me would be a repo that includes the validator NPM package and uses its rules, but I don’t know how doable that is.

We already output the rules on NPM in a folder (dist/eslint)

**Comment by johannhof** [comment]
Maybe add a package.json into the rules folder?

**Comment by tofumatt** [comment]
The rules are written in ES6 and the dist version is only sent to npm. I don't know THAT much about node modules, is it possible to add an extra package.json there?

- tofumatt (Sent from mobile)

**Comment by muffinresearch** [comment]
I'm not convinced that exporting just the eslint rules is that useful on it's own. If were going to enable users to validate code using this then accessing everything the validator can do is more useful than just enabling the eslint rules to be used for example.

**Comment by johannhof** [comment]
Well we could easily write a small script that exports the rules as a separate npm module by having multiple package.json files (similar to https://github.com/facebook/react/tree/master/packages)

**Comment by tofumatt** [comment]
Good point, I guess it would really make more sense to have a whole addon-linter package that handled everything.

And exporting just the eslint rules and using them with eslint directly means you hit the problem of eslint-disable being available, which we don't want for the validtaor ^_^

- tofumatt (Sent from mobile)

**Comment by EnTeQuAk** [comment]
We most recently talked about this and it still isn't quite easy.

What we can do in the meantime is maybe distribute the schema linting package as a separate package that allows it to be used in IDEs.

Other rules can be used too, e.g most of our JavaScript rules are written to be eslint compatible, but distributing other linting paths like the manifest.json parser might be harder and needs some refactoring of the infrastructure.

With that, I'd keep that as p4 but remove the "needs: discussion" label for now.
