### ISSUE TITLE
linter: icons found in manifest not found in package

### ISSUE THREAD

**Issue by dmoneyballer** [mozilla/addons-linter#2442]
### Describe the problem and steps to reproduce it:
When uploading a browser extension it says icons can't be found.
(Please include as many details as possible.)
I uploaded my extension to the chrome webstore and now would like to do the equivalent on firefox.  I had an issue with the manifest not being at the root of my extension so i repackaged my .zip so the manifest is at the root and it says the images for my icons don't exist but they're in my images folder. I thought bringing them up to the root would help so I tried that but the linter still didn't find the icons.  I don't know why it can't find them
### What happened?
^see above
### What did you expect to happen?
the extension to be accepted and to be able continue the publishing process.
### Anything else we should know?
I am a noobish dev and looked at related issues in github and some people seemed to have the same issue but it looked resolved but I couldn't reproduce the results
(Please include screenshots and any relevant files.)

[ext.zip](https://github.com/mozilla/addons-linter/files/2851623/ext.zip)

**Comment by Alien426** [comment]
It is case sensitive. Either rename the icon files to lower case or change it in the manifest.

As a side note: You should really consider moving to pure JavaScript/HTML. Such a tiny extension ...
Without Bootstrap and jQuery it's below 100 kB. Bootstrap and jQuery are over 8x that size!
