### ISSUE TITLE
Error if default_icon is empty

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-linter#2455]
We should probably follow Firefox and error if `default_icon` is empty. https://bugzilla.mozilla.org/show_bug.cgi?id=1419109

**Comment by EnTeQuAk** [comment]
Given https://hg.mozilla.org/mozilla-central/rev/d7bf0d21448d and it's follow-ups landed with the Firefox 66 schema update I think we now already do that.

I see an error `"/browser_action/default_icon" should match pattern "\\S"` for an empty `default_icon`, thus closing.
