### ISSUE TITLE
Error if optional_permissions include more than one values

### ISSUE THREAD

**Issue by zimocode** [mozilla/addons-linter#2457]
Error if optional_permissions include more than one values, whether the value is valid or not.

**Comment by EnTeQuAk** [comment]
Can you provide a bit more context about the why and a few examples?

Usually schema changes like that should be implemented upstream inside Firefox first and then land in the linter at a later stage.

**Comment by zimocode** [comment]
> Can you provide a bit more context about the why and a few examples?
> 
> Usually schema changes like that should be implemented upstream inside Firefox first and then land in the linter at a later stage.

Hi, it's my extension.
[smartup.zip](https://github.com/mozilla/addons-linter/files/3025650/smartup.zip)
