### ISSUE TITLE
Look into handling the deprecated keyword used in the API schemas 

### ISSUE THREAD

**Issue by rpl** [mozilla/addons-linter#2462]
### Describe the problem and steps to reproduce it:

While working on the changes needed for #2283 we noticed that the "deprecated" keyword is not currently being handled, because 'src/schema/validator.js' is actually registering an handler for a  `"deprecated" format`, whereas it is actually a `keyword` and not a `format` (there is actually no `"deprecated" format` used in our WebExtensions API schemas):

https://github.com/mozilla/addons-linter/blob/590d2752a6fbcb9896b6b4f9e85e5d7d7c5770b1/src/schema/validator.js#L35

### What happened?

As part of #2283 we are going to ignore any "deprecated" keyword that is not related to the LWT theme aliases, otherwise we will likely introduce regressions related to deprecation errors that were not being collected.

### What did you expect to happen?

It seems reasonable to take another look to the new linting errors that may be collected if we do handle the "deprecated" keyword for the rest of the API schemas, and then decide if any of them should be actually part of the collected linting errors/warnings.

**Comment by EnTeQuAk** [comment]
@rpl I'm going to tackle this one as part of working on #2556. I noticed that my assumption there, adding something new to `DEPRECATED_APIS` is wrong and that the error messages issued for all that are quite ancient and wrong.

So we're going to need something more sophisticated and the deprecation is already properly represented in the schema.

I was thinking about adding something on top of your static theme deprecation patch to generalize that slightly to have something like a "whitelist" of apis that are deprecated and we want the linter to warn/error about. Ideally that whitelist allows us to fine-tune the behavior we want to see for the linter, e.g if we need it to warn or error on something later.

I'll see how far I can get with that while still keep the amount of work reasonable.

Does that work for you?

**Comment by rpl** [comment]
> I noticed that my assumption there, adding something new to DEPRECATED_APIS is wrong and that the error messages issued for all that are quite ancient and wrong.

@EnTeQuAk yep I think that DEPRECATED_APIS has been originally introduced to report linting errors for APIs that were already deprecated on Chrome and never implemented in Firefox (and so I expect the message to be specifically mentioning that).

> So we're going to need something more sophisticated and the deprecation is already properly represented in the schema.
> I was thinking about adding something on top of your static theme deprecation patch to generalize that slightly
>...
> Does that work for you?

Yeah, definitely, it is basically what I was thinking of when I filed this issue.
Go for it! 
(and let me know when you have opened a PR that I can start review ;-))

(absolutely not mandatory for #2556, but it may be worth to see if we could get rid of the special DEPRECATED_APIS one, once we have a more generalized way of "whitelisting" the api to report deprecation warning for).
