### ISSUE TITLE
JavaScript heap out of memory validation error generated for addons with large JS files

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-linter#2506]
**STR:**

1. Log in to AMO -dev
2. Upload an add-on that has some large JS files (see attached example)
3.  Check the validation message

**Actual result:**
The validation fails with an unexpected error on AMO. 

The actual error that prevented the submission is: 
`FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory`

**Expected result:**
The error message prompted to the users should be more conclusive

**Notes:**
- reproduced on all servers with FF65, Win10x64
[unexpected error.zip](https://github.com/mozilla/addons-linter/files/2984075/unexpected.error.zip)

![image](https://user-images.githubusercontent.com/31961530/54617987-f2159400-4a6a-11e9-93dc-e6c7f74b91f8.png)

**Comment by muffinresearch** [comment]
@EnTeQuAk @bqbn do you know what memory allocation we have for the linter task runs or is it set to the default?

**Comment by bqbn** [comment]
I don't remember doing any memory configuration for node. I don't even know how/where node is called in this case (even though I guess it's on the celery instances)?

Can one of you tell me how node is called by what? Then I can go check our settings for sure.

**Comment by muffinresearch** [comment]
See also https://github.com/mozilla/addons-linter/issues/1248 and https://github.com/mozilla/addons-linter/issues/1248#issuecomment-539121728 for where to use `--max_old_space_size` to up the default memory allocation for node.

**Comment by diox** [comment]
> Can one of you tell me how node is called by what? Then I can go check our settings for sure.

`node` is called by celery worker processes when running the linter.

Looks like `NODE_OPTIONS=--max-old-space-size=2048` on the workers would fix validation for the add-on in #1188. It does locally.

**Comment by bqbn** [comment]
The proposed `NODE_OPTIONS=--max-old-space-size=2048` is merged and will be deployed to -dev along with next commit. Please test it.
