### ISSUE TITLE
Non-useful error message when an icon is not found

### ISSUE THREAD

**Issue by eyalroz** [mozilla/addons-linter#2517]
### Describe the problem and steps to reproduce it:

People trying to update/upgrade their legacy extension with a manifest.json can easily fail to specify the correct location for an icon file, and the linter error doesn't help them realize how to fix the problem.

1. Follow this link: [removedupes_0.3.17_tbird.xpi](https://app.box.com/s/crt6yf2dqcz1wqlarapvy8khvv7jzvt9)
2. Use the download button link to obtain the XPI file
3. Lint it using the currently-deployed ATN linter (I used ATN itself, as an extension author)

### What happened?

I get, among others, the following error message:
> An icon defined in the manifest could not be found in the package.<br>
> Error: Icon could not be found at "chrome/content/removedupes.png".

### What did you expect to happen?

I expected to get some examples of how to refer to an icon based on where it's located within the extension; whether I need a chrome:// URI or not, etc.

Alternatively, there could at least be a link to some other page (on MDN maybe?) which explains these things.

### Anything else we should know?

* I first tried with the icon's chrome URI, which I'd copied from `install.rdf`: `chrome://removedupes/content/removedupes.png`. But that didn't work either.
* ATN also complained about my `removedupes.jar` file having a flagged extension and being unnecessary; not sure why.

**Comment by muffinresearch** [comment]
Neither legacy nor Thunderbird extensions are not supported on AMO. You'll probably want to ask for support here: https://github.com/thundernest/addons-linter/ or https://github.com/thundernest/addons-server/
