### ISSUE TITLE
Inscrutable warning message for legacy extensions

### ISSUE THREAD

**Issue by eyalroz** [mozilla/addons-linter#2518]
### Describe the problem and steps to reproduce it:

1. Follow this link: [removedupes_0.3.17_tbird.xpi](https://app.box.com/s/crt6yf2dqcz1wqlarapvy8khvv7jzvt9)
2. Use the download button link to obtain the XPI file
3. Lint it using the currently-deployed ATN linter (I used ATN itself, as an extension author)

### What happened?

I get, among others, the following warning:

> We allow and encourage an upgrade but you cannot reverse this process. Once your users have the WebExtension installed, they will not be able to install a legacy add-on.

### What did you expect to happen?

* Who is "we"?
* What process?
* What WebExtension? I just added a `manifest.json` because [this page](https://thunderbird-webextensions.readthedocs.io/en/latest/how-to/extensions68.html) said I need to do that.
* Why will my users not be able to install a legacy add-on? What about my legacy add-on?

I don't need an answer on this issue page - the warning message should answer these questions.

**Comment by muffinresearch** [comment]
Firefox hasn't supported legacy extensions since Firefox 57.

AMO no longer supports extensions for Thunderbird either. Please re-file this issue at https://github.com/thundernest/addons-server as that's the right place to get support for https://addons.thunderbird.net/
