### ISSUE TITLE
LWT alias deprecation warning for 'headerURL' doesn't link to the correct instructions

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-linter#2519]
**STR:**

1. Upload a new static theme that is using the `headerURL` property on AMO
2. Check the validation warnings

**Actual result:**
The warning mentions that the manifest is using a deprecated LWT alias, but the instruction link is pointing to the new `colors` properties - see https://mzl.la/2T11Lkc

**Expected result:**
The instruction link should point to https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/theme#images where the deprecation warning for `headerURL` is specified

**Notes:**
- reproduced on all AMO servers with FF66, Win10x64
- Example to submit: 
[headerURL example.zip](https://github.com/mozilla/addons-linter/files/3003217/headerURL.example.zip)

![image](https://user-images.githubusercontent.com/31961530/54919587-d9ddc300-4f09-11e9-87d2-9ae35bee49e5.png)

**Comment by ruchikabgosain** [comment]
Hey @AlexandraMoga is this issue still available? Let me know :)

**Comment by caitmuenster** [comment]
Go for it @ruchikabgosain! 

Mentor: @EnTeQuAk

**Comment by wagnerand** [comment]
@AlexandraMoga mzl.la/2T11Lkc links to https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/theme#Aliases which looks to me is the link we want to show.

I think the actual fix here would be to add `headerURL` and any other missing aliases to that table.

**Comment by ruchikabgosain** [comment]
Hi @wagnerand , so what exactly do what i need to do, can you please provide me little bit more details? Thank you!

**Comment by wagnerand** [comment]
Hi @ruchikabgosain. There is nothing left to do here, we will make the necessary changes on MDN directly, which is tracked in https://github.com/mdn/sprints/issues/1867.
