### ISSUE TITLE
Warn about deprecated proxy APIs

### ISSUE THREAD

**Issue by mconca** [mozilla/addons-linter#2556]
The linter should begin warning that the following APIs will be deprecated in Firefox 71:
- proxy.register
- proxy.unregister
- proxy.onProxyError

This issue can be tracked in [bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1545811).

**Comment by muffinresearch** [comment]
@rpl @EnTeQuAk is this something that needs special casing or will schema changes cover it?

**Comment by EnTeQuAk** [comment]
I think they need to be added to https://github.com/mozilla/addons-linter/blob/d3a36ec608f742f6330e125e32e3ee56b9a2818f/src/const.js#L147 + tests which shouldn't be too much work.

I can take a look at that, unfortunately I must have missed this issue in my email inbox.

**Comment by EnTeQuAk** [comment]
I have a branch at https://github.com/mozilla/addons-linter/tree/refactor-deprecated that is 90% done and solves this and #2462 as well. It didn't make this week's tag unfortunately but I'll have it ready for review on Thursday once I'm back on PTO.
