### ISSUE TITLE
Show warning when an extension requests broad host permissions

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-linter#2562]
When an extension's host permissions include `<all_urls>` or masked URLs like `*://*.mozilla.org/*`, a warning should be shown to the developer with the following message:

> Requesting broad host permissions can discourage users from installing your extension. Make sure that you only request permissions that are needed by your extension.

This issue is planned as a Q3 project, so we still need to refine the messaging and possibly the cases in which we will flag. I'm filing now to open up discussion.

**Comment by muffinresearch** [comment]
@jvillalobos is this still something for q3, and has the discussion happened already?

**Comment by jvillalobos** [comment]
It's not part of Q3, but I think it's okay to have it as a P3. @kewisch, what do you think of the wording and the cases where we should flag?

**Comment by kewisch** [comment]
I think `*://*.mozilla.org/*` would be fairly common and not as objectionable to users as `<all_urls>`. I'd probably aim for patterns where `*` is the host (e.g. `http://*/*`) and`<all_urls>`. The messaging sounds fine, but I'd also link to a page like [requesting the right permissions](https://extensionworkshop.com/documentation/develop/request-the-right-permissions/) to give developers a way to learn more.

**Comment by wagnerand** [comment]
We still want to do that at some point.

**Comment by marchiore** [comment]
Can I work on this?
