### ISSUE TITLE
Think about adding a notice for HTTP URLs?

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-linter#259]
Leaving this for discussion, but it'd be nice if developers used HTTPS APIs. Should we make an option to warn developers that they're using HTTP? @andymckay brought this up in an on-boarding with @jvillalobos. It would be noisy... but maybe good?

Leaving it here for discussion.

**Comment by jvillalobos** [comment]
I suspect there will be way too many false positives, which can be verified by searching on MXR: https://mxr.mozilla.org/addons/search?string=http%3A&find=&findi=&filter=^[^\0]*%24&hitlimit=&tree=addons
There are a number of these that can be easily filtered out, but what's left will probably be still very noisy.

**Comment by muffinresearch** [comment]
I like the idea of able to promote best/better practices. Especially since the user might not have considered the implications (though presumably that's something a review would catch? )

**Comment by muffinresearch** [comment]
Maybe an opt-in warning would work for this kind of feature. If you know you're using https then you'd probably be interested in a way to configure a warning for this in-case you slipped up.

**Comment by jvillalobos** [comment]
The global move to HTTPS is further along, and now we want to add this flag for WebExtensions. The false positives should be fewer for WE than legacy.

**Comment by EnTeQuAk** [comment]
Maybe just restrict that to explicitly analyze `webRequest`, `XMLHttpRequest` and `fetch` for example and check that they're https? But even that could be quite noisy so maybe this depends on https://github.com/mozilla/addons-linter/issues/1436 to allow the rule to be disabled on run-time if we notice too many false positives.

**Comment by EnTeQuAk** [comment]
Removing the unclear labels, as this is a good idea to add a warning. I don't think it's high priority for now though.
