### ISSUE TITLE
Remove bad words list

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-linter#2591]
We keep seeing reports for words that would be a bad one in one language but ok in another one. We decided to remove the entire bad words list.

**Comment by AlexandraMoga** [comment]
Verified fixed on stage with Fx66, Win10x64

I've submitted several add-on packages that used to trigger the "Violation of Mozilla conditions of use" warning and I can confirm that the warning doesn't show up anymore. 

This is an example: 
[3 term-violation - test.zip](https://github.com/mozilla/addons-linter/files/3210948/3.term-violation.-.test.zip)
