### ISSUE TITLE
Regression: Reserved filenames are not scanned in subfolder

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-linter#2618]
Because of a small issue reserved filenames are not properly scanned in a subfolder.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev with Fx67 Win10x64

Reserved files are now caught when included in subfolders:
![image](https://user-images.githubusercontent.com/31961530/58935001-c0ac8a80-8774-11e9-9cfa-47617acc4579.png)
