### ISSUE TITLE
The filetype you uploaded isn't recognized.

### ISSUE THREAD

**Issue by whitevo** [mozilla/addons-linter#2647]
### Describe the problem and steps to reproduce it:
Choosing addon folder.
Creating .rar file with winrar.
Uploading .rar file

### What happened?
Error with youtube addon.rar
Please make sure to report any linting related issues on GitHub
Your add-on failed validation with 1 error.

    The filetype you uploaded isn't recognized.

### What did you expect to happen?
No errors.

**Comment by wagnerand** [comment]
the RAR format is different from ZIP. Only ZIP files are accepted.
