### ISSUE TITLE
Move locale bn-BD to bn

### ISSUE THREAD

**Issue by peiying2** [mozilla/addons-linter#2696]
We are going to merge the two bn-* locales into one to fully utilize the community resources. AMO Linter has only bn-BD. We want to sync up with the rest of the localized products/projects. The plan is

Dev:
- AMO Linter creates an bn folder at repo
- Move bn-BD repo content to bn repo and confirm it's all there
- Remove bn-BD repo

Pontoon (l10n):
- Pontoon dev migrates the data to bn (this includes contributors histories)
- L10n PM confirms the update and closes this issue.

**Comment by peiying2** [comment]
@entequak

**Comment by championshuttler** [comment]
cc @ruchikabgosain/

**Comment by ruchikabgosain** [comment]
Hello @peiying2 can i work on this? 

Thankyou @championshuttler :)

**Comment by peiying2** [comment]
> Hello @peiying2 can i work on this?
> 
> Thankyou @championshuttler :)

As long as the team gives the A-OK, I am good with that!
