### ISSUE TITLE
`snyk` should be a development dependency

### ISSUE THREAD

**Issue by jarrodldavis** [mozilla/addons-linter#2702]
### Describe the problem and steps to reproduce it:
`snyk` has been added as a production dependency for this package when it appears to only be used for development purposes.

### What happened?
I upgraded [`web-ext`](https://github.com/mozilla/web-ext) to version `3.1.1` from `3.0.0`. I noticed a lot of additional transitive dependencies were added to my `package-lock.json`, and most of those new dependencies are a result of `snyk`.

### What did you expect to happen?
I expected a number of updated packages in my `package-lock.json`, but not a lot of new ones.

### Anything else we should know?
`snyk` only appears to be used for its `snyk-protect` command, which is used by `addons-linter`'s `prepare` script. According to [npm's documentation](https://docs.npmjs.com/misc/scripts.html), `prepare` is only run for development purposes:

- when running `npm install` locally, e.g. when developing on `addons-linter`
- before packing/publishing the package to the npm registry
- when installing git dependencies (which I assume to mean installing this package as a git dependency)

It would appear that none of these cases would occur when a consumer of the package is installing it as a dependency, either directly or through `web-ext`.

I've opened an issue for this is `dispensary` as well: https://github.com/mozilla/dispensary/issues/608

**Comment by wagnerand** [comment]
Mentor: @wagnerand 

If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started.

**Comment by rbrishabh** [comment]
Hey! 

I would like to take this up!

I think all that needs to be done is removing snyk from ```dependencies``` in package.json and adding it to

**Comment by wagnerand** [comment]
@rbrishabh 	That's right! Thanks for taking this!
