### ISSUE TITLE
rule: deprecated_file

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-linter#274]
Defined in https://github.com/mozilla/addons-validator/blob/master/docs/rules.md#package-layout; look for seemingly old filenames in the package.

Looks like the code is here: https://github.com/mozilla/amo-validator/blob/master/validator/testcases/packagelayout.py#L30

**Comment by EnTeQuAk** [comment]
I honestly don't think this needs porting over to a WebExtension only world, please re-open if I'm wrong with this.
