### ISSUE TITLE
rule: java_jar

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-linter#276]
From https://github.com/mozilla/amo-validator/blob/master/validator/testcases/packagelayout.py#L49

Looks for Java files and warns against their usage: https://github.com/mozilla/amo-validator/blob/master/validator/testcases/packagelayout.py#L49

**Comment by EnTeQuAk** [comment]
Jars Jars Jars Jars.... Let's write a Jar Song 🎶

Not anymore with WebExtensions, closing because irrelevant these days.
