### ISSUE TITLE
rule: test_godlikea

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-linter#278]
https://github.com/mozilla/addons-validator/blob/master/docs/rules.md#package-layout

Code is here: https://github.com/mozilla/amo-validator/blob/master/validator/testcases/packagelayout.py#L129

The story behind this one is cute copypasta: https://bugzilla.mozilla.org/show_bug.cgi?id=658017

**Comment by EnTeQuAk** [comment]
That tutorial was 6 years ago and probably didn't know that WebExtensions were coming. Let's not implement this, ever :)
