### ISSUE TITLE
rule: should_be_true

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-linter#281]
https://github.com/mozilla/addons-validator/blob/master/docs/rules.md#package-layout

Old code is here: https://github.com/mozilla/amo-validator/blob/master/validator/testcases/packagelayout.py#L210

**Comment by EnTeQuAk** [comment]
not the oppopsite but the same as https://github.com/mozilla/addons-linter/issues/282 - not relevant anymore in our new WebExtensions world order. Let's close this.
