### ISSUE TITLE
rule: should_be_false

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-linter#282]
https://github.com/mozilla/addons-validator/blob/master/docs/rules.md#package-layout

Basically, if a JAR exists this is the opposite of #281.

Old code is here: https://github.com/mozilla/amo-validator/blob/master/validator/testcases/packagelayout.py#L254

**Comment by EnTeQuAk** [comment]
no jar files in webextensions! yeay! Let's close this :)
