### ISSUE TITLE
rule: unknown_file

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-linter#283]
https://github.com/mozilla/addons-validator/blob/master/docs/rules.md#package-layout

Old code is here: https://github.com/mozilla/amo-validator/blob/master/validator/testcases/packagelayout.py#L372

**Comment by EnTeQuAk** [comment]
Is this still relevant? I couldn't find any code that actually warns about this or verifies known / unknown files. Not sure if this is something we still need, maybe @tofumatt or @muffinresearch have that somewhere in the back of their minds? :)

**Comment by muffinresearch** [comment]
This is related to replicating old functionality in the amo-validator see the code above the second link which before showing that warning check various lists of file extensions amongst other things.

It might still be worth warning about unexpected exts, that could be useful for developers.

**Comment by andymckay** [comment]
We've already got a check for specific files: exe, java, swf, things that might be dangerous. I'm honestly not sure what else we could check for here: install.rdf, chrome.manifest?

**Comment by EnTeQuAk** [comment]
Let's close this for now until we have a better idea about what to warn for and once we find use for it.
