### ISSUE TITLE
rule: missing_required

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-linter#284]
https://github.com/mozilla/addons-validator/blob/master/docs/rules.md#package-layout

Old code is here: https://github.com/mozilla/amo-validator/blob/master/validator/testcases/packagelayout.py#L382

**Comment by EnTeQuAk** [comment]
This is based on legacy-addons and there doesn't appear to be much that is really required for things to work. If a manifest.json is missing we already have rules for that, so let's close this and re-open in case we have an actual use-case.
