### ISSUE TITLE
snyk sneaked snyk into dependencies

### ISSUE THREAD

**Issue by Rob--W** [mozilla/addons-linter#2845]
The PR in #2827 by @snyk-bot moved the "snyk" dependency from `devDependencies` to `dependencies`. #2824 added it back to `devDependencies` (as a part of a version bump, possibly an incorrect merge conflict resolution), and now we have "snyk" both as a devDependency (where it should be) and in `dependencies` (where it should not be).

**Comment by wagnerand** [comment]
Good catch. However, snyk [believes](https://github.com/snyk/snyk/issues/146) that it should be in `dependencies`, not in `devDependencies`, so we might keep running into this unless we follow that advise.

**Comment by Rob--W** [comment]
The patches in `.snyk` are only relevant to `devDependencies`, not `dependencies`. Also, I see that some of the patches are not even relevant to the current dependencies (`isparta` and `grunt-gh-pages` are no longer (dev)dependencies, according to `package.json`).

**Comment by timbru31** [comment]
This issue might cause `npm audit` to break with the error message: `The server said: Invalid package tree, run  npm install  to rebuild your package-lock.json`. Not 100% sure though.

**Comment by EnTeQuAk** [comment]
Snyk will be removed in #2899
