### ISSUE TITLE
Management permission is not accepted

### ISSUE THREAD

**Issue by keganlance** [mozilla/addons-linter#2847]
### Describe the problem and steps to reproduce it:
Add the management permission to optional_permissions. Try to upload it to the addons store.

### What happened?
WebExtension is rejected.

### What did you expect to happen?
WebExtension is accepted and the management permission in optional_permissions is ignored.

### Anything else we should know?
The reason this is very useful is the fact this way you don't have to maintain a separate codebase for Chrome, Firefox and other browsers.

**Comment by rpl** [comment]
@wagnerand this is a known issue, it has been reported on bugzilla as [Bug 1399109 - Add `management` as an optional permission](https://bugzilla.mozilla.org/show_bug.cgi?id=1399109), closed as a duplicate in favor of tracking the more generic issue [Bug 1458585 - Allow more permissions to be used as an optional permission](https://bugzilla.mozilla.org/show_bug.cgi?id=1458585).

**Comment by wagnerand** [comment]
Thanks @rpl, let's close it here then.

**Comment by keganlance** [comment]
Thanks for your replies @muffinresearch @wagnerand @rpl 

My issue is not the fact the management can't be optional specifically in Firefox.

The issue is the fact the management permission is being rejected by the addon store when it is present in optional_permissions. Even tho Firefox can run addons with the management permission in optional_permissions just fine.

So there seems to be a difference to what addons Firefox can run and what addons the addons store supports.

My usecase is the fact I want to use a single codebase for both Chrome and Firefox, and this management permission in optional_permissions requires me to have two separate packed extensions, one for chrome with the optional management permission, and one for firefox without the optional management permission.

In my case, the management permission is only used in Chrome.

**Comment by wagnerand** [comment]
The linter takes the webextension schema from Firefox, so unless I am wrong this needs a schema fix in the Firefox codebase.
