### ISSUE TITLE
rule: field_required

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-linter#285]
https://github.com/mozilla/addons-validator/blob/master/docs/rules.md#package-layout

Old code is here, though it seems the required fields are defined elsewhere: https://github.com/mozilla/amo-validator/blob/master/validator/testcases/packagejson.py#L15

**Comment by EnTeQuAk** [comment]
The idea behind this is based on legacy add-ons, we do have required field linting for `manifest.json` already. Closing this.
