### ISSUE TITLE
Consider auto-merging dependency updates

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-linter#2854]
When dependency updates pass all tests, we usually just merge them manually. We could save that time by having renovate auto-merging them. There is even https://docs.renovatebot.com/configuration-options/#stabilitydays which we could use if wanted.

@EnTeQuAk @rpl @muffinresearch for feedback.

**Comment by wagnerand** [comment]
The same decision would probably apply to dispensary.

**Comment by muffinresearch** [comment]
I like the sound of this, especially if we set aside some time for `stabilitydays` in case of a newly introduced issue. I'm thinking at least 7 days would probably work for that. We could probably set this for all repos not just these two if it works well.

**Comment by EnTeQuAk** [comment]
Sounds great to me, let's do this!

@muffinresearch can you configure this for addons-linter and maybe `dispensary` to get at least security related updates into the repo.

7 days for `stabilitydays` sounds fair to me.

**Comment by muffinresearch** [comment]
This sounds like a blocker (from https://docs.renovatebot.com/configuration-options/#automerge):

```
Warning: GitHub currently has a bug where automerge won't work if a GitHub Organization has protected their master branch, and there is no way to configure around this. Hence, automerging will try and fail in such situations. This doc will be updated once that bug/limitation is fixed by GitHub
```

**Comment by EnTeQuAk** [comment]
Do we have this configured on org-level instead of per-repo?

**Comment by rpl** [comment]
It would be nice to automerge at least minor updates related to the npm dependencies.

I would be a bit worried on automerging all major updates, especially for the yargs dependency in the web-ext repo. 
Reviewing renovatebot PRs (especially the changes to the lock file) is definitely "no fun", but we got bitten by an unexpected backward incompatibility related to the array arguments in one of the last yargs updates (and unfortunately it wasn't covered by a web-ext integration test).

I see that renovate bots config should allow to configure [automerge to only merge minor updates](https://docs.renovatebot.com/configuration-options/#automerge):
```
"automerge": true,
  "major": {
    "automerge": false
}
```

**Comment by muffinresearch** [comment]
> Do we have this configured on org-level instead of per-repo?

Hmm, the docs don't make it that clear what is meant by their references to Organizations having protected their master branch. We could try it and see if it works or not.

**Comment by muffinresearch** [comment]
A patch is up so we can give this a try, it might not work due to https://github.com/mozilla/addons-linter/issues/2854#issuecomment-542137537 but let's see.
