### ISSUE TITLE
Consider disabling appveyor

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-linter#2855]
Appveyor in its free tier is pretty limited. It does sequential test runs-only, which can lead to to some backlog when a few PRs are merged. Usually, that happens before the tag, where it can block merging of other patches and thus delay the release. There is no team-access to appveyor, so obsolete builds cannot be canceled.

On top, we got a few flaky tests that fail sometimes on appveyor. Of course, it would be better to fix the tests but our resources for the linter are pretty limited. 

In order to unblock things and speed-up maintenance work, I propose disabling the appveyor integration and focus testing with travis. web-ext doesn't use appveyor either as far as I know.

@EnTeQuAk @rpl @muffinresearch for feedback.

**Comment by wagnerand** [comment]
Recent example: Due to the backlog, it took almost 4 hours for https://github.com/mozilla/addons-linter/pull/2856 to be even opened.

**Comment by EnTeQuAk** [comment]
I do agree that Appveyor blocks development on addons-linter.

web-ext doesn't use Appveyor but uses Travis Windows workers which need to be configured and tested and when we configured Appveyor this too quite some time.

Personally, I don't mind simply removing Appveyor and working on travis windows workers once there's time.

On the other hand, we should not risk regressions in web-ext because of insufficient testing.

**Comment by rpl** [comment]
I also agree that we should migrate this repo from appveyor to travis windows workers.

When I migrated the web-ext repo away from apveyor I also gave a quick look into migrating the addons-linter repo as well, unfortunately [there was something in the encrypted part of the addons-linter travis config](https://github.com/mozilla/addons-linter/blob/7c2439057577fc743cf0ec28de37241085f20c1b/.travis.yml#L33-L37) that was making the travis windows worker to get stuck before starting the job and without logging any useful error:
- https://travis-ci.org/rpl/addons-linter/jobs/452987956

and at the time I wasn't able to spent more time to debug the issue.

Here is the changes applied in that experimental branch (in case those draft patches may be helpful to give it a try again):
- https://github.com/rpl/addons-linter/compare/d17cd9d8d65d076d61ad1de1518f2d5495d152b0..chore/move-windows-ci-tests-to-travis
