### ISSUE TITLE
Upload of new experiment API addon failed

### ISSUE THREAD

**Issue by revad** [mozilla/addons-linter#2863]
I wrote an addon using an experiment API. I attempted to upload it to ATN and got:

Your add-on failed validation with 1 error.
You cannot submit this type of add-on

Also
We have enabled a new linter to process your Add-on. Please make sure to report any issues on GitHub

Hence this issue.

The validation report indicates a warning, not an error:
myapi.setWindowListener is not supported
Warning: This API has not been implemented by Firefox.

But my experiment API, and the manifest and schema entries are copied from this addon:
https://addons.thunderbird.net/en-US/thunderbird/addon/single-domain/

My code is here:
https://github.com/revad/limit_non-BCC_recipients

**Comment by wagnerand** [comment]
This repository is for addons.mozilla.org. Please file ATN issues at https://github.com/thundernest/addons-linter
