### ISSUE TITLE
Remove CRX support?

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-linter#2865]
Addons-server converts CRX files into XPI files when submitted (when we create a file upload) so we never lint CRX files during submission. I am wondering whether we still need to support CRX in addons-linter then. WDYT?

**Comment by jvillalobos** [comment]
There's the [standalone validation tool](https://addons.mozilla.org/developers/addon/validate), and web-ext. Wouldn't those accept CRX without the conversion? If so, do we have or could we get numbers on people using CRX files on them?

**Comment by diox** [comment]
I think for the reasons @jvillalobos mentioned we still need `crx` support in the linter. I don't think we have numbers on users, but we do have issues opened from time to time for bugs in our `crx` support, so it's definitely used, if only by a small minority.
