### ISSUE TITLE
Use addons-scanner-utils `io` package

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-linter#2866]
[addons-scanner-utils](https://github.com/mozilla/addons-scanner-utils) contains a `io` package used by the new scanners. It is a port of the linter files with some fixes and improvements. This would likely fix #858 :)

**Comment by EnTeQuAk** [comment]
The link seems to be pointing into the wrong direction, you're talking about https://github.com/mozilla/addons-scanner-utils right?

I wonder, is the initial commit a 1:1 port of the linters io package so that the commit log represents all the fixes and improvements made? I'd like to make sure we don't run into any regressions for things that may have worked for the other scanners but won't for the linter.

**Comment by willdurand** [comment]
> The link seems to be pointing into the wrong direction, you're talking about [mozilla/addons-scanner-utils](https://github.com/mozilla/addons-scanner-utils) right?

Err.. edited, thanks!

>  is the initial commit a 1:1 port of the linters io package so that the commit log represents all the fixes and improvements made

It's not 1:1 but close enough I'd say. The one big improvement is disabled by default so that would not affect the linter anyway.

**Comment by EnTeQuAk** [comment]
> It's not 1:1 but close enough I'd say. The one big improvement is disabled by default so that would not affect the linter anyway.

Mind to elaborate a bit more or are you referring to https://github.com/mozilla/addons-scanner-utils/commit/17ce0771f5440477e390822c4e2b3999b579573b?

**Comment by willdurand** [comment]
> Mind to elaborate a bit more or are you referring to [mozilla/addons-scanner-utils@17ce077](https://github.com/mozilla/addons-scanner-utils/commit/17ce0771f5440477e390822c4e2b3999b579573b)?

I am indeed referring to https://github.com/mozilla/addons-scanner-utils/pull/27. As for the rest, it can't be a 1:1 port because it has been rewritten with TypeScript.

**Comment by diox** [comment]
Let's keep this opened and try to do it sometime...

**Comment by willdurand** [comment]
See also: https://github.com/mozilla/addons-linter/issues/2865

**Comment by AlexandraMoga** [comment]
@willdurand would some general linter checks (i.e submitting add-ons of various sizes and types, triggering validation warnings/errors) be enough to verify this issue or is there something more specific to be tested?

**Comment by willdurand** [comment]
I think so, yea

**Comment by ioanarusiczki** [comment]
@willdurand Verified on AMO Stage - FF82(Win10).
