### ISSUE TITLE
add support for user_scripts in the manifest parser

### ISSUE THREAD

**Issue by mozfreddyb** [mozilla/addons-linter#2895]
### Describe the problem and steps to reproduce it:

The manifest parser does not check user_scripts. It should do the same checks as applicable for content and background scripts, e.g., check that they are part of the package.

**Comment by rpl** [comment]
Closing as wontfix, we will reconsider as soon as we would have determined how the feature supported by this Firefox-specific MV2 API would be introduced in the set of APIs that are going to be available to MV3 extensions in Firefox.
