### ISSUE TITLE
Be consistent about scan() vs getContents() in tests

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-linter#292]
I was using `getContents()` in some tests I wrote, but as discussed in https://github.com/mozilla/addons-validator/pull/152#issuecomment-153823073 we usually use `scan()` elsewhere. I had okay reasons for using `getContents()` directly but consistency is better than my reasons :smile: 

So we should use `scan()` instead of `getContents()` in places like: https://github.com/mozilla/addons-validator/pull/152/files#diff-c6389008a76eac7ca2f23274ad8ef864L15

**Comment by eviljeff** [comment]
mentor @tofumatt

**Comment by wagnerand** [comment]
Please refer to https://wiki.mozilla.org/Add-ons/Contribute/AMO/Code if this is your first contribution.

If you want to work on this issue and need more information on how or where to fix it, please comment here and we will be happy to provide more details.

**Comment by gilbertginsberg** [comment]
@tofumatt: Steven Gilbert here. Thank you for mentoring. I see this bug was created awhile ago. Is it still valid?  If so, I'd like to give it a go :).

**Comment by tofumatt** [comment]
Hey @gilbertginsberg, sorry for my extremely late response on this one.

This bug appears to still be valid, so feel free to give it a go 😄

**Comment by gilbertginsberg** [comment]
@tofumatt: And now my turn to apologize for the late response. Very good! I'll dig in.

@caitmuenster: I lost track of this issue, so I haven't been working on it. But I'd like to re-visit it, which I plan to do in the coming days. I'll drop a note should I have any questions! Thanks for checking in.

**Comment by gilbertginsberg** [comment]
@tofumatt: I've read through [mozilla#152 (comment)](https://github.com/mozilla/addons-linter/pull/152#issuecomment-153823073), but I'm still not super clear on when you'd use `scan()` over `getContents()`.  Perhaps you can shed some light?  For example should `getContents()` be swapped out for `scan()` only in the context of `rdfScanner`? Or for example I also see `getContents` as a method of [`cssScanner`](https://github.com/mozilla/addons-linter/blob/master/tests/scanners/test.css.js#L61) and [`htmlScanner`](https://github.com/mozilla/addons-linter/blob/master/tests/scanners/test.html.js#L38). Should `scan()` be used instead in those tests as well?

**Comment by tofumatt** [comment]
I'm saying to use `scan()` over `getContents()` in the tests to be consistent, as it should run the same code, if I recall correctly.

That said, I filed this issue some time back and I sort of forget. I think largely it was just to be using `scan()` in any test we use `getContents()` for (unless we are explicitly testing `getContents()` in that test) so the code is consistent and future developers understand the convention.

**Comment by EnTeQuAk** [comment]
short notice, because of https://github.com/mozilla/addons-linter/pull/1296/ turning into a bigger refactor I am touching parts of where we are using `getContents` so if you're already using it, be prepared for conflicts or maybe wait one more day to start :)

**Comment by gilbertginsberg** [comment]
Roger that @EnTeQuAk. Thanks.

**Comment by EnTeQuAk** [comment]
#1296 just landed, as far as I can see it there's only a very small amount of tests left that use `getContents()` where they could use `scan()`, most tests that are left use `getContents()` because they're explicitly test it. There's only `test.installrdf.js` left that uses it in a way where `.scan()` could be used but given that the linter never tests legacy-addons these days that code is doomed to be removed soon.I hope @gilbertginsberg that you didn't invest too much time into that, otherwise I'm sorry for stealing your work 😇 

I'm closing this issue given that the work is primarily done and what's left is doomed to be removed soon-ish.
