### ISSUE TITLE
Node 13 requirement ?

### ISSUE THREAD

**Issue by sublimator** [mozilla/addons-linter#2952]
A lot of people tend to stick to LTS (currently node 12) 
Is there any hard requirement for node 13?

**Comment by EnTeQuAk** [comment]
No, it's not a requirement and only an accident because we recently tried to configure @renovate-bot to handle engine pinning and follow LTS releases but that apparently didn't work as expected.

That has been rolled back now and we'll issue a release shortly.

**Comment by sublimator** [comment]
Awesome! Thanks @EnTeQuAk :)
