### ISSUE TITLE
Add-on failed validation with 1 error

### ISSUE THREAD

**Issue by EdgardoRios** [mozilla/addons-linter#3014]
### Describe the problem and steps to reproduce it:
Hello, I am trying to upload a new version of an Add-on, and failed validation with 1 error.
(Please include as many details as possible.)
Steps:
1. Go to Thunderbird Add-ons page
2. Login and go to 'Tools/Manage My Submissions'.
3. Go to Submit a New Version.
4. Click on 'Select a file...' button.
5. Pick the new file version (*.xpi).
6. Valition and after that, the following error message:
Your add-on failed validation with 1 error.
    GUID is required for Thunderbird Mail Extensions, including Themes.

### What happened?
Validation error.

### What did you expect to happen?
Validation, no errors and upload the new version of the file to Add-ons page

### Anything else we should know?
Yes, this is just a spell checker dictionary, it works just fine in Firefox Add-ons page.
I took a look to 'See full validation report' and could not find an error there.

(Please include screenshots and any relevant files.)
![image](https://user-images.githubusercontent.com/18619087/72763672-74e70e00-3baa-11ea-9d48-a3f528e82fdf.png)

Thanks in advance for your help!

**Comment by muffinresearch** [comment]
Since this is related to a thunderbird specific message it would be best to ask for support via https://github.com/thundernest/addons-server/

**Comment by EdgardoRios** [comment]
Thanks!
