### ISSUE TITLE
Port travis deploy config to dpl v2

### ISSUE THREAD

**Issue by rpl** [mozilla/addons-linter#3045]
### Describe the problem and steps to reproduce it:

While releasing a new tagged release from the web-ext repo, I noticed that the travis job wasn't able to successfully run the deploy task (it did fail with this error: https://travis-ci.org/mozilla/web-ext/jobs/649392805#L283-L284).

It is not unlikely that addons-linter may trigger the same issue once we are going to release the next tagged release.

### Anything else we should know?

https://github.com/mozilla/web-ext/pull/1838 contains the changes that we applied to the web-ext travis config to successfully deploy the new npm package from the travis job.

If the addons-linter travis config triggers the same issue we may want to apply the same kind of changes to this repo as well (otherwise we can defer the change once migrating to travis dpl v2 format does become mandatory).

**Comment by ioanarusiczki** [comment]
@EnTeQuAk Please add some STR for qa. 
Thanks!
