### ISSUE TITLE
test.firefox-schemas-import.js should not create the fake mozilla-central.zip in the project root dir

### ISSUE THREAD

**Issue by rpl** [mozilla/addons-linter#3067]
A fake mozilla-central.zip file is created as part of the test.firefox-schemas-import.js tests, but this file seems to be currently created in the project test file but, as any asset created or manipulated in the test cases, we should actually create it in a temporary directory and remove it when the test is exiting.

**Comment by caitmuenster** [comment]
Mentor: @rpl

**Comment by marchiore** [comment]
Hey, can I work on this?

**Comment by caitmuenster** [comment]
Go for it, @marchiore!

**Comment by marchiore** [comment]
Thanks! Just sent my PR https://github.com/mozilla/addons-linter/pull/3095
