### ISSUE TITLE
There is a JavaScript syntax error. In optional chaining

### ISSUE THREAD

**Issue by DrElvis** [mozilla/addons-linter#3085]
I load the new version of the addon on https://addons.mozilla.org/, but I get a validation error:

> There is a JavaScript syntax error in your code; validation cannot continue on this file.

swears at this line of code:
`arr.find(n => n.values.includes(ee.toString()))?.action();`

namely the question mark.
however, the use of this functionality is described on [https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining)

**Comment by DrElvis** [comment]
I can`t update my extention :(

**Comment by jvillalobos** [comment]
This is probably related to https://github.com/mozilla/addons-linter/issues/2498 and other similar issues. There's some recent JS syntax that the linter doesn't support.

**Comment by alta88** [comment]
Any estimate here for an update? The linter in firefox works for optional chaining and nullish syntax. This is preventing addon updates.

**Comment by michaelts1** [comment]
Any news?
