### ISSUE TITLE
uses_unknown_minified_code is false for some files which look minified

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-linter#3103]
Followup for https://github.com/mozilla/addons-code-manager/issues/1462#issuecomment-606806145

STR:
1. Go to https://code.addons-dev.allizom.org/en-US/compare/618937/versions/1690424...1690425/?path=src%2Faction%2Fstyle.css.map
or https://code.addons-dev.allizom.org/en-US/compare/618937/versions/1690424...1690425/?path=src%2Faction%2Fstyle.css

Actual result:
code manager won't show the files trimmed in compare view because uses_unknown_minified_code is false

Expected result:
The files are trimmed because they're minified files.

Notes:
I will update this issue with other examples later. 
The issue is reproducible on dev with FF74(Win10).

**Comment by ioanarusiczki** [comment]
@diox The work on trimmed minified files in code manager could be affected by this. 

I think Bob can tell better if the fix is needed before fixing https://github.com/mozilla/addons-code-manager/issues/1507 @bobsilverberg

**Comment by bobsilverberg** [comment]
> @diox The work on trimmed minified files in code manager could be affected by this.
> 
> I think Bob can tell better if the fix is needed before fixing [mozilla/addons-code-manager#1507](https://github.com/mozilla/addons-code-manager/issues/1507) @bobsilverberg

This won't have any impact on code in code-manager. It will only help us to identify more types of minified files if we implement the change.

**Comment by rpl** [comment]
We discussed about this issue during the triaging meeting and we agreed that this doesn't look worth fixing
(at least if it doesn't trigger any actual issue for the reviewers).
