### ISSUE TITLE
Travis CI should run prettier check

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-linter#3125]
We should add a travis-ci job job to run prettier and double check that PRs are "prettier-compliant". See: https://github.com/mozilla/addons-frontend/blob/375eee5c2ba0dc24b774e710b0fa301f1ee5b924/package.json#L34

I don't know if we have that already but we could also add a `prettier-dev` npm script to run [pretty-quick](https://www.npmjs.com/package/pretty-quick). This command would only run prettier on changed files and that is both fast and friendly.

**Comment by ioanarusiczki** [comment]
@willdurand Please add some str for qa else mark this qa not needed. 
Thanks!
