### ISSUE TITLE
check optional_permissions

### ISSUE THREAD

**Issue by imonja** [mozilla/addons-linter#3138]
When checking **manifest.json**, if **"optional_permissions"**  is specified, **"management"** 
`
...
"optional_permissions": [
		"management"
	],
...
`

throws an error. 

`...
JSON_INVALID   "/optional_permissions/0" should be equal   to one of the allowed values  Your JSON file could not be parsed. `                  
                                                                                         
`JSON_INVALID   "/optional_permissions/0" is not a valid  key or has invalid extra properties      Your JSON file could not be parsed.   `                    
                                                                                 
`JSON_INVALID   "/optional_permissions/0" should match   pattern "^(https?|wss?|file|ftp|\*)://(\*|\*\.[^*/]+|[^*/]+)/.*$"     Your JSON file could not be parsed.  
...`                     
                                                                                                    
There is no mistake with any other

**Comment by Rob--W** [comment]
`management` is not an optional permission yet. There is work in progress to support it in https://bugzilla.mozilla.org/show_bug.cgi?id=1630419

Once that has landed, and the schemas in the linter been updated with upstream, then this issue will be fixed.

**Comment by imonja** [comment]
Thanks

**Comment by Robbendebiene** [comment]
@Rob--W Can you tell me when exactly the schemas in the linter will be updated with upstream?
I guess some time before the Firefox 77 release date (2020-06-02)?

**Comment by Rob--W** [comment]
@rpl will take care of the update. I guess soon, but otherwise at least before release.

**Comment by Robbendebiene** [comment]
@rpl Firefox 77 will be released today, but the add-on linter on AMO is still not updated. Can you tell me when the update for the add-on linter will role out?
