### ISSUE TITLE
Addon Validation Error

### ISSUE THREAD

**Issue by lunu-bounir** [mozilla/addons-linter#3170]
Please attach a copy of your add-on, and fill in the following information:

[sqlite-manager.zip](https://github.com/mozilla/addons/files/2860499/sqlite-manager.zip)

* Whether this error occurred during the submission of a new add-on, a new version of an existing add-on, a new file in an existing version, or an upload to the standalone validator.

a new version of an existing add-on

* Whether your add-on is listed or unlisted.

Listed

* The URL where you submitted the add-on.

https://addons.mozilla.org/en-US/developers/addon/sqlite-manager-webext/versions/submit/

**Comment by willdurand** [comment]
See also (maybe): https://github.com/mozilla/addons/issues/1219
