### ISSUE TITLE
Changelog is missing for the past two releases

### ISSUE THREAD

**Issue by timbru31** [mozilla/addons-linter#3197]
It would be a great addition if you can provide a changelog for 1.24.0 and 1.25.0. I've also noticed that the git tag for 1.24.0 is missing, this makes diffing even harder.

If you can add those, this makes updating more smoothly.

Thanks :)

**Comment by willdurand** [comment]
Hello, good call, thanks. I created a GitHub release for `1.25.0`: https://github.com/mozilla/addons-linter/releases/tag/1.25.0, which also describes what happened to `1.24.0`. Thanks!

**Comment by timbru31** [comment]
Appreciated :)
