### ISSUE TITLE
new optional permissions for Firefox 77 still throw an error on AMO

### ISSUE THREAD

**Issue by Robbendebiene** [mozilla/addons-linter#3198]
### Describe the problem and steps to reproduce it:

(Please include as many details as possible.)

### What happened?

The add-on linter on AMO still throws errors for the new optional permissions added in Firefox 77 (https://github.com/mozilla/addons-linter/issues/3138). Therefore add-ons cannot be updated or uploaded who want to make use of the new optional permissions.

### What did you expect to happen?

The validation should succeed.

**Comment by willdurand** [comment]
Sorry about that. We will deploy a new version of the linter today (at ~9am PT). It should work after that.
