### ISSUE TITLE
Remove eslint dependency or allow us to work around it

### ISSUE THREAD

**Issue by lfilho** [mozilla/addons-linter#3206]
There's a lot of issues in this repo regarding mdoern javascript code being used, but since the linter here is a bit old, it results as errors for the extension developers.

Personally, I want to use the addons-linter for the addon-specific linting stuff. I already have a javascript linter in my project.

As my comment in https://github.com/mozilla/addons-linter/issues/3062#issuecomment-643825903 , a possible good way forward here would be simply to allow us to specify what do we want to lint, i.e: `web-ext lint ./manifest.json`, this way i could use whatever modern javascript construct i want and have it linted by my own configuration of `eslint`.

Another possible solution, although more complex, is to have `addons-linter` identify an eslint installation and configuration on the user's project and use those ones instead.

Thanks!

**Comment by apriljunge** [comment]
Bypassing eslint would only help during local developement. As this linter ist used by addons.mozilla.org it would still cause errors when publishing the addon.
Fortunaly there's a very promising PR #3181 to finally update eslint :+1:

**Comment by willdurand** [comment]
As mentioned by @apriljunge, we're not going to get rid of eslint.
