### ISSUE TITLE
Using the name "New Extension for Firefox" throws error

### ISSUE THREAD

**Issue by abhijeetnarvekar** [mozilla/addons-linter#3225]
Since today our build pipeline throws error for signing add-on
`Server response: Add-on names cannot contain the Mozilla or Firefox trademarks. (status: 400)`

Add-on name:  "Acrolinx for Firefox"

The guideline states it is acceptable to use "NewGadget Extension for Firefox".
https://www.mozilla.org/en-US/foundation/trademarks/policy/

What is the guideline? Is is allowed to use Firefox in the name or not?

**Comment by willdurand** [comment]
cc @jvillalobos @wagnerand

**Comment by jvillalobos** [comment]
It's not allowed anymore. The documentation just needs to be updated.

**Comment by joshhofstad** [comment]
@jvillalobos just curious, is there a reason for this change?

**Comment by jvillalobos** [comment]
It was always an iffy practice from a branding perspective, but the main reason is that it causes some SEO issues like duplication of "Firefox" in page titles.

**Comment by glad2bhere** [comment]
Hi @jvillalobos , the team I work with is getting ready to release another version of our extension in Firefox. I see the documentation still says "However, it would be acceptable to name your add-on "NewGadget Extension for Firefox”."

I also see that many extensions still use the "Name for Firefox" naming convention. Does this mean that we can proceed with our extension name to be "Acrolinx Extension for Firefox" or "Acrolinx for Firefox" such as other people/companies have done in the picture below?

<img width="787" alt="Screen Shot 2020-12-22 at 10 32 53" src="https://user-images.githubusercontent.com/50232510/102873162-0e651280-4441-11eb-9589-fb74d2f4c72f.png">

**Comment by jvillalobos** [comment]
It's not allowed anymore. Those extensions were named that way before the rule went into effect and we haven't applied it retroactively.
