### ISSUE TITLE
Integrate with JPM

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-linter#323]
We would like to get to the point where we can integrate the validator package with jpm. To do this we'd need to provide a patch to JPM to add a command that will proxy `addons-validator` via `jpm validate`. At this point we'd be a dep. We could probably do this experimentally initially.

This will also depend on: #243 - which allows us to validate on a directory instead of just an xpi/zip as we do currently.

**Comment by andymckay** [comment]
Probably not something we want to do now.
