### ISSUE TITLE
"Sorry we couldn't load your WebExtension" error at submission.

### ISSUE THREAD

**Issue by ElliotHan** [mozilla/addons-linter#3244]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)
At the new version submission page, click on "choose file" and select the attached source (zip file).

### What happened?
Whenever I tried to submit my extension it spits out the "Sorry we couldn't load your WebExtension" error. I didn’t get this error before, so I don’t have a clue why I am getting this error all of the sudden.

### What did you expect to happen?
To pass the automated validation tests without any errors. 

### Anything else we should know?
I have no problem loading the extension with the “load temporary add-on” function at the firefox debug page.

(Please include a link to the page, screenshots and any relevant files.)

![image](https://user-images.githubusercontent.com/43331265/86983943-2c5af580-c1c8-11ea-8321-02e4c5ddb3d7.png)

[kaikas-firefox-1.0.18.zip](https://github.com/mozilla/addons-server/files/4893864/kaikas-firefox-1.0.18.zip)

**Comment by AlexandraMoga** [comment]
I think this error has been reported several times before. See also my issue #2506 which has additional references.

**Comment by jvillalobos** [comment]
Does this only happen on AMO or does it also fail when running `web-ext`? Is there a way to show a clearer error message on AMO?

**Comment by AlexandraMoga** [comment]
I was able to reproduce with `web-ext` as well. The error message is more or less the same, i.e. no additional information to indicate what went wrong.

**Comment by ElliotHan** [comment]
@AlexandraMoga  has the issue https://github.com/mozilla/addons-linter/issues/2506 been resolved after changing node options?

**Comment by willdurand** [comment]
The archive posted above is correctly linted with addons-linter v1.19 but it OOMs with addons-linter v2 so this is a regression, possibly in ESLint itself, we'll have to check.. cc @rpl

**Comment by els-pm-mattstratford** [comment]
Is there a status update on this? We're unable to release* to Firefox until the regression in the addons-linter v2 is fixed.

_*Without decomposing bundles which passed fine before…_

**Comment by noorulhussain** [comment]
Is there any update on this issue?

**Comment by rpl** [comment]
@ElliotHan would you mind to try to submit the extension again? we updated the limits on the worker servers and the linting should now pass successfully.

**Comment by willdurand** [comment]
We think this should be fixed for the reasons mentioned in the comment above. If it's not the case, we can still re-open this issue of course.
