### ISSUE TITLE
False positive submitting Language Pack add-on for Thunderbird 78

### ISSUE THREAD

**Issue by pasqualm** [mozilla/addons-linter#3272]
### Describe the problem and steps to reproduce it:
Hi

I have updated my language pack add-on for Thunderbird 78 but when I submit it in https://addons.thunderbird.net/en-US/developers/addon/valencian-catalan-languag-9730/versions/submit/ the system says the xpi has validation errors:
Your FTL is not valid.
Error: Expected token: " "

localization/ca-valencia/messenger/openpgp/key-wizard.ftl line 128 column 0
Your FTL is not valid.
Error: Expected token: " "

localization/ca-valencia/messenger/openpgp/enigmail.ftl line 244 column 0
Your FTL is not valid.
Error: Expected token: " "

localization/ca-valencia/messenger/openpgp/enigmail.ftl line 251 column 0

But those 2 files with errors are unchanged compared to the same present in the official Catalan language pack (ca.xpi) which can be downloaded here:
http://ftp.mozilla.org/pub/thunderbird/releases/78.0.1/linux-x86_64/xpi/

So the errors must be false positives. I have reviewed them and it seems the validator doesn't like the use of brackets in these ftl files, but they are a valid construction

The extension can be installed locally and seems to be working correctly

Can you take a look at this?

[thunderbird-78.0.1.ca-valencia.langpack.xpi.20200730-1337.xpi.zip](https://github.com/mozilla/addons-linter/files/5001078/thunderbird-78.0.1.ca-valencia.langpack.xpi.20200730-1337.xpi.zip)

**Comment by wagnerand** [comment]
Thanks for the report, please file issues related to the linter for Thunderbird here: https://github.com/thundernest/addons-linter/
