### ISSUE TITLE
You cannot submit this type of add-on

### ISSUE THREAD

**Issue by erich0123** [mozilla/addons-linter#3341]
### Describe the problem and steps to reproduce it:
I'm trying to sign an extension that uses the "theme_experiment" feature. I get the following error when trying to upload the built zip file on AMO or sign it with `web-ext`: `You cannot submit this type of add-on".

Please add a way to sign and publish extensions that make use of experimental features. Maybe you could flag them as experimental and hide them from normal search results by default.

**Comment by jvillalobos** [comment]
Experimental APIs are not for public use, by design. The signing restriction is intentional.

**Comment by erich0123** [comment]
I know. It makes sense but I want to install the extension in my own browser. I'm not trying to publish it on AMO, I just want to sign it. I don't think it's a problem if people distribute experimental add-ons themselves.

**Comment by Rob--W** [comment]
Even if signed, Firefox would not support the experiment.

Theme experiments are only supported for temporarily loaded add-ons (or themes with a privileged signature, or located in the Firefox application directory).

**Comment by erich0123** [comment]
OK, is there a way to install it permanently and can you tell me if the feature is going to be supported officially someday? I think it's a great feature.

**Comment by Rob--W** [comment]
Why do you want to permanently use `theme_experiment`? If it is to load an arbitrary style sheet, use userChrome.css instead.

There is a whole community dedicated to developing userChrome stylesheets at https://reddit.com/r/FirefoxCSS .

**Comment by erich0123** [comment]
I want to toggle the theme to hide the toolbar:

https://github.com/erich0123/firefox-zen-mode

**Comment by Rob--W** [comment]
If you use Dev Edition or Nightly, then with the instructions from your README (`xpinstall.signatures.required=false`) you can already permanently install the add-on without signing it (by zipping it, changing the file extension to `.xpi`, and loading the .xpi file in the browser).

PS. The `extensions.legacy.enabled` pref is not doing anything.

**Comment by erich0123** [comment]
Thanks, I've installed it now.

I thought the `extensions.legacy.enabled` was required because it said so in the docs.

**Comment by Rob--W** [comment]
Which docs?

**Comment by erich0123** [comment]
@Rob--W https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/theme_experiment

**Comment by Rob--W** [comment]
Thanks, I fixed that.
