### ISSUE TITLE
Remove `eslint-plugin-jest` because it is already part of the AMO config

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-linter#3381]
We use https://github.com/mozilla/eslint-config-amo, which provides an ESLint config for all our projects. It already requires `eslint-plugin-jest` so there is no need for it in the linter deps.

**Comment by AlexandraMoga** [comment]
I've submitted a few add-ons on AMO and with `web-ext` and I haven't found parsing issues.
This was verified with stage.
