### ISSUE TITLE
Add an option to disable the auto-close feature when reading xpis

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-linter#3428]
One https://github.com/mozilla/addons-linter/issues/2866 lands, we'll use a new library for the `io` layer and it will allow us to disable an "auto-close" feature when reading XPI files.

In short, instead of opening and closing the XPI every time we read something in it, we'll keep it opened. This should improve the overall perfs a bit (at least, in a different project, this optimization had a significant positive impact).

**Comment by AlexandraMoga** [comment]
@willdurand same question as in #2866, would some general linter tests verify this issue?

**Comment by willdurand** [comment]
This isn't used on addons-server yet so some general linter tests are more than enough

**Comment by ioanarusiczki** [comment]
Verified on AMO stage - FF82(Win10).
