### ISSUE TITLE
Use a version lib to check versions and provide more version related data

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-linter#346]
Jpm has a node dep that looks good for this.

**Comment by tofumatt** [comment]
Not sure if this one needs to stay open for Web Extensions so I'm gonna leave it, but if it seems erroneous feel free to close :smile:

**Comment by EnTeQuAk** [comment]
This could be, as far as I understand it, a stretch goal for the schema pull from mozilla-central but let's close this one for now since it's probably old and unrelated to our current usecases.

If I'm wrong, feel very free to re-open any time.
