### ISSUE TITLE
Validation Issue with Angularjs 1.8

### ISSUE THREAD

**Issue by ysriram1** [mozilla/addons-linter#3466]
My extension is failing validation tests when I'm attempting to upload. I'm getting these errors:

Error: Your add-on uses a JavaScript library we consider unsafe. Read more: https://bit.ly/1TRIyZY
lib/angular/angular-1.8.0/angular.min.js

When I go to the specified url (https://bit.ly/1TRIyZY), it says "We allow the latest 1.x version at submission time; previous versions are not accepted due to security vulnerabilities." 

My extension has been updated to use the latest AngularJS (1.8).

So not sure why it continues to fail validation. Any help is appreciated.

<img width="1061" alt="Screen Shot 2020-11-22 at 10 45 48 AM" src="https://user-images.githubusercontent.com/6699957/99895775-fbc7b400-2caf-11eb-9db7-466086891ef8.png">

**Comment by Rob--W** [comment]
The latest version on the 1.x branch (https://github.com/angular/angular.js/tree/v1.8.x) is currently 1.8.2. Of the 1.8.x series, only 1.8.0 and 1.8.1 are currently blocked. You should use 1.8.2 in your add-on.
