### ISSUE TITLE
Add fail-fast CLI arg.

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-linter#348]
This is so when there's an issue with the processing of the file we can bail on the first error encountered. 

This will speed up debugging of problems with processing large add-ons.

**Comment by caitmuenster** [comment]
Hey @muffinresearch, we think more information might be needed before tagging this as a good first bug.

**Comment by muffinresearch** [comment]
This would entail looking at the collector and running process.exit as soon as an error is added to the list of errors.

[This is the relevant part of the collector](https://github.com/mozilla/addons-linter/blob/0bed228e24efd9d5d3541cf1541a6809bacd5358/src/collector.js#L28) I'm pointing there since I don't think it would make sense to rely on the addError always being called directly - that's just a convenience method.

**Comment by muffinresearch** [comment]
Moving this to contrib welcome since it's probably a better next step rather than a first bug to start with.

**Comment by jasmineflorencio** [comment]
Hi, I would like to handle this issue.

**Comment by EnTeQuAk** [comment]
@jasmineflorencio please go for it! If you need any help or run into any problems along the way feel free to let us know.

**Comment by kamsuri** [comment]
Hey @EnTeQuAk!
I doubt if anyone is working on this issue as there are no workarounds since past 15 days. If it is alright with you, can i take this up?

**Comment by jasmineflorencio** [comment]
@kamsuri, I'm working on this issue but first it seemed like [issue 351](https://github.com/mozilla/addons-linter/issues/351) needed to be solved so I'm waiting to hear back from @EnTeQuAk about that first.

**Comment by kamsuri** [comment]
Alright @jasmineflorencio , I thought no one is working as there was no commit, but now I got the reason.

**Comment by jasmineflorencio** [comment]
@kamsuri I'm not going to be able to participate in Outreachy this round so if you are, then you can take this issue.
