### ISSUE TITLE
Linter Fails on ES6 module default export statement

### ISSUE THREAD

**Issue by SimonBrazell** [mozilla/addons-linter#3541]
### Describe the problem and steps to reproduce it:

Just tried to submit my extension to AMO, the linter failed with a syntax error on line 1, col 1 of the following file:

```
// src/assets/javascripts/helpers/twitter.js

export default class {
  static targets = [
    "twitter.com",
    "www.twitter.com",
    "mobile.twitter.com",
    "pbs.twimg.com",
    "video.twimg.com",
  ];
  static redirects = [
    "https://nitter.net",
    "https://nitter.snopyta.org",
    "https://nitter.42l.fr",
    "https://nitter.nixnet.services",
    "https://nitter.13ad.de",
    "https://nitter.pussthecat.org",
    "https://nitter.mastodont.cat",
    "https://nitter.dark.fail",
    "https://nitter.tedomum.net",
    "https://nitter.cattube.org",
    "https://nitter.fdn.fr",
    "https://nitter.1d4.us",
    "https://nitter.kavin.rocks",
    "https://tweet.lambda.dance",
    "https://nitter.cc",
    "https://nitter.weaponizedhumiliation.com",
    "https://nitter.vxempire.xyz",
    "https://nitter.unixfox.eu",
    "http://3nzoldnxplag42gqjs23xvghtzf6t6yzssrtytnntc6ppc7xxuoneoad.onion",
    "http://nitter.l4qlywnpwqsluw65ts7md3khrivpirse744un3x7mlskqauz5pyuzgqd.onion",
    "http://nitterlgj3n5fgwesu3vxc5h67ruku33nqaoeoocae2mvlzhsu6k7fqd.onion",
    "http://npf37k3mtzwxreiw52ccs5ay4e6qt2fkcs2ndieurdyn2cuzzsfyfvid.onion",
  ];
}

```

Please note the extension runs fine locally, which is why I was just about to publish it...

How do I resolve this?

### What happened?

The linter blocked the zip file stating that there is a JS syntax error on line 1, col 1 - `export default class {`.

```
JS_SYNTAX_ERROR   JavaScript syntax error   There is a JavaScript syntax error in your code; validation   src/assets/javascripts/helpers/…   1      1
                                            cannot continue on this file.                                 twitter.js
```

### What did you expect to happen?

File to pass linter as there is no syntax error in the flagged file.

### Anything else we should know?

![Screen Shot 2021-01-10 at 22 47 08](https://user-images.githubusercontent.com/16571951/104121889-cd07b900-5395-11eb-8312-6a22ee1fc5ab.png)

Not all files using this same syntax fail however, it seems the file below passes:

```
// src/assets/javascripts/helpers/common.js

export default class {
  static filterInstances(instances) {
    return instances.filter((instance) => !instance.includes(".onion"));
  }

  static getRandomInstance(instances) {
    return instances[~~(instances.length * Math.random())];
  }
}
```

**Comment by Rob--W** [comment]
(Public) static fields are not supported by the linter yet - see #3062

```javascript
export default class {
  static targets = [
```

Your second example uses static methods, which are supported.
An alternative to get it to work is to use (public) instance fields.
In your case, it looks like you don't even need classes; a class with only (public) static fields can be replaced with a plain object with properties.

```javascript
export default {
  targets: [ ... ],
  redirects: [ ... ].
};
```

Or, for readability (so that it is more obvious what's being exported) (the `{` and `}` are object literals, the properties are shorthand property names):

```javascript
const targets = [ ... ];
const redirects = [ ... ];
export default { targets, redirects };
```

... or the following (`{` and `}` are here part of the export syntax, and `targets` and `redirects` are exported names)

```javascript
const targets = [ ... ];
const redirects = [ ... ];
export { targets, redirects };
```

or simply:

```javascript
export const targets = [ ... ];
export const redirects = [ ... ];
```

**Comment by SimonBrazell** [comment]
Okay thanks @Rob--W I'll try it with your suggestions instead. I suggest a more descriptive failure message as I did search the repo for issues similar to mine but only found old ones about module exports.

Cheers!

**Comment by SimonBrazell** [comment]
@Rob--W quick question, is there any way to get a pass on the following statement?

`import(browser.extension.getURL("src/assets/javascripts/helpers/twitter.js"))`

This is in a content script, seems to be the only way to import a module as far as I could tell.

**Comment by Rob--W** [comment]
> @Rob--W quick question, is there any way to get a pass on the following statement?
> 
> `import(browser.extension.getURL("src/assets/javascripts/helpers/twitter.js"))`
> 
> This is in a content script, seems to be the only way to import a module as far as I could tell.

Dynamic imports in content scripts are not yet supported by Firefox, see https://bugzilla.mozilla.org/show_bug.cgi?id=1536094

PS. I see in your patch at https://github.com/SimonBrazell/privacy-redirect/commit/f56fc681886450e68fe3597fbcba870436c05ba4 that you've replaced the use of `innerHTML` with `DOMParser` followed by appending the parsed DOM. I guess that you've done that in response to linter warnings. While the warning may have disappeared, the code in `getItem` is still insecure (i.e. prone to HTML injection), the correct solution is to only use `innerHTML` or `DOMParser` for static HTML/XML code, and use DOM methods/properties to assign dynamic values to input elements. If you insist on using `innerHTML`/`DOMParser`, at least html-escape the external input before concatenating them with HTML strings.

**Comment by SimonBrazell** [comment]
> Dynamic imports in content scripts are not yet supported by Firefox, see https://bugzilla.mozilla.org/show_bug.cgi?id=1536094

Discovered that not long after I posted my question, damn shame, I really wanted to modularise my code 🙁

Thanks for the tip, that code was wrong anyway, so I replaced it with `createElement` to build the HTML instead. Would you mind giving an example of how i "html-escape the external input" if i do decide to use `innerHTML` in the future?

Thanks again for your advice!

**Comment by Rob--W** [comment]
> Would you mind giving an example of how i "html-escape the external input" if i do decide to use `innerHTML` in the future?

https://gist.github.com/Rob--W/ec23b9d6db9e56b7e4563f1544e0d546

For more reading about the class of vulnerabilities (XSS) and preventive measures, see https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html

**Comment by SimonBrazell** [comment]
Thanks @Rob--W much appreciated.
