### ISSUE TITLE
JavaScript syntax error with numeric separator

### ISSUE THREAD

**Issue by michaelts1** [mozilla/addons-linter#3543]
### What happened?
I ran Add-ons Linter from the command line, and got a validation error:

> There is a JavaScript syntax error in your code; validation cannot continue on this file.

Which points to this line of code, at column 14:
`let tmp = 10_000`.
It seems that the error is caused by the numeric separator.

### What did you expect to happen?
I expect that Add-ons Linter will not throw any errors, since the use of numeric separators is described on https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#Numeric_separators, and is supported since Firefox 70, which was released more than a year ago.

**Comment by Rob--W** [comment]
Which version of `addons-linter` are you using?

We rely on `eslint` for parsing the file, and eslint already supports it since v7.8.0 (https://github.com/eslint/eslint/releases/tag/v7.8.0).

We are currently using eslint 7.17.0 - https://github.com/mozilla/addons-linter/blob/a8ec9db88a6726f5a54270273791d33789d62ee5/package.json#L54

**Comment by michaelts1** [comment]
Running `addons-linter --version` gives me "2.16.0".
Running `eslint --version`, gives me "v7.17.0".

I created a folder containing only one file that contains only the following line: `1_0;`.
Running `addons-linter ./` still gives me the same error:
>There is a JavaScript syntax error in your code; validation cannot continue on this file.
test.js 1 3

**Comment by Rob--W** [comment]
I see the reason... We're specifying `ecmaVersion: 2020` but numeric literals require 2021 per https://github.com/eslint/espree/pull/448

To fix this, we need to change 2020 to 2021 at https://github.com/mozilla/addons-linter/blob/be94690d29118a0f3c642b2803148a2699b69d67/src/scanners/javascript.js#L13

and add a unit test (to verify that we support numeric separators) in https://github.com/mozilla/addons-linter/blob/be94690d29118a0f3c642b2803148a2699b69d67/tests/unit/scanners/test.javascript.js

Are you interested in contributing a patch?

**Comment by michaelts1** [comment]
I created a pull request to fix this issue.

**Comment by willdurand** [comment]
thanks @michaelts1!
