### ISSUE TITLE
Add support for more JavaScript file extensions

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-linter#3580]
We should lint all supported JS files.

**Comment by AlexandraMoga** [comment]
Add-on validation is now extended to `.jsm` and `.mjs` files. Errors and warnings are detected:

![image](https://user-images.githubusercontent.com/31961530/108365300-b871d880-71ff-11eb-98a5-c5c3c6bc3ca0.png)

Our scanners are also able to detect these files - rules are being matched and a score is applied.
