### ISSUE TITLE
Dependencies versions do not use ranges

### ISSUE THREAD

**Issue by arty-name** [mozilla/addons-linter#3629]
### Describe the problem and steps to reproduce it:

I installed web-ext in my project and now have two versions of eslint: 7.21.0 is used by addons-linter, while the most recent one my project uses is 7.22.0. Eslint is just one example, the same issue is present for other dependencies as well.

### What happened?

Multiple minor or patch versions of dependencies were installed. addons-linter says it needs eslint "7.21.0", not "^7.21.0", so when another dependency installs 7.22.0 it is not enough for addons-linter to be happy.

### What did you expect to happen?

A single version of dependency should have been used to satisfy different dependents, because according to semantic versioning minor and patch versions do not introduce breaking changes.

### Anything else we should know?

To reiterate, this is not about eslint only. All dependencies’ versions in package.json should be specified using range `^`.

**Comment by willdurand** [comment]
There are differences between minor versions and semver isn't always used/respected so we do not use ranges on purpose.

**Comment by arty-name** [comment]
Yes, of course there could be differences, but could you use fixed versions where this resolves an issue and keep ranges for the unproblematic dependencies? The absolute majority of other packages do it this way, and it helps keeping node_modules from bloating, reduces energy consumption and CO2 emissions.

**Comment by eviljeff** [comment]
stability and security (from only installing from a fixed version you have already verified) has a cost, but we think it's worth it.

**Comment by arty-name** [comment]
Isn’t it just illusionary? Your dependencies do not follow your approach, so the versions of your transitional dependencies are not fixed.
