### ISSUE TITLE
Hash-check JSM files

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-linter#3659]
Addons Linter did no use to parse `.jsm` files. A number of add-ons use `.jsm` extension for the library files (for this reason). Recently, linter has started to parse `.jsm` files and therefore it should also hash check them against known libraries.

Hash checking `.jsm` files will reduce processing in case of valid libraries and eliminate unwanted validator messages.
Additionally, it would facilitate add-on review process and better assign weight.

Examples:
https://addons.mozilla.org/en-US/firefox/addon/decentraleyes/  (no validator error since it has not been updated recently)
https://addons.mozilla.org/en-US/firefox/addon/localcdn-fork-of-decentraleyes/
https://addons.mozilla.org/en-US/firefox/addon/firemonkey/

@wagnerand 

### Update
The above mentioned use of libraries must be factored in the decision, since some libraries cause the validation to fail as shown in the following comment.

:bulb:  Therefore as a first step, validator can process `KNOWN_LIBRARY` for the `.jsm` but not process or fail on `BANNED_LIBRARIES`.

**Comment by erosman** [comment]
While on the subject ..... few suggestions

- linter should check hashes before processing file
- if there is a hash-match, break from processing file, then
  - `BANNED_LIBRARIES`: output message
     (_ATM, linter continues to parse known BANNED_LIBRARIES which is needless_)
  - `KNOWN_LIBRARY`: output message
- Review Tools need not process, syntax highlight, and generate error messages for any of the hash-matched libraries (banned or allowed)
  IMHO, they should show them as plain text

**Comment by willdurand** [comment]
> Addons Linter did no use to parse `.jsm` files. A number of add-ons use `.jsm` extension for the library files (for this reason). Recently, linter has started to parse `.jsm` files and therefore it should also hash check them against known libraries.

I thought the changes made to lint `.jsm` files would have enabled that already.  I don't see why we wouldn't want to process `.jsm` files like `.js` files and I don't necessarily agree that `.jsm` files should be used to evade the linter.

**Comment by willdurand** [comment]
cc @wagnerand
