### ISSUE TITLE
Consider adding a warning for usage of canvas drawWindow method, deprecated because of Fission

### ISSUE THREAD

**Issue by zombie** [mozilla/addons-linter#3661]
To help spread awareness about `drawWindow` deprecation, consider adding a warning to the linter for its use.

This would be temporary rule (less than a year), but the issue is that it can't be any more specific than just "a call to an `[object].drawWindow()` method", and may trigger for extensions that just use that name for their own method.

(@rpl and @willdurand think there might be too many false positives, and is probably not worth it)

**Comment by zombie** [comment]
Forgot to mention, I investigated existing similar rules, and I believe I could probably add the rule myself.

**Comment by wagnerand** [comment]
It might make more sense to try and identify add-ons affected and send a transactional email informing them about the upcoming change.

I am hesitant to add more warnings before we have a way to categorize them and show specific categories to specific user groups only (development, publishing, reviewers, developers...).

**Comment by rpl** [comment]
> It might make more sense to try and identify add-ons affected and send a transactional email informing them about the upcoming change.

+1 I agree, this seems to be one of those cases where a code search and direct communications directed to the potentially affected extension may make more sense than adding a new linting rule only for a short while (especially if it is not a blocking one and it may be very likely just ignored).

> I am hesitant to add more warnings before we have a way to categorize them and show specific categories to specific user groups only (development, publishing, reviewers, developers...).

@wagnerand Do we have a bug on file about this kind of categorization?

**Comment by wagnerand** [comment]
> @wagnerand Do we have a bug on file about this kind of categorization?

I am fairly sure I filed one a long time ago in one of the addons repositories, but I can't find it anymore. Maybe it has been closed by stalebot in the meantime.

**Comment by zombie** [comment]
Forgot to link the related meta bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1680359

**Comment by jvillalobos** [comment]
I agree with Andreas that this makes more sense as a one-off, rather than a permanent warning.

**Comment by zombie** [comment]
Thanks all, closing this and will go with a targeted email.
