### ISSUE TITLE
Add-on GUID must be 4chars or more

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-linter#371]
Trunion (the signing server) needs the add-on ID to be 4 chars or more:

uwsgi-prelim-amo-signer: HTTPBadRequest: addon_id is very short(<4 bytes): "@pg"

See: mozilla/olympia#1007

**Comment by muffinresearch** [comment]
Note - web extensions or a least the documentation for manifest.json doesn't mention a guid [1] so this will affect install.rdf parsing only.

Also there was this comment [2] on the related PR which suggests the 4 char limit may cause issues.

[1] https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json
[2] https://github.com/mozilla/olympia/pull/1008#issuecomment-161308854

**Comment by jvillalobos** [comment]
Copying my comment on the pull request:

This is inconsistent with what Firefox accepts, so it will cause developers problems after they've tested their add-on in Firefox and want to submit it. Also, there are existing add-ons with short IDs that would be broken because of this.

This change needs to be discussed at the Product level before it can be accepted.

**Comment by muffinresearch** [comment]
@jvillalobos thanks - we'll not be looking at this just yet. We'll await the outcome of the discussion.

**Comment by tofumatt** [comment]
Looks like this being something that doesn't affect Web Extensions, we can close this.

**Comment by jvillalobos** [comment]
How so? Is there a minimum ID size enforced in Firefox?

**Comment by andymckay** [comment]
@jvillalobos you were the one who wanted to discuss it at the Product level. Can you tell us what happened as a result of that?

**Comment by tofumatt** [comment]
Sorry, my understanding is this wouldn't matter to web extensions, maybe I read this issue wrongly.

**Comment by jvillalobos** [comment]
December happened... I'll bring it up in the open chat tomorrow, where I think Kev will be around.

**Comment by tofumatt** [comment]
My bad, I was too trigger-happy.

I'll re-open this until we have clarification.

**Comment by wagnerand** [comment]
For the record, the min-length is enforced in trunion at https://github.com/mozilla/trunion/blob/master/trunion/validators.py#L167-L170

**Comment by andymckay** [comment]
This is being fixed in trunion, nothing to do here.

https://github.com/mozilla/trunion/pull/19
