### ISSUE TITLE
Omit linting warnings and errors related to manifest_version 3 extension when the addons-linter max allowed manifest version is set to 2

### ISSUE THREAD

**Issue by rpl** [mozilla/addons-linter#3737]
As a follow up for the changes we introduced for #3721, we agreed that:

- when addons-linter is configured to only allow manifest version 2 extensions (which is currently the default behavior while the `--max-manifest-version` cli option value is set to 2)
- we would like to omit the validation errors related to manifest properties only allowed to manifest_version 3 extensions

(e.g. see https://github.com/mozilla/addons-linter/issues/3721#issuecomment-841232347 to see what validation messages are being currently produced for a manifest_version 2 extension with a typo in the background manifest property).

**Comment by rpl** [comment]
Closing as wontfix, we will reconsider as soon as we would have determined how the feature supported by this Firefox-specific MV2 API would be introduced in the set of APIs that are going to be available to MV3 extensions in Firefox.

**Comment by willdurand** [comment]
@rpl is this still necessary?

**Comment by willdurand** [comment]
Probably fixed by https://github.com/mozilla/addons-linter/pull/4397
