### ISSUE TITLE
Use Node 14 as default node version

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-linter#3761]
~~We would like to use Node 14 for AMO on production so we are going to set the default Node version of addons-linter to `14` instead of `12` as it is currently.~~

As discussed with @rpl on Matrix, we're going to continue to use Node 12 as the "default version" so that we can release new versions fully compatible with Node 12 until web-ext is "ready" to deprecate Node 12.

---

For QA: once a new version of the linter has been released and deployed on AMO, please make sure that we can still validate new submissions.

**Comment by willdurand** [comment]
> @willdurand
> I'm thinking of testing this tomorrow at release testing on AMO stage - uploading addons using dev hub.
> I hope it's fine.

I reverted the patch for this issue as we are not ready to build the linter with Node 14. Instead, we'll continue to use Node 12 to build the linter, even if AMO uses Node 14 as runtime (this shouldn't be a problem).

**Comment by willdurand** [comment]
This has been fixed.

**Comment by ioanarusiczki** [comment]
@willdurand I assume this requires testing as mentioned above. Can this be done on AMO dev with linter 5.1.0 ?

**Comment by willdurand** [comment]
> @willdurand I assume this requires testing as mentioned above. Can this be done on AMO dev with linter 5.1.0

I think this has been verified already because the changes aren't new.

**Comment by ioanarusiczki** [comment]
@willdurand Ah ok, thanks!
