### ISSUE TITLE
Check for zip64 zips before passing them to yauzl. 

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-linter#379]
It's a known issue they're unhandled we should add some code to detect and reject them.

**Comment by Roboneet** [comment]
Currently, yauzl supports zip64 zips (https://github.com/thejoshwolfe/yauzl#extrafields) . This wouldn't be an issue anymore.

**Comment by EnTeQuAk** [comment]
Looking at https://github.com/thejoshwolfe/yauzl#limitted-zip64-support this is supported in a way that should work for us. We don't accept zips larger than a few hundred megabytes anyway.

Closing.
