### ISSUE TITLE
Check for encrypted zips.

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-linter#380]
It's known these aren't handled by yauzl so we should detect and reject accordingly.

**Comment by Roboneet** [comment]
I would like to work on this issue. Currently, yauzl provides a method to [check if zips are encrypted](https://github.com/thejoshwolfe/yauzl#isencrypted) . We could add the checks before calling openReadStream and reject if encrypted. Am I on the right track here ?

**Comment by EnTeQuAk** [comment]
> I would like to work on this issue. Currently, yauzl provides a method to check if zips are encrypted . We could add the checks before calling openReadStream and reject if encrypted. Am I on the right track here ?

That is indeed a perfect idea. That would have to touch `getFileAsStream` and `getChunkAsBuffer`, ideally moving the check into it's own method.
