### ISSUE TITLE
Check support for Firefox versions over 100

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-linter#3829]
As Firefox versions > 100 are not too far off it would be good to check if there are any issues from using versions that are >=  100 in manifests and ensure we have test coverage for it.

Hopefully this will be a non-issue but it wouldn't hurt to be sure.

**Comment by Rob--W** [comment]
We should add a unit test with higher version numbers for `applications.gecko.strict_min_version` at: https://github.com/mozilla/addons-linter/blob/872132e9661ea02423b1226a8926d1c9ce890810/tests/unit/schema/test.formats.js#L13

Although not directly linked to browser versions, we should also add unit tests for the `version` format. Langpacks have a version number based on the browser version, so it'd be good to have coverage for that:
https://github.com/mozilla/addons-linter/blob/872132e9661ea02423b1226a8926d1c9ce890810/tests/unit/schema/test.applications.js#L63

**Comment by willdurand** [comment]
We are past Fx 100
