### ISSUE TITLE
AMO Extension validator uses the outdated rules

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-linter#3836]
Re-filed from https://bugzilla.mozilla.org/show_bug.cgi?id=1722817

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4495.0 Safari/537.36

### Steps to reproduce:

Try to submit the attached extension to addons.mozilla.org

### Actual results:

The extension is successfully accepted.

### Expected results:

The extension is rejected:
JavaScript syntax error (Parsing as module error: Unexpected token = at line: 3 and column: 17) (Parsing as script error: Unexpected token = at line: 3 and column: 17)
JavaScript syntax error (Parsing as module error: Unexpected token = at line: 4 and column: 17) (Parsing as script error: 'import' and 'export' may appear only with 'sourceType: module' at line: 1 and column: 1)

The validator can't work with ES6 imports and with class static properties.

While the extension works fine even in Firefox ESR (78) (the actual Firefox version is 90).

**Comment by muffinresearch** [comment]
See the original bug for the extension and further information from QA.

**Comment by wagnerand** [comment]
This sounds similar to #3062.

**Comment by willdurand** [comment]
I am not sure what "outdated rules" means. The linter is very up-to-date on AMO.

Public/class field declarations are not yet fully supported by ESLint, see: https://github.com/eslint/eslint/issues/14343. It's _almost_ there, though.

There is nothing we can do so unless I have overlooked something, we can close this bug.
