### ISSUE TITLE
Import schema for Firefox 90.0b7

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-linter#3844]
Import schema for Firefox 90.0b7, which includes the following changes:

- bookmarks.json - removed two unsupported API methods that are not exposed to extensions on Chrome [Bug 1713674](https://bugzilla.mozilla.org/show_bug.cgi?id=1713674)
- actions.json / browser_action.json / context_menus.json / menus.json - introduced "action" namespace, redefined "browserAction" namespace as an "alias" or the "action" namespace definition [Bug 1706398](https://bugzilla.mozilla.org/show_bug.cgi?id=1706398)
- browser_settings.json - introduces some webRender related browserSettings - [Bug 1714428](https://bugzilla.mozilla.org/show_bug.cgi?id=1714428) and [Bug 1719688](https://bugzilla.mozilla.org/show_bug.cgi?id=1719688)
- geckoProfiler.json - some addition to the geckoProfiler API namespace - [Bug 1715257](https://bugzilla.mozilla.org/show_bug.cgi?id=1715257) and [Bug 1715922](https://bugzilla.mozilla.org/show_bug.cgi?id=1715922)

**Comment by AlexandraMoga** [comment]
@willdurand I've verified add-on uploads on stage - ranging from simple to complex extensions (I've used some high profile extensions as well) to see if there are any issues with the latest linter release.

I didn't know what syntax should be used to tests all the individual changes mentioned in your issue comment. The addition of `action` as an alias for `browser_action` was pretty straightforward, but the others not so much:
- replacing `browser_action` with `action` => MV3 doesn't trigger errors or warnings during validation; MV2 triggers the following warning:
```
Code                         Message                    Description                                 File            Line   Column
MANIFEST_FIELD_UNSUPPORTED   "/action" is in a format   "/action" is in a format not supported in   manifest.json
                             not supported in           manifest versions < 3.
                             manifest versions < 3.
```
