### ISSUE TITLE
Update GH Pages and Circle settings

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-linter#3852]
In order to mitigate #3507 and have a better publishing experience, we updated the location of the little website of this repo in https://github.com/mozilla/addons-linter/issues/3853

We now need to update the `source` in the GH Pages settings:

1. use the `master` branch
2. use the `/docs` folder

After that, we can also update the Circle CI config to remove the `GH_*` env vars (and revoke the GH token).

**Comment by muffinresearch** [comment]
Pages config updated as per requirements above. GH_* env vars removed, GH_TOKEN revoked.

**Comment by willdurand** [comment]
Everything is working as expected. I deleted the `gh-pages` branch.
