### ISSUE TITLE
Make invalid values set in host_permissions a "severity: warning" linting result instead of an "severity: error" one

### ISSUE THREAD

**Issue by rpl** [mozilla/addons-linter#3888]
For an invalid value set in permissions we explicitly set the severity to warnings, if Firefox is also just warning on invalid host_permissions values then the linter should also do the same.

**Comment by Rob--W** [comment]
Related: https://github.com/mozilla/addons-linter/issues/3872#issuecomment-909295172

**Comment by AlexandraMoga** [comment]
I've verified this issue on AMO -dev and I have the following results:

- `manifext_version: 3` add-on with invalid `host_permissions` - i.e. `"foo"`:
![image](https://user-images.githubusercontent.com/31961530/132515510-58c85e59-dd81-4869-bf5e-40243debe8f4.png)

- `manifext_version: 3` add-on with bad `host_permissions` - i.e. not in string format:
![image](https://user-images.githubusercontent.com/31961530/132515615-309d73bc-7d8b-416b-91f1-a0272e097bd5.png)

- `manifext_version: 2` add-on with invalid or bad `host_permissions`  - further  `host_permissions`  validations are ignored:
![image](https://user-images.githubusercontent.com/31961530/132515690-17d50e09-9135-49fb-adda-bcac87b4d520.png)

@rpl with regards to the second example - bad `host_permission` type - the error message says "Permissions should be string. Error: The permission type is unsupported.". Should the message mention "Host permissions" specifically or do we apply this message to any permission related type error?

**Comment by rpl** [comment]
> I've verified this issue on AMO -dev and I have the following results:
> ...
> @rpl with regards to the second example - bad `host_permission` type - the error message says "Permissions should be string. Error: The permission type is unsupported.". Should the message mention "Host permissions" specifically or do we apply this message to any permission related type error?

Thanks @AlexandraMoga, these results looks good to me.

About the error message on an invalid host permission type (non string):
- personally I think it may be just fine as it is for now, both permissions and host permissions are expected to be of type string
- also, once we will have an MDN doc page related to the host_permissions, the description associated to that linting error will be updated to also include a shorted url to the host_permissions MDN doc page too (follow up tracked by #3893)

@willdurand what is your opinion about this ^ ?

**Comment by willdurand** [comment]
> @willdurand what is your opinion about this ^ ?

+1
