### ISSUE TITLE
Tidy up linter.js

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-linter#391]
[`src/validator.js`](https://github.com/mozilla/addons-validator/blob/master/src/validator.js) no longer feels effortless to scroll through in my text editor and has grown quite large. There's a lot of code in there just for `print()`, and while it's nothing too wild it can feel like a bit of an intimidating file for me. I imagine it's worse for new developers.

I'm happy to take this on as I have ideas about it, but we should tidy up this file a bit, and possibly move some of the printing to a separate class.

Also of note, it's too big for babel/webpack to bother optimising; that's what triggered me finally wanting to tackle this after thinking it for awhile:

<img width="702" alt="screenshot 2015-12-04 22 37 26" src="https://cloud.githubusercontent.com/assets/90871/11603149/9ca2003a-9ad7-11e5-8cdf-ced50d917f43.png">

**Comment by muffinresearch** [comment]
Sounds like a plan!

**Comment by tofumatt** [comment]
And I'll have to rename the issue linter.js soon ;-)

**Comment by tofumatt** [comment]
#398 is merged so renaming this to "linter.js". :smile:

**Comment by EnTeQuAk** [comment]
This warning is no longer raised but indeed, the whole printing code (e.g `textOutput` etc) could be put into separate modules and be made easier to be re-used.

Maybe that's a good `contrib:welcome` bug?

**Comment by EnTeQuAk** [comment]
I'm going to close this, as it's never going to happen or can be taken into account when we do significant changes to that file.
