### ISSUE TITLE
Cannot pass General Tests to upload add-on because it contains ES modules and class fields

### ISSUE THREAD

**Issue by sineway** [mozilla/addons-linter#3960]
The are multiple files, but all with the same «symptoms» 

> JavaScript syntax error (Parsing as module error: Unexpected token = at line: 8 and column: 16) (Parsing as script error: 'import' and 'export' may appear only with 'sourceType: module' at line: 4 and column: 1)

[Source file](https://github.com/sineway/emir/blob/master/api/TimeUnit.js)

**Comment by sineway** [comment]
Is there any solution, similar to «add `type: "module"` to manifest» or something? 
I would like to keep my web extension free of JS processing.

**Comment by sineway** [comment]
Should I close duplicate issue at mozilla/addons?

**Comment by ioanarusiczki** [comment]
@willdurand 
The JavaScript syntax error is no longer present with linter 4.0.0 or on AMO dev. 

now:
![dev](https://user-images.githubusercontent.com/33448286/140743942-ca26508f-6e7d-4f92-8ecb-d4ba8a051124.png)

before:
![stage](https://user-images.githubusercontent.com/33448286/140743956-d9696730-4721-45a7-a522-402e2e49e14d.png)


[timeunit.zip](https://github.com/mozilla/addons-linter/files/7496978/timeunit.zip)
