### ISSUE TITLE
Validate `install_origins` property

### ISSUE THREAD

**Issue by diox** [mozilla/addons-linter#3972]
Per [Intend to Implement message on firefox-dev](https://groups.google.com/g/firefox-dev/c/U7GpHE4R-ZY), we want the linter to support a new property : `install_origins`, which is an array of origin strings.

For the moment, the property should be completely optional, and only validated if present (in the future we may warn if it's absent). We'll need to import the schema from Firefox.

A few restrictions that might or might not be in the schema:
- Each entry in the array should be a valid [origin](https://developer.mozilla.org/en-US/docs/Glossary/Origin) (scheme included, and no trailing slash)
  - Wildcards are forbidden
  - ~~Origins in the public suffix list are forbidden (i.e. forbid `com`, allow `foo.com`)~~
  - ~~Origins should be in "canonical form" - punycode version, lowercase, not extra `.` at the end.~~
- Limit to 5 entries

**Comment by diox** [comment]
There will be one soon, I had a head start.

**Comment by AlexandraMoga** [comment]
@diox I've uploaded add-ons on -dev with several variations of `install_origins` values and I have the following results:

- Not accepted:
  - https://example.com/
  - http://www.example.com/
  - www.example.com
  - http://*.example.com
  - *://example.com
  - https://*
  - http://example.com/app2/index.html
  - https://example.com/page_one/page_two?query=something
  - http://example.com/app1


- Accepted:
  - https://example.com
  - http://example
  - http://www.example.com
  - https://myapp.example.com
  - http://example.com:8080
  - https://example.page.io
  - http://example-page-io.com
  - http://example_page_1231io.com
  - https://EXAMPLE.IO
  - http://网站.com
  - http://xn--5tzm5g.com


- Other validation results:
	- max number of allowed origins is 5
	- `install_origins` needs to be an array
	- `install_origins` accepts only string values

- No validation messages right now for:
	- `install_origins` key mispelled, i.e. `install_origin`
	- empty array, i.e. `"install_origins": []`

Let me know if something doesn't match what you've expected.

**Comment by diox** [comment]
> http://example - should this be accepted?

Debatable. This can technically be valid on a local network for instance... Can you file a follow-up and I'll ask for more opinions. In the meantime, please raise an issue if this turns out to cause further issues down the chain like 500 errors or inability to block such origins with [the new admin I just landed](https://github.com/mozilla/addons-server/issues/18331).
