### ISSUE TITLE
Raise error if `install_origins` if absent from manifest for `self-hosted` and MV3

### ISSUE THREAD

**Issue by diox** [mozilla/addons-linter#3973]
MV3 self-hosted add-ons will need to specify in their manifest what origins to allow installs from.

Therefore, in the linter, when `self-hosted` parameter is `true` and `max-manifest-version` is `3` or higher, if `install_origins` is missing from the manifest, an error should be issued. 

Note that an empty `install_origins` value (`[]`) should be allowed for local installation of those add-ons without a web server - so we should only return an error if the key is absent entirely, and only for self-hosted if MV3 are explicitly allowed.

**Comment by willdurand** [comment]
@diox is this issue still relevant?

**Comment by diox** [comment]
No, let's close it and re-assess later what will need to happen in the linter for `install_origins`
