### ISSUE TITLE
Upgrade ESLint to v8

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-linter#3985]
We should upgrade ESLint to v8 so that we can use ECMA version 2022 (13), which will add support for new syntaxes (e.g., class fields and top-level await).

**Comment by ioanarusiczki** [comment]
@willdurand I checked the other issues closed, should I be testing on -dev for some classic uploads and check on regressions?

**Comment by willdurand** [comment]
> @willdurand I checked the other issues closed, should I be testing on -dev for some classic uploads and check on regressions?

Yes please, if you have time.

**Comment by ioanarusiczki** [comment]
@willdurand  I did not see anything unusual. 
Verified on AMO dev - FF94(Win10).
