### ISSUE TITLE
Switch to using JSON schema for manifest.json

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-linter#400]
The rules for the manifest.json are quite structured. Whilst it's just JSON we should move to a schema-based approach and split the schema into its own repo to benefit other tools that can use it.

Using a versioned schema should scale much better as we add increasingly more complex rules as to what settings are allowed in a particular context.

**Comment by muffinresearch** [comment]
Blocked due to potential duplcated effort between this and platform.

**Comment by andymckay** [comment]
Supports #33

**Comment by tofumatt** [comment]
Even though we don't care about maxVersions in usage, we should check for well-formedness. This is how the old validator handles it: https://github.com/mozilla/amo-validator/issues/385
