### ISSUE TITLE
Add better support for /developer attrs in manifest.json

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-linter#4008]
As documented in https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/developer, specifically:

> The object, and both of its properties, are optional. The "name" and "url" properties, if present, will override the  author and homepage_url keys, respectively

**Comment by ioanarusiczki** [comment]
@willdurand I verified this on AMO dev:

- This [addon](https://addons-dev.allizom.org/en-US/firefox/addon/catrowan-codcockrou-haret_11/) was submitted with "author" and "homepage_url" keys only ->  dev hub Edit Page displays "homepage_url" from manifest.json. After install about:addons will display the information provided by  "author" and "homepage_url"

- the second [addon](https://addons-dev.allizom.org/en-US/firefox/addon/catrowan-dev-only/) was submitted with "developer" Object into manifest.json. Dev hub(or the frontend) is not displaying the "url". After I installed the addon, in about:addons the "name" and "url" are provided. 

- the third [addon](https://addons-dev.allizom.org/en-US/firefox/addon/catrowan-codcockrou-haret_23/) has the old keys and "developer" in manifest.json. Dev hub(and homepage from detail page) will display the information from "homepage_url". Meanwhile, about:addons displays "name" and "url" so it seems to override the old keys. 

![aboutaddons](https://user-images.githubusercontent.com/33448286/140935585-c8743913-de19-4023-af2d-b4d030d48e44.png)

My thought is that AMO should be on the same page with about:addons in the last 2 cases.

**Comment by ioanarusiczki** [comment]
@willdurand I think AMO dev is on 4.0.0 linter version - where I tested for this issue. I hope that's ok.

**Comment by willdurand** [comment]
> @willdurand I think AMO dev is on 4.0.0 linter version - where I tested for this issue. I hope that's ok.

I will deploy addons-linter 4.1.0 on -dev soon.

**Comment by ioanarusiczki** [comment]
@willdurand So should I re-test this?

**Comment by willdurand** [comment]
> @willdurand So should I re-test this?

yes, but only to make sure that AMO surfaces the error.

**Comment by ioanarusiczki** [comment]
@willdurand Yes, I see that AMO issue as before meaning information from "developer" is not present.

**Comment by ioanarusiczki** [comment]
@willdurand 

- I tested with invalid "url" and I get a red warning 

![invalid url](https://user-images.githubusercontent.com/33448286/141101654-f7b00584-8a9e-4c8e-8763-af57c354019b.png)

- The following format is accepted as valid : "url": "https://example", and I hoped it will throw an error.

![is accepted](https://user-images.githubusercontent.com/33448286/141102484-ffed9237-1500-426e-8740-126a2688f74d.png)
