### ISSUE TITLE
Automate dispensary libraries updates

### ISSUE THREAD

**Issue by diox** [mozilla/addons-linter#4010]
Updates to libraries in this repo are made by humans (generally @wagnerand), with someone:
- Checking if there are updates manually
- Updating the [json file](https://github.com/mozilla/dispensary/blob/master/src/libraries.json) with the relevant version number for the library that needs to be updated
- Generating the hashes by running `npm update`
- Tagging and releasing a new version

We need to find ways to automate this process. Particular attention needs to be paid to the hashes, to make sure they match what the developers would pick when downloading the files from the website of the library.

**Comment by willdurand** [comment]
I don't think we can add a lot more automation to this process given we need to review the different updates manually. Lets revisit this decision later if needed.
