### ISSUE TITLE
Fix typo in the IGNORED_APPLICATIONS_PROPERTY localizable message

### ISSUE THREAD

**Issue by rpl** [mozilla/addons-linter#4024]
We have spotted this typo while preparing to localize this message, the last quote character (`"`) is a typo and should be removed:

https://github.com/mozilla/addons-linter/blob/c96d7aebcbcd1dc0cfa5a62cbb4645e3801334e2/src/messages/manifestjson.js#L506

**Comment by ioanarusiczki** [comment]
@willdurand 
I see this being fixed on linter 4.1.0 ->not yet on AMO dev which still shows the typo right now. 

![typo is fixed on 4 1 0](https://user-images.githubusercontent.com/33448286/140940335-c15ea5ce-94c8-43da-b317-8b71e00e085c.png)

testing sample : [manifest.zip](https://github.com/mozilla/addons-server/files/7505363/manifest.zip)
