### ISSUE TITLE
Add a command to automatically update the list of (dispensary) libraries in the `README` file

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-linter#4030]
We should not have to maintain the list of libraries manually. There is a JSON file (`libraries.json`) containing the URLs so we should parse this file and update the `README.md` file automatically. See this script from the `dispensary` project: https://github.com/mozilla/dispensary/blob/3edf6e910afb6fd24c1e10d9b0b52a48ad49634b/bin/build-doc

mentor: @willdurand

**Comment by rpl** [comment]
@willdurand this task seems isolate enough to be something that can be worked on in parallel, and also reasonably small to be worked on as a good first bug.

Are you ok to be set as mentor for this bug?

As a side note:

While looking to the original script from the archived dispensary repository linked in the issue description, I see that:
- in the dispensary README.md file the unordered list of libraries was surrounded by `<!--RELEASE_PAGES_START-->` / `<!--RELEASE_PAGES_END-->`, which was used by the script to detect which section of the README.md to update
- while the list of libraries in the addons-linter repo isn't (at least not at the moment) surrounded by those start and end markers
It seems a detail that it may be good to keep in mind while working to prepare a PR for this issue.

**Comment by willdurand** [comment]
@rpl yep

**Comment by lucaseverett** [comment]
@willdurand I submitted PR #4416 to implement bin/build-doc from the old Dispensary repo.
