### ISSUE TITLE
Support langpacks

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-linter#404]
This can be a roll-up and we should break this down into smaller pieces.

**Comment by Nolski** [comment]
Langpacks do look like they have some validation component to them. A lang pack has CSS and HTML that need to be validated just like any other addon.

We will also need to build parsers for the `.dtd` [0] and `.properties` [1] files.

[[0]](https://github.com/mozilla/amo-validator/blob/master/validator/testcases/l10n/dtd.py) https://github.com/mozilla/amo-validator/blob/master/validator/testcases/l10n/properties.py
[[1]](https://github.com/mozilla/amo-validator/blob/master/validator/testcases/l10n/properties.py) https://github.com/mozilla/amo-validator/blob/master/validator/testcases/l10n/properties.py

**Comment by EnTeQuAk** [comment]
I'm confused, didn't we say language packs need to be supported eventually?

**Comment by muffinresearch** [comment]
Yeah I'm just clearing this until we need it - since we can use the old validator until that point. I'd hope eventually they'd make their way to web-ext format at some point too.
