### ISSUE TITLE
Addon Validation Error - Sorry, we couldn't load your WebExtension.

### ISSUE THREAD

**Issue by danny0838** [mozilla/addons-linter#4068]
Please attach a copy of your add-on, and fill in the following information:

* Whether this error occurred during the submission of a new add-on, a new version of an existing add-on, a new file in an existing version, or an upload to the standalone validator.

> a new version of an existing add-on

* Whether your add-on is listed or unlisted.

> listed

* The URL where you submitted the add-on.

> https://addons.mozilla.org/zh-TW/developers/addon/webscrapbook/versions/submit/

* The approximate time you submitted the add-on, with timezone.

> Sun Nov 21 2021 22:33:05 GMT+0800

[WebScrapbook.zip](https://github.com/mozilla/addons/files/7576434/WebScrapbook.zip)

**Comment by willdurand** [comment]
See also: https://github.com/mozilla/eslint-plugin-no-unsanitized/issues/188

**Comment by ioanarusiczki** [comment]
@willdurand I verified this on -dev and -stage -> the webextension passes validation (with lots of warnings) but I see that it fails on prod so I guess it is alright now. 

![validation](https://user-images.githubusercontent.com/33448286/143472514-bbad2ab0-6ce0-4eb3-9f5e-6e4645105385.png)
