### ISSUE TITLE
'http://example' is accepted as a valid `install_origins` value

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-linter#4071]
Follow up for https://github.com/mozilla/addons-linter/issues/3972#issuecomment-979978525

### Description:

While testing #3972, I've noticed that a URL in format "http://example" is accepted as a valid `install_origins` value.
On @diox 's recommendation, I'm opening this issue to discuss this behavior further.

From https://github.com/mozilla/addons-linter/issues/3972#issuecomment-979978525:

>http://example - should this be accepted?

>>Debatable. This can technically be valid on a local network for instance... Can you file a follow-up and I'll ask for more opinions.

**Comment by Rob--W** [comment]
Acceptable IMO. It's a valid URL, and could be resolved in some network.

`http://example` is not worse than `http://obviously.not.existing.example.com`

**Comment by diox** [comment]
Yeah let's allow that.
