### ISSUE TITLE
Add a link to MDN doc page as part of the description of MANIFEST_INSTALL_ORIGINS error message

### ISSUE THREAD

**Issue by diox** [mozilla/addons-linter#4084]
As part of https://github.com/mozilla/addons-linter/issues/4061 we're going to add more specific error messages for errors related to `install_origins`. Ideally we'd have a link to a MDN page, but that MDN page doesn't exist yet and needs to be created first. Once it exists, we can go back and edit the `description` or `MANIFEST_INSTALL_ORIGINS` to include the link to it.

**Comment by willdurand** [comment]
@diox is this issue still relevant?

**Comment by diox** [comment]
Let's close it for now.

**Comment by AlexandraMoga** [comment]
There is a MDN link in validation error messages related to `install_origins` pointing to https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/install_origins, which is not available yet.
![image](https://user-images.githubusercontent.com/31961530/202170654-aae2e543-2244-4c6f-bf60-15cc69e5db18.png)

@willdurand in https://github.com/mozilla/addons-linter/pull/4591#issuecomment-1315393328 you're mentioning that this error message is not displayed at the moment, but I'm not sure what you mean by that. I can upload an extension that uses the `install_origins` property on prod and see the error message for invalid install origins. Maybe you mean that this property is not actively used at the moment, so running into this error is highly unlikely?

**Comment by willdurand** [comment]
> I can upload an extension that uses the `install_origins` property on prod and see the error message for invalid install origins. Maybe you mean that this property is not actively used at the moment, so running into this error is highly unlikely?

Why would you do that? ;-)  In short, this top-level manifest key should not be used, FF will actually ignore it very soon, see https://bugzilla.mozilla.org/show_bug.cgi?id=1800703. That's why users should never see this error message.

And yeah, the MDN page is not published for the same reason. The short url is valid, still (and if we ever document `install_origins`, it will point to the right page on MDN).
