### ISSUE TITLE
Add option to validate single file

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-linter#413]
Main use case for this is allowing a linting tool (eg. Atom, Sublime, etc.) to validate a single file based on file type.

So users could do: `addons-linter --file foo/bar.js --type js`. Or even take `STDIN`.

**Comment by andymckay** [comment]
I would like this, I want to do this :)

**Comment by vcarciu** [comment]
Please add some STRs for this bug or add the "needs no qa" label
