### ISSUE TITLE
Improve memory usage while scanning bigger js files by removing redundant and obsolete custom eslint rules

### ISSUE THREAD

**Issue by rpl** [mozilla/addons-linter#4142]
As part of reduce OOM issue while scanning bigger js files, I tried the approach we agreed on in our last triage meeting but trying to scan all js files sequentially and run a GC pass after each scanned file was not yet able to prevent the OOM issue.

As an alternative strategy I did run some more tests to bisect which were the eslint rule that are introducing the memory usage issue, especially given that the memory growing behavior it really looked like a leak.

The result of these tests pin-pointed the memory usage issue (at least the one that actually triggers the OOM when included and it doesn't when excluded) on the following two custom eslint rules defined in the addons-linter sources itself:

- [src/rules/javascript/deprecated-entities.js](https://github.com/mozilla/addons-linter/blob/master/src/rules/javascript/deprecated-entities.js):
  - emit warnings on document.write calls, technically overlaps with something that is also covered by rules from [mozilla/eslint-plugin-no-unsanitized/](https://github.com/mozilla/eslint-plugin-no-unsanitized/), but the plugin seems more efficient from a memory usage perspective.
- [src/rules/javascript/event-listener-fourth.js](https://github.com/mozilla/addons-linter/blob/master/src/rules/javascript/event-listener-fourth.js):
  - this rules seems to be emitting warnings on a Firefox-only non-standard parameter of the DOM addEventListener method (`wantsUntrusted`), but it doesn't seem to be relevant anymore for WebExtensions extensions (for WebExtensions documents `wantsUntrusted` should be already defaulting to `true` as it does regular webcontent, while the rule seems to matter only when the extensions were often executed in privileged documents where the `wantsUntrusted` param was defaulting to `false`)

Both the rule were using [a `getNodeReference` helper method defined in src/utils.js](https://github.com/mozilla/addons-linter/blob/255b50f2041bc06a85530d13f393db5a4e488bdb/src/utils.js#L86), and they were the only users of that helper method.

Given that this helper was likely the source of the inefficient memory usage, I'm proposing to remove:
- the two custom eslint rules (which, besides being inefficient from a memory usage perspective, seems to be redundant or obsolete)
- remove alspo the `getNodeReference` helper function along with the only two users, to avoid being tempted to use it in a new rule (if we need something similar, we can look into using the eslint helper that we are using in [mozilla/eslint-plugin-no-unsanitized/](https://github.com/mozilla/eslint-plugin-no-unsanitized/) as part of its "variable tracing" feature).

**Comment by ioanarusiczki** [comment]
@rpl 

With linter 4.7.0 I used innerHTML, eval, content_security_policy and document.write : same linter warnings as before (AMO dev/stage are still on 4.6.0) except for document.write which on 4.7.0 no longer throws a yellow warning as before but it's been noticed by @willdurand 

Let me know if there's anything else to check.

**Comment by rpl** [comment]
> @rpl
> 
> With linter 4.7.0 I used innerHTML, eval, content_security_policy and document.write : same linter warnings as before (AMO dev/stage are still on 4.6.0) except for document.write which on 4.7.0 no longer throws a yellow warning as before but it's been noticed by @willdurand
> 
> Let me know if there's anything else to check.

It would be good to give it a try also to run the addons-linter on an addon zip file that we know it was triggering the "Out Of Memory" issue and confirm that this version does complete the validation, the most recent one that we got a report for is attached to mozilla/addons#1380

**Comment by ioanarusiczki** [comment]
@rpl The phantom.zip from https://github.com/mozilla/addons/issues/1380 triggered 74 warnings but 0 errors on 4.7.0

![warnings](https://user-images.githubusercontent.com/33448286/151188754-c433ba4f-959c-4c0b-8672-bbce5b9f40ac.png)


With 4.6.0 the addon fails validation 

![fails](https://user-images.githubusercontent.com/33448286/151188451-ec5df320-d0f4-4cef-8a3d-1626b8d41c44.png)

**Comment by rpl** [comment]
> @rpl The phantom.zip from [mozilla/addons#1380](https://github.com/mozilla/addons/issues/1380) triggered 74 warnings but 0 errors on 4.7.0
> ![warnings](https://user-images.githubusercontent.com/33448286/151188754-c433ba4f-959c-4c0b-8672-bbce5b9f40ac.png)
> 
> With 4.6.0 the addon fails validation
> 
> ![fails](https://user-images.githubusercontent.com/33448286/151188451-ec5df320-d0f4-4cef-8a3d-1626b8d41c44.png)

@ioanarusiczki great! thanks for verifying that explicitly :heart:

**Comment by ioanarusiczki** [comment]
@rpl Sure, anytime! 

Then I'll mark this verified on linter 4.7.0
