### ISSUE TITLE
Performance: match vs test

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-linter#4179]
When using `match() as `if` condition where `true/false` is required, `test()` would be at least twice faster.

https://github.com/mozilla/addons-linter/blob/872132e9661ea02423b1226a8926d1c9ce890810/src/scanners/filename.js#L16-L28

If it is acceptable, I can make a PR.

**Comment by willdurand** [comment]
> If it is acceptable, I can make a PR.

I think that's fine. I am not sure why we use `match` here.

**Comment by willdurand** [comment]
Not sure about the `switch` vs `if/else`, please update the function names only.

**Comment by ioanarusiczki** [comment]
@willdurand Is this qa needed? Please add some str
Thanks!

**Comment by willdurand** [comment]
> @willdurand Is this qa needed? Please add some str

As long as the linter continues to behave as expected, there is nothing else. It's an internal refactoring that shouldn't impact anything.

**Comment by ioanarusiczki** [comment]
@willdurand Ok, I'll try to run a set of tests on 4.11.0

**Comment by ioanarusiczki** [comment]
@willdurand 

So far, among samples I used I had the phantom.zip from https://github.com/mozilla/addons-linter/issues/4142#issuecomment-1022305843 

I tried it on -stage, and after a long waiting I get the "    Sorry, we couldn't load your WebExtension." 
On -prod with linter 4.9.0 it passes validation with lots of warnings (as I described in that issue).

**Comment by ioanarusiczki** [comment]
@willdurand I tried various addon uploads and I did not find other issues. 
Marking this verified on AMO stage.
