### ISSUE TITLE
index.js split()

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-linter#4182]
As I was looking at the code, I have noticed areas that could be updated. Here are some general comments.

Example:

https://github.com/mozilla/addons-linter/blob/6d415fa41e4bead3363e330888383e4beb1f3f9f/src/dispensary/index.js#L17-L22

There should be no need to perform `split()` twice.
```js
      for (const hashEntry of this._getCachedHashes()) {
        const [hash, library] = hashEntry.split(' ');

        this._cachedHashes[hash] = library;
      }
 ```
 
 Also, `.split(/\s+/)` might prove to be more robust, and error-free. e.g.
 ```js
      for (const hashEntry of this._getCachedHashes()) {
        const [hash, library] = hashEntry.split(/\s+/);

        this._cachedHashes[hash] = library;
      }
 ```

In case `forEach` is acceptable
 ```js
      this._getCachedHashes().forEach((hashEntry) => {
        const [hash, library] = hashEntry.split(/\s+/);

        this._cachedHashes[hash] = library;
      });
 ```

**Comment by willdurand** [comment]
@erosman would you like to submit a PR?

**Comment by willdurand** [comment]
I don't think it matters much, the return value being an array and the regexp whitespace do make sense. The loop... I don't have an opinion.
