### ISSUE TITLE
Add Bootstrap 5.0.0-5.1.3 Hashes

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-linter#4192]
Note: Added files have not been checked for security issues, however they are accepted in addon reviews.

**Comment by willdurand** [comment]
@wagnerand something for SV?

**Comment by wagnerand** [comment]
Hm, maybe. Someone needs to review that library, understand the changes and asses the review impact.

**Comment by willdurand** [comment]
We'd need to review more than just bootstrap, many libraries we track in dispensary need to be reviewed.
