### ISSUE TITLE
Detect when a package is in a nested directory. 

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-linter#424]
It's easy to package a dir which might result in things like manifest.json being under a directory in the package rather than being at the top level. We should flag that.

**Comment by andymckay** [comment]
It currently throws:
                                                 
![screenshot 2017-05-19 16 52 42](https://cloud.githubusercontent.com/assets/74699/26270870/9dfc6888-3cb3-11e7-8ffa-a9059886d6ca.png)

Along with:

![screenshot 2017-05-19 16 53 21](https://cloud.githubusercontent.com/assets/74699/26270873/b2bf7684-3cb3-11e7-987c-525431ff6c20.png)

Are you suggesting something that says something like "hey no manifest.json found, but we've found one under a sub-directory over here?". Or just updating that message to be more webextension-y focused?

**Comment by ravneette** [comment]
I would like to work on this.

From the code I could get that it is here : https://github.com/mozilla/addons-linter/blob/master/src/linter.js#L274 that a new check needs to be added? 

Which adds a notice if we have a manifest.json file in some sub-directory.

**Comment by kewisch** [comment]
We've discussed this is just a matter of changing the current message to add a note to check that it is not in a subfolder.

**Comment by AlexandraMoga** [comment]
I've tried loading an extension on -dev for which the manifest.json was located in a sub-directory. The message I receive during validation is "No install.rdf or manifest.json found. Add-on missing manifest."

Are the changes not available yet or am I missing something?
