### ISSUE TITLE
manifest.json was not found

### ISSUE THREAD

**Issue by junkycoder** [mozilla/addons-linter#4289]
I am trying to publish our extension (Addon for Mozillas) but the validator shows "manifest.json was not found" error.

## What the directory contains
```bash
firefox-extension
├── arrive.js
├── background.js
├── background.js.map
├── browser-polyfill.js
├── content.css
├── content.js
├── content.js.map
├── icons
│   ├── icon128.png
│   ├── icon16.png
│   └── icon64.png
└── manifest.json
``` 

## How is uploaded zip made
```bash
➜ zip -r -X firefox-extension.zip firefox-extension/*
  adding: firefox-extension/arrive.js (deflated 76%)
  adding: firefox-extension/background.js (deflated 69%)
  adding: firefox-extension/background.js.map (deflated 68%)
  adding: firefox-extension/browser-polyfill.js (deflated 80%)
  adding: firefox-extension/content.css (deflated 72%)
  adding: firefox-extension/content.js (deflated 71%)
  adding: firefox-extension/content.js.map (deflated 75%)
  adding: firefox-extension/icons/ (stored 0%)
  adding: firefox-extension/icons/icon16.png (stored 0%)
  adding: firefox-extension/icons/icon128.png (stored 0%)
  adding: firefox-extension/icons/icon64.png (stored 0%)
  adding: firefox-extension/manifest.json (deflated 78%)
```

## Double check
1. Given `manifest.json` is a valid JSON. 
2. Already submitted to chrome webstore (but they do not have such validation).

## Attachments
1. [heureka-extension.zip](https://github.com/mozilla/addons-linter/files/8590513/heureka-extension.zip)
3. <img width="1001" alt="Snímek obrazovky 2022-04-29 v 13 47 59" src="https://user-images.githubusercontent.com/1243903/165938632-2a2ea13b-3555-4f5d-8d22-85038e5a59c6.png">

## Questions
1. Am I missing something?
2. Is this the right place to ask?
4. Whats wrong with uploaded zip?

**Comment by willdurand** [comment]
>     1. Am I missing something?

I think your ZIP file contains a directory instead of just the files inside this directory. Try this:

```
$ cd firefox-extension
$ zip -r -X ../firefox-extension.zip *
```
 
>     2. Is this the right place to ask?

Yes.

>     3. Whats wrong with uploaded zip?

Nothing.

**Comment by junkycoder** [comment]
> > 1. Am I missing something?
> 
> I think your ZIP file contains a directory instead of just the files inside this directory. Try this:
> 
> ```
> $ cd firefox-extension
> $ zip -r -X ../firefox-extension.zip *
> ```
> 
> > 2. Is this the right place to ask?
> 
> Yes.
> 
> > 3. Whats wrong with uploaded zip?
> 
> Nothing.

Wow, that was speed! You are right, obviously, and I thanks you a lot.
