### ISSUE TITLE
Require the addon id to be included in the manifest for manifest_version 3 extensions

### ISSUE THREAD

**Issue by rpl** [mozilla/addons-linter#4303]
As part of [Bug 1755872 - Make add-on ID mandatory in the manifest for MV3](https://bugzilla.mozilla.org/show_bug.cgi?id=1755872) triage we agreed to look into enforcing the manifest of manifest_version 3 extension to explicitly include the addon id in the manifest at submission time before being signed.

After we have enforced it for all signed extension we may consider what other issues we still have and if additional changes on the Firefox side would help with fill those gaps.

**Comment by ioanarusiczki** [comment]
@willdurand 
I've tested today on addons-linter 5.3.0 with addon samples (from prod) and a dictionary. 
- I added into manifest.json "manifest_version": 3
- used "id" under "applications" or  "browser_specific_settings" 

With 'addons-linter sideberry.xpi  --max-manifest-version=3':

This is the error message when there's no id in the manifest:

![error message](https://user-images.githubusercontent.com/33448286/168610337-4bbf2692-2c15-43fd-a413-91350d4147f0.png)

When an invalid id format is used I get the same error messages as before:
![invalid id](https://user-images.githubusercontent.com/33448286/168611853-cfd3de3e-ea41-4b91-8daa-02a8a2a37530.png)

+2 erros that have been detailed into https://github.com/mozilla/addons-linter/issues/3843#issuecomment-892687526 when there's MV3 with MV2 specific keys.

I'm going to complete all my testing tomorrow, check themes and lang packs too. So far it looks good to me.

**Comment by ioanarusiczki** [comment]
@willdurand 

- All addon types require an id when manifest version is 3. 

- I've noticed on AMO dev an error that it not thrown by the linter locally, so it must be from server:

![error from server](https://user-images.githubusercontent.com/33448286/168816258-7c649e6d-f494-4ae3-ba29-3ca6bb5c250e.png)

Using the CLI `addons-linter langpack.xpi  --max-manifest-version=4` I will not get the error above, I hope that's alright.

**Comment by willdurand** [comment]
> * I've noticed on AMO dev an error that it not thrown by the linter locally when the MV > 3, so it must be from server:

@ioanarusiczki so you essentially have a `manifest.json` with `"manifest_version": 4` in it?

> Using the CLI `addons-linter langpack.xpi --max-manifest-version=4` I will not get the error above, I hope that's alright.

Yeah, by default the max manifest version is `2`. It should be `3` [when the `enable-mv3-submissions` waffle flag is enabled](https://github.com/mozilla/addons-server/blob/52607ebaa342026280d54b9f3bece404a4369073/src/olympia/devhub/tasks.py#L451).

Do you know the state of this waffle flag on AMO -dev?

Also, in theory, you should be passing `--max-manifest-version=4` but `--max-manifest-version=3`.

**Comment by ioanarusiczki** [comment]
> so you essentially have a manifest.json with "manifest_version": 4 in it?

@willdurand 

Yes, I have it inside manifest.json. 

>Do you know the state of this waffle flag on AMO -dev? 

I checked it today and the waffle is enabled on dev. Disabled on stage.

**Comment by willdurand** [comment]
Ok, thanks.

So yes please try with `--max-manifest-version=3` locally (I edited my comment above). If that works locally, that should output the same message as in your screenshot above (which is expected).
