### ISSUE TITLE
Detect and report permissions and properties requiring a privileged signature

### ISSUE THREAD

**Issue by rpl** [mozilla/addons-linter#4306]
The changes to the Firefox JSONSchema data in work as part of [Bug 1739114 - Gate each privileged extension feature by a webextension permission](https://bugzilla.mozilla.org/show_bug.cgi?id=1739114) will allow the addons-linter ManifestJSONParser to detect if an extension is including a permission or manifest property that requires a privileged signature.

To make it easier to detect when an addon is being submitted to be signed by AMO while it should have been signed with a privileged signature (and then submitted to AMO as already signed to be discoverable and listed on AMO) we plan to:

- make use of the updates to the schema to allow src/schema/validator to detect and collect linting results for the permissions and properties that are marked as privileged in the schema data
- report the linting results related to privileged permissions and properties as:
  - blocking linting errors if the addon isn't already signed
  - non-blocking linting warning if the addon is already signed

(detecting the "already signed" status by checking for the presence of the signatures files in the add-on assets, similarly to how the `ALREADY_SIGNED` rule detects it).

**Comment by wagnerand** [comment]
See also https://github.com/mozilla/addons-server/issues/18254

**Comment by willdurand** [comment]
> To make it easier to detect when an addon is being submitted to be signed by AMO while it should have been signed with a privileged signature (and then submitted to AMO as already signed to be discoverable and listed on AMO) we plan to:

Note that this is also a requirement for Shipit as per https://github.com/mozilla-extensions/xpi-manifest/issues/136

**Comment by ioanarusiczki** [comment]
@willdurand

I tested locally with linter 5.5.0, I added permissions from https://bugzilla.mozilla.org/show_bug.cgi?id=1739114#c5 into a standard add-on (with no privileged signature), and these are the results:

- for activityLog, mozillaAddons, networkStatus, normandyAddonStudy, telemetry, urlbar ->

![screen1](https://user-images.githubusercontent.com/33448286/169833496-ebbb9da9-42ad-4161-ac8b-203c24ec2beb.png)


-adding the permissions above, validation will fail with a red warning when `--privileged` is passed into the CLI

![needsmozilladdons](https://user-images.githubusercontent.com/33448286/169834139-4c45f369-84f4-4e14-a78f-a07ce22f9a94.png)

- validation will pass with no red warnings if mozillaAddons is also added together with the other permissions with `--privileged`

![no errors](https://user-images.githubusercontent.com/33448286/169834477-bd65e9b1-97b8-4e34-a069-e9b4899729fa.png)

- with `geckoViewAddons` and `nativeMessagingFromContent` I only  get a yellow linter warning:
"/permissions: Invalid permissions See https://mzl.la/1R1n1t0 (MDN Docs) for more information.   manifest.json"geckoViewAddons" at 6." 

- `nativeMessaging` passes with no errors or warning but that should be fine (reading the comments)
- I have an old sample of what I think it is a privileged signature addon, these are the linter results: 

![priviliged addon](https://user-images.githubusercontent.com/33448286/169835111-2f33839b-ea3d-4b41-aaa7-3ae18d867e51.png)

**Comment by willdurand** [comment]
> for `activityLog`, `mozillaAddons`, `networkStatus`, `normandyAddonStudy`, `telemetry`, `urlbar` ->

Expected since we don't want privileged permissions in regular extensions.

> -adding the permissions above, validation will fail with a red warning when `--privileged` is passed into the CLI

Excellent, `mozillaAddons` is indeed required.

> validation will pass with no red warnings if `mozillaAddons` is also added together with the other permissions with `--privileged`

Excellent.

> with geckoViewAddons and nativeMessagingFromContent I only get a yellow linter warning:
"/permissions: Invalid permissions See [mzl.la/1R1n1t0](https://mzl.la/1R1n1t0) (MDN Docs) for more information. manifest.json"geckoViewAddons" at 6."
>
> nativeMessaging passes with no errors or warning but that should be fine (reading the comments)

Hum, interesting. @rpl WDYT?

> * I have an old sample of what I think it is a privileged signature addon, these are the linter results:

Yes, when the extension has a signature already, we don't emit errors about privileged stuff.

**Comment by rpl** [comment]
> > with geckoViewAddons and nativeMessagingFromContent I only get a yellow linter warning:
> > "/permissions: Invalid permissions See [mzl.la/1R1n1t0](https://mzl.la/1R1n1t0) (MDN Docs) for more information. manifest.json"geckoViewAddons" at 6."
> > nativeMessaging passes with no errors or warning but that should be fine (reading the comments)
> 
> Hum, interesting. @rpl WDYT?

The schema import script in the addons-linter doesn't actually import any of the mobile-schema and so those prefs are unknown from an addons-linter perspective (and that should have been the case also before the changes introduced in #4307.

Besides that, from what I recall geckoViewAddons and nativeMessagingFromContent are both privileged permissions available only on GeckoView builds because they are being used in GeckoView's AndroidComponent and Fenix as builtins (and so not actually signed), and so there shouldn't be any signed extension currently using them outside of that small set of builtins addons.

I wouldn't exclude completely that we may consider special case these GeckoView-only permission if we would ever need a different behavior for those prefs, but for now it should be ok to don't special case than and leave the current behavior unchanged.

**Comment by ioanarusiczki** [comment]
@rpl @willdurand In that case I can mark this verified by qa, because I don't think there's anything else I could do.
