### ISSUE TITLE
Mute error about `update_url` when `--privileged` is specified

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-linter#4333]
I just noticed that the linter emits an error when `update_url` is used in a privileged extension (see: [TaskCluster `live.log` for the remote-settings-devtools extension](https://firefox-ci-tc.services.mozilla.com/tasks/QORvbwUaQwi0TGYFNcZPng/runs/0/logs/public/logs/live.log)).

I believe this is OK because we cannot determine whether the extension will be listed or unlisted so we should disable this message when `--privileged` is passed.

**Comment by ioanarusiczki** [comment]
@willdurand 

1. I added the update_url into a manifest for a standard extension plus ""mozillaAddons" permission:
- without --privileged flag, 2 red errors are triggered CODE MANIFEST_PERMISSIONS_PRIVILEGED and MANIFEST_UPDATE_URL
- with --privileged flag, only one yellow warning is triggered ->  MANIFEST_UPDATE_URL (which used to be red without the flag)

2. A Mozilla signed extension:
- without --privileged flag, the update_url throws an error.
- with  --privileged flag, the update_url becomes a yellow warning. 

I believe this is the expected result.
