### ISSUE TITLE
Can not upload to server with new version

### ISSUE THREAD

**Issue by timothymarois** [mozilla/addons-linter#4340]
![Screen Shot 2022-05-23 at 2 22 56 PM](https://user-images.githubusercontent.com/2489333/169882924-a41e0c6d-ff21-4bf6-a847-68fa1ff18b70.png)

Server is not responding after uploading

**Comment by Rob--W** [comment]
Is this still happening?

What is the package that you are trying to upload?

**Comment by timothymarois** [comment]
Looks like it was resolved. But was frustrating error. Probably some server update.
