### ISSUE TITLE
Make hidden and action mutually exclusive

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-linter#4432]
Hidden extensions should ideally not have any browser actions because it is a bit odd to not see the extension anywhere (e.g., not in about:addons) but still see a button in the toolbar and no way to remove the extension for instance. FTR, extensions can only be "hidden" if they are _privileged_ extensions. That isn't possible for "regular" extensions.

We currently don't have any privileged extensions with browser actions but there is no restriction. We are going to [make that happen in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1781998) but it would be good to emit an error too.

**Comment by ioanarusiczki** [comment]
@rpl @willdurand 

I tried with linter version 5.14.0 using a mozilla-signed extension to add browswer_action and page_action into manifest.json.

 I didn't get an error with my testing sample. I'm attaching it, maybe I'm doing something wrong? 

[test2.zip](https://github.com/mozilla/addons-linter/files/9351134/test2.zip)

**Comment by willdurand** [comment]
This is only for privileged extensions with `hidden: true` in the `manifest.json` file and one (or all) of `browser_action`, `page_action` and `action`.

**Comment by ioanarusiczki** [comment]
@willdurand 

I get the error message locally while testing it with --privileged flag and "hidden":true. Here's action property used in MV3:

![actionmv3](https://user-images.githubusercontent.com/33448286/185057605-484e6893-b961-4f41-ade3-b11c33304943.png)

I've also noticed that on the testing servers (AMO dev) this error is not available. Is this expected? Maybe these addons are uploaded with web-ext (It's just an assumption).

**Comment by willdurand** [comment]
> I've also noticed that on the testing servers (AMO dev) this error is not available. Is this expected? Maybe these addons are uploaded with web-ext (It's just an assumption).

Yes, it is expected I think. The linter shouldn't be executed with the `--privileged` flag on AMO

**Comment by willdurand** [comment]
> I get the error message locally while testing it with --privileged flag and "hidden":true. Here's action property used in MV3:

That looks good to me.
