### ISSUE TITLE
Verify that locale directories contain a messages.json file

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-linter#4504]
### Describe the problem and steps to reproduce it:

1. Prepare a _valid_ XPI file that also contains a directory with locales, and a `default_locale` in the manifest. The `_locales` dir should also contain something like this:

```
_locales/.github/empty.txt
```

2. `addons-linter /path/to/xpi/created/above/file.xpi`

### What happened?

No error.

### What did you expect to happen?

An error about the `_locales/.github` directory that should have a `messages.json` file.

### Anything else we should know?

(Please include screenshots and any relevant files.)

**Comment by ioanarusiczki** [comment]
@willdurand 

I verified this on addons-linter 5.17.0 -> am error message is displayed

![red error message](https://user-images.githubusercontent.com/33448286/195337271-3a32ade1-843c-434f-9cd9-de8dd8d052f4.png)
