### ISSUE TITLE
Get to parity with amo-validator on Web Extensions

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-linter#452]
We should figure out more what this means, but we want to use this for Web Extensions going forward.

(Think of this like a reminder/tracking bug.)

**Comment by muffinresearch** [comment]
Added the needs-info flag as we need to document the list of things that we need to do to meet the parity with the amo-validator here as a checklist or as bugs that relate to this one.

**Comment by tofumatt** [comment]
As discussed at the JS validator meeting today, we should label all bugs that relate to this so we know how close it is to completion; it (and possibly #400) are our blockers to getting it validating WebExtensions on prod (at least side-by-side with the existing amo-validator).

**Comment by EnTeQuAk** [comment]
Two things I found so far are #557 and #556 which are required for WebExtensions too.

**Comment by EnTeQuAk** [comment]
I think most of the issues here are already solved and the linter already validates quite a bunch more than the validator does. Should we maybe close this and continue issue-by-issue?

**Comment by andymckay** [comment]
Agreed.
