### ISSUE TITLE
Add deprecating warning for `applications` key in manifest in MV2, error in MV3

### ISSUE THREAD

**Issue by diox** [mozilla/addons-linter#4533]
The `applications` key in the manifest is an old synonym for `browser_specific_settings`. The latter is supported by other browsers and should be used instead - in fact we don't even document `applications` anymore.

Let's deprecate `applications` in the linter, warning about it in MV2, erroring in MV3 so that we don't have to maintain those 2 different paths.

**Comment by ioanarusiczki** [comment]
@diox 
@willdurand 

I verified this on linter 5.19.0 -> I get a warning for MV2 and an error for MV3

![warningforMV2](https://user-images.githubusercontent.com/33448286/198013342-141faf6f-0073-44d8-9e91-e85a1f3802a3.png)

![errorsinMV3](https://user-images.githubusercontent.com/33448286/198013371-a2ff89ec-2613-4b8e-9f27-4087d2250b03.png)
