### ISSUE TITLE
Error on submission: `Empty language directory`

### ISSUE THREAD

**Issue by jrie** [mozilla/addons-linter#4552]
### Describe the problem and steps to reproduce it:

Try to upload a .zip of my addon for submission. I currently (still) make use of `manifest.json` in version 2.

### What happened?

I receive the error `"Empty language directory"` and displaying in detail `messages.json file missing in "_locales/en"`
But the file `messages.json` is included in `_locales/en` folder.

### What did you expect to happen?

There should be no error shown and the submitted version should be added, and the add-on updated.

**Comment by willdurand** [comment]
@jrie do you have files other than a `messages.json` one in `_locales/en` by chance? If so, this is #4535 and it's going to be fixed later this week (on Thursday evening Berlin time)

**Comment by jrie** [comment]
@willdurand , that is indeed the case. I do host a language related help file in the `_locales/en` folder. Thank you for the quick response. So I wait for submission until the fix is landed.

**Comment by willdurand** [comment]
Thanks. I am going to close this issue then. Sorry for the inconvenience!
