### ISSUE TITLE
Use the online validator until this one is ready

### ISSUE THREAD

**Issue by arieljannai** [mozilla/addons-linter#460]
Hi,

I think it might be useful to wrap the access to the [online validator](https://addons.mozilla.org/en-US/developers/addon/validate) to get validation from the command line.
It could be useful, and can be replaced seamlessly when the addons-linter is ready.

What do you think about it?

**Comment by muffinresearch** [comment]
I would imagine something like would be best done as a separate project rather than as part of this.
