### ISSUE TITLE
Min version for proxy permission

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-linter#4631]
I came arccos the following error. I already have an addon with `proxy` permission and `"strict_min_version": "63.0"` that is working fine.

MDN [proxy](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/proxy) document doesn't mention min version 91 either.

> Error: The "proxy" permission requires "strict_min_version" to be set to "91.1.0" or above. Please update your manifest.json version to specify a minimum Firefox version.

![Screenshot 2022-12-19 at 18-14-35 Validation Results for geo zip Developer Hub Add-ons for Firefox](https://user-images.githubusercontent.com/6458876/208453007-931d82c3-3600-4c9a-9782-2dc410218220.png)

**Comment by willdurand** [comment]
Yeah, that is expected, see: https://blog.mozilla.org/security/2021/10/25/securing-the-proxy-api-for-firefox-add-ons/

**Comment by erosman** [comment]
Thanks for the clarification. :+1:
