### ISSUE TITLE
Switch to a proper rdf parser

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-linter#464]
We only need to parse install.rdf file for dictionaries and langpacks but it would be a good idea to use a better parser.

**Comment by muffinresearch** [comment]
I'm looking to use rdf-ext's xml parser but immediately it's blowing up on unqualified about attrs - I've filed an issue here: https://github.com/rdf-ext/rdf-parser-rdfxml/issues/1

Another issue is that with a quick patch to fix the previous problem parsing a basic install.rdf example the subjects are coming up as blank nodes. This appears to disagree with the output of rdflib (python).

**Comment by EnTeQuAk** [comment]
I'm closing this as this is not needed anymore.
