### ISSUE TITLE
'Duplicate add-on ID found' error when uploading new add-on again after deleting the previous submission

### ISSUE THREAD

**Issue by DukeLuo** [mozilla/addons-linter#4672]
### Describe the problem and steps to reproduce it:
I deleted my submission of a new add-on in 'Manage My Submissions' section and later I uploaded the same new add-on again. It saied there is a 'Duplicate add-on ID found' error. 
<img width="1121" alt="image" src="https://user-images.githubusercontent.com/26000789/211577929-70aef5c8-6ce2-49cd-adac-8b37b4a17430.png">

But when I see the full validation report, there is no such error.
<img width="1091" alt="image" src="https://user-images.githubusercontent.com/26000789/211578294-d340284a-b512-4812-b5b4-dce4c2b642e0.png">

### What happened?
There is a 'Duplicate add-on ID found' error. 

### What did you expect to happen?
No error and upload the new add-on successfully.

### Anything else we should know?
There is no add-on submission  in 'Manage My Submissions' section
<img width="672" alt="image" src="https://user-images.githubusercontent.com/26000789/211579394-11dabe2f-1448-4188-b55d-2a6c1e0abc39.png">

**Comment by diox** [comment]
It's tricky because it's not a linting issue. There is nothing wrong with the add-on itself, it's purely because you're trying to upload it to AMO. I agree maybe we could make it more obvious in the standadlone validator on AMO though.
