### ISSUE TITLE
Invalid file name in archive: _locales\en\messages.json

### ISSUE THREAD

**Issue by ganohr** [mozilla/addons-linter#4673]
### Describe the problem and steps to reproduce it:

Hello.
I am the developer of the following addon:
https://addons.mozilla.org/en-GB/firefox/addon/ramot/

I created a new version and did a check to update.
https://addons.mozilla.org/en-GB/developers/addon/ramot/versions/submit/

### What happened?

When I checked the addon for updates, I got the following error message and was unable to register the updates.
`Invalid file name in archive: _locales\en\messages.json`

This addon works fine on Firefox.
Of course, the localization works well too.

* This addon zipped by Windows 10(PowerShell)

### What did you expect to happen?

I want the check to pass so I can register the addon.

### Anything else we should know?

[RamoT-0.0.2.zip](https://github.com/mozilla/addons-linter/files/10398466/RamoT-0.0.2.zip)

Thanks.

**Comment by Rob--W** [comment]
The archive uses `\` slashes, but `/` slashes are expected.

It looks like Powershell cannot be configured to use the correct slash, according to https://superuser.com/questions/1678786/is-there-a-way-to-make-powershell-use-forward-slashes-instead-of-backslashes-for

So I suggest to use a different tool to create the zip file, e.g. `7z` - https://www.7-zip.org/
Alternatively, use the `web-ext build` command to generate the zip file; see https://extensionworkshop.com/documentation/develop/getting-started-with-web-ext/#packaging-your-extension . To install `web-ext`, see https://extensionworkshop.com/documentation/develop/getting-started-with-web-ext

**Comment by ganohr** [comment]
Thank you for your reply.

As I expected, the problem was the format of the ZIP I created with PowerShell.
Thanks for letting me know.

However, isn't it strange that whether registration is possible or not depends on the format of the ZIP?

Also, since I build extensions for Chrome/Edge/Firefox at once with shared resources, I need to use an external ZIP tool.
I think PS ZIP is used a lot by Windows developers.

This time, I thought that there was a high possibility that there was a problem with the check tool, so I reported it just in case.

thank you.

**Comment by Rob--W** [comment]
The PS Zip tool is behaving incorrectly here. Zip files should use forward slashes as path separators, not backslashes, according to the [specification of the zip file format](https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT):

>4.4.17.1 The name of the file, with optional relative path. The path stored MUST NOT contain a drive or device letter, or a leading slash. All slashes MUST be forward slashes '/' as opposed to backwards slashes '\\' for compatibility with Amiga and UNIX file systems etc. If input came from standard input, there is no file name field.

I'll close this issue since it's not something that we're going to change; it was already wontfixed in #1426 and https://github.com/mozilla/addons/issues/769
