### ISSUE TITLE
Tests print out noise to console

### ISSUE THREAD

**Issue by bershanskiy** [mozilla/addons-linter#4705]
### Describe the problem and steps to reproduce it:

Run tests (`npm run build` and `npm run test`)

### What happened?

Tests print out errors like which say "Selected file(s) not found" and various "Validation Summary" stuff.

### What did you expect to happen?

All tests pass without noisy console logs.

### Anything else we should know?

N/A

**Comment by willdurand** [comment]
I am not sure about that tbh, if something goes wrong, it'd be good to have all logs to debug/pin-point the problem(s).

**Comment by bershanskiy** [comment]
Most other tests silence the output as well (e.g., all other occurrences of `addonLinter.print = sinon.stub();`). However, I understand that there could be a difference between these tests which I'm not seeing.

**Comment by willdurand** [comment]
The previous occurrences were likely added before my time. This is a lot of boilerplate to write in each test case OR we need to make changes to have helper functions to configure a stub once for all. Hiding output is usually done by Jest automagically (although sometimes it does not do it and I am not sure why). That being said, it is quite useful to have all the information logged, especially when a test case breaks.
