### ISSUE TITLE
Make sure "preview" in BCD versions is supported (or does not break everything)

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-linter#4713]
This is something we discussed at our stand-up: we will introduce "preview" values in BCD for features that are behind pref (or nightly only). We should make sure that this won't break the linter.

**Comment by Rob--W** [comment]
The linter only cares about `version_added` here:

- https://github.com/mozilla/addons-linter/blob/2158835a17500589f8ea361473474349d0200391/src/utils.js#L379-L410
- https://github.com/mozilla/addons-linter/blob/2158835a17500589f8ea361473474349d0200391/src/parsers/manifestjson.js#L150

and the unit tests for these files:
- https://github.com/mozilla/addons-linter/blob/2158835a17500589f8ea361473474349d0200391/tests/unit/test.utils.js
- https://github.com/mozilla/addons-linter/blob/2158835a17500589f8ea361473474349d0200391/tests/unit/parsers/test.manifestjson.js

**Comment by willdurand** [comment]
Nope, sorry. No need to verify anything here.
