### ISSUE TITLE
"/background" is in an unsupported format.

### ISSUE THREAD

**Issue by julian-jian** [mozilla/addons-linter#4746]
I am trying to publish our extension (Addon for Mozillas) but the validator shows ""/background" is in an unsupported format." error.

Attachments
![企业微信截图_20230309151529](https://user-images.githubusercontent.com/45332525/223948311-bf1c6dba-230c-4ab3-91e0-e112637772d5.png)
![企业微信截图_20230309152251](https://user-images.githubusercontent.com/45332525/223949772-412ac546-035b-4bd2-8975-a66669111696.png)

**Comment by willdurand** [comment]
`background.service_worker` isn't supported on Firefox. Please see: https://extensionworkshop.com/documentation/develop/manifest-v3-migration-guide/
