### ISSUE TITLE
Tesseract's WASM file too big to process

### ISSUE THREAD

**Issue by wrbl606** [mozilla/addons-linter#4748]
### Describe the problem and steps to reproduce it:
Hello, I'm writing the [what-to-click](https://github.com/wrbl606/what-to-click/tree/ff521792b3bee70389782cdc3ed024eec9f3b5f8) extension. I've added the [tesseract.js](https://github.com/naptha/tesseract.js) library locally for OCR functionality, which works fine, but it caused Firefox Addons linter to fail.

### What happened?
Tesseract uses WebAssembly to speed up the process of analysing images. This comes with a file size overhead, which is so great, that I can no longer upload my extension to the Developer Hub:

<img width="967" alt="image" src="https://user-images.githubusercontent.com/15102395/224568507-d7307209-dad5-42e0-a1c8-cc0c89381c1b.png">

<img width="967" alt="image" src="https://user-images.githubusercontent.com/15102395/224568544-df8760e1-05e9-4e9a-a877-3d5781f36e75.png">

The linter suggestion is valid, I would very much like to split the file into smaller ones (the enourmous filesize comes from a blob included in it), but I don't see a way of doing this because of the way the file is handled -- it's automatically loaded by  tesseract, not the extension code, so `import/export` directives doesn't work and I also doesn't have the `browser` object available. The blob is also critical to be included in the file as because of [this issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1294996), `importScripts` is not available.

### What did you expect to happen?

I expected to be able to submit the next version of my extension as a Firefox addon.

### Anything else we should know?

The simplest solution would be to bump the singular file size limit to 5MB, as the problematic file is 4.8MB big, and such limit bump shouldn't cause overload on linter servers. However, if you see any option to reduce the filesize by any means I'm certinly open to it.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDLINT-5)

**Comment by lmk123** [comment]
I'm having the same problem.

I have developed an extension to recognize text in images, which also uses tesseract.js. My extension uploads to the chrome extension webstore fine, but I have this problem when uploading in firefox add-ons.

**Comment by lmk123** [comment]
I found a workaround that can solve this problem, hope it can help you.

https://github.com/naptha/tesseract.js/issues/732#issuecomment-1506373701
