### ISSUE TITLE
uploading extension problem "manifest.json was not found"... HElP

### ISSUE THREAD

**Issue by JustmeHello** [mozilla/addons-linter#4810]
### Describe the problem and steps to reproduce it:

while uploading a new extension ...it keeps saying:
"Your add-on failed validation with 1 error.

    manifest.json was not found" ...the manifest.js is included

### Anything else we should know?

(Please include screenshots and any relevant files.)

**Comment by willdurand** [comment]
That sometimes happens when the zip/xpi file contains a directory that contains the source files and the manifest. The `manifest.json` should be listed as a direct child of the archive.
