### ISSUE TITLE
Some localized strings are not extracted (and therefore not localized)

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-linter#4825]
We use `oneLine` for some of our localized strings but that breaks the extraction task. This isn't exactly a new issue (see: https://github.com/mozilla/addons-frontend/issues/2108) but we never noticed that we had the same problem in this repo. Let's fix it.

For QA: we expect more strings to be localized in the near future (e.g. in Italian). We can verify that by running the linter with a `LC_ALL` env var:

```
LC_ALL=it_IT addons-linter addon.xpi
```

**Comment by ioanarusiczki** [comment]
@willdurand 

I tried on linter 6.1.0 with your example, it says LC_ALL is not recognized 

![6 1 0](https://user-images.githubusercontent.com/33448286/235087328-5942742d-218e-47b4-b6ee-665161a7a86a.png)

If I reverse it and run it, I get the validation summary 

![reversed](https://user-images.githubusercontent.com/33448286/235088086-36108f9e-fa96-4aa7-a0fc-47b5a684dcb9.png)

**Comment by ioanarusiczki** [comment]
@willdurand Sorry I did not check the release date of the linter, the current version needs an update.

**Comment by willdurand** [comment]
I think, in this case, it does not matter since the `LC_ALL` env var is probably not recognized on Windows...

**Comment by willdurand** [comment]
Indeed... I can reproduce too. That does not look too great :(

**Comment by willdurand** [comment]
@ioanarusiczki addons-linter v6.3.1 should fix this problem (hopefully)

**Comment by willdurand** [comment]
We might have another bug  here[^1] but at least we can verify this issue with:

```
LC_ALL=it addons-linter /path/to/some/extension
```

**Comment by ioanarusiczki** [comment]
@willdurand 

I did some research, so on Windows I must set the env variable with `set LC_ALL=de` 

![windowsenv](https://user-images.githubusercontent.com/33448286/236415117-a42d09ba-8a2a-4c17-887f-d8ce96809bde.png)

**Comment by ioanarusiczki** [comment]
@willdurand About your [comment ](https://github.com/mozilla/addons-linter/issues/4825#issuecomment-1534605998 )

When I tried with LC_ALL=pt_PT or LC_ALL=pt_BR it returned translated strings. pt_PT or pt_BR dialects are also available on AMO

AMO does not have `it_IT` , (it's just `it`) , or `de_DE` so perhaps that's why it doesn't work when I use them in that format.
