### ISSUE TITLE
[L10n]: String with localizability issue

### ISSUE THREAD

**Issue by peiying2** [mozilla/addons-linter#4836]
### Describe the problem and steps to reproduce it:

Community reported that there are issues with the placeholder and the structure of the string: 
1). 
`https://pontoon.mozilla.org/he/amo-linter/all-resources/?string=279109`
- I think this string should be split into 2 sentences?

`- The placeholder here should have been with %, not $:`
2). 
`https://pontoon.mozilla.org/zh-TW/amo-linter/LC_MESSAGES/messages.po/?string=279091`
- The closing at the end of the string is not needed: `...Please avoid using 'eval' and the 'Function' constructor when at all possible.'`

**Comment by peiying2** [comment]
@willdurand thank you for the quick response. I just got another report. I added to the Description above. It should be a simple fix.

**Comment by ioanarusiczki** [comment]
@willdurand I'm not sure how to test this.  I see 2 messages [here](https://github.com/mozilla/addons-linter/pull/4837/commits/2cc48d1ed0eb3d0119c1b28f2e7e06e91b10fc82)  

Are those that need to be checked in English ?

**Comment by willdurand** [comment]
> Are those that need to be checked in English ?

Yes. That should be more than enough.

**Comment by AlexandraMoga** [comment]
I've verified this issue on AMO -dev and the two strings seem to be fixed now:

CSS issue:

[before]
![image](https://user-images.githubusercontent.com/31961530/235912742-eeb605bb-3b37-43b0-99af-08f52ed9e4bb.png)

[after]
![image](https://user-images.githubusercontent.com/31961530/235912663-20ddeecd-84aa-4d0b-b1c6-f88ad92e7984.png)

EVAL issue:

[before]
![image](https://user-images.githubusercontent.com/31961530/235913061-0ecf13fe-3ae0-434b-b51a-fca95494f8b7.png)

[after]
![image](https://user-images.githubusercontent.com/31961530/235913262-2e479d31-22bc-4cce-8bfc-7d7be4814ed3.png)
