### ISSUE TITLE
A notice should be displayed when strict_max_version is specified for gecko_android 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-linter#4855]
From https://github.com/mozilla/addons-linter/issues/4780#issuecomment-1532855396

There's a difference in notices for this case: 

 `       "gecko": {
        "id": "testdummy6@test",
	"strict_min_version": "110.0",
	"strict_max_version":"100.0"
        } ` 

Here I get a notice:  "strict_max_version" not required.

For 	 `"browser_specific_settings": {
        "gecko": {
            "id": "testdummy6@test"
        } ,
		"gecko_android": {
            "strict_min_version": "113.0",
	   "strict_max_version":"100.0"
        }
    }`

There's no notice.

Expected result:
A notice should be displayed for gecko_android too when strict_max_version is used in manifest.json of an extension.

**Comment by ioanarusiczki** [comment]
@willdurand Moved the milestone.

**Comment by ioanarusiczki** [comment]
@willdurand The fix is on the next linter version. Just let me know when it lands. Thanks!

**Comment by willdurand** [comment]
Please see: https://github.com/mozilla/addons-linter/releases/tag/6.5.0

**Comment by ioanarusiczki** [comment]
@willdurand 

Yes, this has been fixed on linter 6.5.0

I attach the screenshot -> before and after 

![verified](https://github.com/mozilla/addons-linter/assets/33448286/161a87ab-abad-4ad2-bdc0-94b4cfdd81c6)
