### ISSUE TITLE
Better validate the `name` field in the manifest

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-linter#4904]
See: https://github.com/mozilla/addons-server/issues/20785

**Comment by ioanarusiczki** [comment]
@willdurand  I don't see a tag for 6.8.0 so let me know when I can check this. 
Thanks!

**Comment by ioanarusiczki** [comment]
@willdurand 

- When whitespaces are used in manifest.json for name or they're added before or after the name -> an error is raised

- When I used one char for the name but without using whitespaces , let's say "name": "1" , this error is thrown together with "/name" must NOT have fewer than 2 " . Submission is not valid anyway but whitespaces haven't been used either, so let me know if I should file this edge case.

![2 errors](https://github.com/mozilla/addons-linter/assets/33448286/b9602f34-27df-4470-bb80-ba8a1be98b53)
