### ISSUE TITLE
Firefox 117 schema

### ISSUE THREAD

**Issue by rpl** [mozilla/addons-linter#4994]
This issue is about import updated WebExtensions API JSONSchema files from Firefox 117.

**Comment by rpl** [comment]
This issue is likely to be closed without a pull request, there isn't at the moment any schema data changes to import in 117 beta and unlikely to change before the end of the 117 beta cycle.

The following is the output of the import script after executing it today:

```
$ ./scripts/download-import-schema-from-gecko-dev beta
Partial cloning gecko-dev branch beta
Cloning into '/tmp/gecko-dev--partial-107762-yVAw7S11oq40'...
Partial clone completed

Importing WebExtensions API JSONSchema data from Gecko 117.0b5

Schema changes diff:

No changes to the schema data
```

**Comment by rpl** [comment]
I executed the schema data import script once more today, and as expected there are still no changes to API schemas introduced in 117.0b9. At this point we can close this issue with no pull request.

@willdurand Do we prefer to close it as done (where done is "no action needed") or as "not planned" (considering it as a wontfix because of no data to be imported)?

**Comment by willdurand** [comment]
Not sure the distinction matters here, let's just close it because there is no action needed.
