### ISSUE TITLE
Explore es6 gettext/translating template string.

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-linter#50]
So that we can do easy substitutions.

**Comment by dmatteo** [comment]
Did you learned something worth sharing?

**Comment by tofumatt** [comment]
Nothing yet, we haven't really looked at this since early in the project. Not sure when we'd get to explore it, but at least output is already being output through a no-op `gettext` function which could be replaced by a real one in the future.

**Comment by dmatteo** [comment]
There's a bug open on gettext, but nobody even replied...

http://savannah.gnu.org/bugs/index.php?46111

**Comment by muffinresearch** [comment]
I think this is a wontfix since we have no plans to localise this project at the moment.
