### ISSUE TITLE
Suggest dropping `incognito: "split"` when present in manifest.json

### ISSUE THREAD

**Issue by Rob--W** [mozilla/addons-linter#5261]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1876924 for context.

`incognito: "split"` is not supported in Firefox, only in Chrome.

In Firefox, `incognito: "spanning"` is the only supported value that enables users to opt in to allowing extensions access in private browsing mode. The only other supported value is `incognito: "not_allowed"`, which prevents users from using an extension in private browsing mode.

In bug 1876924, I'm patching Firefox to allow Firefox to load extensions even when `incognito: "split"` is used in the manifest, with a fallback to "not_allowed"`. Extensions that do not rely on Chrome's "split" mode should remove the key from the manifest (or set the value to `incognito: "spanning"`). This enables users to use the extension in private browsing mode, if they opt in to it.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDLINT-528)

**Comment by ioanarusiczki** [comment]
I tried with "incognito":"split"

On AMO dev with linter 6.29.0

![warning on AMO dev](https://github.com/mozilla/addons-linter/assets/33448286/9068b97d-4fb6-4205-a503-3fe8f9bf70e6)

With linter 6.28.0

![error with amo stage](https://github.com/mozilla/addons-linter/assets/33448286/bd54a8b7-9df6-4290-9b20-4cea8a30fa59)



The [other 2 allowed values](https://developer.chrome.com/docs/extensions/reference/manifest#incognito) -> no problems , extension passed validation. 

With other values than allowed such as "incognito":"incognito" -> error "/incognito" must be equal to one of the allowed values
