### ISSUE TITLE
manifest.json not found in .zip file

### ISSUE THREAD

**Issue by BlucyBlue** [mozilla/addons-linter#5285]
I have packaged my extension for submission in a .zip file.  After submitting it for automated validation, I have received an error that there is no manifest.json.

If I manually open the .zip file, I can clearly see the file.  Moreover, I can use the files to test the extension manually in the browser.

I'm on macOS 14.4.1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDLINT-551)

**Comment by Ainias** [comment]
@BlucyBlue how did it work for you? I can't get it to work with my extension. manifest.json is present in the zip

**Comment by BlucyBlue** [comment]
@Ainias I made the mistake of zipping the folder where the extension files are. What needs to be done is to select all the extension files, and zip them. The result should be that manifest.json is on the very top level of the zip file.

**Comment by Ainias** [comment]
Ahh thank you! This was it!
