### ISSUE TITLE
Typo: `UNEXPECTED_GLOGAL_ARG` -> `UNEXPECTED_GLOBAL_ARG`

### ISSUE THREAD

**Issue by torokati44** [mozilla/addons-linter#5297]
Just a quick drive-by report about a typo in one of your lint IDs:
https://github.com/mozilla/addons-linter/blob/b7791fe5247f90ff35e0b986d5caa09c0464ab9e/src/messages/javascript.js#L76

Noticed by @danielhjacobs in https://github.com/ruffle-rs/ruffle/actions/runs/9136529660/job/25125423320#step:6:105.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDLINT-564)

**Comment by ioanarusiczki** [comment]
Running locally  linter 6.28.0 for [Ruffle](https://addons.mozilla.org/en-US/firefox/addon/ruffle_rs/)

Typo is fixed

![unexpected global arh](https://github.com/mozilla/addons-linter/assets/33448286/80f98e0b-c9f0-40ba-957f-079649ebe3ef)
