### ISSUE TITLE
Consider removing the `MANIFEST_V3_FIREFOX_ANDROID_LIMITATIONS` rule

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-linter#5328]
The `MANIFEST_V3_FIREFOX_ANDROID_LIMITATIONS` rule was added for Add-ons/Android GA. We should remove this rule when we have better support of MV3 in Firefox for Android.

**Comment by Rob--W** [comment]
> We should remove this rule when we have better support of MV3 in Firefox for Android.

A major blocker was the absence of host permissions, without a UI to grant permissions. The permissions being granted by default landed in Firefox 127 (https://bugzilla.mozilla.org/show_bug.cgi?id=1889402), which will reach release next week (https://whattrainisitnow.com/release/?version=127).

Can we remove the rule now, or do you see another blocker?

**Comment by ioanarusiczki** [comment]
@willdurand I'm not sure what to test for this. Please let me know.

**Comment by willdurand** [comment]
The linter used to emit a warning when an MV3 extension had the `gecko_android` key in the manifest.

**Comment by ioanarusiczki** [comment]
Ahh, I didn't see any warning for an MV3 with gecko-android , but I'll re-check compared to the old linter. Thanks!

**Comment by ioanarusiczki** [comment]
On 6.29.0 I see the warning present with a server warning which is still there for mv3

![warnings](https://github.com/mozilla/addons-linter/assets/33448286/53a9ee04-05fd-4bab-893b-5094c432ffa9)

On AMO dev  6.30.0 "Warning: Manifest Version 3 is not fully supported on Firefox for Android." is no longer available.
