### ISSUE TITLE
Prevent the use of the enterprise flag

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-linter#5330]
We want to prevent the use of the enterprise flag until we are ready to accept these enterprise add-ons on AMO.

**Comment by willdurand** [comment]
For QA: the manifest prop is `admin_install_only`. It is a boolean and it could be set in `browser_specific_settings.gecko` OR `applications.gecko`.

**Comment by ioanarusiczki** [comment]
I tried on AMO dev with linter 6.30.0 the admin_install_only prop into `browser_specific_settings.gecko` with mv2 and mv3 and then with `applications.gecko` (on mv2). Also tested for listed and unlisted.

 For both cases `true` and  `false` I get  "Error: The "admin_install_only" property is reserved and can only be used in enterprise add-ons."

![must be bolean](https://github.com/mozilla/addons-linter/assets/33448286/b5cc50fd-f210-44ba-b3bb-8eef14742b67)
