### ISSUE TITLE
Enterprise add-ons should be treated as self-hosted add-ons

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-linter#5345]
When `--enterprise` is passed, then `--self-hosted` should also be implies. By definition, an enterprise add-on is more or less like an unlisted add-on and cannot be listed on AMO. That's why we need to treat enterprise add-ons as unlisted in the linter.

For example, `bss.gecko.update_url` can be used in an enterprise add-on when this bug is fixed.

**Comment by ioanarusiczki** [comment]
I'll wait for 6.31.0 to test.
