### ISSUE TITLE
An extra quotation mark at the end a sentence 

### ISSUE THREAD

**Issue by peiying2** [mozilla/addons-linter#5350]
### Describe the problem and steps to reproduce it:

`"/browser_specific_settings/gecko/admin_install_only" property must be set to "true"."` 

The last quotation mark at the end of the sentence should to be removed. 

String location: 
- #:src/messages/manifestjson.js:833
- https://pontoon.mozilla.org/nl/amo-linter/LC_MESSAGES/messages.po/

**Comment by Rob--W** [comment]
This has already been fixed by https://github.com/mozilla/addons-linter/pull/5347.
