### ISSUE TITLE
The report table is always wider than terminal

### ISSUE THREAD

**Issue by fregante** [mozilla/addons-linter#5419]
### Describe the problem and steps to reproduce it:

Run the basic `addons-linter folder/` on an extension with warnings

### What happened?

The calculated window with is always ~15 tighter than it is. I'm using a mostly unmodified Terminal.app with Fish Shell. The same happens with `zsh`. Also same issue when used in VS Code's terminal windows.

`web-ext lint` is also affected.

### Demo

https://github.com/user-attachments/assets/3e765e7c-a098-4301-aaa8-0a05915ef3cd

**Comment by ioanarusiczki** [comment]
Lgtm with VS code Terminal - using poweshell or cmd

![visual studio code with terminal](https://github.com/user-attachments/assets/ddc10c6b-4611-4d83-8a70-03e9ec7641be)
