### ISSUE TITLE
Test for handling of XML bombs 

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-linter#542]
We have some bugs with test-cases so lets use them to see how the chosen parser lib handles such cases.

**Comment by EnTeQuAk** [comment]
addons-server has specific tests for xml-bombs so we aren't affected by that on AMO.

When I developed this on addons-server I figured that there aren't good libraries in the JavaScript world that won't need significant engineering effort to implement these checks.

With that in mind and AMO being safe against XML bombs I'm going to close this.
