### ISSUE TITLE
Validate length of `description` in manifest.json and locales

### ISSUE THREAD

**Issue by xPaw** [mozilla/addons-linter#5436]
The description length is set to 132 in manifest.json docs: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/description

Furthermore, the upload to Microsoft's extensions site fails if any of the locales contain translation for `description` that is longer than 132 characters.

**Comment by willdurand** [comment]
I think this is a mistake in MDN, which we'll need to fix. Firefox doesn't limit the length and AMO doesn't either.

**Comment by xPaw** [comment]
It likely comes from the Chrome docs: https://developer.chrome.com/docs/extensions/reference/manifest/description?hl=en

**Comment by willdurand** [comment]
Yeah, indeed. I fixed the MDN docs: https://github.com/mdn/content/pull/36495
