### ISSUE TITLE
Check for CSP changes in the manifest and flag them for reviewers

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-linter#562]
We should warn for all CSP changes made to the manifest so reviewers know to check and make sure there are appropriate.

Certain CSP changes should be straight-up not allowed; others should warn developers and reviewers.

This will solve a lot of security issues.

**Comment by andymckay** [comment]
Would this be something we add to mozilla/web-extension-manifest-schema? I'm not quite sure how I'd do that, it seems like a particular AMO specific thing.
