### ISSUE TITLE
Run example web extensions against our linter

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-linter#563]
@rpl mentioned it would be cool to run the list of example extensions we provide (https://github.com/mdn/webextensions-examples) to see what kinds of errors they output or if there's something there we are catching we shouldn't.

Just a neat idea/nice-to-have filing here, but no rush.

**Comment by atsay** [comment]
Perhaps this should be a One & Done task instead? http://oneanddone.mozilla.org/

**Comment by andymckay** [comment]
I have run every webextensions in the examples through the linter and they all passed. Not a single error. Probably because they've all been reviewed and tested prior to landing. So meh not sure what to do here. Closing.
