### ISSUE TITLE
Point user to README or run build if they try to run the binary without building it first

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-linter#572]
If the user doesn't RTFM, they will get an error trying to run `./bin/addons-linter` and may think the linter is busted. We should catch that error and handle it; this is silly but polite.

**Comment by eviljeff** [comment]
This would be a good first bug for someone who knows Javascript.

Getting started for any contributors: https://wiki.mozilla.org/Add-ons/Contribute/AMO/Code

**Comment by Revanth47** [comment]
@eviljeff Can I take up this issue?

**Comment by eviljeff** [comment]
@Revanth47 sure!  It should just be a matter of changing https://github.com/mozilla/addons-linter/blob/master/bin/addons-linter to check for the presence of the executable or folder and giving an appropriate message to the user if it's not built yet. @tofumatt should be able to provide more detail.

**Comment by Revanth47** [comment]
So I just check if the "dist" folder exists and if it doesn't I'll just display this link '[https://github.com/mozilla/addons-linter#readme](https://github.com/mozilla/addons-linter#readme)'

**Comment by wagnerand** [comment]
@tofumatt @eviljeff could you reply to @Revanth47 please?

**Comment by tofumatt** [comment]
> So I just check if the "dist" folder exists and if it doesn't I'll just display this link 'https://github.com/mozilla/addons-linter#readme'? @tofumatt @eviljeff

Sorry I missed this!

Basically: yes. You specifically want to check for the [built file in `dist/` that `/bin/addons-linter` tries to `require`](https://github.com/mozilla/addons-linter/blob/master/bin/addons-linter#L8): that file is `dist/addons-linter.js`.

**Comment by wagnerand** [comment]
@Revanth47 are you still working on this?

**Comment by Divya063** [comment]
can I take up this issue?

**Comment by tofumatt** [comment]
@Divya063 Yes, feel free to work on it, thanks 😀

**Comment by Divya063** [comment]
@tofumatt please review

**Comment by wagnerand** [comment]
This got fixed in https://github.com/mozilla/addons-linter/pull/1492
