### ISSUE TITLE
Create a warning list for third party libraries

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-linter#598]
We need to warn reviewers of potentially dangerous or forbidden third party libraries.

My proposal would be to create a list of third party libraries we always warn about, similar to what we already have with dispensary for whitelisting.

**Comment by tofumatt** [comment]
My only question is how much flexibility do you need? Do you want a list of libraries to warn about and a separate list to error about? That's what it sounds like, just wanted to be sure.

In the past we removed libraries from dispensary we didn't want to allow, but I think the appropriate move is to include them again. In the linter itself we can maintain a list of not allowed libraries, and libraries to warn about.

**Comment by wagnerand** [comment]
> My only question is how much flexibility do you need? Do you want a list
of libraries to warn about and a separate list to error about? That's what
it sounds like, just wanted to be sure.


Yes.


Note that the lists need to be file-based, e.g. for library X we want to
allow 2.0, warn for 1.5 and error for 1.0.
