### ISSUE TITLE
Handle BOM encoding

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-linter#606]
See https://github.com/mozilla/addons-server/issues/2038 for an example that currently fails and maybe https://github.com/mozilla/amo-validator/blob/master/validator/unicodehelper.py for an idea on a fix.

**Comment by muffinresearch** [comment]
One consideration here is that this patch linked fixes the problem from the linter's PoV but do we know if the browser will blow up if it's handed files containing a BOM?

**Comment by EnTeQuAk** [comment]
apparently it seems that the addon installs fine according to mozilla/addons-server#2038 - I didn't check but it seems Firefox allows or at least strips the BOM somehow.
