### ISSUE TITLE
Flag known hidden files

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-linter#617]
References: https://github.com/mozilla/addons-server/issues/2187

Examples:

* `__MACOSX` - a hidden directory found in zips created by OSX's archive util.
*  ~~`.DS_STORE`~~  `.DS_Store` - aka mac droppings https://en.wikipedia.org/wiki/.DS_Store
* `Thumbs.db` - windows thumbnail cache 

Check the old code on amo-validator for any other things we should look for and how the errors should be surfaced.

**Comment by muffinresearch** [comment]
Fwiw: dealing with the `__MACOSX` dir is the highest priority since it breaks validation.

**Comment by andymckay** [comment]
Fixed I think.
