### ISSUE TITLE
Allow CLI parser to be run from a (Celery) queue

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-linter#62]
@andymckay, @mstriemer, and I talked about #49. What we actually need is to use the existing https://github.com/mozilla/olympia Django app as our API server (having multiple front ends is needless) to handle the Validator's API (eg: upload a file for validation -> get an ID -> query said ID for its validation status).

Do need to get the validator to run as a Celery task that can get data from the Django API (put into celery) and then send data back.

The API would return a status of the validation (processing/complete) with a series of messages/warnings/errors (as JSON, which the validator can already easily produce being a JS app).

**Comment by tofumatt** [comment]
Note that running the npm version will fail until we fix #185, but I'm looking to fix that soon :smile:

**Comment by muffinresearch** [comment]
Ok #185 and #201 are fixed. The package looks to be functional when installed from npm now.

**Comment by EnTeQuAk** [comment]
Awesome, thanks a lot @muffinresearch!

**Comment by EnTeQuAk** [comment]
I think this already fixed now and QA is already testing the new linter on -dev.
