### ISSUE TITLE
Ability to read the first chunk of a file

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-linter#627]
The `src/io` libraries allow to read the whole file as a string, or stream the whole file. To support #56 we need to be able to just get the first 260 odd bytes. So we could just wrap the `getFileAsStream` in a convenience method, or add in a `getFileAsChunk` or something (although the latter means changing the calling methods). Then we can pass this chunk through to something like https://www.npmjs.com/package/file-type and get the file type.

**Comment by muffinresearch** [comment]
This package [1] looks like it would help make that nice and straight-forward since it makes it possible to grab the first `n` bytes from a stream.

[1] https://www.npmjs.com/package/first-chunk-stream
