### ISSUE TITLE
Already signed

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-linter#666]
Lets warn if the add-on is already signed, eg:

![screenshot 2016-05-12 15 52 11](https://cloud.githubusercontent.com/assets/74699/15232959/8ef1d28a-1859-11e6-9dce-be68f6485605.png)

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF46(Win 7).
A warning message is displayed if the add-on is already signed.
Postfix screenshot: 
![2016-05-16_0939](https://cloud.githubusercontent.com/assets/15685960/15282197/28a5d582-1b4a-11e6-8041-164a2b72515b.png)
