### ISSUE TITLE
Deal with inline CSS and style elements when parsing HTML.

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-linter#67]
We're going to need a way to hand-off in-line CSS and style-blocks to the CSSParser when parsing the HTML

**Comment by andymckay** [comment]
I don't think we need to do this. Currently all the CSS does is check for invalid nesting.

**Comment by EnTeQuAk** [comment]
I think it'd still be nice to create the infrastructure for such hand-offs. Aside that the current css checks are relatively weak I think there's quite a few things to do, also maybe related to new themes coming up some time?

**Comment by muffinresearch** [comment]
I'm going to wontfix this since I don't see us getting to it.
