### ISSUE TITLE
presence of background/persistent

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-linter#675]
Isn't an error, its a warning about it being deprecated, so we'll have to tone that down in addons-validator.

**Comment by EnTeQuAk** [comment]
@andymckay can you elaborate on this a bit more, add a bugzilla bug or something with examples? I couldn't find anything in `amo-validator` and my searches didn't show up any results so far. Is this related to WebExtensions?

**Comment by andymckay** [comment]
This is WebExtensions, #765 will likely take care of this.

**Comment by andymckay** [comment]
It's this: https://developer.chrome.com/extensions/event_pages see the "persistent": false? Unfortunately it looks like #765 did not take care of this.

**Comment by EnTeQuAk** [comment]
This seems to be handled by fd646c2dd59e4623df511b5d9de41cfc13220eca
