### ISSUE TITLE
Deal with inline JS and script blocks when parsing the HTML

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-linter#68]
We're going to need to handle any JS we come across whilst processing the HTML files.

**Comment by tofumatt** [comment]
Relates to #54, which I started on last night/this morning. I'll see if I can integrate it in, but it might be a separate refactor branch :smile:

**Comment by muffinresearch** [comment]
Yeah, I think it'll make sense to tackle these as separate iterations once the basics are there.

**Comment by andymckay** [comment]
In WebExtensions, inline JS isn't allowed by CSP. Does this mean we can close this?

Maybe just give a warning if we see a script tag inside a HTML file? I've seen a few people inlining JS who were surprised by this, so its probably a good idea to do.

**Comment by vcarciu** [comment]
I tried to verify this bug using the attached Webextension, but no warning was displayed about inline script tags in HTML. Please let me know if I am doing something wrong.
[360CitiesTabExtension.zip](https://github.com/mozilla/addons-linter/files/979445/360CitiesTabExtension.zip)

**Comment by muffinresearch** [comment]
@vcarciu it probably wasn't released yet. Should be on -dev now though + stage shortly https://github.com/mozilla/addons-server/commit/87f49a40ee7a5e87d9b9efde8e91b9019e8b13d1

**Comment by vcarciu** [comment]
@muffinresearch : Thanks, this is now on -dev  : 
![linterjsinlinewarning](https://cloud.githubusercontent.com/assets/1583842/25861632/046999ec-34ee-11e7-857c-bac9efbfb6d2.png)
