### ISSUE TITLE
Merge multiple javascript errors

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-linter#682]
See https://github.com/mozilla/addons-server/issues/2174#issuecomment-219674845 for an example, e.g if there are many javascript errors we should downgrade additional errors to warnings as we're doing in https://github.com/mozilla/addons-linter/pull/672 too.

**Comment by andymckay** [comment]
I don't follow, if one file is broken then that's an error, but then later files just become warnings? That doesn't make sense to me and we should be consistent. If a JS file can't be parsed it should either be a warning or an error.

The reason in #672 is that one mistake in one line of code generates 4 lines of errors.

I think the problem in this case is how its surfaced up into the validator and people are complaining about the showing of "Unknown Word" or "JS Error" out of context and repeated.

Perhaps changing the errors that appear in UX to say "The validator returned multiple errors" and linking through to the details would make more sense.

**Comment by tofumatt** [comment]
I think the aim here is to not show "JS syntax error" multiple times. That's a smart idea but they are different syntax errors across different files and worthwhile to have distinctly when doing a local validation (they should point to the file/line of the error).

In the web interface simply saying "your add-on has JS syntax errors that prevent it from being run" *once* would be fine, but that should be a matter of seeing how many messages with a `JS_SYNTAX_ERROR` code are returned and only showing one.

This feels like an AMO bug and not a linter one; the linter should preserve all errors but AMO's interface could show only one for something like this.

**Comment by EnTeQuAk** [comment]
Closing as irrelevant, the addons-linter should never merge messages of any kind. This is something AMO can or should do potentially but isn't blocking or really necessary at the moment.
