### ISSUE TITLE
A couple [potentially] unused dependencies

### ISSUE THREAD

**Issue by pdehaan** [mozilla/addons-linter#691]
### Steps to reproduce:
1. Install [**depcheck**](http://npm.im/depcheck) globally.
2. Run `$ depcheck` from the root folder.
### Actual results:

``` sh
$ depcheck

Unused Dependencies
* sha.js

Unused devDependencies
* babel-core
* babel-plugin-transform-class-properties
* babel-plugin-transform-es2015-modules-commonjs
* babel-preset-es2015
* babel-preset-stage-2
* coveralls
* gfm.css
* grunt-contrib-clean
* grunt-contrib-copy
* grunt-eslint
* grunt-gh-pages
* grunt-istanbul
* grunt-mocha-test
* grunt-newer
* grunt-webpack
* json-loader
* webpack-dev-server
```

I think **sha.js** is unused, and possibly **json-loader** (which I didn't see referenced in the webpack config file). I think the rest are referenced via Grunt tasks or .babelrc.

**Comment by pdehaan** [comment]
Looks like **sha.js** was removed via #1040.
Not sure about the rest of the devDependencies.

I've switched to using [**depcheck-ci**](http://npm.im/depcheck-ci) which is a wrapper for **depcheck** module and lets you configure it via a config file instead of really long CLI commands.

### Current status:

1. Create a top level .depcheckrc file and add the following:

    ```json
    {
      "ignore": [
        "babel-*",
        "grunt-*"
      ]
    }
    ```

2. Install `$ npm i depcheck-ci`

3. Run `$ $(npm bin)/depcheck-ci`

#### Output:

```sh
$ $(npm bin)/depcheck-ci
error: You have unused dependencies:

gfm.css,
isparta,
json-loader,
mocha-multi,
webpack-dev-server

$ echo $? # 1
```

**Comment by EnTeQuAk** [comment]
I'm closing this for now, there will be lots of code removed in the near future and we'll remove many more dependencies with it.
