### ISSUE TITLE
Unpack and validate a CRX file

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-linter#696]
Supports https://github.com/mozilla/addons-server/issues/2579

We should allow the linter to unpack and validate a CRX file. The CRX format is just a fancy ZIP, but we may even be able to use https://github.com/shyiko/node-crx-parser rather than unpacking it ourselves.

**Comment by tofumatt** [comment]
Not sure if the linter can handle extracting the CRX then writing out an XPI for addons-server to further handle/process, but that would be sweet.

**Comment by andymckay** [comment]
It feels like altering the add-on might be a bit much for the linter to do. I know @kumar303 was looking at getting web-ext to build out .crx, it already does .xpi's wonder if it makes sense to use web-ext? Dunno. Then we'd have the web-ext and the linter depending upon each other and then npm implodes.

**Comment by tofumatt** [comment]
Yeah putting it into web-ext might make more sense. The linter should be able to be fed CRX files, but which lib is actually handling it doesn’t matter to me :)

**Comment by kumar303** [comment]
To be honest, I don't think web-ext would ever need to *read* .crx files, only write them. This is the related web-ext tracker: https://github.com/mozilla/web-ext/issues/119

**Comment by tofumatt** [comment]
And the linter really only needs to read them. Seems like we have different needs then :-)
