### ISSUE TITLE
Add retire.js

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-linter#699]
http://retirejs.github.io/retire.js/ looks like a great tool for spotting security issues in third party libraries. We really can't keep up with that on our own.

I think we could either just use their node client or fetch their json files (e.g. https://github.com/RetireJS/retire.js/blob/master/repository/jsrepository.json) and check files against it in the linter directly.

**Comment by muffinresearch** [comment]
Is this for the linter's deps or the files we're scanning?

**Comment by wagnerand** [comment]
Sorry, this would be for the add-on files we are scanning.

**Comment by tofumatt** [comment]
Using the node client would not work well as we'd need to use it to scan files in a folder, which is not (always) how the linter scans things.

**Comment by EnTeQuAk** [comment]
Notes from #1323, that adds detection for minified code that also adds a basis for adding retire.js and other detection methods and potentially opens up the possibility of detecting potential security vulnerabilities.

Medium time intensive:

Write parser that searches for code based on https://github.com/RetireJS/retire.js/blob/master/repository/jsrepository.json - see exractors, e.g https://github.com/RetireJS/retire.js/blob/master/repository/jsrepository.json#L64-L84 and matches libraries more broadly than dispensary does. This integration could actually end up being an improvement to dispensary detecting libraries and their version numbers and white/blacklisting them.

Hard, time intensive:

    find / read package.json
    find / read npm-shrinkwrap.json
    find / read yarn.lock
    find / read package-lock.json
    Try to figure out common data-structures and build a dependency-map which we can then use to warn accordingly

Both ways can be thrown against a database of security vulnerabilities (e.g from retire.js or nodesecurity or others).
