### ISSUE TITLE
Validate `default_locale` is being set if _locales/ folder exists

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-linter#701]
Supports https://github.com/mozilla/addons-server/issues/1681

From https://developer.chrome.com/extensions/i18n:

> Important: If an extension has a _locales directory, the manifest must define "default_locale"

**Comment by EnTeQuAk** [comment]
An example: https://dxr.mozilla.org/mozilla-central/source/toolkit/mozapps/extensions/test/addons/webextension_3/manifest.json

**Comment by andymckay** [comment]
Thanks for working on this, it caught me out :(
