### ISSUE TITLE
Strip update_url and warn developers instead of erroring

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-linter#726]
We banned the usage of `update_url` in #565 if a Web Extension is on AMO, but it might be more constructive to strip it out and alert developers that extensions hosted on AMO cannot use `update_url`... and that they need to upload new versions of their extensions to AMO for users to get updates.

But this way they could use the same manifest as their Chrome add-ons.

Supports https://github.com/mozilla/addons-server/issues/2579

**Comment by andymckay** [comment]
The original bug suggested we error if the `update_url` in the root is specified. I was reading through the bug https://bugzilla.mozilla.org/show_bug.cgi?id=1192435 and docs https://developer.mozilla.org/en-US/Add-ons/Updates#Enabling_updates_to_your_extension and I think https://github.com/mozilla/addons-linter/issues/565 might be a bit overbearing.

If an `update_url` in the root is specified, its just not used by Firefox at all, we only use the one specified in `applications`. So its not really an error if its specified.

I would recommend we downgrade `update_url` being present to being a warning "hey you've got a key that we don't know about, perhaps you really meant applications > gecko > update_url or perhaps you've just uploaded a chrome add-on".

If thats the case, this becomes a lot easier.

Just cc'ing @kmaglione and @wagnerand to check if that's the case.

**Comment by tofumatt** [comment]
Oooooh cool. That's actually a really good thing to know. And if they are explicitly targeting `applications.gecko` we _can_ error because they're doing something specific to us they shouldn't be on AMO.

👍

**Comment by andymckay** [comment]
Ah good point. Bug #565 just targetted the wrong `update_url` and stopping the one in `applications.gecko` is what we should be doing.

**Comment by wagnerand** [comment]
> If an `update_url` in the root is specified, its just not used by Firefox at all, we only use the one specified in `applications`. So its not really an error if its specified.

Sorry I did not know that. I was under the impression Firefox would use the same key as Chrome.

**Comment by wagnerand** [comment]
@andymckay does this block enabling the linter on prod? Just askin'...

**Comment by tofumatt** [comment]
It should not.

- tofumatt

**Comment by andymckay** [comment]
Nah, I imagine there'll be almost no-one who hits it and it will be fixed up next week when this lands.

**Comment by ValentinaPC** [comment]
I've verified this on FF50(Win 7).
The update_url link does not throw an error, just a warning.
Also, the submission process was completed with success. The add-on is signed, accespts new versions and version-check works as expected.
Please see the postfix screenshost:
![manifest](https://cloud.githubusercontent.com/assets/15685960/15884887/fee0d958-2d5b-11e6-8ed6-ade66d2a2842.png)
![submission](https://cloud.githubusercontent.com/assets/15685960/15884894/09f2150a-2d5c-11e6-847d-5323e3a2a87c.png)
![report](https://cloud.githubusercontent.com/assets/15685960/15884898/0fdd9a7a-2d5c-11e6-8038-ed296377cfb3.png)

If there is anything I forgot and needs to be checked, please let me know.

**Comment by vcarciu** [comment]
@tofumatt : can you please add some STRs to this bug or mark it with "needs no qa" label ?

**Comment by tofumatt** [comment]
@ValentinaPC That is perfect, thanks!
