### ISSUE TITLE
 Reject manifests with any "incognito" property other than "spanning"

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-linter#728]
See: https://bugzilla.mozilla.org/show_bug.cgi?id=1277686 for more.

**Comment by andymckay** [comment]
This is fixed.

**Comment by vcarciu** [comment]
Verified as fixed for "incognito" different than "spanning" : 
![incognito](https://cloud.githubusercontent.com/assets/1583842/16380540/52a556d0-3c80-11e6-8f2a-70818636c4b1.gif)
