### ISSUE TITLE
"Should not have additional properties" message isn't super-clear

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-linter#732]
As pointed out in https://github.com/mozilla/addons-server/issues/2846#issuecomment-223596538, this message isn't super-clear; maybe we should improve it.

Meant to open this here, accidentally opened https://github.com/mozilla/addons-server/issues/2849. Oops!

**Comment by cosminbadescuSV** [comment]
The message is displayed properly, see the video: 
![message](https://cloud.githubusercontent.com/assets/15885467/15885429/cbd0a440-2d5f-11e6-842b-70c81ca02c91.gif)
