### ISSUE TITLE
Duplicate output in --help

### ISSUE THREAD

**Issue by pdehaan** [mozilla/addons-linter#735]
### Steps to reproduce:
```bash
✗ ./node_modules/.bin/addons-linter --help
Usage: ./node_modules/.bin/addons-linter [options] library-json-file

Mozilla Dispensary v0.5.0

Options:
  --log-level         The log-level to generate
  [string] [choices: "fatal", "error", "warn", "info", "debug", "trace", "fatal", "error", "warn", "info", "debug", "trace"]
                                                                                                          [default: "fatal"]
  --output, -o, -o    The type of output to generate    [string] [choices: "json", "text", "json", "text"] [default: "json"]
  --metadata          Output only metadata as JSON                                              [boolean] [default: "false"]
  --pretty            Prettify JSON output                                                        [boolean] [default: false]
  --stack             Show stacktraces when errors are thrown                                     [boolean] [default: false]
  --boring            Disables colorful shell output                                              [boolean] [default: false]
  --self-hosted       Disables messages related to hosting on addons.mozilla.org.                 [boolean] [default: false]
  --max               Maximum number of concurrent HTTP requests                                    [string] [default: "35"]
  --libraries         Custom library file                [string] [default: "node_modules/addons-linter/src/libraries.json"]
  -h, --help, --help  Show help                                                                                    [boolean]
```

### Actual results:

> `--log-level`         The log-level to generate [string]
> [choices: "fatal", "error", "warn", "info", "debug", "trace", "fatal", "error", "warn", "info", "debug", "trace"]
> [default: "fatal"]

> `--output`, `-o`, `-o`    The type of output to generate    [string]
> [choices: "json", "text", "json", "text"]
> [default: "json"]

1. The "choices" are duplicated for both `--log-level` and `--output`.
2. For some reason `--output` shows the `-o` shortcut twice: `--output, -o, -o`
3. Same with `--help` flag showing twice: `-h, --help, --help`

**Comment by andymckay** [comment]
I was getting really confused by this and then I notice it says: `Mozilla Dispensary v0.5.0` and not addons-linter. dispensary has the exact same set of yargs, aliases and options and that's causing (my guess) things to be registered twice and dispensary overwriting the linter one?

https://github.com/mozilla/dispensary/blob/master/src/cli.js#L10

@tofumatt any ideas?

**Comment by tofumatt** [comment]
I'm guessing that, erroneously, the CLI bit of dispensary is being loaded when it's included by `addons-linter` on the CLI.

Surely we can fix this easily, just requires seeing why it's not running in "non-CLI mode". It's really more an issue with dispensary than the linter, but I'll leave the bug here for now 😄

**Comment by kumar303** [comment]
Looks like we have the same issue in [web-ext](https://github.com/mozilla/web-ext) now that we are pulling in addons-linter as a dep. So I guess we need a patch to dispensary?

**Comment by kumar303** [comment]
For web-ext, only the `--help` option is duplicaed

**Comment by tofumatt** [comment]
Indeed. I’ll happily take a look at it this weekend; shouldn’t be too
complicated.
