### ISSUE TITLE
Updating XUL -> Web Extension

### ISSUE THREAD

**Issue by cpriest** [mozilla/addons-linter#757]
Hello, I'm the author of Snap Links.  v2 is a XUL based version and I have a new v3 I'm trying to upload based on the Web Extensions platform.

When I try to upload the new version, it is showing me:
> Your add-on failed validation with 1 error.
>     Add-on ID doesn't match add-on.

I'm not sure what is mis-matching, [here is a zip file](https://github.com/mozilla/addons-linter/files/322563/install.zip) the old install.rdf and the new manifest.json files.

Is this a linter problem or a user error?

**Comment by wagnerand** [comment]
What is the URL to your add-on and the email address of your AMO account? Please provide the real add-on file you want to upload.

You can also send those information to amo-admins AT mozilla DOT org.

**Comment by cpriest** [comment]
I'll shoot them an email, its probably something I'm just doing wrong.  The URL for the add-on is https://addons.mozilla.org/en-US/firefox/addon/snaplinksplus/
Email address should be firefox at rxv dot me

**Comment by wagnerand** [comment]
This is being handled by amo-admins. Fwiw, it's a user error as far as we can see.

**Comment by cpriest** [comment]
Yeah, I've no idea how that happened, it was literally the first thing I thought of/changed.  I even verified the build system was using the old (matching, but no-longer-wanted extension id).  I must have tried uploading the old version or something.  😵
