### ISSUE TITLE
Deprecated chrome.extension.onRequest API

### ISSUE THREAD

**Issue by vasilicamihasca** [mozilla/addons-linter#761]
**Steps to reproduce:**
Submit the attached web-extension on AMO-dev: 
[grammar_ginger.zip](https://github.com/mozilla/addons-linter/files/325587/grammar_ginger.zip)

**Expected results:**
A deprecated API warning appears while uploading the webextension.

**Actual results:**
There is no warning displayed.

**Additional notes:**
- This issue reproduces on AMO-dev, AMO-stage and AMO-production using Firefox 50.0a1 (2016-06-20) under Windows 10 64-bit.
- After submitting and installing the webextension, the following error appears in Browser Console: TypeError: chrome.extension.onRequest is undefined
[Learn More]background.min.js:21:89382
- More details in: https://developer.chrome.com/extensions/extension#event-onRequest

**Comment by andymckay** [comment]
Needs #780
