### ISSUE TITLE
Deprecated chrome.app.getDetails API

### ISSUE THREAD

**Issue by vasilicamihasca** [mozilla/addons-linter#762]
**Steps to reproduce:**
Submit the attached web-extension on AMO-dev:
[weather.zip](https://github.com/mozilla/addons-linter/files/325639/weather.zip)

**Expected results:**
A deprecated API warning appears while uploading the webextension.

**Actual results:**
There is no warning displayed.

**Additional notes:**
- This issue reproduces on AMO-dev, AMO-stage and AMO-production using Firefox 50.0a1 (2016-06-20) under Windows 10 64-bit.
- After submitting and installing the webextension, the following error appears in Browser Console: TypeError: chrome.app is undefined
[Learn More]network.js:9:1
- More details in: http://stackoverflow.com/questions/9167150/where-is-chrome-app-officially-documented and https://bugs.chromium.org/p/chromium/issues/detail?id=111354

**Comment by andymckay** [comment]
Needs #780
