### ISSUE TITLE
Beta string versions should be allowed

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-linter#764]
@raphaelfaria previously filed this bug here: mozilla/web-extension-manifest-schema#144

The schema currently supports only integer numbers on version parts and prevents the signing of beta versions of web extensions.
It should allow this match `(a|alpha|b|beta|pre|rc)\d*$` at the last version part as described in: https://developer.mozilla.org/en-US/docs/Toolkit_version_format and https://developer.mozilla.org/en-US/Add-ons/AMO/Policy/Maintenance

**Comment by tofumatt** [comment]
Looks like [our fix didn't quite address what's in the docs](https://github.com/mozilla/addons-linter/commit/2488841578d555af1d55907e89348caa5ade36c5#commitcomment-18505623), so reopening this one.
