### ISSUE TITLE
Import schema from central once it's on v4

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-linter#765]
Copy of mozilla/web-extension-manifest-schema#14

We have the schema here and platform has one being built out in mozilla-central. When everything has stabilized we should consolidate. For example we'll probably be looking to do an import of the mozilla-central schema as opposed to manually keeping them up to date.

This depends on mozilla-central moving to v4 of json-schema spec https://bugzilla.mozilla.org/show_bug.cgi?id=1243516

**Comment by mstriemer** [comment]
There is some discussion about beta version strings in https://github.com/mozilla/addons-server/issues/4220 that will be relevant when pulling in the schema.

**Comment by muffinresearch** [comment]
@mstriemer, presumably this one be closed now?

**Comment by mstriemer** [comment]
The current process upgrades the Firefox schemas to the new format. The plan was to backport that to Firefox so this seems like it's still valid to me.

**Comment by muffinresearch** [comment]
> The current process upgrades the Firefox schemas to the new format. The plan was to backport that to Firefox so this seems like it's still valid to me.

Would it make more sense to have a bugzilla bug for upgrading FF to use upgraded version of the schemas and then a separate issue here to migrate the linter onto that once it's done?

This issue was more about getting the linter to the point of using schemas out of mozilla-central, but the way it ended up happening was slightly different to what was proposed in the description.

**Comment by mstriemer** [comment]
[Bug 1243516](https://bugzilla.mozilla.org/show_bug.cgi?id=1243516) exists to upgrade the schemas in Firefox. Making a new bug depending on that works for me.

**Comment by muffinresearch** [comment]
@mstriemer great, thanks - I'll close this one and file a new one.
