### ISSUE TITLE
Duplicated warnings at add-on validation

### ISSUE THREAD

**Issue by vasilicamihasca** [mozilla/addons-linter#768]
**Steps to reproduce:**
1. Try to submit the following add-on:
[testaddon.zip](https://github.com/mozilla/addons-linter/files/327956/testaddon.zip)
2. Select “See full validation report”

**Expected results:**
Each warning is specified only a single time.

**Actual results:**
A few warnings are duplicated.

**Additional notes:**
- This issue reproduces on AMO-dev, AMO-stage and AMO-production using Firefox 50.0a1 (2016-06-21) under Windows 10 64-bit.
- Please see the attached screenshots for this issue:
![2016-06-22_1320](https://cloud.githubusercontent.com/assets/18114210/16268016/436f3dbe-3895-11e6-960e-3c77d2312919.png)
![2016-06-22_1321](https://cloud.githubusercontent.com/assets/18114210/16268022/476c49fc-3895-11e6-9b03-7218846bb634.png)
![2016-06-22_1323](https://cloud.githubusercontent.com/assets/18114210/16268025/4a51423a-3895-11e6-933d-e6fbfd4c53c9.png)
![2016-06-22_1530](https://cloud.githubusercontent.com/assets/18114210/16268030/4df507be-3895-11e6-824c-49d76322d291.png)

**Comment by andymckay** [comment]
That's not a WebExtension to moved over to mozilla/amo-validator#449.
