### ISSUE TITLE
Deprecated chrome.tabs.getSelected API

### ISSUE THREAD

**Issue by vasilicamihasca** [mozilla/addons-linter#769]
**Steps to reproduce:**
Submit the attached webextension:
[test11.zip](https://github.com/mozilla/addons-linter/files/328240/test11.zip)

**Expected results:**
A deprecated API warning appears while uploading the webextension.

**Actual results:**
There is no warning displayed.

**Additional notes:**
- This issue reproduces on AMO-dev, AMO-stage and AMO-production using Firefox 50.0a1 (2016-06-22) under Windows 10 64-bit.
- After submitting and installing the webextension, the following error appears in Browser Console while clicking on the webextension icon: TypeError: chrome.tabs.getSelected is not a function         [Learn More]popup.js:15:3
- More details in: https://developer.chrome.com/extensions/tabs#method-getSelected

**Comment by andymckay** [comment]
Needs #780
