### ISSUE TITLE
Deprecated chrome.tabs.sendRequest API

### ISSUE THREAD

**Issue by vasilicamihasca** [mozilla/addons-linter#772]
**Steps to reproduce:**
Submit the attached web-extension on AMO-dev:
[imagequilts.zip](https://github.com/mozilla/addons-linter/files/329948/imagequilts.zip)

**Expected results:**
A deprecated API warning appears while uploading the webextension.

**Actual results:**
There is no warning displayed.

**Additional notes:**
- This issue reproduces on AMO-dev, AMO-stage and AMO-production using Firefox 50.0a1 (2016-06-22) under Windows 10 64-bit.
- After submitting and installing the webextension, the following error appears in Browser Console while clicking on the webextension icon: chrome.tabs.sendRequest is not a function     background.js:59
- More details in: https://developer.chrome.com/extensions/tabs#method-sendRequest

**Comment by andymckay** [comment]
Needs #780
