### ISSUE TITLE
Deprecated chrome.tabs.getAllInWindow API

### ISSUE THREAD

**Issue by vasilicamihasca** [mozilla/addons-linter#773]
**Steps to reproduce:**
Submit the attached web-extension:
[chrome_clock.zip](https://github.com/mozilla/addons-linter/files/329969/chrome_clock.zip)

**Expected results:**
A deprecated API warning appears while uploading the webextension.

**Actual results:**
There is no warning displayed.

**Additional notes:**
- This issue reproduces on AMO-dev, AMO-stage and AMO-production using Firefox 50.0a1 (2016-06-22) under Windows 10 64-bit.
- After submitting and installing the webextension, the following error appears in Browser Console while clicking on the webextension icon: chrome.tabs.getAllInWindow is not a function     popup.js:16
- More details in: https://developer.chrome.com/extensions/tabs#method-getAllInWindow

**Comment by andymckay** [comment]
Needs #780
