### ISSUE TITLE
Deprecated chrome.tabs.onSelectionChanged API

### ISSUE THREAD

**Issue by vasilicamihasca** [mozilla/addons-linter#774]
**Steps to reproduce:**
Submit the attached web-extension:
[be_limitless.zip](https://github.com/mozilla/addons-linter/files/330075/be_limitless.zip)

**Expected results:**
A deprecated API warning appears while uploading the webextension.

**Actual results:**
There is no warning displayed.

**Additional notes:**
- This issue reproduces on AMO-dev, AMO-stage and AMO-production using Firefox 50.0a1 (2016-06-22) under Windows 10 64-bit.
- After submitting and installing the webextension, the following error appears in Browser Console: TypeError: chrome.tabs.onSelectionChanged is undefined
[Learn More]background.js:215:3
- More details in: https://developer.chrome.com/extensions/tabs#event-onSelectionChanged

**Comment by andymckay** [comment]
Needs #780
