### ISSUE TITLE
Deprecated chrome.tabs.onActiveChanged API

### ISSUE THREAD

**Issue by vasilicamihasca** [mozilla/addons-linter#775]
**Steps to reproduce:**
Submit the attached web-extension:
[ghostery.zip](https://github.com/mozilla/addons-linter/files/330114/ghostery.zip)

**Expected results:**
A deprecated API warning appears while uploading the webextension.

**Actual results:**
There is no warning displayed.

**Additional notes:**
- This issue reproduces on AMO-dev, AMO-stage and AMO-production using Firefox 50.0a1 (2016-06-22) under Windows 10 64-bit.
- After submitting and installing the webextension, the following error appears in Browser Console: TypeError: chrome.tabs.onActiveChanged is undefined
[Learn More]background.js:15590:3
- More details in: https://developer.chrome.com/extensions/tabs#event-onActiveChanged

**Comment by andymckay** [comment]
Supports #780
