### ISSUE TITLE
Deprecated chrome.extension.sendRequest  API

### ISSUE THREAD

**Issue by vasilicamihasca** [mozilla/addons-linter#776]
**Steps to reproduce:**
Submit the attached web-extension:
[gamingwonderland.zip](https://github.com/mozilla/addons-linter/files/330198/gamingwonderland.zip)

**Expected results:**
A deprecated API warning appears while uploading the webextension.

**Actual results:**
There is no warning displayed.

**Additional notes:**
- This issue reproduces on AMO-dev, AMO-stage and AMO-production using Firefox 50.0a1 (2016-06-23) under Windows 10 64-bit.
- After submitting and installing the webextension, the following error appears in Browser Console: TypeError: chrome.extension.sendRequest is not a function  messaging.js:113
- More details in: https://developer.chrome.com/extensions/extension#method-sendRequest

**Comment by andymckay** [comment]
Supports #780
