### ISSUE TITLE
Deprecated chrome.extension.onRequestExternal API

### ISSUE THREAD

**Issue by vasilicamihasca** [mozilla/addons-linter#777]
**Steps to reproduce:**
Submit the attached web-extension:

**Expected results:**
A deprecated API warning appears while uploading the webextension.

**Actual results:**
There is no warning displayed.

**Additional notes:**
- This issue reproduces on AMO-dev, AMO-stage and AMO-production using Firefox 50.0a1 (2016-06-23) under Windows 10 64-bit.
- After submitting and installing the webextension, the following error appears in Browser Console: TypeError: chrome.extension.onRequestExternal is undefined [Learn More] openPopoutWhenAsked.js:2:1
- More details in: https://developer.chrome.com/extensions/extension#event-onRequestExternal

**Comment by andymckay** [comment]
Supports #780
