### ISSUE TITLE
Flag bad permissions (or have a whitelist of permissions)

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-linter#789]
Supports https://github.com/mozilla/addons-server/issues/2726, we need to make sure only known permissions are allowed, or we'll end up accepting Chrome "app" extensions that don't work in Firefox.

**Comment by tofumatt** [comment]
Keeping up with a whitelist, it looks like, will be a nightmare. Let's go for a blacklist, at least for now (until we get the manifest from Firefox #765).

**Comment by vcarciu** [comment]
@tofumatt  : can you please add some STRs to this bug or mark it as "needs no qa" ?

**Comment by tofumatt** [comment]
You can try uploading this Chrome web app: http://cl.ly/3n3n0e2E1k3L (first you'll need to delete https://addons-dev.allizom.org/en-US/firefox/addon/amazon-storywriter/). You should get a failed validation and should not be able to upload the Chrome web app.

**Comment by vcarciu** [comment]
Tested with a similar Chrome web app(modified the name of the one from above) and I was not able to upload it : 

![javascript](https://cloud.githubusercontent.com/assets/1583842/16458949/b2932630-3e29-11e6-813a-54fe61188a54.png)
