### ISSUE TITLE
The use of mozIndexedDB should not be an error but a warning

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-linter#796]
Libraries and frameworks still use mozIndexedDB when assessing what's available in the browser, even https://github.com/mozilla/localForage/. The rules doc also says this should be a warning, but it is currently an error which for example, makes it impossible to submit webextensions that use localForage.

**Comment by tofumatt** [comment]
Agreed, seems sane to be a warning, actually. I didn't think of the case of checking for it but not using it.
