### ISSUE TITLE
[WebExtensions] Localized `homepage_url` in manifest is wrongly considered invalid

### ISSUE THREAD

**Issue by Marat-Tanalin** [mozilla/addons-linter#836]
I have localized my `homepage_url` manifest parameter by using `__MSG_addon_url__` as value and providing its locale-specific value via the message with the `addon_url` key in files `en/messages.json` and `ru/messages.json` in the `_locales` folder of my [extension](https://addons.mozilla.org/en-us/firefox/addon/consistent-https/) written using the WebExtensions API.

But I was **not** able to publish the new version just because the validation script of Addons.Mozilla.org wrongly treats such localized URL as invalid since the validator have apparently no clue that it’s actually not the URL itself, but a _reference_ to the corresponding _localized string_.

So I’ve been forced to replace the `homepage_url`-parameter value back to the real URL (hard-coded english one instead of own URL for each locale) for now. Thanks.

**Comment by Marat-Tanalin** [comment]
Surprisingly, this trivial bug is still not fixed. When trying to upload an extension with the localized `homepage_url` parameter in manifest, it says:

> "/homepage_url" should match format "uri"

and does not allow to add such version of the extension.

**Comment by andymckay** [comment]
If its trivial, would you consider sending in a pull request to fix it?

**Comment by Marat-Tanalin** [comment]
@andymckay Obviously, it's trivial for authors of the tool, not for third-party people. If it's not trivial for authors to account for locales, then the check should be just removed at all since it's works incorrectly.

**Comment by ValentinaPC** [comment]
Verified on AMO-dev FF48(Win 7)
After making the changes indicated above in .xpi ( in manifest.json: "homepage_url":"__MSG_addon_url__" and in messages.json from [es] locale: "addon_url":"www.xyz.com") I receive the same erros as the reporter mentioned in the first comment.
Please see the screenshot:
![homepage_url](https://cloud.githubusercontent.com/assets/15685960/18244022/96b896d0-7366-11e6-9962-80d778d03a45.png)

Please let me know if I missed something.
Thanks!

**Comment by Marat-Tanalin** [comment]
@ValentinaPC According to your screenshot, protocol in your URL is missing, so the URL is actually invalid even if linter had support for localizing URLs.

For the rest, looks like linter version actually used on addons.mozilla.org is updated with a noticeable delay, so bug fixes made here are not immediately available there.

**Comment by ValentinaPC** [comment]
Yeah, the protocol was left behind from mistake, but, independent of that, as you were saying above, the URLs are still not localized. Waiting the moment. :)

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF48.0.2(Win 7)
Postfix screenshot and video:
![eshomepage](https://cloud.githubusercontent.com/assets/15685960/18503888/fa5d2a2c-7a67-11e6-8eb0-908b9b266e5c.png)
![homepage_url](https://cloud.githubusercontent.com/assets/15685960/18503923/35b61d9a-7a68-11e6-860f-5b0f224592b0.gif)
