### ISSUE TITLE
Question: Is Angular officially banned?

### ISSUE THREAD

**Issue by ArnonEilat** [mozilla/addons-linter#842]
I'm building extension using Angular.JS.
According to this [article](https://github.com/mozilla/addons-linter/blob/master/docs/third-party-libraries.md) its not allowed to use Angular in extensions - is this officially?

Is there any way to use angular despite this limitation?

**Comment by tofumatt** [comment]
You can use newer versions of Angular, anything 2.x should be fine. Older versions have a security vulnerability and are not supported.

**Comment by ArnonEilat** [comment]
@tofumatt Tanks for the response
Using Angular 2.x make me to rewrite the whole extension all over again.

What does it mean Angular 1.x is not supported? right now its working...
And what happen if i use it anyway? will it remove from [AMO](https://addons.mozilla.org)? 

Is there official guidelines about which libraries i can use?

**Comment by tofumatt** [comment]
Only the latest version of Angular 1.5.x is supported, but it is deprecated and we encourage Angular 2.x. Right now we will accept a version with the latest Angular 1.5, but in the future it will likely be unsupported. This is a policy the review team has made, all I know is what's written in the document you linked to. Maybe we should explain it more in that doc.

- tofumatt

**Comment by kewisch** [comment]
Note also, this deprecation means we will not accept add-ons using Angular 1.x after September.

**Comment by tofumatt** [comment]
Ah. Could you add that to the document about thirf party libraries and to
the message in the linter? That'd really help.

- tofumatt
