### ISSUE TITLE
Move dispensary into the linter

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-linter#869]
No one other than us seems to use https://github.com/mozilla/dispensary as a dependency. Updating it and the linter at the same time is a bit of a pain, so we should move dispensary into the linter to make updates easier.

**Comment by ioanarusiczki** [comment]
@willdurand In case this can be tested let me know.

**Comment by willdurand** [comment]
@ioanarusiczki yeah, you can submit an extension with a known file from the list: https://github.com/mozilla/addons-linter/blob/master/src/dispensary/hashes.txt

**Comment by AlexandraMoga** [comment]
@willdurand I've tested with a few of the files mentioned in https://github.com/mozilla/addons-linter/blob/master/src/dispensary/hashes.txt and compared the validation results from -dev and prod. There were no differences as far as I could tell.

Here are some examples:

- validation messages when certain `.js` libraries are identified in the archive(*)
![image](https://user-images.githubusercontent.com/31961530/141108681-b8841ad9-2f44-4ccc-89b8-621284727007.png)
 *a note on angular - I've checked a few libraries and for all of them I've received the "Banned js library" error:
![image](https://user-images.githubusercontent.com/31961530/141109076-6c2277d7-ccfc-4188-90c7-a3334ddc70c3.png)

- validation messages for invalid syntax:
![image](https://user-images.githubusercontent.com/31961530/141109347-0a52d5f4-4875-4173-bebe-c73005cc85ea.png)

**Comment by willdurand** [comment]
> @willdurand I've tested with a few of the files mentioned in [`master`/src/dispensary/hashes.txt](https://github.com/mozilla/addons-linter/blob/master/src/dispensary/hashes.txt) and compared the validation results from -dev and prod. There were no differences as far as I could tell.

No difference = good :)
