### ISSUE TITLE
Delete mozilla/web-extension-manifest-schema

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-linter#883]
We've had plenty of releases with https://github.com/mozilla/web-extension-manifest-schema rolled into the linter and it will always exist on NPM, but we should delete the repo https://github.com/mozilla/web-extension-manifest-schema (or at least disable greenkeeper notifications for it).

I don't have admin access to it so I can't seem to handle this.

**Comment by andymckay** [comment]
Deleted.
