### ISSUE TITLE
Refactor errors in JSONParser/JSONScanner/ManifestParser

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-linter#895]
These classes all access a `Linter`'s `collector` property directly, but would be better serviced acting more like the rest of the scanners. This is to do with the fact that historically, there was only `ManifestJSONParser`, but now that we scan all JSON files (#779) we needed to refactor things a bit. Maybe.

**Comment by hameleonka** [comment]
Do you want to make it like singleton, once created and used everywhere, all depended items just ask collector factory to provide collector for them, instead of passing it via constructor params, is this description correct?

**Comment by EnTeQuAk** [comment]
I'm going to close this, it may not be as nice as it could be but things seem to work nicely during recent development. I don't think we have the manpower to master a refactor here anytime soon anyway.
