### ISSUE TITLE
Does Angular 1.x is supported for web extensions?

### ISSUE THREAD

**Issue by suyogdilipkale** [mozilla/addons-linter#922]
Hello,

as per https://github.com/mozilla/addons-linter/blob/master/docs/third-party-libraries.md 
you have mentioned that angular 1.x is not supported for add-ons, **does it applicable for browser extensions as well?**

**I have developed plugin to add some features on website's contents that user are browsing, as my understanding it’s counted as a browser extension and not a add-on. Please confirm me if I am wrong.**

**Does Angular 1.x and Jquery 3.1 is supported for web extensions?**

**Comment by wagnerand** [comment]
This has been answered in a cross-post email.
