### ISSUE TITLE
No error displayed at submission for invalid strict_min_version 

### ISSUE THREAD

**Issue by vasilicamihasca** [mozilla/addons-linter#931]
**Steps to reproduce:**
1.Try to submit the following webextension, which has strict_min_version = “abc”:
[apply-css.zip](https://github.com/mozilla/addons-linter/files/463887/apply-css.zip)

**Expected results:**
There is displayed an invalid strict_min_version error.

**Actual results:**
The webextension is validated with no errors and the platforms checkboxes are disabled.

**Additional notes:**
- This issue reproduces on AMO-dev, AMO-stage and AMO-production using Firefox 51.0a1 (2016-09-08) under Windows 10 64-bit.
- Please see the attached screenshot:
  ![2016-09-09_1506](https://cloud.githubusercontent.com/assets/18114210/18386592/a7ba14ee-76a0-11e6-8dd5-cc58e3497ec8.png)

**Comment by andymckay** [comment]
@EnTeQuAk this is up to AMO I think?

**Comment by EnTeQuAk** [comment]
missing this validation-wise is addons-linter imho although I didn't check yet.

**Comment by muffinresearch** [comment]
@vasilicamihasca is this still the case? I'm wondering if recent additions of the schema will now cause warnings for this issue and if the `strict_min_version` is too low e.g: https://github.com/mozilla/addons/issues/338

**Comment by andymckay** [comment]
The schema doesn't know anything about the actual value of the version, only AMO knows this. I think this bug should be in addons-server?

**Comment by vasilicamihasca** [comment]
This issue is no longer reproducible on AMO-dev, AMO-stage and AMO-production using Firefox 55.0a1 (2017-05-22). A proper error is successfully displayed. See attached screenshot.
![2017-05-23_1203](https://cloud.githubusercontent.com/assets/18114210/26347126/25edc5de-3fb1-11e7-8716-dd8034ef7a82.png)
Based on this I am closing the issue.
