### ISSUE TITLE
Invalid strict_max_version does not return an error at webextension update

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-linter#961]
STR:
1. Submit a webextension i.e. https://addons.allizom.org/en-US/developers/addon/valpocket/versions
2. Add a new version for that webextension that has an nonexistent strict_max_version (i.e. 52.*, 53.0, etc)

ER:
A message saying that the strict_max_version is invalid or not supported is displayed.

AR:
No message is displayed. The version is blocked in "loading" state. No error in the console.

Notes/Issues:
Not reproducing for add-ons.
Verified on FF49(Win 7). Issue is reproducing all around AMO servers.
Screenshots for this issue: 
- at submission
  ![submission](https://cloud.githubusercontent.com/assets/15685960/18950440/75fe73fc-8648-11e6-9151-e889b36a19d2.png)
- at update: 
  ![invalidmaxvrs](https://cloud.githubusercontent.com/assets/15685960/18950446/804500ba-8648-11e6-9f37-5d3ea831609f.png)

**Comment by EnTeQuAk** [comment]
@mstriemer is this already something your schema-patches fix?

**Comment by wagnerand** [comment]
Hm, I'm not sure we need to check for this.

@jvillalobos wdyt?

**Comment by jvillalobos** [comment]
It looks like the new version of this is https://github.com/mozilla/addons-server/issues/6046, in which case I would agree that we need to have good checks for min and max versions.

**Comment by wagnerand** [comment]
Ah, I see. Makes sense. I'm not sure the linter knows about valid appversions, so it might be something to be fixed on `addons-server`. @EnTeQuAk probably knows.

**Comment by EnTeQuAk** [comment]
The linter does not know about app versions, amo-validator did but that was mostly a hack. It's probably best to get this validated in addons-server.

**Comment by diox** [comment]
@ValentinaPC could you retest? https://github.com/mozilla/addons-server/issues/6226 might have fixed this.

**Comment by ValentinaPC** [comment]
So.... I don't know if your supposition is right, but if I set a `strict_max_version` to `53`, or `53.a`, or `57.*` or any nonexistent version for any webextension - no error message is displayed at submission and the max version in Dev Hub is `*`.
Are we ok with this fix?

**Comment by diox** [comment]
It's better (because the submission no longer fails) but still not ideal (we should validate the versions). In any case that's not a linter bug, it's an addons-server bug. Could you re-open on addons-server so that we can close this one?

**Comment by ValentinaPC** [comment]
Sure. I'll mark this verified-fixed.
