### ISSUE TITLE
web-ext lint error: Too many non-option arguments: got 1, maximum of 0

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-linter#969]
### Describe the problem and steps to reproduce it:

To reproduce:
* upgrade the `addons-linter` dependency of `web-ext` to `0.15.4`
* run `npm install` and `npm run build` to get a new `web-ext`
* cd into any add-on
* type `web-ext lint`

### What happened?

It shows a usage message with this error:
```
Too many non-option arguments: got 1, maximum of 0
````

### What did you expect to happen?

The command should show a lint report

### Anything else we should know?

`web-ext` simulates passing a directory of source as the first command line argument to `addons-linter` [like this](https://github.com/mozilla/web-ext/blob/master/src/cmd/lint.js#L75). Maybe something changed? I don't see anything obvious at a glance.

**Comment by tofumatt** [comment]
Oh darn, nothing should have changed (I know we upgraded yargs recently though, so I'll go back and see if that's what breaks it).

Thanks!

**Comment by kumar303** [comment]
Also, I owe @rpl so many 🍻 for adding functional tests to web-ext

**Comment by tofumatt** [comment]
Not sure the cause yet, but just tested on every release after `0.15.1` and this always happens in `web-ext` (`0.15.1` works for me locally though).

So this is a regression, introduced in `0.15.2`.

**Comment by tofumatt** [comment]
The main feature change in `0.15.2` was scanning *all* JSON files in an add-on, not just the manifest.json.

https://github.com/mozilla/addons-linter/commit/067dd4d4027207cb1dbba8daf89dc65cf1f03ae8

I'm guessing this is causing an issue, darn, I didn't think it'd be a breaking change.

**Comment by kumar303** [comment]
Ooh, looks like this fixed itself? I don't see the error anymore as of https://github.com/mozilla/web-ext/pull/570

**Comment by kumar303** [comment]
![80s-laptop](https://cloud.githubusercontent.com/assets/55398/19290760/dad41592-8fd6-11e6-90b3-f6dff7dfcaca.jpg)

**Comment by tofumatt** [comment]
![wat](https://cloud.githubusercontent.com/assets/90871/19305326/413658ea-9068-11e6-9bc1-785e6f3290c3.jpg)
