### ISSUE TITLE
Warn if an API is used without the permission

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-linter#978]
### Describe the problem and steps to reproduce it:

Use a WebExtension API in Firefox and find out you didn't ask for its permission.
### What happened?

The API doesn't work.
### What did you expect to happen?

A warning would be nice.

Let's see if we can print out a nice warning in the linter that you used API X but didn't use permission Y. With the addition of the deprecated API part of the linter this should be pretty easy.
### Anything else we should know?

(Please include screenshots and any relevant files.)

**Comment by andymckay** [comment]
This data is in the schema and should depend upon #765

**Comment by Divya063** [comment]
@andymckay Can I take this issue?

**Comment by andymckay** [comment]
We can't assign it to you, because github won't allow you to. But if you'd like to work on it, that would be great.

**Comment by EnTeQuAk** [comment]
I marked this as `contrib: assigned` so you're good to work on this.

**Comment by Divya063** [comment]
Thanks 😄 @EnTeQuAk

**Comment by Divya063** [comment]
@andymckay I'm a bit confused here, do the "permissions" refer to permissions in manifest.json or the  permissions used in core Permission API functionality (Permissions API)

**Comment by muffinresearch** [comment]
@Divya063 this relates to the permissions the developer has asked for in the manifest.json.

**Comment by paavininanda** [comment]
Hi! It seems that this issue has not been resolved yet. I would like to work on this. Can i take it up?

**Comment by EnTeQuAk** [comment]
@Divya063 are you still working on this issue? Otherwise @paavininanda seems interested in taking this too.

I just wanted to make sure @paavininanda doesn't start working on it while someone else already does.

**Comment by Divya063** [comment]
Hi @EnTeQuAk , Currently I'm working on issue #1074  so she can take this up.
